use super::{
    Attribute, ClassFile, CodeAttribute, Constant, Member, append_bootstrap_classes,
    build_bootstrap_class,
};

pub(super) fn append_alerts(classes: &mut Vec<ClassFile>) {
    append_bootstrap_classes!(classes;
        // javax/microedition/lcdui/Alert
        ClassFile {
            minor_version: 0,
            major_version: 48,
            constant_pool: vec![
                None,
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 3 }),
                Some(Constant::Class { name_index: 4 }),
                Some(Constant::NameAndType { name_index: 5, descriptor_index: 6 }),
                Some(Constant::Utf8("javax/microedition/lcdui/Screen".to_owned())),
                Some(Constant::Utf8("<init>".to_owned())),
                Some(Constant::Utf8("()V".to_owned())),
                Some(Constant::Class { name_index: 8 }),
                Some(Constant::Utf8("javax/microedition/lcdui/Alert".to_owned())),
                Some(Constant::Fieldref { class_index: 7, name_and_type_index: 10 }),
                Some(Constant::NameAndType { name_index: 11, descriptor_index: 12 }),
                Some(Constant::Utf8("timeout".to_owned())),
                Some(Constant::Utf8("I".to_owned())),
                Some(Constant::Methodref { class_index: 7, name_and_type_index: 14 }),
                Some(Constant::NameAndType { name_index: 15, descriptor_index: 16 }),
                Some(Constant::Utf8("setTitle".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;)V".to_owned())),
                Some(Constant::Fieldref { class_index: 7, name_and_type_index: 18 }),
                Some(Constant::NameAndType { name_index: 19, descriptor_index: 20 }),
                Some(Constant::Utf8("text".to_owned())),
                Some(Constant::Utf8("Ljava/lang/String;".to_owned())),
                Some(Constant::Fieldref { class_index: 7, name_and_type_index: 22 }),
                Some(Constant::NameAndType { name_index: 23, descriptor_index: 24 }),
                Some(Constant::Utf8("image".to_owned())),
                Some(Constant::Utf8("Ljavax/microedition/lcdui/Image;".to_owned())),
                Some(Constant::Fieldref { class_index: 7, name_and_type_index: 26 }),
                Some(Constant::NameAndType { name_index: 27, descriptor_index: 28 }),
                Some(Constant::Utf8("type".to_owned())),
                Some(Constant::Utf8("Ljavax/microedition/lcdui/AlertType;".to_owned())),
                Some(Constant::Methodref { class_index: 7, name_and_type_index: 30 }),
                Some(Constant::NameAndType { name_index: 31, descriptor_index: 6 }),
                Some(Constant::Utf8("__requestRepaint".to_owned())),
                Some(Constant::Class { name_index: 33 }),
                Some(Constant::Utf8("java/lang/IllegalArgumentException".to_owned())),
                Some(Constant::Methodref { class_index: 32, name_and_type_index: 3 }),
                Some(Constant::Methodref { class_index: 36, name_and_type_index: 37 }),
                Some(Constant::Class { name_index: 38 }),
                Some(Constant::NameAndType { name_index: 39, descriptor_index: 40 }),
                Some(Constant::Utf8("java/lang/System".to_owned())),
                Some(Constant::Utf8("currentTimeMillis".to_owned())),
                Some(Constant::Utf8("()J".to_owned())),
                Some(Constant::Fieldref { class_index: 7, name_and_type_index: 42 }),
                Some(Constant::NameAndType { name_index: 43, descriptor_index: 44 }),
                Some(Constant::Utf8("shownAt".to_owned())),
                Some(Constant::Utf8("J".to_owned())),
                Some(Constant::Fieldref { class_index: 7, name_and_type_index: 46 }),
                Some(Constant::NameAndType { name_index: 47, descriptor_index: 48 }),
                Some(Constant::Utf8("indicator".to_owned())),
                Some(Constant::Utf8("Ljavax/microedition/lcdui/Gauge;".to_owned())),
                Some(Constant::Methodref { class_index: 50, name_and_type_index: 51 }),
                Some(Constant::Class { name_index: 52 }),
                Some(Constant::NameAndType { name_index: 53, descriptor_index: 54 }),
                Some(Constant::Utf8("javax/microedition/lcdui/Gauge".to_owned())),
                Some(Constant::Utf8("isInteractive".to_owned())),
                Some(Constant::Utf8("()Z".to_owned())),
                Some(Constant::Fieldref { class_index: 7, name_and_type_index: 56 }),
                Some(Constant::NameAndType { name_index: 57, descriptor_index: 58 }),
                Some(Constant::Utf8("next".to_owned())),
                Some(Constant::Utf8("Ljavax/microedition/lcdui/Displayable;".to_owned())),
                Some(Constant::Methodref { class_index: 60, name_and_type_index: 61 }),
                Some(Constant::Class { name_index: 62 }),
                Some(Constant::NameAndType { name_index: 63, descriptor_index: 64 }),
                Some(Constant::Utf8("javax/microedition/lcdui/Display".to_owned())),
                Some(Constant::Utf8("__returnFromAlert".to_owned())),
                Some(Constant::Utf8("(Ljavax/microedition/lcdui/Displayable;)V".to_owned())),
                Some(Constant::Fieldref { class_index: 66, name_and_type_index: 67 }),
                Some(Constant::Class { name_index: 68 }),
                Some(Constant::NameAndType { name_index: 69, descriptor_index: 28 }),
                Some(Constant::Utf8("javax/microedition/lcdui/AlertType".to_owned())),
                Some(Constant::Utf8("ERROR".to_owned())),
                Some(Constant::Integer(11141120)),
                Some(Constant::Fieldref { class_index: 66, name_and_type_index: 72 }),
                Some(Constant::NameAndType { name_index: 73, descriptor_index: 28 }),
                Some(Constant::Utf8("WARNING".to_owned())),
                Some(Constant::Integer(13399808)),
                Some(Constant::Integer(2379678)),
                Some(Constant::Methodref { class_index: 77, name_and_type_index: 78 }),
                Some(Constant::Class { name_index: 79 }),
                Some(Constant::NameAndType { name_index: 80, descriptor_index: 81 }),
                Some(Constant::Utf8("javax/microedition/lcdui/Graphics".to_owned())),
                Some(Constant::Utf8("setColor".to_owned())),
                Some(Constant::Utf8("(I)V".to_owned())),
                Some(Constant::Methodref { class_index: 77, name_and_type_index: 83 }),
                Some(Constant::NameAndType { name_index: 84, descriptor_index: 85 }),
                Some(Constant::Utf8("fillRect".to_owned())),
                Some(Constant::Utf8("(IIII)V".to_owned())),
                Some(Constant::Methodref { class_index: 77, name_and_type_index: 87 }),
                Some(Constant::NameAndType { name_index: 88, descriptor_index: 89 }),
                Some(Constant::Utf8("drawImage".to_owned())),
                Some(Constant::Utf8("(Ljavax/microedition/lcdui/Image;III)V".to_owned())),
                Some(Constant::Methodref { class_index: 91, name_and_type_index: 92 }),
                Some(Constant::Class { name_index: 93 }),
                Some(Constant::NameAndType { name_index: 94, descriptor_index: 95 }),
                Some(Constant::Utf8("javax/microedition/lcdui/Image".to_owned())),
                Some(Constant::Utf8("getHeight".to_owned())),
                Some(Constant::Utf8("()I".to_owned())),
                Some(Constant::Methodref { class_index: 77, name_and_type_index: 97 }),
                Some(Constant::NameAndType { name_index: 98, descriptor_index: 99 }),
                Some(Constant::Utf8("drawString".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;III)V".to_owned())),
                Some(Constant::Methodref { class_index: 50, name_and_type_index: 101 }),
                Some(Constant::NameAndType { name_index: 102, descriptor_index: 103 }),
                Some(Constant::Utf8("__paint".to_owned())),
                Some(Constant::Utf8("(Ljavax/microedition/lcdui/Graphics;IIIZ)V".to_owned())),
                Some(Constant::Class { name_index: 105 }),
                Some(Constant::Utf8("javax/microedition/lcdui/Command".to_owned())),
                Some(Constant::String { string_index: 107 }),
                Some(Constant::Utf8("Dismiss".to_owned())),
                Some(Constant::Methodref { class_index: 104, name_and_type_index: 109 }),
                Some(Constant::NameAndType { name_index: 5, descriptor_index: 110 }),
                Some(Constant::Utf8("(Ljava/lang/String;II)V".to_owned())),
                Some(Constant::Fieldref { class_index: 7, name_and_type_index: 112 }),
                Some(Constant::NameAndType { name_index: 113, descriptor_index: 114 }),
                Some(Constant::Utf8("DISMISS_COMMAND".to_owned())),
                Some(Constant::Utf8("Ljavax/microedition/lcdui/Command;".to_owned())),
                Some(Constant::Utf8("FOREVER".to_owned())),
                Some(Constant::Utf8("ConstantValue".to_owned())),
                Some(Constant::Integer(-2)),
                Some(Constant::Utf8("Code".to_owned())),
                Some(Constant::Utf8("LineNumberTable".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;Ljava/lang/String;Ljavax/microedition/lcdui/Image;Ljavax/microedition/lcdui/AlertType;)V".to_owned())),
                Some(Constant::Utf8("getString".to_owned())),
                Some(Constant::Utf8("()Ljava/lang/String;".to_owned())),
                Some(Constant::Utf8("setString".to_owned())),
                Some(Constant::Utf8("getImage".to_owned())),
                Some(Constant::Utf8("()Ljavax/microedition/lcdui/Image;".to_owned())),
                Some(Constant::Utf8("setImage".to_owned())),
                Some(Constant::Utf8("(Ljavax/microedition/lcdui/Image;)V".to_owned())),
                Some(Constant::Utf8("getType".to_owned())),
                Some(Constant::Utf8("()Ljavax/microedition/lcdui/AlertType;".to_owned())),
                Some(Constant::Utf8("setType".to_owned())),
                Some(Constant::Utf8("(Ljavax/microedition/lcdui/AlertType;)V".to_owned())),
                Some(Constant::Utf8("getTimeout".to_owned())),
                Some(Constant::Utf8("setTimeout".to_owned())),
                Some(Constant::Utf8("StackMapTable".to_owned())),
                Some(Constant::Utf8("getIndicator".to_owned())),
                Some(Constant::Utf8("()Ljavax/microedition/lcdui/Gauge;".to_owned())),
                Some(Constant::Utf8("setIndicator".to_owned())),
                Some(Constant::Utf8("(Ljavax/microedition/lcdui/Gauge;)V".to_owned())),
                Some(Constant::Utf8("showNotify".to_owned())),
                Some(Constant::Utf8("__setNext".to_owned())),
                Some(Constant::Utf8("__hostIdle".to_owned())),
                Some(Constant::Utf8("__keyPressed".to_owned())),
                Some(Constant::Utf8("__paintContent".to_owned())),
                Some(Constant::Utf8("(Ljavax/microedition/lcdui/Graphics;II)V".to_owned())),
                Some(Constant::Utf8("<clinit>".to_owned())),
                Some(Constant::Utf8("SourceFile".to_owned())),
                Some(Constant::Utf8("generated_bootstrap.rs".to_owned())),
            ],
            access_flags: 33,
            this_class: 7,
            super_class: 2,
            interfaces: vec![],
            fields: vec![
                Member { access_flags: 25, name_index: 115, descriptor_index: 12, attributes: vec![
                    Attribute::Raw { name_index: 116, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x75,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 113, descriptor_index: 114, attributes: Vec::new() },
                Member { access_flags: 2, name_index: 19, descriptor_index: 20, attributes: Vec::new() },
                Member { access_flags: 2, name_index: 23, descriptor_index: 24, attributes: Vec::new() },
                Member { access_flags: 2, name_index: 27, descriptor_index: 28, attributes: Vec::new() },
                Member { access_flags: 2, name_index: 11, descriptor_index: 12, attributes: Vec::new() },
                Member { access_flags: 2, name_index: 43, descriptor_index: 44, attributes: Vec::new() },
                Member { access_flags: 2, name_index: 47, descriptor_index: 48, attributes: Vec::new() },
                Member { access_flags: 2, name_index: 57, descriptor_index: 58, attributes: Vec::new() },
            ],
            methods: vec![
                Member { access_flags: 1, name_index: 5, descriptor_index: 16, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 118, max_stack: 2, max_locals: 2, code: vec![
                        0x2a, 0xb7, 0x00, 0x01, 0x2a, 0x10, 0xfe, 0xb5, 0x00, 0x09, 0x2a, 0x2b, 0xb6, 0x00, 0x0d, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 5, descriptor_index: 120, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 118, max_stack: 2, max_locals: 5, code: vec![
                        0x2a, 0xb7, 0x00, 0x01, 0x2a, 0x10, 0xfe, 0xb5, 0x00, 0x09, 0x2a, 0x2b, 0xb6, 0x00, 0x0d, 0x2a, 0x2c, 0xb5, 0x00, 0x11,
                        0x2a, 0x2d, 0xb5, 0x00, 0x15, 0x2a, 0x19, 0x04, 0xb5, 0x00, 0x19, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 121, descriptor_index: 122, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 118, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x11, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 123, descriptor_index: 16, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 118, max_stack: 2, max_locals: 2, code: vec![
                        0x2a, 0x2b, 0xb5, 0x00, 0x11, 0x2a, 0xb6, 0x00, 0x1d, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 124, descriptor_index: 125, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 118, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x15, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 126, descriptor_index: 127, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 118, max_stack: 2, max_locals: 2, code: vec![
                        0x2a, 0x2b, 0xb5, 0x00, 0x15, 0x2a, 0xb6, 0x00, 0x1d, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 128, descriptor_index: 129, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 118, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x19, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 130, descriptor_index: 131, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 118, max_stack: 2, max_locals: 2, code: vec![
                        0x2a, 0x2b, 0xb5, 0x00, 0x19, 0x2a, 0xb6, 0x00, 0x1d, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 132, descriptor_index: 95, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 118, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x09, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 133, descriptor_index: 81, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 118, max_stack: 3, max_locals: 2, code: vec![
                        0x1b, 0x9d, 0x00, 0x11, 0x1b, 0x10, 0xfe, 0x9f, 0x00, 0x0b, 0xbb, 0x00, 0x20, 0x59, 0xb7, 0x00, 0x22, 0xbf, 0x2a, 0x1b,
                        0xb5, 0x00, 0x09, 0x2a, 0xb8, 0x00, 0x23, 0xb5, 0x00, 0x29, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 135, descriptor_index: 136, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 118, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x2d, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 137, descriptor_index: 138, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 118, max_stack: 2, max_locals: 2, code: vec![
                        0x2b, 0xc6, 0x00, 0x12, 0x2b, 0xb6, 0x00, 0x31, 0x99, 0x00, 0x0b, 0xbb, 0x00, 0x20, 0x59, 0xb7, 0x00, 0x22, 0xbf, 0x2a,
                        0x2b, 0xb5, 0x00, 0x2d, 0x2a, 0xb6, 0x00, 0x1d, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 4, name_index: 139, descriptor_index: 6, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 118, max_stack: 3, max_locals: 1, code: vec![
                        0x2a, 0xb8, 0x00, 0x23, 0xb5, 0x00, 0x29, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 0, name_index: 140, descriptor_index: 64, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 118, max_stack: 2, max_locals: 2, code: vec![
                        0x2a, 0x2b, 0xb5, 0x00, 0x37, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 0, name_index: 141, descriptor_index: 6, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 118, max_stack: 4, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x09, 0x10, 0xfe, 0x9f, 0x00, 0x1b, 0xb8, 0x00, 0x23, 0x2a, 0xb4, 0x00, 0x29, 0x65, 0x2a, 0xb4, 0x00,
                        0x09, 0x85, 0x94, 0x9b, 0x00, 0x0a, 0x2a, 0xb4, 0x00, 0x37, 0xb8, 0x00, 0x3b, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 0, name_index: 142, descriptor_index: 81, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 118, max_stack: 2, max_locals: 2, code: vec![
                        0x1b, 0x10, 0xfb, 0x9f, 0x00, 0x15, 0x1b, 0x10, 0x35, 0x9f, 0x00, 0x0f, 0x1b, 0x10, 0x0a, 0x9f, 0x00, 0x09, 0x1b, 0x10,
                        0xf9, 0xa0, 0x00, 0x0a, 0x2a, 0xb4, 0x00, 0x37, 0xb8, 0x00, 0x3b, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 0, name_index: 143, descriptor_index: 144, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 118, max_stack: 6, max_locals: 5, code: vec![
                        0x1c, 0x10, 0x08, 0x60, 0x36, 0x04, 0x2b, 0x2a, 0xb4, 0x00, 0x19, 0xb2, 0x00, 0x41, 0xa6, 0x00, 0x08, 0x12, 0x46, 0xa7,
                        0x00, 0x14, 0x2a, 0xb4, 0x00, 0x19, 0xb2, 0x00, 0x47, 0xa6, 0x00, 0x08, 0x12, 0x4a, 0xa7, 0x00, 0x05, 0x12, 0x4b, 0xb6,
                        0x00, 0x4c, 0x2b, 0x10, 0x08, 0x15, 0x04, 0x11, 0x00, 0xe0, 0x06, 0xb6, 0x00, 0x52, 0x84, 0x04, 0x0a, 0x2b, 0x03, 0xb6,
                        0x00, 0x4c, 0x2a, 0xb4, 0x00, 0x15, 0xc6, 0x00, 0x1f, 0x2b, 0x2a, 0xb4, 0x00, 0x15, 0x10, 0x78, 0x15, 0x04, 0x10, 0x11,
                        0xb6, 0x00, 0x56, 0x15, 0x04, 0x2a, 0xb4, 0x00, 0x15, 0xb6, 0x00, 0x5a, 0x07, 0x60, 0x60, 0x36, 0x04, 0x2a, 0xb4, 0x00,
                        0x11, 0xc6, 0x00, 0x11, 0x2b, 0x2a, 0xb4, 0x00, 0x11, 0x10, 0x08, 0x15, 0x04, 0x10, 0x14, 0xb6, 0x00, 0x60, 0x2a, 0xb4,
                        0x00, 0x2d, 0xc6, 0x00, 0x16, 0x2a, 0xb4, 0x00, 0x2d, 0x2b, 0x10, 0x08, 0x15, 0x04, 0x10, 0x14, 0x60, 0x11, 0x00, 0xe0,
                        0x03, 0xb6, 0x00, 0x64, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 8, name_index: 145, descriptor_index: 6, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 118, max_stack: 5, max_locals: 0, code: vec![
                        0xbb, 0x00, 0x68, 0x59, 0x12, 0x6a, 0x07, 0x03, 0xb7, 0x00, 0x6c, 0xb3, 0x00, 0x6f, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
            ],
            attributes: Vec::new(),
        },
        // javax/microedition/lcdui/AlertType
        ClassFile {
            minor_version: 0,
            major_version: 48,
            constant_pool: vec![
                None,
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 3 }),
                Some(Constant::Class { name_index: 4 }),
                Some(Constant::NameAndType { name_index: 5, descriptor_index: 6 }),
                Some(Constant::Utf8("java/lang/Object".to_owned())),
                Some(Constant::Utf8("<init>".to_owned())),
                Some(Constant::Utf8("()V".to_owned())),
                Some(Constant::Class { name_index: 8 }),
                Some(Constant::Utf8("javax/microedition/lcdui/AlertType".to_owned())),
                Some(Constant::Methodref { class_index: 7, name_and_type_index: 3 }),
                Some(Constant::Fieldref { class_index: 7, name_and_type_index: 11 }),
                Some(Constant::NameAndType { name_index: 12, descriptor_index: 13 }),
                Some(Constant::Utf8("ALARM".to_owned())),
                Some(Constant::Utf8("Ljavax/microedition/lcdui/AlertType;".to_owned())),
                Some(Constant::Fieldref { class_index: 7, name_and_type_index: 15 }),
                Some(Constant::NameAndType { name_index: 16, descriptor_index: 13 }),
                Some(Constant::Utf8("CONFIRMATION".to_owned())),
                Some(Constant::Fieldref { class_index: 7, name_and_type_index: 18 }),
                Some(Constant::NameAndType { name_index: 19, descriptor_index: 13 }),
                Some(Constant::Utf8("ERROR".to_owned())),
                Some(Constant::Fieldref { class_index: 7, name_and_type_index: 21 }),
                Some(Constant::NameAndType { name_index: 22, descriptor_index: 13 }),
                Some(Constant::Utf8("INFO".to_owned())),
                Some(Constant::Fieldref { class_index: 7, name_and_type_index: 24 }),
                Some(Constant::NameAndType { name_index: 25, descriptor_index: 13 }),
                Some(Constant::Utf8("WARNING".to_owned())),
                Some(Constant::Utf8("Code".to_owned())),
                Some(Constant::Utf8("LineNumberTable".to_owned())),
                Some(Constant::Utf8("playSound".to_owned())),
                Some(Constant::Utf8("(Ljavax/microedition/lcdui/Display;)Z".to_owned())),
                Some(Constant::Utf8("StackMapTable".to_owned())),
                Some(Constant::Utf8("<clinit>".to_owned())),
                Some(Constant::Utf8("SourceFile".to_owned())),
                Some(Constant::Utf8("generated_bootstrap.rs".to_owned())),
            ],
            access_flags: 33,
            this_class: 7,
            super_class: 2,
            interfaces: vec![],
            fields: vec![
                Member { access_flags: 25, name_index: 12, descriptor_index: 13, attributes: Vec::new() },
                Member { access_flags: 25, name_index: 16, descriptor_index: 13, attributes: Vec::new() },
                Member { access_flags: 25, name_index: 19, descriptor_index: 13, attributes: Vec::new() },
                Member { access_flags: 25, name_index: 22, descriptor_index: 13, attributes: Vec::new() },
                Member { access_flags: 25, name_index: 25, descriptor_index: 13, attributes: Vec::new() },
            ],
            methods: vec![
                Member { access_flags: 4, name_index: 5, descriptor_index: 6, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 26, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb7, 0x00, 0x01, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 28, descriptor_index: 29, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 26, max_stack: 1, max_locals: 2, code: vec![
                        0x2b, 0xc6, 0x00, 0x07, 0x04, 0xa7, 0x00, 0x04, 0x03, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 8, name_index: 31, descriptor_index: 6, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 26, max_stack: 2, max_locals: 0, code: vec![
                        0xbb, 0x00, 0x07, 0x59, 0xb7, 0x00, 0x09, 0xb3, 0x00, 0x0a, 0xbb, 0x00, 0x07, 0x59, 0xb7, 0x00, 0x09, 0xb3, 0x00, 0x0e,
                        0xbb, 0x00, 0x07, 0x59, 0xb7, 0x00, 0x09, 0xb3, 0x00, 0x11, 0xbb, 0x00, 0x07, 0x59, 0xb7, 0x00, 0x09, 0xb3, 0x00, 0x14,
                        0xbb, 0x00, 0x07, 0x59, 0xb7, 0x00, 0x09, 0xb3, 0x00, 0x17, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
            ],
            attributes: Vec::new(),
        },
    );
}
