use super::{
    Attribute, ClassFile, CodeAttribute, Constant, Member, append_bootstrap_classes,
    build_bootstrap_class,
};

use super::super::choice_flags::ChoiceFlags;

const FLAGS: ChoiceFlags = ChoiceFlags {
    code_name: 152,
    entries: 17,
    size: 37,
    entry: 41,
    kind: 29,
    cursor: 82,
    selected: 88,
    is_selected: 92,
    invalidate: 62,
    null_exception: (26, 28),
    argument_exception: (23, 25),
};

pub(super) fn append_choices(classes: &mut Vec<ClassFile>) {
    append_bootstrap_classes!(classes;
        // javax/microedition/lcdui/Choice
        ClassFile {
            minor_version: 0,
            major_version: 48,
            constant_pool: vec![
                None,
                Some(Constant::Class { name_index: 2 }),
                Some(Constant::Utf8("javax/microedition/lcdui/Choice".to_owned())),
                Some(Constant::Class { name_index: 4 }),
                Some(Constant::Utf8("java/lang/Object".to_owned())),
                Some(Constant::Utf8("EXCLUSIVE".to_owned())),
                Some(Constant::Utf8("I".to_owned())),
                Some(Constant::Utf8("ConstantValue".to_owned())),
                Some(Constant::Integer(1)),
                Some(Constant::Utf8("MULTIPLE".to_owned())),
                Some(Constant::Integer(2)),
                Some(Constant::Utf8("IMPLICIT".to_owned())),
                Some(Constant::Integer(3)),
                Some(Constant::Utf8("POPUP".to_owned())),
                Some(Constant::Integer(4)),
                Some(Constant::Utf8("TEXT_WRAP_DEFAULT".to_owned())),
                Some(Constant::Integer(0)),
                Some(Constant::Utf8("TEXT_WRAP_ON".to_owned())),
                Some(Constant::Utf8("TEXT_WRAP_OFF".to_owned())),
                Some(Constant::Utf8("size".to_owned())),
                Some(Constant::Utf8("()I".to_owned())),
                Some(Constant::Utf8("getString".to_owned())),
                Some(Constant::Utf8("(I)Ljava/lang/String;".to_owned())),
                Some(Constant::Utf8("getImage".to_owned())),
                Some(Constant::Utf8("(I)Ljavax/microedition/lcdui/Image;".to_owned())),
                Some(Constant::Utf8("append".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;Ljavax/microedition/lcdui/Image;)I".to_owned())),
                Some(Constant::Utf8("insert".to_owned())),
                Some(Constant::Utf8("(ILjava/lang/String;Ljavax/microedition/lcdui/Image;)V".to_owned())),
                Some(Constant::Utf8("delete".to_owned())),
                Some(Constant::Utf8("(I)V".to_owned())),
                Some(Constant::Utf8("deleteAll".to_owned())),
                Some(Constant::Utf8("()V".to_owned())),
                Some(Constant::Utf8("set".to_owned())),
                Some(Constant::Utf8("isSelected".to_owned())),
                Some(Constant::Utf8("(I)Z".to_owned())),
                Some(Constant::Utf8("getSelectedIndex".to_owned())),
                Some(Constant::Utf8("getSelectedFlags".to_owned())),
                Some(Constant::Utf8("([Z)I".to_owned())),
                Some(Constant::Utf8("setSelectedIndex".to_owned())),
                Some(Constant::Utf8("(IZ)V".to_owned())),
                Some(Constant::Utf8("setSelectedFlags".to_owned())),
                Some(Constant::Utf8("([Z)V".to_owned())),
                Some(Constant::Utf8("setFitPolicy".to_owned())),
                Some(Constant::Utf8("getFitPolicy".to_owned())),
                Some(Constant::Utf8("setFont".to_owned())),
                Some(Constant::Utf8("(ILjavax/microedition/lcdui/Font;)V".to_owned())),
                Some(Constant::Utf8("getFont".to_owned())),
                Some(Constant::Utf8("(I)Ljavax/microedition/lcdui/Font;".to_owned())),
                Some(Constant::Utf8("SourceFile".to_owned())),
                Some(Constant::Utf8("generated_bootstrap.rs".to_owned())),
            ],
            access_flags: 1537,
            this_class: 1,
            super_class: 3,
            interfaces: vec![],
            fields: vec![
                Member { access_flags: 25, name_index: 5, descriptor_index: 6, attributes: vec![
                    Attribute::Raw { name_index: 7, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x08,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 9, descriptor_index: 6, attributes: vec![
                    Attribute::Raw { name_index: 7, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x0a,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 11, descriptor_index: 6, attributes: vec![
                    Attribute::Raw { name_index: 7, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x0c,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 13, descriptor_index: 6, attributes: vec![
                    Attribute::Raw { name_index: 7, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x0e,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 15, descriptor_index: 6, attributes: vec![
                    Attribute::Raw { name_index: 7, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x10,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 17, descriptor_index: 6, attributes: vec![
                    Attribute::Raw { name_index: 7, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x08,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 18, descriptor_index: 6, attributes: vec![
                    Attribute::Raw { name_index: 7, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x0a,
                    ] },
                ] },
            ],
            methods: vec![
                Member { access_flags: 1025, name_index: 19, descriptor_index: 20, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 21, descriptor_index: 22, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 23, descriptor_index: 24, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 25, descriptor_index: 26, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 27, descriptor_index: 28, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 29, descriptor_index: 30, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 31, descriptor_index: 32, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 33, descriptor_index: 28, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 34, descriptor_index: 35, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 36, descriptor_index: 20, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 37, descriptor_index: 38, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 39, descriptor_index: 40, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 41, descriptor_index: 42, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 43, descriptor_index: 30, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 44, descriptor_index: 20, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 45, descriptor_index: 46, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 47, descriptor_index: 48, attributes: Vec::new() },
            ],
            attributes: Vec::new(),
        },
        // javax/microedition/lcdui/ChoiceData
        ClassFile {
            minor_version: 0,
            major_version: 48,
            constant_pool: vec![
                None,
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 3 }),
                Some(Constant::Class { name_index: 4 }),
                Some(Constant::NameAndType { name_index: 5, descriptor_index: 6 }),
                Some(Constant::Utf8("java/lang/Object".to_owned())),
                Some(Constant::Utf8("<init>".to_owned())),
                Some(Constant::Utf8("()V".to_owned())),
                Some(Constant::Class { name_index: 8 }),
                Some(Constant::Utf8("java/lang/NullPointerException".to_owned())),
                Some(Constant::Methodref { class_index: 7, name_and_type_index: 3 }),
                Some(Constant::Fieldref { class_index: 11, name_and_type_index: 12 }),
                Some(Constant::Class { name_index: 13 }),
                Some(Constant::NameAndType { name_index: 14, descriptor_index: 15 }),
                Some(Constant::Utf8("javax/microedition/lcdui/ChoiceData".to_owned())),
                Some(Constant::Utf8("text".to_owned())),
                Some(Constant::Utf8("Ljava/lang/String;".to_owned())),
                Some(Constant::Fieldref { class_index: 11, name_and_type_index: 17 }),
                Some(Constant::NameAndType { name_index: 18, descriptor_index: 19 }),
                Some(Constant::Utf8("image".to_owned())),
                Some(Constant::Utf8("Ljavax/microedition/lcdui/Image;".to_owned())),
                Some(Constant::Utf8("font".to_owned())),
                Some(Constant::Utf8("Ljavax/microedition/lcdui/Font;".to_owned())),
                Some(Constant::Utf8("selected".to_owned())),
                Some(Constant::Utf8("Z".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;Ljavax/microedition/lcdui/Image;)V".to_owned())),
                Some(Constant::Utf8("Code".to_owned())),
                Some(Constant::Utf8("LineNumberTable".to_owned())),
                Some(Constant::Utf8("StackMapTable".to_owned())),
                Some(Constant::Class { name_index: 29 }),
                Some(Constant::Utf8("java/lang/String".to_owned())),
                Some(Constant::Class { name_index: 31 }),
                Some(Constant::Utf8("javax/microedition/lcdui/Image".to_owned())),
                Some(Constant::Utf8("SourceFile".to_owned())),
                Some(Constant::Utf8("generated_bootstrap.rs".to_owned())),
            ],
            access_flags: 48,
            this_class: 11,
            super_class: 2,
            interfaces: vec![],
            fields: vec![
                Member { access_flags: 0, name_index: 14, descriptor_index: 15, attributes: Vec::new() },
                Member { access_flags: 0, name_index: 18, descriptor_index: 19, attributes: Vec::new() },
                Member { access_flags: 0, name_index: 20, descriptor_index: 21, attributes: Vec::new() },
                Member { access_flags: 0, name_index: 22, descriptor_index: 23, attributes: Vec::new() },
            ],
            methods: vec![
                Member { access_flags: 0, name_index: 5, descriptor_index: 24, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 25, max_stack: 2, max_locals: 3, code: vec![
                        0x2a, 0xb7, 0x00, 0x01, 0x2b, 0xc7, 0x00, 0x0b, 0xbb, 0x00, 0x07, 0x59, 0xb7, 0x00, 0x09, 0xbf, 0x2a, 0x2b, 0xb5, 0x00,
                        0x0a, 0x2a, 0x2c, 0xb5, 0x00, 0x10, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
            ],
            attributes: Vec::new(),
        },
        // javax/microedition/lcdui/ChoiceGroup
        ClassFile {
            minor_version: 0,
            major_version: 48,
            constant_pool: vec![
                None,
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 3 }),
                Some(Constant::Class { name_index: 4 }),
                Some(Constant::NameAndType { name_index: 5, descriptor_index: 6 }),
                Some(Constant::Utf8("javax/microedition/lcdui/ChoiceGroup".to_owned())),
                Some(Constant::Utf8("<init>".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;I[Ljava/lang/String;[Ljavax/microedition/lcdui/Image;)V".to_owned())),
                Some(Constant::Methodref { class_index: 8, name_and_type_index: 9 }),
                Some(Constant::Class { name_index: 10 }),
                Some(Constant::NameAndType { name_index: 5, descriptor_index: 11 }),
                Some(Constant::Utf8("javax/microedition/lcdui/Item".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;)V".to_owned())),
                Some(Constant::Class { name_index: 13 }),
                Some(Constant::Utf8("java/util/Vector".to_owned())),
                Some(Constant::Methodref { class_index: 12, name_and_type_index: 15 }),
                Some(Constant::NameAndType { name_index: 5, descriptor_index: 16 }),
                Some(Constant::Utf8("()V".to_owned())),
                Some(Constant::Fieldref { class_index: 2, name_and_type_index: 18 }),
                Some(Constant::NameAndType { name_index: 19, descriptor_index: 20 }),
                Some(Constant::Utf8("entries".to_owned())),
                Some(Constant::Utf8("Ljava/util/Vector;".to_owned())),
                Some(Constant::Class { name_index: 22 }),
                Some(Constant::Utf8("javax/microedition/lcdui/Choice".to_owned())),
                Some(Constant::Class { name_index: 24 }),
                Some(Constant::Utf8("java/lang/IllegalArgumentException".to_owned())),
                Some(Constant::Methodref { class_index: 23, name_and_type_index: 15 }),
                Some(Constant::Class { name_index: 27 }),
                Some(Constant::Utf8("java/lang/NullPointerException".to_owned())),
                Some(Constant::Methodref { class_index: 26, name_and_type_index: 15 }),
                Some(Constant::Fieldref { class_index: 2, name_and_type_index: 30 }),
                Some(Constant::NameAndType { name_index: 31, descriptor_index: 32 }),
                Some(Constant::Utf8("type".to_owned())),
                Some(Constant::Utf8("I".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 34 }),
                Some(Constant::NameAndType { name_index: 35, descriptor_index: 36 }),
                Some(Constant::Utf8("append".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;Ljavax/microedition/lcdui/Image;)I".to_owned())),
                Some(Constant::Methodref { class_index: 12, name_and_type_index: 38 }),
                Some(Constant::NameAndType { name_index: 39, descriptor_index: 40 }),
                Some(Constant::Utf8("size".to_owned())),
                Some(Constant::Utf8("()I".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 42 }),
                Some(Constant::NameAndType { name_index: 43, descriptor_index: 44 }),
                Some(Constant::Utf8("entry".to_owned())),
                Some(Constant::Utf8("(I)Ljavax/microedition/lcdui/ChoiceData;".to_owned())),
                Some(Constant::Fieldref { class_index: 46, name_and_type_index: 47 }),
                Some(Constant::Class { name_index: 48 }),
                Some(Constant::NameAndType { name_index: 49, descriptor_index: 50 }),
                Some(Constant::Utf8("javax/microedition/lcdui/ChoiceData".to_owned())),
                Some(Constant::Utf8("text".to_owned())),
                Some(Constant::Utf8("Ljava/lang/String;".to_owned())),
                Some(Constant::Fieldref { class_index: 46, name_and_type_index: 52 }),
                Some(Constant::NameAndType { name_index: 53, descriptor_index: 54 }),
                Some(Constant::Utf8("image".to_owned())),
                Some(Constant::Utf8("Ljavax/microedition/lcdui/Image;".to_owned())),
                Some(Constant::Methodref { class_index: 46, name_and_type_index: 56 }),
                Some(Constant::NameAndType { name_index: 5, descriptor_index: 57 }),
                Some(Constant::Utf8("(Ljava/lang/String;Ljavax/microedition/lcdui/Image;)V".to_owned())),
                Some(Constant::Methodref { class_index: 12, name_and_type_index: 59 }),
                Some(Constant::NameAndType { name_index: 60, descriptor_index: 61 }),
                Some(Constant::Utf8("addElement".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/Object;)V".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 63 }),
                Some(Constant::NameAndType { name_index: 64, descriptor_index: 16 }),
                Some(Constant::Utf8("invalidate".to_owned())),
                Some(Constant::Class { name_index: 66 }),
                Some(Constant::Utf8("java/lang/IndexOutOfBoundsException".to_owned())),
                Some(Constant::Methodref { class_index: 65, name_and_type_index: 15 }),
                Some(Constant::Methodref { class_index: 12, name_and_type_index: 69 }),
                Some(Constant::NameAndType { name_index: 70, descriptor_index: 71 }),
                Some(Constant::Utf8("insertElementAt".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/Object;I)V".to_owned())),
                Some(Constant::Methodref { class_index: 12, name_and_type_index: 73 }),
                Some(Constant::NameAndType { name_index: 74, descriptor_index: 75 }),
                Some(Constant::Utf8("removeElementAt".to_owned())),
                Some(Constant::Utf8("(I)V".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 77 }),
                Some(Constant::NameAndType { name_index: 78, descriptor_index: 16 }),
                Some(Constant::Utf8("normalize".to_owned())),
                Some(Constant::Methodref { class_index: 12, name_and_type_index: 80 }),
                Some(Constant::NameAndType { name_index: 81, descriptor_index: 16 }),
                Some(Constant::Utf8("removeAllElements".to_owned())),
                Some(Constant::Fieldref { class_index: 2, name_and_type_index: 83 }),
                Some(Constant::NameAndType { name_index: 84, descriptor_index: 32 }),
                Some(Constant::Utf8("cursor".to_owned())),
                Some(Constant::Methodref { class_index: 12, name_and_type_index: 86 }),
                Some(Constant::NameAndType { name_index: 87, descriptor_index: 71 }),
                Some(Constant::Utf8("setElementAt".to_owned())),
                Some(Constant::Fieldref { class_index: 46, name_and_type_index: 89 }),
                Some(Constant::NameAndType { name_index: 90, descriptor_index: 91 }),
                Some(Constant::Utf8("selected".to_owned())),
                Some(Constant::Utf8("Z".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 93 }),
                Some(Constant::NameAndType { name_index: 94, descriptor_index: 95 }),
                Some(Constant::Utf8("isSelected".to_owned())),
                Some(Constant::Utf8("(I)Z".to_owned())),
                Some(Constant::Fieldref { class_index: 2, name_and_type_index: 97 }),
                Some(Constant::NameAndType { name_index: 98, descriptor_index: 32 }),
                Some(Constant::Utf8("fitPolicy".to_owned())),
                Some(Constant::Fieldref { class_index: 46, name_and_type_index: 100 }),
                Some(Constant::NameAndType { name_index: 101, descriptor_index: 102 }),
                Some(Constant::Utf8("font".to_owned())),
                Some(Constant::Utf8("Ljavax/microedition/lcdui/Font;".to_owned())),
                Some(Constant::Methodref { class_index: 104, name_and_type_index: 105 }),
                Some(Constant::Class { name_index: 106 }),
                Some(Constant::NameAndType { name_index: 107, descriptor_index: 108 }),
                Some(Constant::Utf8("javax/microedition/lcdui/Font".to_owned())),
                Some(Constant::Utf8("getDefaultFont".to_owned())),
                Some(Constant::Utf8("()Ljavax/microedition/lcdui/Font;".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 110 }),
                Some(Constant::NameAndType { name_index: 111, descriptor_index: 112 }),
                Some(Constant::Utf8("getLabel".to_owned())),
                Some(Constant::Utf8("()Ljava/lang/String;".to_owned())),
                Some(Constant::Methodref { class_index: 104, name_and_type_index: 114 }),
                Some(Constant::NameAndType { name_index: 115, descriptor_index: 40 }),
                Some(Constant::Utf8("getHeight".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 117 }),
                Some(Constant::NameAndType { name_index: 118, descriptor_index: 16 }),
                Some(Constant::Utf8("notifyStateChanged".to_owned())),
                Some(Constant::Methodref { class_index: 120, name_and_type_index: 121 }),
                Some(Constant::Class { name_index: 122 }),
                Some(Constant::NameAndType { name_index: 123, descriptor_index: 75 }),
                Some(Constant::Utf8("javax/microedition/lcdui/Graphics".to_owned())),
                Some(Constant::Utf8("setColor".to_owned())),
                Some(Constant::Methodref { class_index: 120, name_and_type_index: 125 }),
                Some(Constant::NameAndType { name_index: 126, descriptor_index: 127 }),
                Some(Constant::Utf8("drawString".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;III)V".to_owned())),
                Some(Constant::Integer(2379678)),
                Some(Constant::String { string_index: 130 }),
                Some(Constant::Utf8("[x] ".to_owned())),
                Some(Constant::String { string_index: 132 }),
                Some(Constant::Utf8("[ ] ".to_owned())),
                Some(Constant::String { string_index: 134 }),
                Some(Constant::Utf8("(*) ".to_owned())),
                Some(Constant::String { string_index: 136 }),
                Some(Constant::Utf8("( ) ".to_owned())),
                Some(Constant::Methodref { class_index: 138, name_and_type_index: 139 }),
                Some(Constant::Class { name_index: 140 }),
                Some(Constant::NameAndType { name_index: 141, descriptor_index: 142 }),
                Some(Constant::Utf8("java/lang/String".to_owned())),
                Some(Constant::Utf8("concat".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;)Ljava/lang/String;".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 144 }),
                Some(Constant::NameAndType { name_index: 145, descriptor_index: 146 }),
                Some(Constant::Utf8("getFont".to_owned())),
                Some(Constant::Utf8("(I)Ljavax/microedition/lcdui/Font;".to_owned())),
                Some(Constant::Methodref { class_index: 12, name_and_type_index: 148 }),
                Some(Constant::NameAndType { name_index: 149, descriptor_index: 150 }),
                Some(Constant::Utf8("elementAt".to_owned())),
                Some(Constant::Utf8("(I)Ljava/lang/Object;".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;I)V".to_owned())),
                Some(Constant::Utf8("Code".to_owned())),
                Some(Constant::Utf8("LineNumberTable".to_owned())),
                Some(Constant::Utf8("StackMapTable".to_owned())),
                Some(Constant::Class { name_index: 156 }),
                Some(Constant::Utf8("[Ljava/lang/String;".to_owned())),
                Some(Constant::Class { name_index: 158 }),
                Some(Constant::Utf8("[Ljavax/microedition/lcdui/Image;".to_owned())),
                Some(Constant::Class { name_index: 160 }),
                Some(Constant::Utf8("javax/microedition/lcdui/Image".to_owned())),
                Some(Constant::Utf8("getString".to_owned())),
                Some(Constant::Utf8("(I)Ljava/lang/String;".to_owned())),
                Some(Constant::Utf8("getImage".to_owned())),
                Some(Constant::Utf8("(I)Ljavax/microedition/lcdui/Image;".to_owned())),
                Some(Constant::Utf8("insert".to_owned())),
                Some(Constant::Utf8("(ILjava/lang/String;Ljavax/microedition/lcdui/Image;)V".to_owned())),
                Some(Constant::Utf8("delete".to_owned())),
                Some(Constant::Utf8("deleteAll".to_owned())),
                Some(Constant::Utf8("set".to_owned())),
                Some(Constant::Utf8("getSelectedIndex".to_owned())),
                Some(Constant::Utf8("getSelectedFlags".to_owned())),
                Some(Constant::Utf8("([Z)I".to_owned())),
                Some(Constant::Class { name_index: 174 }),
                Some(Constant::Utf8("[Z".to_owned())),
                Some(Constant::Utf8("setSelectedIndex".to_owned())),
                Some(Constant::Utf8("(IZ)V".to_owned())),
                Some(Constant::Utf8("setSelectedFlags".to_owned())),
                Some(Constant::Utf8("([Z)V".to_owned())),
                Some(Constant::Utf8("setFitPolicy".to_owned())),
                Some(Constant::Utf8("getFitPolicy".to_owned())),
                Some(Constant::Utf8("setFont".to_owned())),
                Some(Constant::Utf8("(ILjavax/microedition/lcdui/Font;)V".to_owned())),
                Some(Constant::Utf8("__height".to_owned())),
                Some(Constant::Utf8("(I)I".to_owned())),
                Some(Constant::Utf8("__key".to_owned())),
                Some(Constant::Utf8("__paint".to_owned())),
                Some(Constant::Utf8("(Ljavax/microedition/lcdui/Graphics;IIIZ)V".to_owned())),
                Some(Constant::Utf8("SourceFile".to_owned())),
                Some(Constant::Utf8("generated_bootstrap.rs".to_owned())),
            ],
            access_flags: 33,
            this_class: 2,
            super_class: 8,
            interfaces: vec![21],
            fields: vec![
                Member { access_flags: 18, name_index: 31, descriptor_index: 32, attributes: Vec::new() },
                Member { access_flags: 18, name_index: 19, descriptor_index: 20, attributes: Vec::new() },
                Member { access_flags: 2, name_index: 84, descriptor_index: 32, attributes: Vec::new() },
                Member { access_flags: 2, name_index: 98, descriptor_index: 32, attributes: Vec::new() },
            ],
            methods: vec![
                Member { access_flags: 1, name_index: 5, descriptor_index: 151, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 152, max_stack: 5, max_locals: 3, code: vec![
                        0x2a, 0x2b, 0x1c, 0x01, 0x01, 0xb7, 0x00, 0x01, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 5, descriptor_index: 6, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 152, max_stack: 4, max_locals: 6, code: vec![
                        0x2a, 0x2b, 0xb7, 0x00, 0x07, 0x2a, 0xbb, 0x00, 0x0c, 0x59, 0xb7, 0x00, 0x0e, 0xb5, 0x00, 0x11, 0x1c, 0x04, 0x9f, 0x00,
                        0x15, 0x1c, 0x05, 0x9f, 0x00, 0x10, 0x1c, 0x07, 0x9f, 0x00, 0x0b, 0xbb, 0x00, 0x17, 0x59, 0xb7, 0x00, 0x19, 0xbf, 0x2d,
                        0xc7, 0x00, 0x10, 0x19, 0x04, 0xc6, 0x00, 0x0b, 0xbb, 0x00, 0x1a, 0x59, 0xb7, 0x00, 0x1c, 0xbf, 0x19, 0x04, 0xc6, 0x00,
                        0x13, 0x19, 0x04, 0xbe, 0x2d, 0xbe, 0x9f, 0x00, 0x0b, 0xbb, 0x00, 0x17, 0x59, 0xb7, 0x00, 0x19, 0xbf, 0x2a, 0x1c, 0xb5,
                        0x00, 0x1d, 0x2d, 0xc6, 0x00, 0x2a, 0x03, 0x36, 0x05, 0x15, 0x05, 0x2d, 0xbe, 0xa2, 0x00, 0x20, 0x2a, 0x2d, 0x15, 0x05,
                        0x32, 0x19, 0x04, 0xc7, 0x00, 0x07, 0x01, 0xa7, 0x00, 0x08, 0x19, 0x04, 0x15, 0x05, 0x32, 0xb6, 0x00, 0x21, 0x57, 0x84,
                        0x05, 0x01, 0xa7, 0xff, 0xdf, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 39, descriptor_index: 40, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 152, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x11, 0xb6, 0x00, 0x25, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 161, descriptor_index: 162, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 152, max_stack: 2, max_locals: 2, code: vec![
                        0x2a, 0x1b, 0xb7, 0x00, 0x29, 0xb4, 0x00, 0x2d, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 163, descriptor_index: 164, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 152, max_stack: 2, max_locals: 2, code: vec![
                        0x2a, 0x1b, 0xb7, 0x00, 0x29, 0xb4, 0x00, 0x33, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 35, descriptor_index: 36, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 152, max_stack: 5, max_locals: 3, code: vec![
                        0x2a, 0xb4, 0x00, 0x11, 0xbb, 0x00, 0x2e, 0x59, 0x2b, 0x2c, 0xb7, 0x00, 0x37, 0xb6, 0x00, 0x3a, 0x2a, 0xb6, 0x00, 0x3e,
                        0x2a, 0xb4, 0x00, 0x11, 0xb6, 0x00, 0x25, 0x04, 0x64, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 165, descriptor_index: 166, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 152, max_stack: 5, max_locals: 4, code: vec![
                        0x1b, 0x9b, 0x00, 0x0e, 0x1b, 0x2a, 0xb4, 0x00, 0x11, 0xb6, 0x00, 0x25, 0xa4, 0x00, 0x0b, 0xbb, 0x00, 0x41, 0x59, 0xb7,
                        0x00, 0x43, 0xbf, 0x2a, 0xb4, 0x00, 0x11, 0xbb, 0x00, 0x2e, 0x59, 0x2c, 0x2d, 0xb7, 0x00, 0x37, 0x1b, 0xb6, 0x00, 0x44,
                        0x2a, 0xb6, 0x00, 0x3e, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 167, descriptor_index: 75, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 152, max_stack: 2, max_locals: 2, code: vec![
                        0x2a, 0x1b, 0xb7, 0x00, 0x29, 0x57, 0x2a, 0xb4, 0x00, 0x11, 0x1b, 0xb6, 0x00, 0x48, 0x2a, 0xb7, 0x00, 0x4c, 0x2a, 0xb6,
                        0x00, 0x3e, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 168, descriptor_index: 16, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 152, max_stack: 2, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x11, 0xb6, 0x00, 0x4f, 0x2a, 0x03, 0xb5, 0x00, 0x52, 0x2a, 0xb6, 0x00, 0x3e, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 169, descriptor_index: 166, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 152, max_stack: 5, max_locals: 4, code: vec![
                        0x2a, 0xb4, 0x00, 0x11, 0xbb, 0x00, 0x2e, 0x59, 0x2c, 0x2d, 0xb7, 0x00, 0x37, 0x1b, 0xb6, 0x00, 0x55, 0x2a, 0xb6, 0x00,
                        0x3e, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 94, descriptor_index: 95, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 152, max_stack: 2, max_locals: 3, code: vec![
                        0x2a, 0x1b, 0xb7, 0x00, 0x29, 0x4d, 0x2a, 0xb4, 0x00, 0x1d, 0x05, 0xa0, 0x00, 0x0a, 0x2c, 0xb4, 0x00, 0x58, 0xa7, 0x00,
                        0x10, 0x1b, 0x2a, 0xb4, 0x00, 0x52, 0xa0, 0x00, 0x07, 0x04, 0xa7, 0x00, 0x04, 0x03, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 170, descriptor_index: 40, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 152, max_stack: 2, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x1d, 0x05, 0x9f, 0x00, 0x0d, 0x2a, 0xb4, 0x00, 0x11, 0xb6, 0x00, 0x25, 0x9a, 0x00, 0x07, 0x02, 0xa7,
                        0x00, 0x07, 0x2a, 0xb4, 0x00, 0x52, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 171, descriptor_index: 172, attributes: vec![
                    Attribute::Code(FLAGS.get()),
                ] },
                Member { access_flags: 1, name_index: 175, descriptor_index: 176, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 152, max_stack: 2, max_locals: 4, code: vec![
                        0x2a, 0x1b, 0xb7, 0x00, 0x29, 0x4e, 0x2a, 0xb4, 0x00, 0x1d, 0x05, 0xa0, 0x00, 0x0b, 0x2d, 0x1c, 0xb5, 0x00, 0x58, 0xa7,
                        0x00, 0x0c, 0x1c, 0x99, 0x00, 0x08, 0x2a, 0x1b, 0xb5, 0x00, 0x52, 0x2a, 0xb6, 0x00, 0x3e, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 177, descriptor_index: 178, attributes: vec![
                    Attribute::Code(FLAGS.set()),
                ] },
                Member { access_flags: 1, name_index: 179, descriptor_index: 75, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 152, max_stack: 2, max_locals: 2, code: vec![
                        0x1b, 0x9b, 0x00, 0x08, 0x1b, 0x05, 0xa4, 0x00, 0x0b, 0xbb, 0x00, 0x17, 0x59, 0xb7, 0x00, 0x19, 0xbf, 0x2a, 0x1b, 0xb5,
                        0x00, 0x60, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 180, descriptor_index: 40, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 152, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x60, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 181, descriptor_index: 182, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 152, max_stack: 2, max_locals: 3, code: vec![
                        0x2a, 0x1b, 0xb7, 0x00, 0x29, 0x2c, 0xb5, 0x00, 0x63, 0x2a, 0xb6, 0x00, 0x3e, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 145, descriptor_index: 146, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 152, max_stack: 2, max_locals: 3, code: vec![
                        0x2a, 0x1b, 0xb7, 0x00, 0x29, 0xb4, 0x00, 0x63, 0x4d, 0x2c, 0xc7, 0x00, 0x09, 0xb8, 0x00, 0x67, 0xa7, 0x00, 0x04, 0x2c,
                        0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 0, name_index: 183, descriptor_index: 184, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 152, max_stack: 4, max_locals: 2, code: vec![
                        0x2a, 0xb6, 0x00, 0x6d, 0xc7, 0x00, 0x07, 0x03, 0xa7, 0x00, 0x0b, 0xb8, 0x00, 0x67, 0xb6, 0x00, 0x71, 0x04, 0x60, 0x2a,
                        0xb4, 0x00, 0x11, 0xb6, 0x00, 0x25, 0xb8, 0x00, 0x67, 0xb6, 0x00, 0x71, 0x06, 0x60, 0x68, 0x60, 0x06, 0x60, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 0, name_index: 185, descriptor_index: 75, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 152, max_stack: 3, max_locals: 3, code: vec![
                        0x2a, 0xb4, 0x00, 0x11, 0xb6, 0x00, 0x25, 0x9a, 0x00, 0x04, 0xb1, 0x03, 0x3d, 0x1b, 0x02, 0x9f, 0x00, 0x15, 0x1b, 0x10,
                        0xfd, 0x9f, 0x00, 0x0f, 0x1b, 0x10, 0x32, 0x9f, 0x00, 0x09, 0x1b, 0x10, 0x34, 0xa0, 0x00, 0x20, 0x2a, 0x2a, 0xb4, 0x00,
                        0x52, 0x2a, 0xb4, 0x00, 0x11, 0xb6, 0x00, 0x25, 0x60, 0x04, 0x64, 0x2a, 0xb4, 0x00, 0x11, 0xb6, 0x00, 0x25, 0x70, 0xb5,
                        0x00, 0x52, 0xa7, 0x00, 0x89, 0x1b, 0x10, 0xfe, 0x9f, 0x00, 0x15, 0x1b, 0x10, 0xfc, 0x9f, 0x00, 0x0f, 0x1b, 0x10, 0x38,
                        0x9f, 0x00, 0x09, 0x1b, 0x10, 0x36, 0xa0, 0x00, 0x18, 0x2a, 0x2a, 0xb4, 0x00, 0x52, 0x04, 0x60, 0x2a, 0xb4, 0x00, 0x11,
                        0xb6, 0x00, 0x25, 0x70, 0xb5, 0x00, 0x52, 0xa7, 0x00, 0x5c, 0x1b, 0x10, 0xfb, 0x9f, 0x00, 0x0f, 0x1b, 0x10, 0x35, 0x9f,
                        0x00, 0x09, 0x1b, 0x10, 0x0a, 0xa0, 0x00, 0x4a, 0x2a, 0xb4, 0x00, 0x1d, 0x05, 0xa0, 0x00, 0x26, 0x2a, 0x2a, 0xb4, 0x00,
                        0x52, 0xb7, 0x00, 0x29, 0x2a, 0x2a, 0xb4, 0x00, 0x52, 0xb7, 0x00, 0x29, 0xb4, 0x00, 0x58, 0x9a, 0x00, 0x07, 0x04, 0xa7,
                        0x00, 0x04, 0x03, 0xb5, 0x00, 0x58, 0x04, 0x3d, 0xa7, 0x00, 0x1f, 0x2a, 0x2a, 0xb4, 0x00, 0x52, 0xb7, 0x00, 0x29, 0xb4,
                        0x00, 0x58, 0x9a, 0x00, 0x11, 0x2a, 0x2a, 0xb4, 0x00, 0x52, 0xb7, 0x00, 0x29, 0x04, 0xb5, 0x00, 0x58, 0x04, 0x3d, 0x2a,
                        0xb6, 0x00, 0x3e, 0x1c, 0x99, 0x00, 0x07, 0x2a, 0xb6, 0x00, 0x74, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 0, name_index: 186, descriptor_index: 187, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 152, max_stack: 5, max_locals: 9, code: vec![
                        0x2b, 0x03, 0xb6, 0x00, 0x77, 0x2a, 0xb6, 0x00, 0x6d, 0xc6, 0x00, 0x1a, 0x2b, 0x2a, 0xb6, 0x00, 0x6d, 0x1c, 0x1d, 0x10,
                        0x14, 0xb6, 0x00, 0x7c, 0x1d, 0xb8, 0x00, 0x67, 0xb6, 0x00, 0x71, 0x04, 0x60, 0x60, 0x3e, 0x03, 0x36, 0x06, 0x15, 0x06,
                        0x2a, 0xb4, 0x00, 0x11, 0xb6, 0x00, 0x25, 0xa2, 0x00, 0x75, 0x2a, 0x15, 0x06, 0xb7, 0x00, 0x29, 0x3a, 0x07, 0x2b, 0x15,
                        0x05, 0x99, 0x00, 0x11, 0x15, 0x06, 0x2a, 0xb4, 0x00, 0x52, 0xa0, 0x00, 0x08, 0x12, 0x80, 0xa7, 0x00, 0x04, 0x03, 0xb6,
                        0x00, 0x77, 0x2a, 0xb4, 0x00, 0x1d, 0x05, 0xa0, 0x00, 0x15, 0x19, 0x07, 0xb4, 0x00, 0x58, 0x99, 0x00, 0x08, 0x12, 0x81,
                        0xa7, 0x00, 0x18, 0x12, 0x83, 0xa7, 0x00, 0x13, 0x15, 0x06, 0x2a, 0xb4, 0x00, 0x52, 0xa0, 0x00, 0x08, 0x12, 0x85, 0xa7,
                        0x00, 0x05, 0x12, 0x87, 0x3a, 0x08, 0x2b, 0x19, 0x08, 0x19, 0x07, 0xb4, 0x00, 0x2d, 0xb6, 0x00, 0x89, 0x1c, 0x1d, 0x10,
                        0x14, 0xb6, 0x00, 0x7c, 0x1d, 0x2a, 0x15, 0x06, 0xb6, 0x00, 0x8f, 0xb6, 0x00, 0x71, 0x06, 0x60, 0x60, 0x3e, 0x84, 0x06,
                        0x01, 0xa7, 0xff, 0x85, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 2, name_index: 43, descriptor_index: 44, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 152, max_stack: 2, max_locals: 2, code: vec![
                        0x2a, 0xb4, 0x00, 0x11, 0x1b, 0xb6, 0x00, 0x93, 0xc0, 0x00, 0x2e, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 2, name_index: 78, descriptor_index: 16, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 152, max_stack: 3, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x52, 0x2a, 0xb4, 0x00, 0x11, 0xb6, 0x00, 0x25, 0xa1, 0x00, 0x10, 0x2a, 0x2a, 0xb4, 0x00, 0x11, 0xb6,
                        0x00, 0x25, 0x04, 0x64, 0xb5, 0x00, 0x52, 0x2a, 0xb4, 0x00, 0x52, 0x9c, 0x00, 0x08, 0x2a, 0x03, 0xb5, 0x00, 0x52, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
            ],
            attributes: Vec::new(),
        },
    );
}
