use super::{
    Attribute, ClassFile, CodeAttribute, Constant, Member, append_bootstrap_classes,
    build_bootstrap_class,
};

pub(super) fn append_commands_items(classes: &mut Vec<ClassFile>) {
    append_bootstrap_classes!(classes;
        // javax/microedition/lcdui/Command
        ClassFile {
            minor_version: 0,
            major_version: 48,
            constant_pool: vec![
                None,
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 3 }),
                Some(Constant::Class { name_index: 4 }),
                Some(Constant::NameAndType { name_index: 5, descriptor_index: 6 }),
                Some(Constant::Utf8("javax/microedition/lcdui/Command".to_owned())),
                Some(Constant::Utf8("<init>".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;Ljava/lang/String;II)V".to_owned())),
                Some(Constant::Methodref { class_index: 8, name_and_type_index: 9 }),
                Some(Constant::Class { name_index: 10 }),
                Some(Constant::NameAndType { name_index: 5, descriptor_index: 11 }),
                Some(Constant::Utf8("java/lang/Object".to_owned())),
                Some(Constant::Utf8("()V".to_owned())),
                Some(Constant::Class { name_index: 13 }),
                Some(Constant::Utf8("java/lang/NullPointerException".to_owned())),
                Some(Constant::Methodref { class_index: 12, name_and_type_index: 9 }),
                Some(Constant::Class { name_index: 16 }),
                Some(Constant::Utf8("java/lang/IllegalArgumentException".to_owned())),
                Some(Constant::Methodref { class_index: 15, name_and_type_index: 9 }),
                Some(Constant::Fieldref { class_index: 2, name_and_type_index: 19 }),
                Some(Constant::NameAndType { name_index: 20, descriptor_index: 21 }),
                Some(Constant::Utf8("shortLabel".to_owned())),
                Some(Constant::Utf8("Ljava/lang/String;".to_owned())),
                Some(Constant::Fieldref { class_index: 2, name_and_type_index: 23 }),
                Some(Constant::NameAndType { name_index: 24, descriptor_index: 21 }),
                Some(Constant::Utf8("longLabel".to_owned())),
                Some(Constant::Fieldref { class_index: 2, name_and_type_index: 26 }),
                Some(Constant::NameAndType { name_index: 27, descriptor_index: 28 }),
                Some(Constant::Utf8("type".to_owned())),
                Some(Constant::Utf8("I".to_owned())),
                Some(Constant::Fieldref { class_index: 2, name_and_type_index: 30 }),
                Some(Constant::NameAndType { name_index: 31, descriptor_index: 28 }),
                Some(Constant::Utf8("priority".to_owned())),
                Some(Constant::Utf8("SCREEN".to_owned())),
                Some(Constant::Utf8("ConstantValue".to_owned())),
                Some(Constant::Integer(1)),
                Some(Constant::Utf8("BACK".to_owned())),
                Some(Constant::Integer(2)),
                Some(Constant::Utf8("CANCEL".to_owned())),
                Some(Constant::Integer(3)),
                Some(Constant::Utf8("OK".to_owned())),
                Some(Constant::Integer(4)),
                Some(Constant::Utf8("HELP".to_owned())),
                Some(Constant::Integer(5)),
                Some(Constant::Utf8("STOP".to_owned())),
                Some(Constant::Integer(6)),
                Some(Constant::Utf8("EXIT".to_owned())),
                Some(Constant::Integer(7)),
                Some(Constant::Utf8("ITEM".to_owned())),
                Some(Constant::Integer(8)),
                Some(Constant::Utf8("(Ljava/lang/String;II)V".to_owned())),
                Some(Constant::Utf8("Code".to_owned())),
                Some(Constant::Utf8("LineNumberTable".to_owned())),
                Some(Constant::Utf8("StackMapTable".to_owned())),
                Some(Constant::Class { name_index: 54 }),
                Some(Constant::Utf8("java/lang/String".to_owned())),
                Some(Constant::Utf8("getLabel".to_owned())),
                Some(Constant::Utf8("()Ljava/lang/String;".to_owned())),
                Some(Constant::Utf8("getLongLabel".to_owned())),
                Some(Constant::Utf8("getCommandType".to_owned())),
                Some(Constant::Utf8("()I".to_owned())),
                Some(Constant::Utf8("getPriority".to_owned())),
                Some(Constant::Utf8("SourceFile".to_owned())),
                Some(Constant::Utf8("generated_bootstrap.rs".to_owned())),
            ],
            access_flags: 33,
            this_class: 2,
            super_class: 8,
            interfaces: vec![],
            fields: vec![
                Member { access_flags: 25, name_index: 32, descriptor_index: 28, attributes: vec![
                    Attribute::Raw { name_index: 33, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x22,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 35, descriptor_index: 28, attributes: vec![
                    Attribute::Raw { name_index: 33, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x24,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 37, descriptor_index: 28, attributes: vec![
                    Attribute::Raw { name_index: 33, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x26,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 39, descriptor_index: 28, attributes: vec![
                    Attribute::Raw { name_index: 33, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x28,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 41, descriptor_index: 28, attributes: vec![
                    Attribute::Raw { name_index: 33, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x2a,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 43, descriptor_index: 28, attributes: vec![
                    Attribute::Raw { name_index: 33, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x2c,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 45, descriptor_index: 28, attributes: vec![
                    Attribute::Raw { name_index: 33, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x2e,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 47, descriptor_index: 28, attributes: vec![
                    Attribute::Raw { name_index: 33, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x30,
                    ] },
                ] },
                Member { access_flags: 18, name_index: 20, descriptor_index: 21, attributes: Vec::new() },
                Member { access_flags: 18, name_index: 24, descriptor_index: 21, attributes: Vec::new() },
                Member { access_flags: 18, name_index: 27, descriptor_index: 28, attributes: Vec::new() },
                Member { access_flags: 18, name_index: 31, descriptor_index: 28, attributes: Vec::new() },
            ],
            methods: vec![
                Member { access_flags: 1, name_index: 5, descriptor_index: 49, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 50, max_stack: 5, max_locals: 4, code: vec![
                        0x2a, 0x2b, 0x01, 0x1c, 0x1d, 0xb7, 0x00, 0x01, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 5, descriptor_index: 6, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 50, max_stack: 2, max_locals: 5, code: vec![
                        0x2a, 0xb7, 0x00, 0x07, 0x2b, 0xc7, 0x00, 0x0b, 0xbb, 0x00, 0x0c, 0x59, 0xb7, 0x00, 0x0e, 0xbf, 0x1d, 0x04, 0xa1, 0x00,
                        0x09, 0x1d, 0x10, 0x08, 0xa4, 0x00, 0x0b, 0xbb, 0x00, 0x0f, 0x59, 0xb7, 0x00, 0x11, 0xbf, 0x2a, 0x2b, 0xb5, 0x00, 0x12,
                        0x2a, 0x2c, 0xb5, 0x00, 0x16, 0x2a, 0x1d, 0xb5, 0x00, 0x19, 0x2a, 0x15, 0x04, 0xb5, 0x00, 0x1d, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 55, descriptor_index: 56, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 50, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x12, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 57, descriptor_index: 56, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 50, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x16, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 58, descriptor_index: 59, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 50, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x19, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 60, descriptor_index: 59, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 50, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x1d, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
            ],
            attributes: Vec::new(),
        },
        // javax/microedition/lcdui/CommandListener
        ClassFile {
            minor_version: 0,
            major_version: 48,
            constant_pool: vec![
                None,
                Some(Constant::Class { name_index: 2 }),
                Some(Constant::Utf8("javax/microedition/lcdui/CommandListener".to_owned())),
                Some(Constant::Class { name_index: 4 }),
                Some(Constant::Utf8("java/lang/Object".to_owned())),
                Some(Constant::Utf8("commandAction".to_owned())),
                Some(Constant::Utf8("(Ljavax/microedition/lcdui/Command;Ljavax/microedition/lcdui/Displayable;)V".to_owned())),
                Some(Constant::Utf8("SourceFile".to_owned())),
                Some(Constant::Utf8("generated_bootstrap.rs".to_owned())),
            ],
            access_flags: 1537,
            this_class: 1,
            super_class: 3,
            interfaces: vec![],
            fields: Vec::new(),
            methods: vec![
                Member { access_flags: 1025, name_index: 5, descriptor_index: 6, attributes: Vec::new() },
            ],
            attributes: Vec::new(),
        },
        // javax/microedition/lcdui/CustomItem
        ClassFile {
            minor_version: 0,
            major_version: 48,
            constant_pool: vec![
                None,
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 3 }),
                Some(Constant::Class { name_index: 4 }),
                Some(Constant::NameAndType { name_index: 5, descriptor_index: 6 }),
                Some(Constant::Utf8("javax/microedition/lcdui/Item".to_owned())),
                Some(Constant::Utf8("<init>".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;)V".to_owned())),
                Some(Constant::Class { name_index: 8 }),
                Some(Constant::Utf8("javax/microedition/lcdui/CustomItem".to_owned())),
                Some(Constant::Methodref { class_index: 7, name_and_type_index: 10 }),
                Some(Constant::NameAndType { name_index: 11, descriptor_index: 12 }),
                Some(Constant::Utf8("getMinContentWidth".to_owned())),
                Some(Constant::Utf8("()I".to_owned())),
                Some(Constant::Methodref { class_index: 7, name_and_type_index: 14 }),
                Some(Constant::NameAndType { name_index: 15, descriptor_index: 16 }),
                Some(Constant::Utf8("getPrefContentHeight".to_owned())),
                Some(Constant::Utf8("(I)I".to_owned())),
                Some(Constant::Methodref { class_index: 7, name_and_type_index: 18 }),
                Some(Constant::NameAndType { name_index: 19, descriptor_index: 12 }),
                Some(Constant::Utf8("getMinContentHeight".to_owned())),
                Some(Constant::Methodref { class_index: 7, name_and_type_index: 21 }),
                Some(Constant::NameAndType { name_index: 22, descriptor_index: 23 }),
                Some(Constant::Utf8("getLabel".to_owned())),
                Some(Constant::Utf8("()Ljava/lang/String;".to_owned())),
                Some(Constant::Methodref { class_index: 25, name_and_type_index: 26 }),
                Some(Constant::Class { name_index: 27 }),
                Some(Constant::NameAndType { name_index: 28, descriptor_index: 29 }),
                Some(Constant::Utf8("javax/microedition/lcdui/Font".to_owned())),
                Some(Constant::Utf8("getDefaultFont".to_owned())),
                Some(Constant::Utf8("()Ljavax/microedition/lcdui/Font;".to_owned())),
                Some(Constant::Methodref { class_index: 25, name_and_type_index: 31 }),
                Some(Constant::NameAndType { name_index: 32, descriptor_index: 12 }),
                Some(Constant::Utf8("getHeight".to_owned())),
                Some(Constant::Methodref { class_index: 7, name_and_type_index: 34 }),
                Some(Constant::NameAndType { name_index: 35, descriptor_index: 36 }),
                Some(Constant::Utf8("keyPressed".to_owned())),
                Some(Constant::Utf8("(I)V".to_owned())),
                Some(Constant::Methodref { class_index: 38, name_and_type_index: 39 }),
                Some(Constant::Class { name_index: 40 }),
                Some(Constant::NameAndType { name_index: 41, descriptor_index: 36 }),
                Some(Constant::Utf8("javax/microedition/lcdui/Graphics".to_owned())),
                Some(Constant::Utf8("setColor".to_owned())),
                Some(Constant::Methodref { class_index: 38, name_and_type_index: 43 }),
                Some(Constant::NameAndType { name_index: 44, descriptor_index: 45 }),
                Some(Constant::Utf8("drawString".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;III)V".to_owned())),
                Some(Constant::Methodref { class_index: 7, name_and_type_index: 47 }),
                Some(Constant::NameAndType { name_index: 48, descriptor_index: 16 }),
                Some(Constant::Utf8("__height".to_owned())),
                Some(Constant::Methodref { class_index: 7, name_and_type_index: 50 }),
                Some(Constant::NameAndType { name_index: 51, descriptor_index: 52 }),
                Some(Constant::Utf8("paint".to_owned())),
                Some(Constant::Utf8("(Ljavax/microedition/lcdui/Graphics;II)V".to_owned())),
                Some(Constant::Utf8("NONE".to_owned())),
                Some(Constant::Utf8("I".to_owned())),
                Some(Constant::Utf8("ConstantValue".to_owned())),
                Some(Constant::Integer(0)),
                Some(Constant::Utf8("TRAVERSE_HORIZONTAL".to_owned())),
                Some(Constant::Integer(1)),
                Some(Constant::Utf8("TRAVERSE_VERTICAL".to_owned())),
                Some(Constant::Integer(2)),
                Some(Constant::Utf8("KEY_PRESS".to_owned())),
                Some(Constant::Integer(4)),
                Some(Constant::Utf8("KEY_RELEASE".to_owned())),
                Some(Constant::Integer(8)),
                Some(Constant::Utf8("KEY_REPEAT".to_owned())),
                Some(Constant::Integer(16)),
                Some(Constant::Utf8("POINTER_PRESS".to_owned())),
                Some(Constant::Integer(32)),
                Some(Constant::Utf8("POINTER_RELEASE".to_owned())),
                Some(Constant::Integer(64)),
                Some(Constant::Utf8("POINTER_DRAG".to_owned())),
                Some(Constant::Integer(128)),
                Some(Constant::Utf8("Code".to_owned())),
                Some(Constant::Utf8("LineNumberTable".to_owned())),
                Some(Constant::Utf8("getPrefContentWidth".to_owned())),
                Some(Constant::Utf8("sizeChanged".to_owned())),
                Some(Constant::Utf8("(II)V".to_owned())),
                Some(Constant::Utf8("traverse".to_owned())),
                Some(Constant::Utf8("(III[I)Z".to_owned())),
                Some(Constant::Utf8("traverseOut".to_owned())),
                Some(Constant::Utf8("()V".to_owned())),
                Some(Constant::Utf8("keyReleased".to_owned())),
                Some(Constant::Utf8("keyRepeated".to_owned())),
                Some(Constant::Utf8("pointerPressed".to_owned())),
                Some(Constant::Utf8("pointerReleased".to_owned())),
                Some(Constant::Utf8("pointerDragged".to_owned())),
                Some(Constant::Utf8("getInteractionModes".to_owned())),
                Some(Constant::Utf8("__minimumWidth".to_owned())),
                Some(Constant::Utf8("StackMapTable".to_owned())),
                Some(Constant::Utf8("__key".to_owned())),
                Some(Constant::Utf8("__paint".to_owned())),
                Some(Constant::Utf8("(Ljavax/microedition/lcdui/Graphics;IIIZ)V".to_owned())),
                Some(Constant::Utf8("SourceFile".to_owned())),
                Some(Constant::Utf8("generated_bootstrap.rs".to_owned())),
            ],
            access_flags: 1057,
            this_class: 7,
            super_class: 2,
            interfaces: vec![],
            fields: vec![
                Member { access_flags: 28, name_index: 53, descriptor_index: 54, attributes: vec![
                    Attribute::Raw { name_index: 55, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x38,
                    ] },
                ] },
                Member { access_flags: 28, name_index: 57, descriptor_index: 54, attributes: vec![
                    Attribute::Raw { name_index: 55, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x3a,
                    ] },
                ] },
                Member { access_flags: 28, name_index: 59, descriptor_index: 54, attributes: vec![
                    Attribute::Raw { name_index: 55, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x3c,
                    ] },
                ] },
                Member { access_flags: 28, name_index: 61, descriptor_index: 54, attributes: vec![
                    Attribute::Raw { name_index: 55, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x3e,
                    ] },
                ] },
                Member { access_flags: 28, name_index: 63, descriptor_index: 54, attributes: vec![
                    Attribute::Raw { name_index: 55, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x40,
                    ] },
                ] },
                Member { access_flags: 28, name_index: 65, descriptor_index: 54, attributes: vec![
                    Attribute::Raw { name_index: 55, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x42,
                    ] },
                ] },
                Member { access_flags: 28, name_index: 67, descriptor_index: 54, attributes: vec![
                    Attribute::Raw { name_index: 55, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x44,
                    ] },
                ] },
                Member { access_flags: 28, name_index: 69, descriptor_index: 54, attributes: vec![
                    Attribute::Raw { name_index: 55, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x46,
                    ] },
                ] },
                Member { access_flags: 28, name_index: 71, descriptor_index: 54, attributes: vec![
                    Attribute::Raw { name_index: 55, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x48,
                    ] },
                ] },
            ],
            methods: vec![
                Member { access_flags: 4, name_index: 5, descriptor_index: 6, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 73, max_stack: 2, max_locals: 2, code: vec![
                        0x2a, 0x2b, 0xb7, 0x00, 0x01, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1028, name_index: 11, descriptor_index: 12, attributes: Vec::new() },
                Member { access_flags: 1028, name_index: 19, descriptor_index: 12, attributes: Vec::new() },
                Member { access_flags: 1028, name_index: 75, descriptor_index: 16, attributes: Vec::new() },
                Member { access_flags: 1028, name_index: 15, descriptor_index: 16, attributes: Vec::new() },
                Member { access_flags: 1028, name_index: 51, descriptor_index: 52, attributes: Vec::new() },
                Member { access_flags: 4, name_index: 76, descriptor_index: 77, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 73, max_stack: 0, max_locals: 3, code: vec![
                        0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 4, name_index: 78, descriptor_index: 79, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 73, max_stack: 1, max_locals: 5, code: vec![
                        0x03, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 4, name_index: 80, descriptor_index: 81, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 73, max_stack: 0, max_locals: 1, code: vec![
                        0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 4, name_index: 35, descriptor_index: 36, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 73, max_stack: 0, max_locals: 2, code: vec![
                        0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 4, name_index: 82, descriptor_index: 36, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 73, max_stack: 0, max_locals: 2, code: vec![
                        0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 4, name_index: 83, descriptor_index: 36, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 73, max_stack: 0, max_locals: 2, code: vec![
                        0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 4, name_index: 84, descriptor_index: 77, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 73, max_stack: 0, max_locals: 3, code: vec![
                        0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 4, name_index: 85, descriptor_index: 77, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 73, max_stack: 0, max_locals: 3, code: vec![
                        0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 4, name_index: 86, descriptor_index: 77, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 73, max_stack: 0, max_locals: 3, code: vec![
                        0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 20, name_index: 87, descriptor_index: 12, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 73, max_stack: 1, max_locals: 1, code: vec![
                        0x10, 0x1f, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 0, name_index: 88, descriptor_index: 12, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 73, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb6, 0x00, 0x09, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 0, name_index: 48, descriptor_index: 16, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 73, max_stack: 2, max_locals: 3, code: vec![
                        0x2a, 0x1b, 0xb6, 0x00, 0x0d, 0x3d, 0x1c, 0x2a, 0xb6, 0x00, 0x11, 0xa2, 0x00, 0x08, 0x2a, 0xb6, 0x00, 0x11, 0x3d, 0x2a,
                        0xb6, 0x00, 0x14, 0xc7, 0x00, 0x07, 0x03, 0xa7, 0x00, 0x0b, 0xb8, 0x00, 0x18, 0xb6, 0x00, 0x1e, 0x04, 0x60, 0x1c, 0x60,
                        0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 0, name_index: 90, descriptor_index: 36, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 73, max_stack: 2, max_locals: 2, code: vec![
                        0x2a, 0x1b, 0xb6, 0x00, 0x21, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 0, name_index: 91, descriptor_index: 92, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 73, max_stack: 5, max_locals: 6, code: vec![
                        0x2a, 0xb6, 0x00, 0x14, 0xc6, 0x00, 0x1f, 0x2b, 0x03, 0xb6, 0x00, 0x25, 0x2b, 0x2a, 0xb6, 0x00, 0x14, 0x1c, 0x1d, 0x10,
                        0x14, 0xb6, 0x00, 0x2a, 0x1d, 0xb8, 0x00, 0x18, 0xb6, 0x00, 0x1e, 0x04, 0x60, 0x60, 0x3e, 0x2a, 0x2b, 0x15, 0x04, 0x2a,
                        0x15, 0x04, 0xb6, 0x00, 0x2e, 0xb6, 0x00, 0x31, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
            ],
            attributes: Vec::new(),
        },
        // javax/microedition/lcdui/DateField
        ClassFile {
            minor_version: 0,
            major_version: 48,
            constant_pool: vec![
                None,
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 3 }),
                Some(Constant::Class { name_index: 4 }),
                Some(Constant::NameAndType { name_index: 5, descriptor_index: 6 }),
                Some(Constant::Utf8("java/util/TimeZone".to_owned())),
                Some(Constant::Utf8("getDefault".to_owned())),
                Some(Constant::Utf8("()Ljava/util/TimeZone;".to_owned())),
                Some(Constant::Methodref { class_index: 8, name_and_type_index: 9 }),
                Some(Constant::Class { name_index: 10 }),
                Some(Constant::NameAndType { name_index: 11, descriptor_index: 12 }),
                Some(Constant::Utf8("javax/microedition/lcdui/DateField".to_owned())),
                Some(Constant::Utf8("<init>".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;ILjava/util/TimeZone;)V".to_owned())),
                Some(Constant::Methodref { class_index: 14, name_and_type_index: 15 }),
                Some(Constant::Class { name_index: 16 }),
                Some(Constant::NameAndType { name_index: 11, descriptor_index: 17 }),
                Some(Constant::Utf8("javax/microedition/lcdui/Item".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;)V".to_owned())),
                Some(Constant::Class { name_index: 19 }),
                Some(Constant::Utf8("java/lang/NullPointerException".to_owned())),
                Some(Constant::Methodref { class_index: 18, name_and_type_index: 21 }),
                Some(Constant::NameAndType { name_index: 11, descriptor_index: 22 }),
                Some(Constant::Utf8("()V".to_owned())),
                Some(Constant::Methodref { class_index: 8, name_and_type_index: 24 }),
                Some(Constant::NameAndType { name_index: 25, descriptor_index: 26 }),
                Some(Constant::Utf8("setInputMode".to_owned())),
                Some(Constant::Utf8("(I)V".to_owned())),
                Some(Constant::Fieldref { class_index: 8, name_and_type_index: 28 }),
                Some(Constant::NameAndType { name_index: 29, descriptor_index: 30 }),
                Some(Constant::Utf8("zone".to_owned())),
                Some(Constant::Utf8("Ljava/util/TimeZone;".to_owned())),
                Some(Constant::Fieldref { class_index: 8, name_and_type_index: 32 }),
                Some(Constant::NameAndType { name_index: 33, descriptor_index: 34 }),
                Some(Constant::Utf8("date".to_owned())),
                Some(Constant::Utf8("Ljava/util/Date;".to_owned())),
                Some(Constant::Class { name_index: 36 }),
                Some(Constant::Utf8("java/util/Date".to_owned())),
                Some(Constant::Methodref { class_index: 35, name_and_type_index: 38 }),
                Some(Constant::NameAndType { name_index: 39, descriptor_index: 40 }),
                Some(Constant::Utf8("getTime".to_owned())),
                Some(Constant::Utf8("()J".to_owned())),
                Some(Constant::Methodref { class_index: 35, name_and_type_index: 42 }),
                Some(Constant::NameAndType { name_index: 11, descriptor_index: 43 }),
                Some(Constant::Utf8("(J)V".to_owned())),
                Some(Constant::Methodref { class_index: 8, name_and_type_index: 45 }),
                Some(Constant::NameAndType { name_index: 46, descriptor_index: 22 }),
                Some(Constant::Utf8("invalidate".to_owned())),
                Some(Constant::Fieldref { class_index: 8, name_and_type_index: 48 }),
                Some(Constant::NameAndType { name_index: 49, descriptor_index: 50 }),
                Some(Constant::Utf8("mode".to_owned())),
                Some(Constant::Utf8("I".to_owned())),
                Some(Constant::Class { name_index: 52 }),
                Some(Constant::Utf8("java/lang/IllegalArgumentException".to_owned())),
                Some(Constant::Methodref { class_index: 51, name_and_type_index: 21 }),
                Some(Constant::Methodref { class_index: 8, name_and_type_index: 55 }),
                Some(Constant::NameAndType { name_index: 56, descriptor_index: 57 }),
                Some(Constant::Utf8("getLabel".to_owned())),
                Some(Constant::Utf8("()Ljava/lang/String;".to_owned())),
                Some(Constant::Methodref { class_index: 59, name_and_type_index: 60 }),
                Some(Constant::Class { name_index: 61 }),
                Some(Constant::NameAndType { name_index: 62, descriptor_index: 63 }),
                Some(Constant::Utf8("javax/microedition/lcdui/Font".to_owned())),
                Some(Constant::Utf8("getDefaultFont".to_owned())),
                Some(Constant::Utf8("()Ljavax/microedition/lcdui/Font;".to_owned())),
                Some(Constant::Methodref { class_index: 59, name_and_type_index: 65 }),
                Some(Constant::NameAndType { name_index: 66, descriptor_index: 67 }),
                Some(Constant::Utf8("getHeight".to_owned())),
                Some(Constant::Utf8("()I".to_owned())),
                Some(Constant::Long(-60000)),
                None,
                Some(Constant::Methodref { class_index: 8, name_and_type_index: 71 }),
                Some(Constant::NameAndType { name_index: 72, descriptor_index: 43 }),
                Some(Constant::Utf8("adjust".to_owned())),
                Some(Constant::Long(60000)),
                None,
                Some(Constant::Methodref { class_index: 35, name_and_type_index: 76 }),
                Some(Constant::NameAndType { name_index: 77, descriptor_index: 43 }),
                Some(Constant::Utf8("setTime".to_owned())),
                Some(Constant::Methodref { class_index: 8, name_and_type_index: 79 }),
                Some(Constant::NameAndType { name_index: 80, descriptor_index: 22 }),
                Some(Constant::Utf8("notifyStateChanged".to_owned())),
                Some(Constant::Methodref { class_index: 82, name_and_type_index: 83 }),
                Some(Constant::Class { name_index: 84 }),
                Some(Constant::NameAndType { name_index: 85, descriptor_index: 26 }),
                Some(Constant::Utf8("javax/microedition/lcdui/Graphics".to_owned())),
                Some(Constant::Utf8("setColor".to_owned())),
                Some(Constant::Methodref { class_index: 82, name_and_type_index: 87 }),
                Some(Constant::NameAndType { name_index: 88, descriptor_index: 89 }),
                Some(Constant::Utf8("drawString".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;III)V".to_owned())),
                Some(Constant::Integer(2379678)),
                Some(Constant::Methodref { class_index: 82, name_and_type_index: 92 }),
                Some(Constant::NameAndType { name_index: 93, descriptor_index: 94 }),
                Some(Constant::Utf8("fillRect".to_owned())),
                Some(Constant::Utf8("(IIII)V".to_owned())),
                Some(Constant::Integer(16777215)),
                Some(Constant::String { string_index: 97 }),
                Some(Constant::Utf8("<unset>".to_owned())),
                Some(Constant::Methodref { class_index: 99, name_and_type_index: 100 }),
                Some(Constant::Class { name_index: 101 }),
                Some(Constant::NameAndType { name_index: 102, descriptor_index: 103 }),
                Some(Constant::Utf8("java/lang/String".to_owned())),
                Some(Constant::Utf8("valueOf".to_owned())),
                Some(Constant::Utf8("(J)Ljava/lang/String;".to_owned())),
                Some(Constant::Utf8("DATE".to_owned())),
                Some(Constant::Utf8("ConstantValue".to_owned())),
                Some(Constant::Integer(1)),
                Some(Constant::Utf8("TIME".to_owned())),
                Some(Constant::Integer(2)),
                Some(Constant::Utf8("DATE_TIME".to_owned())),
                Some(Constant::Integer(3)),
                Some(Constant::Utf8("(Ljava/lang/String;I)V".to_owned())),
                Some(Constant::Utf8("Code".to_owned())),
                Some(Constant::Utf8("LineNumberTable".to_owned())),
                Some(Constant::Utf8("StackMapTable".to_owned())),
                Some(Constant::Utf8("getDate".to_owned())),
                Some(Constant::Utf8("()Ljava/util/Date;".to_owned())),
                Some(Constant::Utf8("setDate".to_owned())),
                Some(Constant::Utf8("(Ljava/util/Date;)V".to_owned())),
                Some(Constant::Utf8("getInputMode".to_owned())),
                Some(Constant::Utf8("__height".to_owned())),
                Some(Constant::Utf8("(I)I".to_owned())),
                Some(Constant::Utf8("__key".to_owned())),
                Some(Constant::Utf8("__paint".to_owned())),
                Some(Constant::Utf8("(Ljavax/microedition/lcdui/Graphics;IIIZ)V".to_owned())),
                Some(Constant::Utf8("SourceFile".to_owned())),
                Some(Constant::Utf8("generated_bootstrap.rs".to_owned())),
            ],
            access_flags: 33,
            this_class: 8,
            super_class: 14,
            interfaces: vec![],
            fields: vec![
                Member { access_flags: 25, name_index: 104, descriptor_index: 50, attributes: vec![
                    Attribute::Raw { name_index: 105, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x6a,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 107, descriptor_index: 50, attributes: vec![
                    Attribute::Raw { name_index: 105, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x6c,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 109, descriptor_index: 50, attributes: vec![
                    Attribute::Raw { name_index: 105, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x6e,
                    ] },
                ] },
                Member { access_flags: 2, name_index: 33, descriptor_index: 34, attributes: Vec::new() },
                Member { access_flags: 2, name_index: 49, descriptor_index: 50, attributes: Vec::new() },
                Member { access_flags: 2, name_index: 29, descriptor_index: 30, attributes: Vec::new() },
            ],
            methods: vec![
                Member { access_flags: 1, name_index: 11, descriptor_index: 111, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 112, max_stack: 4, max_locals: 3, code: vec![
                        0x2a, 0x2b, 0x1c, 0xb8, 0x00, 0x01, 0xb7, 0x00, 0x07, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 11, descriptor_index: 12, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 112, max_stack: 2, max_locals: 4, code: vec![
                        0x2a, 0x2b, 0xb7, 0x00, 0x0d, 0x2d, 0xc7, 0x00, 0x0b, 0xbb, 0x00, 0x12, 0x59, 0xb7, 0x00, 0x14, 0xbf, 0x2a, 0x1c, 0xb6,
                        0x00, 0x17, 0x2a, 0x2d, 0xb5, 0x00, 0x1b, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 115, descriptor_index: 116, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 112, max_stack: 4, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x1f, 0xc7, 0x00, 0x07, 0x01, 0xa7, 0x00, 0x11, 0xbb, 0x00, 0x23, 0x59, 0x2a, 0xb4, 0x00, 0x1f, 0xb6,
                        0x00, 0x25, 0xb7, 0x00, 0x29, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 117, descriptor_index: 118, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 112, max_stack: 5, max_locals: 2, code: vec![
                        0x2a, 0x2b, 0xc7, 0x00, 0x07, 0x01, 0xa7, 0x00, 0x0e, 0xbb, 0x00, 0x23, 0x59, 0x2b, 0xb6, 0x00, 0x25, 0xb7, 0x00, 0x29,
                        0xb5, 0x00, 0x1f, 0x2a, 0xb6, 0x00, 0x2c, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 119, descriptor_index: 67, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 112, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x2f, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 25, descriptor_index: 26, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 112, max_stack: 2, max_locals: 2, code: vec![
                        0x1b, 0x04, 0xa1, 0x00, 0x08, 0x1b, 0x06, 0xa4, 0x00, 0x0b, 0xbb, 0x00, 0x33, 0x59, 0xb7, 0x00, 0x35, 0xbf, 0x2a, 0x1b,
                        0xb5, 0x00, 0x2f, 0x2a, 0xb6, 0x00, 0x2c, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 0, name_index: 120, descriptor_index: 121, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 112, max_stack: 2, max_locals: 2, code: vec![
                        0x2a, 0xb6, 0x00, 0x36, 0xc7, 0x00, 0x07, 0x03, 0xa7, 0x00, 0x0b, 0xb8, 0x00, 0x3a, 0xb6, 0x00, 0x40, 0x04, 0x60, 0xb8,
                        0x00, 0x3a, 0xb6, 0x00, 0x40, 0x60, 0x08, 0x60, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 0, name_index: 122, descriptor_index: 26, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 112, max_stack: 3, max_locals: 2, code: vec![
                        0x1b, 0x10, 0xfd, 0x9f, 0x00, 0x09, 0x1b, 0x10, 0x34, 0xa0, 0x00, 0x0d, 0x2a, 0x14, 0x00, 0x44, 0xb7, 0x00, 0x46, 0xa7,
                        0x00, 0x16, 0x1b, 0x10, 0xfc, 0x9f, 0x00, 0x09, 0x1b, 0x10, 0x36, 0xa0, 0x00, 0x0a, 0x2a, 0x14, 0x00, 0x49, 0xb7, 0x00,
                        0x46, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 2, name_index: 72, descriptor_index: 43, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 112, max_stack: 5, max_locals: 3, code: vec![
                        0x2a, 0xb4, 0x00, 0x1f, 0xc7, 0x00, 0x12, 0x2a, 0xbb, 0x00, 0x23, 0x59, 0x09, 0xb7, 0x00, 0x29, 0xb5, 0x00, 0x1f, 0xa7,
                        0x00, 0x13, 0x2a, 0xb4, 0x00, 0x1f, 0x2a, 0xb4, 0x00, 0x1f, 0xb6, 0x00, 0x25, 0x1f, 0x61, 0xb6, 0x00, 0x4b, 0x2a, 0xb6,
                        0x00, 0x4e, 0x2a, 0xb6, 0x00, 0x2c, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 0, name_index: 123, descriptor_index: 124, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 112, max_stack: 6, max_locals: 6, code: vec![
                        0x2b, 0x03, 0xb6, 0x00, 0x51, 0x2a, 0xb6, 0x00, 0x36, 0xc6, 0x00, 0x1a, 0x2b, 0x2a, 0xb6, 0x00, 0x36, 0x1c, 0x1d, 0x10,
                        0x14, 0xb6, 0x00, 0x56, 0x1d, 0xb8, 0x00, 0x3a, 0xb6, 0x00, 0x40, 0x04, 0x60, 0x60, 0x3e, 0x15, 0x05, 0x99, 0x00, 0x25,
                        0x2b, 0x12, 0x5a, 0xb6, 0x00, 0x51, 0x2b, 0x1c, 0x05, 0x64, 0x1d, 0x04, 0x64, 0x15, 0x04, 0x05, 0x60, 0xb8, 0x00, 0x3a,
                        0xb6, 0x00, 0x40, 0x05, 0x60, 0xb6, 0x00, 0x5b, 0x2b, 0x12, 0x5f, 0xb6, 0x00, 0x51, 0x2b, 0x2a, 0xb4, 0x00, 0x1f, 0xc7,
                        0x00, 0x08, 0x12, 0x60, 0xa7, 0x00, 0x0d, 0x2a, 0xb4, 0x00, 0x1f, 0xb6, 0x00, 0x25, 0xb8, 0x00, 0x62, 0x1c, 0x1d, 0x10,
                        0x14, 0xb6, 0x00, 0x56, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
            ],
            attributes: Vec::new(),
        },
    );
}
