use super::{
    Attribute, ClassFile, CodeAttribute, Constant, Member, append_bootstrap_classes,
    build_bootstrap_class,
};

mod gauge;

pub(super) fn append_forms(classes: &mut Vec<ClassFile>) {
    append_bootstrap_classes!(classes;
        // javax/microedition/lcdui/Form
        ClassFile {
            minor_version: 0,
            major_version: 48,
            constant_pool: vec![
                None,
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 3 }),
                Some(Constant::Class { name_index: 4 }),
                Some(Constant::NameAndType { name_index: 5, descriptor_index: 6 }),
                Some(Constant::Utf8("javax/microedition/lcdui/Screen".to_owned())),
                Some(Constant::Utf8("<init>".to_owned())),
                Some(Constant::Utf8("()V".to_owned())),
                Some(Constant::Class { name_index: 8 }),
                Some(Constant::Utf8("java/util/Vector".to_owned())),
                Some(Constant::Methodref { class_index: 7, name_and_type_index: 3 }),
                Some(Constant::Fieldref { class_index: 11, name_and_type_index: 12 }),
                Some(Constant::Class { name_index: 13 }),
                Some(Constant::NameAndType { name_index: 14, descriptor_index: 15 }),
                Some(Constant::Utf8("javax/microedition/lcdui/Form".to_owned())),
                Some(Constant::Utf8("items".to_owned())),
                Some(Constant::Utf8("Ljava/util/Vector;".to_owned())),
                Some(Constant::Methodref { class_index: 11, name_and_type_index: 17 }),
                Some(Constant::NameAndType { name_index: 18, descriptor_index: 19 }),
                Some(Constant::Utf8("setTitle".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;)V".to_owned())),
                Some(Constant::Methodref { class_index: 11, name_and_type_index: 21 }),
                Some(Constant::NameAndType { name_index: 22, descriptor_index: 23 }),
                Some(Constant::Utf8("append".to_owned())),
                Some(Constant::Utf8("(Ljavax/microedition/lcdui/Item;)I".to_owned())),
                Some(Constant::Class { name_index: 25 }),
                Some(Constant::Utf8("java/lang/NullPointerException".to_owned())),
                Some(Constant::Methodref { class_index: 24, name_and_type_index: 3 }),
                Some(Constant::Methodref { class_index: 11, name_and_type_index: 28 }),
                Some(Constant::NameAndType { name_index: 29, descriptor_index: 30 }),
                Some(Constant::Utf8("attach".to_owned())),
                Some(Constant::Utf8("(Ljavax/microedition/lcdui/Item;)V".to_owned())),
                Some(Constant::Methodref { class_index: 7, name_and_type_index: 32 }),
                Some(Constant::NameAndType { name_index: 33, descriptor_index: 34 }),
                Some(Constant::Utf8("addElement".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/Object;)V".to_owned())),
                Some(Constant::Methodref { class_index: 11, name_and_type_index: 36 }),
                Some(Constant::NameAndType { name_index: 37, descriptor_index: 6 }),
                Some(Constant::Utf8("__requestRepaint".to_owned())),
                Some(Constant::Methodref { class_index: 7, name_and_type_index: 39 }),
                Some(Constant::NameAndType { name_index: 40, descriptor_index: 41 }),
                Some(Constant::Utf8("size".to_owned())),
                Some(Constant::Utf8("()I".to_owned())),
                Some(Constant::Class { name_index: 43 }),
                Some(Constant::Utf8("javax/microedition/lcdui/StringItem".to_owned())),
                Some(Constant::Methodref { class_index: 42, name_and_type_index: 45 }),
                Some(Constant::NameAndType { name_index: 5, descriptor_index: 46 }),
                Some(Constant::Utf8("(Ljava/lang/String;Ljava/lang/String;)V".to_owned())),
                Some(Constant::Class { name_index: 48 }),
                Some(Constant::Utf8("javax/microedition/lcdui/ImageItem".to_owned())),
                Some(Constant::Class { name_index: 50 }),
                Some(Constant::Utf8("javax/microedition/lcdui/Item".to_owned())),
                Some(Constant::Methodref { class_index: 47, name_and_type_index: 52 }),
                Some(Constant::NameAndType { name_index: 5, descriptor_index: 53 }),
                Some(Constant::Utf8("(Ljava/lang/String;Ljavax/microedition/lcdui/Image;ILjava/lang/String;)V".to_owned())),
                Some(Constant::Class { name_index: 55 }),
                Some(Constant::Utf8("java/lang/IndexOutOfBoundsException".to_owned())),
                Some(Constant::Methodref { class_index: 54, name_and_type_index: 3 }),
                Some(Constant::Methodref { class_index: 7, name_and_type_index: 58 }),
                Some(Constant::NameAndType { name_index: 59, descriptor_index: 60 }),
                Some(Constant::Utf8("insertElementAt".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/Object;I)V".to_owned())),
                Some(Constant::Fieldref { class_index: 11, name_and_type_index: 62 }),
                Some(Constant::NameAndType { name_index: 63, descriptor_index: 64 }),
                Some(Constant::Utf8("selected".to_owned())),
                Some(Constant::Utf8("I".to_owned())),
                Some(Constant::Methodref { class_index: 11, name_and_type_index: 66 }),
                Some(Constant::NameAndType { name_index: 67, descriptor_index: 68 }),
                Some(Constant::Utf8("get".to_owned())),
                Some(Constant::Utf8("(I)Ljavax/microedition/lcdui/Item;".to_owned())),
                Some(Constant::Fieldref { class_index: 49, name_and_type_index: 70 }),
                Some(Constant::NameAndType { name_index: 71, descriptor_index: 72 }),
                Some(Constant::Utf8("owner".to_owned())),
                Some(Constant::Utf8("Ljavax/microedition/lcdui/Form;".to_owned())),
                Some(Constant::Methodref { class_index: 7, name_and_type_index: 74 }),
                Some(Constant::NameAndType { name_index: 75, descriptor_index: 60 }),
                Some(Constant::Utf8("setElementAt".to_owned())),
                Some(Constant::Methodref { class_index: 7, name_and_type_index: 77 }),
                Some(Constant::NameAndType { name_index: 78, descriptor_index: 79 }),
                Some(Constant::Utf8("removeElementAt".to_owned())),
                Some(Constant::Utf8("(I)V".to_owned())),
                Some(Constant::Methodref { class_index: 7, name_and_type_index: 81 }),
                Some(Constant::NameAndType { name_index: 82, descriptor_index: 83 }),
                Some(Constant::Utf8("elementAt".to_owned())),
                Some(Constant::Utf8("(I)Ljava/lang/Object;".to_owned())),
                Some(Constant::Methodref { class_index: 7, name_and_type_index: 85 }),
                Some(Constant::NameAndType { name_index: 86, descriptor_index: 6 }),
                Some(Constant::Utf8("removeAllElements".to_owned())),
                Some(Constant::Methodref { class_index: 11, name_and_type_index: 88 }),
                Some(Constant::NameAndType { name_index: 89, descriptor_index: 79 }),
                Some(Constant::Utf8("__setScroll".to_owned())),
                Some(Constant::Fieldref { class_index: 11, name_and_type_index: 91 }),
                Some(Constant::NameAndType { name_index: 92, descriptor_index: 93 }),
                Some(Constant::Utf8("stateListener".to_owned())),
                Some(Constant::Utf8("Ljavax/microedition/lcdui/ItemStateListener;".to_owned())),
                Some(Constant::Methodref { class_index: 11, name_and_type_index: 95 }),
                Some(Constant::NameAndType { name_index: 96, descriptor_index: 6 }),
                Some(Constant::Utf8("ensureVisible".to_owned())),
                Some(Constant::Class { name_index: 98 }),
                Some(Constant::Utf8("javax/microedition/lcdui/TextField".to_owned())),
                Some(Constant::Methodref { class_index: 97, name_and_type_index: 100 }),
                Some(Constant::NameAndType { name_index: 101, descriptor_index: 102 }),
                Some(Constant::Utf8("getString".to_owned())),
                Some(Constant::Utf8("()Ljava/lang/String;".to_owned())),
                Some(Constant::Methodref { class_index: 49, name_and_type_index: 104 }),
                Some(Constant::NameAndType { name_index: 105, descriptor_index: 79 }),
                Some(Constant::Utf8("__key".to_owned())),
                Some(Constant::Methodref { class_index: 49, name_and_type_index: 107 }),
                Some(Constant::NameAndType { name_index: 108, descriptor_index: 6 }),
                Some(Constant::Utf8("__activate".to_owned())),
                Some(Constant::Methodref { class_index: 110, name_and_type_index: 111 }),
                Some(Constant::Class { name_index: 112 }),
                Some(Constant::NameAndType { name_index: 113, descriptor_index: 114 }),
                Some(Constant::Utf8("java/lang/String".to_owned())),
                Some(Constant::Utf8("equals".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/Object;)Z".to_owned())),
                Some(Constant::InterfaceMethodref { class_index: 116, name_and_type_index: 117 }),
                Some(Constant::Class { name_index: 118 }),
                Some(Constant::NameAndType { name_index: 119, descriptor_index: 30 }),
                Some(Constant::Utf8("javax/microedition/lcdui/ItemStateListener".to_owned())),
                Some(Constant::Utf8("itemStateChanged".to_owned())),
                Some(Constant::Methodref { class_index: 49, name_and_type_index: 121 }),
                Some(Constant::NameAndType { name_index: 122, descriptor_index: 123 }),
                Some(Constant::Utf8("__height".to_owned())),
                Some(Constant::Utf8("(I)I".to_owned())),
                Some(Constant::Methodref { class_index: 49, name_and_type_index: 125 }),
                Some(Constant::NameAndType { name_index: 126, descriptor_index: 127 }),
                Some(Constant::Utf8("__paint".to_owned())),
                Some(Constant::Utf8("(Ljavax/microedition/lcdui/Graphics;IIIZ)V".to_owned())),
                Some(Constant::Class { name_index: 129 }),
                Some(Constant::Utf8("java/lang/IllegalStateException".to_owned())),
                Some(Constant::Methodref { class_index: 128, name_and_type_index: 3 }),
                Some(Constant::Methodref { class_index: 11, name_and_type_index: 132 }),
                Some(Constant::NameAndType { name_index: 133, descriptor_index: 41 }),
                Some(Constant::Utf8("__getScroll".to_owned())),
                Some(Constant::Utf8("Code".to_owned())),
                Some(Constant::Utf8("LineNumberTable".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;[Ljavax/microedition/lcdui/Item;)V".to_owned())),
                Some(Constant::Utf8("StackMapTable".to_owned())),
                Some(Constant::Class { name_index: 139 }),
                Some(Constant::Utf8("[Ljavax/microedition/lcdui/Item;".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;)I".to_owned())),
                Some(Constant::Utf8("(Ljavax/microedition/lcdui/Image;)I".to_owned())),
                Some(Constant::Utf8("insert".to_owned())),
                Some(Constant::Utf8("(ILjavax/microedition/lcdui/Item;)V".to_owned())),
                Some(Constant::Utf8("set".to_owned())),
                Some(Constant::Utf8("delete".to_owned())),
                Some(Constant::Utf8("deleteAll".to_owned())),
                Some(Constant::Utf8("setItemStateListener".to_owned())),
                Some(Constant::Utf8("(Ljavax/microedition/lcdui/ItemStateListener;)V".to_owned())),
                Some(Constant::Utf8("__keyPressed".to_owned())),
                Some(Constant::Utf8("__paintContent".to_owned())),
                Some(Constant::Utf8("(Ljavax/microedition/lcdui/Graphics;II)V".to_owned())),
                Some(Constant::Class { name_index: 153 }),
                Some(Constant::Utf8("javax/microedition/lcdui/Graphics".to_owned())),
                Some(Constant::Utf8("__itemInvalidated".to_owned())),
                Some(Constant::Utf8("__notifyStateChanged".to_owned())),
                Some(Constant::Utf8("SourceFile".to_owned())),
                Some(Constant::Utf8("generated_bootstrap.rs".to_owned())),
            ],
            access_flags: 33,
            this_class: 11,
            super_class: 2,
            interfaces: vec![],
            fields: vec![
                Member { access_flags: 18, name_index: 14, descriptor_index: 15, attributes: Vec::new() },
                Member { access_flags: 2, name_index: 92, descriptor_index: 93, attributes: Vec::new() },
                Member { access_flags: 2, name_index: 63, descriptor_index: 64, attributes: Vec::new() },
            ],
            methods: vec![
                Member { access_flags: 1, name_index: 5, descriptor_index: 19, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 134, max_stack: 3, max_locals: 2, code: vec![
                        0x2a, 0xb7, 0x00, 0x01, 0x2a, 0xbb, 0x00, 0x07, 0x59, 0xb7, 0x00, 0x09, 0xb5, 0x00, 0x0a, 0x2a, 0x2b, 0xb6, 0x00, 0x10,
                        0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 5, descriptor_index: 136, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 134, max_stack: 3, max_locals: 4, code: vec![
                        0x2a, 0xb7, 0x00, 0x01, 0x2a, 0xbb, 0x00, 0x07, 0x59, 0xb7, 0x00, 0x09, 0xb5, 0x00, 0x0a, 0x2a, 0x2b, 0xb6, 0x00, 0x10,
                        0x2c, 0xc6, 0x00, 0x19, 0x03, 0x3e, 0x1d, 0x2c, 0xbe, 0xa2, 0x00, 0x11, 0x2a, 0x2c, 0x1d, 0x32, 0xb6, 0x00, 0x14, 0x57,
                        0x84, 0x03, 0x01, 0xa7, 0xff, 0xef, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 22, descriptor_index: 23, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 134, max_stack: 2, max_locals: 2, code: vec![
                        0x2b, 0xc7, 0x00, 0x0b, 0xbb, 0x00, 0x18, 0x59, 0xb7, 0x00, 0x1a, 0xbf, 0x2a, 0x2b, 0xb7, 0x00, 0x1b, 0x2a, 0xb4, 0x00,
                        0x0a, 0x2b, 0xb6, 0x00, 0x1f, 0x2a, 0xb6, 0x00, 0x23, 0x2a, 0xb4, 0x00, 0x0a, 0xb6, 0x00, 0x26, 0x04, 0x64, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 22, descriptor_index: 140, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 134, max_stack: 5, max_locals: 2, code: vec![
                        0x2a, 0xbb, 0x00, 0x2a, 0x59, 0x01, 0x2b, 0xb7, 0x00, 0x2c, 0xb6, 0x00, 0x14, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 22, descriptor_index: 141, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 134, max_stack: 7, max_locals: 2, code: vec![
                        0x2a, 0xbb, 0x00, 0x2f, 0x59, 0x01, 0x2b, 0x03, 0x01, 0xb7, 0x00, 0x33, 0xb6, 0x00, 0x14, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 142, descriptor_index: 143, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 134, max_stack: 3, max_locals: 3, code: vec![
                        0x2c, 0xc7, 0x00, 0x0b, 0xbb, 0x00, 0x18, 0x59, 0xb7, 0x00, 0x1a, 0xbf, 0x1b, 0x9b, 0x00, 0x0e, 0x1b, 0x2a, 0xb4, 0x00,
                        0x0a, 0xb6, 0x00, 0x26, 0xa4, 0x00, 0x0b, 0xbb, 0x00, 0x36, 0x59, 0xb7, 0x00, 0x38, 0xbf, 0x2a, 0x2c, 0xb7, 0x00, 0x1b,
                        0x2a, 0xb4, 0x00, 0x0a, 0x2c, 0x1b, 0xb6, 0x00, 0x39, 0x1b, 0x2a, 0xb4, 0x00, 0x3d, 0xa3, 0x00, 0x18, 0x2a, 0xb4, 0x00,
                        0x0a, 0xb6, 0x00, 0x26, 0x04, 0xa4, 0x00, 0x0d, 0x2a, 0x59, 0xb4, 0x00, 0x3d, 0x04, 0x60, 0xb5, 0x00, 0x3d, 0x2a, 0xb6,
                        0x00, 0x23, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 144, descriptor_index: 143, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 134, max_stack: 3, max_locals: 4, code: vec![
                        0x2c, 0xc7, 0x00, 0x0b, 0xbb, 0x00, 0x18, 0x59, 0xb7, 0x00, 0x1a, 0xbf, 0x2a, 0x1b, 0xb6, 0x00, 0x41, 0x4e, 0x2d, 0x2c,
                        0xa6, 0x00, 0x04, 0xb1, 0x2a, 0x2c, 0xb7, 0x00, 0x1b, 0x2d, 0x01, 0xb5, 0x00, 0x45, 0x2a, 0xb4, 0x00, 0x0a, 0x2c, 0x1b,
                        0xb6, 0x00, 0x49, 0x2a, 0xb6, 0x00, 0x23, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 145, descriptor_index: 79, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 134, max_stack: 3, max_locals: 3, code: vec![
                        0x2a, 0x1b, 0xb6, 0x00, 0x41, 0x4d, 0x2c, 0x01, 0xb5, 0x00, 0x45, 0x2a, 0xb4, 0x00, 0x0a, 0x1b, 0xb6, 0x00, 0x4c, 0x2a,
                        0xb4, 0x00, 0x3d, 0x2a, 0xb4, 0x00, 0x0a, 0xb6, 0x00, 0x26, 0xa1, 0x00, 0x10, 0x2a, 0x2a, 0xb4, 0x00, 0x0a, 0xb6, 0x00,
                        0x26, 0x04, 0x64, 0xb5, 0x00, 0x3d, 0x2a, 0xb4, 0x00, 0x3d, 0x9c, 0x00, 0x08, 0x2a, 0x03, 0xb5, 0x00, 0x3d, 0x2a, 0xb6,
                        0x00, 0x23, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 146, descriptor_index: 6, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 134, max_stack: 2, max_locals: 2, code: vec![
                        0x03, 0x3c, 0x1b, 0x2a, 0xb4, 0x00, 0x0a, 0xb6, 0x00, 0x26, 0xa2, 0x00, 0x18, 0x2a, 0xb4, 0x00, 0x0a, 0x1b, 0xb6, 0x00,
                        0x50, 0xc0, 0x00, 0x31, 0x01, 0xb5, 0x00, 0x45, 0x84, 0x01, 0x01, 0xa7, 0xff, 0xe3, 0x2a, 0xb4, 0x00, 0x0a, 0xb6, 0x00,
                        0x54, 0x2a, 0x03, 0xb5, 0x00, 0x3d, 0x2a, 0x03, 0xb6, 0x00, 0x57, 0x2a, 0xb6, 0x00, 0x23, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 40, descriptor_index: 41, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 134, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x0a, 0xb6, 0x00, 0x26, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 67, descriptor_index: 68, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 134, max_stack: 2, max_locals: 2, code: vec![
                        0x2a, 0xb4, 0x00, 0x0a, 0x1b, 0xb6, 0x00, 0x50, 0xc0, 0x00, 0x31, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 147, descriptor_index: 148, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 134, max_stack: 2, max_locals: 2, code: vec![
                        0x2a, 0x2b, 0xb5, 0x00, 0x5a, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 0, name_index: 149, descriptor_index: 79, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 134, max_stack: 3, max_locals: 4, code: vec![
                        0x2a, 0xb4, 0x00, 0x0a, 0xb6, 0x00, 0x26, 0x9a, 0x00, 0x04, 0xb1, 0x1b, 0x02, 0x9f, 0x00, 0x09, 0x1b, 0x10, 0x32, 0xa0,
                        0x00, 0x1b, 0x2a, 0xb4, 0x00, 0x3d, 0x9e, 0x00, 0x0d, 0x2a, 0x59, 0xb4, 0x00, 0x3d, 0x04, 0x64, 0xb5, 0x00, 0x3d, 0x2a,
                        0xb7, 0x00, 0x5e, 0xa7, 0x00, 0x8d, 0x1b, 0x10, 0xfe, 0x9f, 0x00, 0x09, 0x1b, 0x10, 0x38, 0xa0, 0x00, 0x24, 0x2a, 0xb4,
                        0x00, 0x3d, 0x2a, 0xb4, 0x00, 0x0a, 0xb6, 0x00, 0x26, 0x04, 0x64, 0xa2, 0x00, 0x0d, 0x2a, 0x59, 0xb4, 0x00, 0x3d, 0x04,
                        0x60, 0xb5, 0x00, 0x3d, 0x2a, 0xb7, 0x00, 0x5e, 0xa7, 0x00, 0x60, 0x2a, 0x2a, 0xb4, 0x00, 0x3d, 0xb6, 0x00, 0x41, 0x4d,
                        0x2c, 0xc1, 0x00, 0x61, 0x99, 0x00, 0x0d, 0x2c, 0xc0, 0x00, 0x61, 0xb6, 0x00, 0x63, 0xa7, 0x00, 0x04, 0x01, 0x4e, 0x2c,
                        0x1b, 0xb6, 0x00, 0x67, 0x1b, 0x10, 0xfb, 0x9f, 0x00, 0x0f, 0x1b, 0x10, 0x35, 0x9f, 0x00, 0x09, 0x1b, 0x10, 0x0a, 0xa0,
                        0x00, 0x07, 0x2c, 0xb6, 0x00, 0x6a, 0x2a, 0xb4, 0x00, 0x5a, 0xc6, 0x00, 0x22, 0x2c, 0xc1, 0x00, 0x61, 0x99, 0x00, 0x1b,
                        0x2d, 0x2c, 0xc0, 0x00, 0x61, 0xb6, 0x00, 0x63, 0xb6, 0x00, 0x6d, 0x9a, 0x00, 0x0d, 0x2a, 0xb4, 0x00, 0x5a, 0x2c, 0xb9,
                        0x00, 0x73, 0x02, 0x00, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 0, name_index: 150, descriptor_index: 151, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 134, max_stack: 7, max_locals: 8, code: vec![
                        0x1c, 0x36, 0x04, 0x03, 0x36, 0x05, 0x15, 0x05, 0x2a, 0xb4, 0x00, 0x0a, 0xb6, 0x00, 0x26, 0xa2, 0x00, 0x4c, 0x2a, 0x15,
                        0x05, 0xb6, 0x00, 0x41, 0x3a, 0x06, 0x19, 0x06, 0x11, 0x00, 0xe6, 0xb6, 0x00, 0x78, 0x36, 0x07, 0x15, 0x04, 0x15, 0x07,
                        0x60, 0x9b, 0x00, 0x23, 0x15, 0x04, 0x1d, 0xa2, 0x00, 0x1d, 0x19, 0x06, 0x2b, 0x08, 0x15, 0x04, 0x11, 0x00, 0xe6, 0x15,
                        0x05, 0x2a, 0xb4, 0x00, 0x3d, 0xa0, 0x00, 0x07, 0x04, 0xa7, 0x00, 0x04, 0x03, 0xb6, 0x00, 0x7c, 0x15, 0x04, 0x15, 0x07,
                        0x06, 0x60, 0x60, 0x36, 0x04, 0x84, 0x05, 0x01, 0xa7, 0xff, 0xae, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 0, name_index: 154, descriptor_index: 6, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 134, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb6, 0x00, 0x23, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 0, name_index: 155, descriptor_index: 30, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 134, max_stack: 2, max_locals: 2, code: vec![
                        0x2a, 0xb4, 0x00, 0x5a, 0xc6, 0x00, 0x0d, 0x2a, 0xb4, 0x00, 0x5a, 0x2b, 0xb9, 0x00, 0x73, 0x02, 0x00, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 2, name_index: 29, descriptor_index: 30, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 134, max_stack: 2, max_locals: 2, code: vec![
                        0x2b, 0xb4, 0x00, 0x45, 0xc6, 0x00, 0x0b, 0xbb, 0x00, 0x80, 0x59, 0xb7, 0x00, 0x82, 0xbf, 0x2b, 0x2a, 0xb5, 0x00, 0x45,
                        0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 2, name_index: 96, descriptor_index: 6, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 134, max_stack: 3, max_locals: 5, code: vec![
                        0x03, 0x3c, 0x03, 0x3d, 0x1c, 0x2a, 0xb4, 0x00, 0x3d, 0xa2, 0x00, 0x19, 0x1b, 0x2a, 0x1c, 0xb6, 0x00, 0x41, 0x11, 0x00,
                        0xe6, 0xb6, 0x00, 0x78, 0x06, 0x60, 0x60, 0x3c, 0x84, 0x02, 0x01, 0xa7, 0xff, 0xe5, 0x2a, 0x2a, 0xb4, 0x00, 0x3d, 0xb6,
                        0x00, 0x41, 0x11, 0x00, 0xe6, 0xb6, 0x00, 0x78, 0x3e, 0x11, 0x01, 0x0e, 0x36, 0x04, 0x1b, 0x2a, 0xb6, 0x00, 0x83, 0xa2,
                        0x00, 0x0b, 0x2a, 0x1b, 0xb6, 0x00, 0x57, 0xa7, 0x00, 0x1a, 0x1b, 0x1d, 0x60, 0x2a, 0xb6, 0x00, 0x83, 0x15, 0x04, 0x60,
                        0xa4, 0x00, 0x0d, 0x2a, 0x1b, 0x1d, 0x60, 0x15, 0x04, 0x64, 0xb6, 0x00, 0x57, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
            ],
            attributes: Vec::new(),
        },
        // javax/microedition/lcdui/Gauge
        ClassFile {
            minor_version: 0,
            major_version: 48,
            constant_pool: vec![
                None,
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 3 }),
                Some(Constant::Class { name_index: 4 }),
                Some(Constant::NameAndType { name_index: 5, descriptor_index: 6 }),
                Some(Constant::Utf8("javax/microedition/lcdui/Item".to_owned())),
                Some(Constant::Utf8("<init>".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;)V".to_owned())),
                Some(Constant::Class { name_index: 8 }),
                Some(Constant::Utf8("javax/microedition/lcdui/Gauge".to_owned())),
                Some(Constant::Class { name_index: 10 }),
                Some(Constant::Utf8("java/lang/IllegalArgumentException".to_owned())),
                Some(Constant::Methodref { class_index: 9, name_and_type_index: 12 }),
                Some(Constant::NameAndType { name_index: 5, descriptor_index: 13 }),
                Some(Constant::Utf8("()V".to_owned())),
                Some(Constant::Fieldref { class_index: 7, name_and_type_index: 15 }),
                Some(Constant::NameAndType { name_index: 16, descriptor_index: 17 }),
                Some(Constant::Utf8("interactive".to_owned())),
                Some(Constant::Utf8("Z".to_owned())),
                Some(Constant::Fieldref { class_index: 7, name_and_type_index: 19 }),
                Some(Constant::NameAndType { name_index: 20, descriptor_index: 21 }),
                Some(Constant::Utf8("maximum".to_owned())),
                Some(Constant::Utf8("I".to_owned())),
                Some(Constant::Methodref { class_index: 7, name_and_type_index: 23 }),
                Some(Constant::NameAndType { name_index: 24, descriptor_index: 25 }),
                Some(Constant::Utf8("setValue".to_owned())),
                Some(Constant::Utf8("(I)V".to_owned())),
                Some(Constant::Fieldref { class_index: 7, name_and_type_index: 27 }),
                Some(Constant::NameAndType { name_index: 28, descriptor_index: 21 }),
                Some(Constant::Utf8("value".to_owned())),
                Some(Constant::Methodref { class_index: 7, name_and_type_index: 30 }),
                Some(Constant::NameAndType { name_index: 31, descriptor_index: 13 }),
                Some(Constant::Utf8("invalidate".to_owned())),
                Some(Constant::Methodref { class_index: 7, name_and_type_index: 33 }),
                Some(Constant::NameAndType { name_index: 34, descriptor_index: 35 }),
                Some(Constant::Utf8("getLabel".to_owned())),
                Some(Constant::Utf8("()Ljava/lang/String;".to_owned())),
                Some(Constant::Methodref { class_index: 37, name_and_type_index: 38 }),
                Some(Constant::Class { name_index: 39 }),
                Some(Constant::NameAndType { name_index: 40, descriptor_index: 41 }),
                Some(Constant::Utf8("javax/microedition/lcdui/Font".to_owned())),
                Some(Constant::Utf8("getDefaultFont".to_owned())),
                Some(Constant::Utf8("()Ljavax/microedition/lcdui/Font;".to_owned())),
                Some(Constant::Methodref { class_index: 37, name_and_type_index: 43 }),
                Some(Constant::NameAndType { name_index: 44, descriptor_index: 45 }),
                Some(Constant::Utf8("getHeight".to_owned())),
                Some(Constant::Utf8("()I".to_owned())),
                Some(Constant::Methodref { class_index: 7, name_and_type_index: 47 }),
                Some(Constant::NameAndType { name_index: 48, descriptor_index: 13 }),
                Some(Constant::Utf8("notifyStateChanged".to_owned())),
                Some(Constant::Methodref { class_index: 50, name_and_type_index: 51 }),
                Some(Constant::Class { name_index: 52 }),
                Some(Constant::NameAndType { name_index: 53, descriptor_index: 25 }),
                Some(Constant::Utf8("javax/microedition/lcdui/Graphics".to_owned())),
                Some(Constant::Utf8("setColor".to_owned())),
                Some(Constant::Methodref { class_index: 50, name_and_type_index: 55 }),
                Some(Constant::NameAndType { name_index: 56, descriptor_index: 57 }),
                Some(Constant::Utf8("drawString".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;III)V".to_owned())),
                Some(Constant::Methodref { class_index: 50, name_and_type_index: 59 }),
                Some(Constant::NameAndType { name_index: 60, descriptor_index: 61 }),
                Some(Constant::Utf8("drawRect".to_owned())),
                Some(Constant::Utf8("(IIII)V".to_owned())),
                Some(Constant::Integer(2379678)),
                Some(Constant::Integer(5592405)),
                Some(Constant::Methodref { class_index: 50, name_and_type_index: 65 }),
                Some(Constant::NameAndType { name_index: 66, descriptor_index: 61 }),
                Some(Constant::Utf8("fillRect".to_owned())),
                Some(Constant::Utf8("INDEFINITE".to_owned())),
                Some(Constant::Utf8("ConstantValue".to_owned())),
                Some(Constant::Integer(-1)),
                Some(Constant::Utf8("CONTINUOUS_IDLE".to_owned())),
                Some(Constant::Integer(0)),
                Some(Constant::Utf8("INCREMENTAL_IDLE".to_owned())),
                Some(Constant::Integer(1)),
                Some(Constant::Utf8("CONTINUOUS_RUNNING".to_owned())),
                Some(Constant::Integer(2)),
                Some(Constant::Utf8("INCREMENTAL_UPDATING".to_owned())),
                Some(Constant::Integer(3)),
                Some(Constant::Utf8("(Ljava/lang/String;ZII)V".to_owned())),
                Some(Constant::Utf8("Code".to_owned())),
                Some(Constant::Utf8("LineNumberTable".to_owned())),
                Some(Constant::Utf8("StackMapTable".to_owned())),
                Some(Constant::Class { name_index: 83 }),
                Some(Constant::Utf8("java/lang/String".to_owned())),
                Some(Constant::Utf8("isInteractive".to_owned())),
                Some(Constant::Utf8("()Z".to_owned())),
                Some(Constant::Utf8("getMaxValue".to_owned())),
                Some(Constant::Utf8("setMaxValue".to_owned())),
                Some(Constant::Utf8("getValue".to_owned())),
                Some(Constant::Utf8("__height".to_owned())),
                Some(Constant::Utf8("(I)I".to_owned())),
                Some(Constant::Utf8("__key".to_owned())),
                Some(Constant::Utf8("__paint".to_owned())),
                Some(Constant::Utf8("(Ljavax/microedition/lcdui/Graphics;IIIZ)V".to_owned())),
                Some(Constant::Utf8("SourceFile".to_owned())),
                Some(Constant::Utf8("generated_bootstrap.rs".to_owned())),
            ],
            access_flags: 33,
            this_class: 7,
            super_class: 2,
            interfaces: vec![],
            fields: vec![
                Member { access_flags: 25, name_index: 67, descriptor_index: 21, attributes: vec![
                    Attribute::Raw { name_index: 68, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x45,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 70, descriptor_index: 21, attributes: vec![
                    Attribute::Raw { name_index: 68, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x47,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 72, descriptor_index: 21, attributes: vec![
                    Attribute::Raw { name_index: 68, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x49,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 74, descriptor_index: 21, attributes: vec![
                    Attribute::Raw { name_index: 68, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x4b,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 76, descriptor_index: 21, attributes: vec![
                    Attribute::Raw { name_index: 68, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x4d,
                    ] },
                ] },
                Member { access_flags: 18, name_index: 16, descriptor_index: 17, attributes: Vec::new() },
                Member { access_flags: 2, name_index: 20, descriptor_index: 21, attributes: Vec::new() },
                Member { access_flags: 2, name_index: 28, descriptor_index: 21, attributes: Vec::new() },
            ],
            methods: vec![
                Member { access_flags: 1, name_index: 5, descriptor_index: 78, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 79, max_stack: 2, max_locals: 5, code: vec![
                        0x2a, 0x2b, 0xb7, 0x00, 0x01, 0x1d, 0x9d, 0x00, 0x10, 0x1d, 0x02, 0x9f, 0x00, 0x0b, 0xbb, 0x00, 0x09, 0x59, 0xb7, 0x00,
                        0x0b, 0xbf, 0x1c, 0x99, 0x00, 0x10, 0x1d, 0x02, 0xa0, 0x00, 0x0b, 0xbb, 0x00, 0x09, 0x59, 0xb7, 0x00, 0x0b, 0xbf, 0x2a,
                        0x1c, 0xb5, 0x00, 0x0e, 0x2a, 0x1d, 0xb5, 0x00, 0x12, 0x2a, 0x15, 0x04, 0xb6, 0x00, 0x16, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 84, descriptor_index: 85, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 79, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x0e, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 86, descriptor_index: 45, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 79, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x12, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 87, descriptor_index: 25, attributes: vec![
                    Attribute::Code(gauge::set_maximum()),
                ] },
                Member { access_flags: 1, name_index: 88, descriptor_index: 45, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 79, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x1a, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 24, descriptor_index: 25, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 79, max_stack: 3, max_locals: 2, code: vec![
                        0x2a, 0xb4, 0x00, 0x12, 0x02, 0xa0, 0x00, 0x1c, 0x1b, 0x9b, 0x00, 0x08, 0x1b, 0x06, 0xa4, 0x00, 0x0b, 0xbb, 0x00, 0x09,
                        0x59, 0xb7, 0x00, 0x0b, 0xbf, 0x2a, 0x1b, 0xb5, 0x00, 0x1a, 0xa7, 0x00, 0x1f, 0x2a, 0x1b, 0x9c, 0x00, 0x07, 0x03, 0xa7,
                        0x00, 0x13, 0x1b, 0x2a, 0xb4, 0x00, 0x12, 0xa4, 0x00, 0x0a, 0x2a, 0xb4, 0x00, 0x12, 0xa7, 0x00, 0x04, 0x1b, 0xb5, 0x00,
                        0x1a, 0x2a, 0xb6, 0x00, 0x1d, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 0, name_index: 89, descriptor_index: 90, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 79, max_stack: 2, max_locals: 2, code: vec![
                        0x2a, 0xb6, 0x00, 0x20, 0xc7, 0x00, 0x07, 0x03, 0xa7, 0x00, 0x0b, 0xb8, 0x00, 0x24, 0xb6, 0x00, 0x2a, 0x04, 0x60, 0x10,
                        0x0e, 0x60, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 0, name_index: 91, descriptor_index: 25, attributes: vec![
                    Attribute::Code(gauge::key()),
                ] },
                Member { access_flags: 0, name_index: 92, descriptor_index: 93, attributes: vec![
                    Attribute::Code(gauge::paint()),
                ] },
            ],
            attributes: Vec::new(),
        },
    );
}
