//! `Timer` and `TimerTask` scheduling declarations.

use super::{
    Attribute, ClassFile, CodeAttribute, Constant, ExceptionHandler, Member,
    append_bootstrap_classes, build_bootstrap_class,
};

pub(super) fn append_timers(classes: &mut Vec<ClassFile>) {
    append_bootstrap_classes!(classes;
        // java/util/Timer
        ClassFile {
            minor_version: 0,
            major_version: 48,
            constant_pool: vec![
                None,
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 3 }),
                Some(Constant::Class { name_index: 4 }),
                Some(Constant::NameAndType { name_index: 5, descriptor_index: 6 }),
                Some(Constant::Utf8("java/lang/Object".to_owned())),
                Some(Constant::Utf8("<init>".to_owned())),
                Some(Constant::Utf8("()V".to_owned())),
                Some(Constant::Long(-1)),
                None,
                Some(Constant::Methodref { class_index: 10, name_and_type_index: 11 }),
                Some(Constant::Class { name_index: 12 }),
                Some(Constant::NameAndType { name_index: 13, descriptor_index: 14 }),
                Some(Constant::Utf8("java/util/Timer".to_owned())),
                Some(Constant::Utf8("scheduleTask".to_owned())),
                Some(Constant::Utf8("(Ljava/util/TimerTask;JJZ)V".to_owned())),
                Some(Constant::Class { name_index: 16 }),
                Some(Constant::Utf8("java/lang/NullPointerException".to_owned())),
                Some(Constant::Methodref { class_index: 15, name_and_type_index: 3 }),
                Some(Constant::Methodref { class_index: 19, name_and_type_index: 20 }),
                Some(Constant::Class { name_index: 21 }),
                Some(Constant::NameAndType { name_index: 22, descriptor_index: 23 }),
                Some(Constant::Utf8("java/util/Date".to_owned())),
                Some(Constant::Utf8("getTime".to_owned())),
                Some(Constant::Utf8("()J".to_owned())),
                Some(Constant::Methodref { class_index: 10, name_and_type_index: 25 }),
                Some(Constant::NameAndType { name_index: 26, descriptor_index: 14 }),
                Some(Constant::Utf8("scheduleAbsolute".to_owned())),
                Some(Constant::Fieldref { class_index: 10, name_and_type_index: 28 }),
                Some(Constant::NameAndType { name_index: 29, descriptor_index: 30 }),
                Some(Constant::Utf8("cancelled".to_owned())),
                Some(Constant::Utf8("Z".to_owned())),
                Some(Constant::Fieldref { class_index: 32, name_and_type_index: 33 }),
                Some(Constant::Class { name_index: 34 }),
                Some(Constant::NameAndType { name_index: 35, descriptor_index: 30 }),
                Some(Constant::Utf8("java/util/TimerTask".to_owned())),
                Some(Constant::Utf8("scheduled".to_owned())),
                Some(Constant::Fieldref { class_index: 32, name_and_type_index: 28 }),
                Some(Constant::Class { name_index: 38 }),
                Some(Constant::Utf8("java/lang/IllegalStateException".to_owned())),
                Some(Constant::Methodref { class_index: 37, name_and_type_index: 3 }),
                Some(Constant::Class { name_index: 41 }),
                Some(Constant::Utf8("java/lang/IllegalArgumentException".to_owned())),
                Some(Constant::Methodref { class_index: 40, name_and_type_index: 3 }),
                Some(Constant::Methodref { class_index: 44, name_and_type_index: 45 }),
                Some(Constant::Class { name_index: 46 }),
                Some(Constant::NameAndType { name_index: 47, descriptor_index: 23 }),
                Some(Constant::Utf8("java/lang/System".to_owned())),
                Some(Constant::Utf8("currentTimeMillis".to_owned())),
                Some(Constant::Fieldref { class_index: 32, name_and_type_index: 49 }),
                Some(Constant::NameAndType { name_index: 50, descriptor_index: 51 }),
                Some(Constant::Utf8("executionTime".to_owned())),
                Some(Constant::Utf8("J".to_owned())),
                Some(Constant::Methodref { class_index: 10, name_and_type_index: 53 }),
                Some(Constant::NameAndType { name_index: 54, descriptor_index: 14 }),
                Some(Constant::Utf8("schedule0".to_owned())),
                Some(Constant::Class { name_index: 56 }),
                Some(Constant::Utf8("java/lang/Error".to_owned())),
                Some(Constant::Class { name_index: 58 }),
                Some(Constant::Utf8("java/lang/Long".to_owned())),
                Some(Constant::Long(9223372036854775807)),
                None,
                Some(Constant::Methodref { class_index: 10, name_and_type_index: 62 }),
                Some(Constant::NameAndType { name_index: 63, descriptor_index: 6 }),
                Some(Constant::Utf8("cancel0".to_owned())),
                Some(Constant::Utf8("Code".to_owned())),
                Some(Constant::Utf8("LineNumberTable".to_owned())),
                Some(Constant::Utf8("schedule".to_owned())),
                Some(Constant::Utf8("(Ljava/util/TimerTask;J)V".to_owned())),
                Some(Constant::Utf8("(Ljava/util/TimerTask;Ljava/util/Date;)V".to_owned())),
                Some(Constant::Utf8("StackMapTable".to_owned())),
                Some(Constant::Utf8("(Ljava/util/TimerTask;JJ)V".to_owned())),
                Some(Constant::Utf8("(Ljava/util/TimerTask;Ljava/util/Date;J)V".to_owned())),
                Some(Constant::Utf8("scheduleAtFixedRate".to_owned())),
                Some(Constant::Utf8("cancel".to_owned())),
                Some(Constant::Utf8("SourceFile".to_owned())),
                Some(Constant::Utf8("generated_bootstrap.rs".to_owned())),
            ],
            access_flags: 33,
            this_class: 10,
            super_class: 2,
            interfaces: vec![],
            fields: vec![
                Member { access_flags: 2, name_index: 29, descriptor_index: 30, attributes: Vec::new() },
            ],
            methods: vec![
                Member { access_flags: 258, name_index: 54, descriptor_index: 14, attributes: Vec::new() },
                Member { access_flags: 258, name_index: 63, descriptor_index: 6, attributes: Vec::new() },
                Member { access_flags: 1, name_index: 5, descriptor_index: 6, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 64, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb7, 0x00, 0x01, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 66, descriptor_index: 67, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 64, max_stack: 7, max_locals: 4, code: vec![
                        0x2a, 0x2b, 0x20, 0x14, 0x00, 0x07, 0x03, 0xb7, 0x00, 0x09, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 66, descriptor_index: 68, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 64, max_stack: 7, max_locals: 3, code: vec![
                        0x2c, 0xc7, 0x00, 0x0b, 0xbb, 0x00, 0x0f, 0x59, 0xb7, 0x00, 0x11, 0xbf, 0x2a, 0x2b, 0x2c, 0xb6, 0x00, 0x12, 0x14, 0x00,
                        0x07, 0x03, 0xb7, 0x00, 0x18, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 66, descriptor_index: 70, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 64, max_stack: 7, max_locals: 6, code: vec![
                        0x2a, 0x2b, 0x20, 0x16, 0x04, 0x03, 0xb7, 0x00, 0x09, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 66, descriptor_index: 71, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 64, max_stack: 7, max_locals: 5, code: vec![
                        0x2c, 0xc7, 0x00, 0x0b, 0xbb, 0x00, 0x0f, 0x59, 0xb7, 0x00, 0x11, 0xbf, 0x2a, 0x2b, 0x2c, 0xb6, 0x00, 0x12, 0x21, 0x03,
                        0xb7, 0x00, 0x18, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 72, descriptor_index: 70, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 64, max_stack: 7, max_locals: 6, code: vec![
                        0x2a, 0x2b, 0x20, 0x16, 0x04, 0x04, 0xb7, 0x00, 0x09, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 72, descriptor_index: 71, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 64, max_stack: 7, max_locals: 5, code: vec![
                        0x2c, 0xc7, 0x00, 0x0b, 0xbb, 0x00, 0x0f, 0x59, 0xb7, 0x00, 0x11, 0xbf, 0x2a, 0x2b, 0x2c, 0xb6, 0x00, 0x12, 0x21, 0x04,
                        0xb7, 0x00, 0x18, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 2, name_index: 26, descriptor_index: 14, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 64, max_stack: 7, max_locals: 10, code: vec![
                        0x2b, 0xc7, 0x00, 0x0b, 0xbb, 0x00, 0x0f, 0x59, 0xb7, 0x00, 0x11, 0xbf, 0x2a, 0xb4, 0x00, 0x1b, 0x9a, 0x00, 0x11, 0x2b,
                        0xb4, 0x00, 0x1f, 0x9a, 0x00, 0x0a, 0x2b, 0xb4, 0x00, 0x24, 0x99, 0x00, 0x0b, 0xbb, 0x00, 0x25, 0x59, 0xb7, 0x00, 0x27,
                        0xbf, 0x20, 0x09, 0x94, 0x9b, 0x00, 0x13, 0x16, 0x04, 0x09, 0x94, 0x99, 0x00, 0x0c, 0x16, 0x04, 0x14, 0x00, 0x07, 0x94,
                        0x9c, 0x00, 0x0b, 0xbb, 0x00, 0x28, 0x59, 0xb7, 0x00, 0x2a, 0xbf, 0xb8, 0x00, 0x2b, 0x37, 0x07, 0x20, 0x16, 0x07, 0x94,
                        0x9c, 0x00, 0x06, 0x16, 0x07, 0x41, 0x2b, 0x04, 0xb5, 0x00, 0x1f, 0x2b, 0x20, 0xb5, 0x00, 0x30, 0x2a, 0x2b, 0x20, 0x16,
                        0x04, 0x15, 0x06, 0xb7, 0x00, 0x34, 0xa7, 0x00, 0x12, 0x3a, 0x09, 0x2b, 0x03, 0xb5, 0x00, 0x1f, 0x2b, 0x09, 0xb5, 0x00,
                        0x30, 0x19, 0x09, 0xbf, 0xb1,
                    ], exception_table: vec![
                        ExceptionHandler { start_pc: 96, end_pc: 106, handler_pc: 109, catch_type: 55 },
                    ], attributes: Vec::new() }),
                ] },
                Member { access_flags: 2, name_index: 13, descriptor_index: 14, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 64, max_stack: 7, max_locals: 10, code: vec![
                        0x2b, 0xc7, 0x00, 0x0b, 0xbb, 0x00, 0x0f, 0x59, 0xb7, 0x00, 0x11, 0xbf, 0x2a, 0xb4, 0x00, 0x1b, 0x9a, 0x00, 0x11, 0x2b,
                        0xb4, 0x00, 0x1f, 0x9a, 0x00, 0x0a, 0x2b, 0xb4, 0x00, 0x24, 0x99, 0x00, 0x0b, 0xbb, 0x00, 0x25, 0x59, 0xb7, 0x00, 0x27,
                        0xbf, 0x20, 0x09, 0x94, 0x9b, 0x00, 0x13, 0x16, 0x04, 0x09, 0x94, 0x99, 0x00, 0x0c, 0x16, 0x04, 0x14, 0x00, 0x07, 0x94,
                        0x9c, 0x00, 0x0b, 0xbb, 0x00, 0x28, 0x59, 0xb7, 0x00, 0x2a, 0xbf, 0xb8, 0x00, 0x2b, 0x37, 0x07, 0x16, 0x07, 0x09, 0x94,
                        0x9e, 0x00, 0x16, 0x20, 0x14, 0x00, 0x3b, 0x16, 0x07, 0x65, 0x94, 0x9e, 0x00, 0x0b, 0xbb, 0x00, 0x28, 0x59, 0xb7, 0x00,
                        0x2a, 0xbf, 0x2b, 0x04, 0xb5, 0x00, 0x1f, 0x2b, 0x16, 0x07, 0x20, 0x61, 0xb5, 0x00, 0x30, 0x2a, 0x2b, 0x2b, 0xb4, 0x00,
                        0x30, 0x16, 0x04, 0x15, 0x06, 0xb7, 0x00, 0x34, 0xa7, 0x00, 0x12, 0x3a, 0x09, 0x2b, 0x03, 0xb5, 0x00, 0x1f, 0x2b, 0x09,
                        0xb5, 0x00, 0x30, 0x19, 0x09, 0xbf, 0xb1,
                    ], exception_table: vec![
                        ExceptionHandler { start_pc: 115, end_pc: 128, handler_pc: 131, catch_type: 55 },
                    ], attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 73, descriptor_index: 6, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 64, max_stack: 2, max_locals: 1, code: vec![
                        0x2a, 0x04, 0xb5, 0x00, 0x1b, 0x2a, 0xb7, 0x00, 0x3d, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
            ],
            attributes: Vec::new(),
        },
        // java/util/TimerTask
        ClassFile {
            minor_version: 0,
            major_version: 48,
            constant_pool: vec![
                None,
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 3 }),
                Some(Constant::Class { name_index: 4 }),
                Some(Constant::NameAndType { name_index: 5, descriptor_index: 6 }),
                Some(Constant::Utf8("java/lang/Object".to_owned())),
                Some(Constant::Utf8("<init>".to_owned())),
                Some(Constant::Utf8("()V".to_owned())),
                Some(Constant::Fieldref { class_index: 8, name_and_type_index: 9 }),
                Some(Constant::Class { name_index: 10 }),
                Some(Constant::NameAndType { name_index: 11, descriptor_index: 12 }),
                Some(Constant::Utf8("java/util/TimerTask".to_owned())),
                Some(Constant::Utf8("scheduled".to_owned())),
                Some(Constant::Utf8("Z".to_owned())),
                Some(Constant::Fieldref { class_index: 8, name_and_type_index: 14 }),
                Some(Constant::NameAndType { name_index: 15, descriptor_index: 12 }),
                Some(Constant::Utf8("cancelled".to_owned())),
                Some(Constant::Fieldref { class_index: 8, name_and_type_index: 17 }),
                Some(Constant::NameAndType { name_index: 18, descriptor_index: 19 }),
                Some(Constant::Utf8("executionTime".to_owned())),
                Some(Constant::Utf8("J".to_owned())),
                Some(Constant::Class { name_index: 21 }),
                Some(Constant::Utf8("java/lang/Runnable".to_owned())),
                Some(Constant::Utf8("Code".to_owned())),
                Some(Constant::Utf8("LineNumberTable".to_owned())),
                Some(Constant::Utf8("run".to_owned())),
                Some(Constant::Utf8("cancel".to_owned())),
                Some(Constant::Utf8("()Z".to_owned())),
                Some(Constant::Utf8("StackMapTable".to_owned())),
                Some(Constant::Utf8("scheduledExecutionTime".to_owned())),
                Some(Constant::Utf8("()J".to_owned())),
                Some(Constant::Utf8("SourceFile".to_owned())),
                Some(Constant::Utf8("generated_bootstrap.rs".to_owned())),
            ],
            access_flags: 1057,
            this_class: 8,
            super_class: 2,
            interfaces: vec![20],
            fields: vec![
                Member { access_flags: 0, name_index: 11, descriptor_index: 12, attributes: Vec::new() },
                Member { access_flags: 0, name_index: 15, descriptor_index: 12, attributes: Vec::new() },
                Member { access_flags: 0, name_index: 18, descriptor_index: 19, attributes: Vec::new() },
            ],
            methods: vec![
                Member { access_flags: 1, name_index: 5, descriptor_index: 6, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 22, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb7, 0x00, 0x01, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1025, name_index: 24, descriptor_index: 6, attributes: Vec::new() },
                Member { access_flags: 1, name_index: 25, descriptor_index: 26, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 22, max_stack: 2, max_locals: 2, code: vec![
                        0x2a, 0xb4, 0x00, 0x07, 0x99, 0x00, 0x0e, 0x2a, 0xb4, 0x00, 0x0d, 0x9a, 0x00, 0x07, 0x04, 0xa7, 0x00, 0x04, 0x03, 0x3c,
                        0x2a, 0x04, 0xb5, 0x00, 0x0d, 0x1b, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 28, descriptor_index: 29, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 22, max_stack: 2, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x10, 0xad,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
            ],
            attributes: Vec::new(),
        },
    );
}
