//! `FileConnection` implementation and listing.

use super::filter::wildcard_code;
use super::{
    Attribute, ClassFile, CodeAttribute, Constant, ExceptionHandler, Member,
    append_bootstrap_classes, build_bootstrap_class,
};

pub(super) fn append_classes(classes: &mut Vec<ClassFile>) {
    append_bootstrap_classes!(classes;
        // javax/microedition/io/file/FileConnectionImpl
        ClassFile {
            minor_version: 0,
            major_version: 48,
            constant_pool: vec![
                None,
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 3 }),
                Some(Constant::Class { name_index: 4 }),
                Some(Constant::NameAndType { name_index: 5, descriptor_index: 6 }),
                Some(Constant::Utf8("javax/microedition/io/file/FileConnectionImpl".to_owned())),
                Some(Constant::Utf8("writeAt0".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;[BJ)V".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 8 }),
                Some(Constant::NameAndType { name_index: 9, descriptor_index: 10 }),
                Some(Constant::Utf8("write0".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;[BZ)V".to_owned())),
                Some(Constant::Fieldref { class_index: 2, name_and_type_index: 12 }),
                Some(Constant::NameAndType { name_index: 13, descriptor_index: 14 }),
                Some(Constant::Utf8("url".to_owned())),
                Some(Constant::Utf8("Ljava/lang/String;".to_owned())),
                Some(Constant::Methodref { class_index: 16, name_and_type_index: 17 }),
                Some(Constant::Class { name_index: 18 }),
                Some(Constant::NameAndType { name_index: 19, descriptor_index: 20 }),
                Some(Constant::Utf8("java/lang/Object".to_owned())),
                Some(Constant::Utf8("<init>".to_owned())),
                Some(Constant::Utf8("()V".to_owned())),
                Some(Constant::Fieldref { class_index: 2, name_and_type_index: 22 }),
                Some(Constant::NameAndType { name_index: 23, descriptor_index: 24 }),
                Some(Constant::Utf8("open".to_owned())),
                Some(Constant::Utf8("Z".to_owned())),
                Some(Constant::Fieldref { class_index: 2, name_and_type_index: 26 }),
                Some(Constant::NameAndType { name_index: 27, descriptor_index: 28 }),
                Some(Constant::Utf8("mode".to_owned())),
                Some(Constant::Utf8("I".to_owned())),
                Some(Constant::Class { name_index: 30 }),
                Some(Constant::Utf8("javax/microedition/io/file/IllegalModeException".to_owned())),
                Some(Constant::String { string_index: 32 }),
                Some(Constant::Utf8("connection closed".to_owned())),
                Some(Constant::Methodref { class_index: 29, name_and_type_index: 34 }),
                Some(Constant::NameAndType { name_index: 19, descriptor_index: 35 }),
                Some(Constant::Utf8("(Ljava/lang/String;)V".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 37 }),
                Some(Constant::NameAndType { name_index: 38, descriptor_index: 20 }),
                Some(Constant::Utf8("requireOpen".to_owned())),
                Some(Constant::Class { name_index: 40 }),
                Some(Constant::Utf8("javax/microedition/io/Connector".to_owned())),
                Some(Constant::String { string_index: 42 }),
                Some(Constant::Utf8("connection is not readable".to_owned())),
                Some(Constant::String { string_index: 44 }),
                Some(Constant::Utf8("connection is not writable".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 46 }),
                Some(Constant::NameAndType { name_index: 47, descriptor_index: 20 }),
                Some(Constant::Utf8("requireRead".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 49 }),
                Some(Constant::NameAndType { name_index: 50, descriptor_index: 51 }),
                Some(Constant::Utf8("metadata0".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;)[J".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 53 }),
                Some(Constant::NameAndType { name_index: 54, descriptor_index: 55 }),
                Some(Constant::Utf8("metadata".to_owned())),
                Some(Constant::Utf8("()[J".to_owned())),
                Some(Constant::Class { name_index: 57 }),
                Some(Constant::Utf8("java/io/IOException".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 59 }),
                Some(Constant::NameAndType { name_index: 60, descriptor_index: 61 }),
                Some(Constant::Utf8("getName".to_owned())),
                Some(Constant::Utf8("()Ljava/lang/String;".to_owned())),
                Some(Constant::String { string_index: 63 }),
                Some(Constant::Utf8(".".to_owned())),
                Some(Constant::Methodref { class_index: 65, name_and_type_index: 66 }),
                Some(Constant::Class { name_index: 67 }),
                Some(Constant::NameAndType { name_index: 68, descriptor_index: 69 }),
                Some(Constant::Utf8("java/lang/String".to_owned())),
                Some(Constant::Utf8("startsWith".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;)Z".to_owned())),
                Some(Constant::Class { name_index: 71 }),
                Some(Constant::Utf8("java/io/ByteArrayInputStream".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 73 }),
                Some(Constant::NameAndType { name_index: 74, descriptor_index: 75 }),
                Some(Constant::Utf8("read0".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;)[B".to_owned())),
                Some(Constant::Methodref { class_index: 70, name_and_type_index: 77 }),
                Some(Constant::NameAndType { name_index: 19, descriptor_index: 78 }),
                Some(Constant::Utf8("([B)V".to_owned())),
                Some(Constant::Class { name_index: 80 }),
                Some(Constant::Utf8("java/io/DataInputStream".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 82 }),
                Some(Constant::NameAndType { name_index: 83, descriptor_index: 84 }),
                Some(Constant::Utf8("openInputStream".to_owned())),
                Some(Constant::Utf8("()Ljava/io/InputStream;".to_owned())),
                Some(Constant::Methodref { class_index: 79, name_and_type_index: 86 }),
                Some(Constant::NameAndType { name_index: 19, descriptor_index: 87 }),
                Some(Constant::Utf8("(Ljava/io/InputStream;)V".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 89 }),
                Some(Constant::NameAndType { name_index: 90, descriptor_index: 91 }),
                Some(Constant::Utf8("openOutputStream".to_owned())),
                Some(Constant::Utf8("(J)Ljava/io/OutputStream;".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 93 }),
                Some(Constant::NameAndType { name_index: 94, descriptor_index: 20 }),
                Some(Constant::Utf8("requireWrite".to_owned())),
                Some(Constant::Class { name_index: 96 }),
                Some(Constant::Utf8("java/lang/IllegalArgumentException".to_owned())),
                Some(Constant::Methodref { class_index: 95, name_and_type_index: 17 }),
                Some(Constant::Class { name_index: 99 }),
                Some(Constant::Utf8("javax/microedition/io/file/FileConnectionImpl$FileOutput".to_owned())),
                Some(Constant::Methodref { class_index: 98, name_and_type_index: 101 }),
                Some(Constant::NameAndType { name_index: 19, descriptor_index: 102 }),
                Some(Constant::Utf8("(Ljavax/microedition/io/file/FileConnectionImpl;J)V".to_owned())),
                Some(Constant::Class { name_index: 104 }),
                Some(Constant::Utf8("java/io/DataOutputStream".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 106 }),
                Some(Constant::NameAndType { name_index: 90, descriptor_index: 107 }),
                Some(Constant::Utf8("()Ljava/io/OutputStream;".to_owned())),
                Some(Constant::Methodref { class_index: 103, name_and_type_index: 109 }),
                Some(Constant::NameAndType { name_index: 19, descriptor_index: 110 }),
                Some(Constant::Utf8("(Ljava/io/OutputStream;)V".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 112 }),
                Some(Constant::NameAndType { name_index: 113, descriptor_index: 35 }),
                Some(Constant::Utf8("create0".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 115 }),
                Some(Constant::NameAndType { name_index: 116, descriptor_index: 35 }),
                Some(Constant::Utf8("mkdir0".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 118 }),
                Some(Constant::NameAndType { name_index: 119, descriptor_index: 35 }),
                Some(Constant::Utf8("delete0".to_owned())),
                Some(Constant::Class { name_index: 121 }),
                Some(Constant::Utf8("java/lang/NullPointerException".to_owned())),
                Some(Constant::Methodref { class_index: 120, name_and_type_index: 17 }),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 124 }),
                Some(Constant::NameAndType { name_index: 125, descriptor_index: 126 }),
                Some(Constant::Utf8("rename0".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 128 }),
                Some(Constant::NameAndType { name_index: 129, descriptor_index: 130 }),
                Some(Constant::Utf8("truncate0".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;J)V".to_owned())),
                Some(Constant::String { string_index: 132 }),
                Some(Constant::Utf8("*".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 134 }),
                Some(Constant::NameAndType { name_index: 135, descriptor_index: 136 }),
                Some(Constant::Utf8("list".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;Z)Ljava/util/Enumeration;".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 138 }),
                Some(Constant::NameAndType { name_index: 139, descriptor_index: 75 }),
                Some(Constant::Utf8("list0".to_owned())),
                Some(Constant::Methodref { class_index: 79, name_and_type_index: 141 }),
                Some(Constant::NameAndType { name_index: 142, descriptor_index: 143 }),
                Some(Constant::Utf8("readInt".to_owned())),
                Some(Constant::Utf8("()I".to_owned())),
                Some(Constant::Class { name_index: 145 }),
                Some(Constant::Utf8("java/util/Vector".to_owned())),
                Some(Constant::Methodref { class_index: 144, name_and_type_index: 17 }),
                Some(Constant::Methodref { class_index: 79, name_and_type_index: 148 }),
                Some(Constant::NameAndType { name_index: 149, descriptor_index: 61 }),
                Some(Constant::Utf8("readUTF".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 151 }),
                Some(Constant::NameAndType { name_index: 152, descriptor_index: 153 }),
                Some(Constant::Utf8("matches".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;Ljava/lang/String;)Z".to_owned())),
                Some(Constant::Methodref { class_index: 144, name_and_type_index: 155 }),
                Some(Constant::NameAndType { name_index: 156, descriptor_index: 157 }),
                Some(Constant::Utf8("addElement".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/Object;)V".to_owned())),
                Some(Constant::Methodref { class_index: 144, name_and_type_index: 159 }),
                Some(Constant::NameAndType { name_index: 160, descriptor_index: 161 }),
                Some(Constant::Utf8("elements".to_owned())),
                Some(Constant::Utf8("()Ljava/util/Enumeration;".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 163 }),
                Some(Constant::NameAndType { name_index: 164, descriptor_index: 165 }),
                Some(Constant::Utf8("wildcard".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;ILjava/lang/String;I)Z".to_owned())),
                Some(Constant::Methodref { class_index: 65, name_and_type_index: 167 }),
                Some(Constant::NameAndType { name_index: 168, descriptor_index: 143 }),
                Some(Constant::Utf8("length".to_owned())),
                Some(Constant::Methodref { class_index: 65, name_and_type_index: 170 }),
                Some(Constant::NameAndType { name_index: 171, descriptor_index: 172 }),
                Some(Constant::Utf8("charAt".to_owned())),
                Some(Constant::Utf8("(I)C".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 174 }),
                Some(Constant::NameAndType { name_index: 175, descriptor_index: 176 }),
                Some(Constant::Utf8("directorySize0".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;Z)J".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 178 }),
                Some(Constant::NameAndType { name_index: 179, descriptor_index: 180 }),
                Some(Constant::Utf8("space0".to_owned())),
                Some(Constant::Utf8("(I)J".to_owned())),
                Some(Constant::Long(-1)),
                None,
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 184 }),
                Some(Constant::NameAndType { name_index: 185, descriptor_index: 186 }),
                Some(Constant::Utf8("isHidden".to_owned())),
                Some(Constant::Utf8("()Z".to_owned())),
                Some(Constant::String { string_index: 188 }),
                Some(Constant::Utf8("hidden attribute unsupported".to_owned())),
                Some(Constant::Methodref { class_index: 56, name_and_type_index: 34 }),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 191 }),
                Some(Constant::NameAndType { name_index: 192, descriptor_index: 186 }),
                Some(Constant::Utf8("canRead".to_owned())),
                Some(Constant::String { string_index: 194 }),
                Some(Constant::Utf8("readable attribute unsupported".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 196 }),
                Some(Constant::NameAndType { name_index: 197, descriptor_index: 186 }),
                Some(Constant::Utf8("canWrite".to_owned())),
                Some(Constant::String { string_index: 199 }),
                Some(Constant::Utf8("writable attribute unsupported".to_owned())),
                Some(Constant::Methodref { class_index: 65, name_and_type_index: 201 }),
                Some(Constant::NameAndType { name_index: 202, descriptor_index: 203 }),
                Some(Constant::Utf8("equals".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/Object;)Z".to_owned())),
                Some(Constant::String { string_index: 205 }),
                Some(Constant::Utf8("..".to_owned())),
                Some(Constant::Methodref { class_index: 65, name_and_type_index: 207 }),
                Some(Constant::NameAndType { name_index: 208, descriptor_index: 209 }),
                Some(Constant::Utf8("indexOf".to_owned())),
                Some(Constant::Utf8("(I)I".to_owned())),
                Some(Constant::String { string_index: 211 }),
                Some(Constant::Utf8("/".to_owned())),
                Some(Constant::Methodref { class_index: 65, name_and_type_index: 213 }),
                Some(Constant::NameAndType { name_index: 214, descriptor_index: 69 }),
                Some(Constant::Utf8("endsWith".to_owned())),
                Some(Constant::Methodref { class_index: 65, name_and_type_index: 216 }),
                Some(Constant::NameAndType { name_index: 217, descriptor_index: 209 }),
                Some(Constant::Utf8("lastIndexOf".to_owned())),
                Some(Constant::Methodref { class_index: 65, name_and_type_index: 219 }),
                Some(Constant::NameAndType { name_index: 220, descriptor_index: 221 }),
                Some(Constant::Utf8("substring".to_owned())),
                Some(Constant::Utf8("(II)Ljava/lang/String;".to_owned())),
                Some(Constant::Methodref { class_index: 65, name_and_type_index: 223 }),
                Some(Constant::NameAndType { name_index: 224, descriptor_index: 225 }),
                Some(Constant::Utf8("concat".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;)Ljava/lang/String;".to_owned())),
                Some(Constant::Methodref { class_index: 65, name_and_type_index: 227 }),
                Some(Constant::NameAndType { name_index: 220, descriptor_index: 228 }),
                Some(Constant::Utf8("(I)Ljava/lang/String;".to_owned())),
                Some(Constant::String { string_index: 230 }),
                Some(Constant::Utf8("".to_owned())),
                Some(Constant::String { string_index: 232 }),
                Some(Constant::Utf8("//".to_owned())),
                Some(Constant::Methodref { class_index: 65, name_and_type_index: 234 }),
                Some(Constant::NameAndType { name_index: 208, descriptor_index: 235 }),
                Some(Constant::Utf8("(Ljava/lang/String;)I".to_owned())),
                Some(Constant::Methodref { class_index: 65, name_and_type_index: 237 }),
                Some(Constant::NameAndType { name_index: 208, descriptor_index: 238 }),
                Some(Constant::Utf8("(II)I".to_owned())),
                Some(Constant::Class { name_index: 240 }),
                Some(Constant::Utf8("javax/microedition/io/file/FileConnection".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;I)V".to_owned())),
                Some(Constant::Utf8("Code".to_owned())),
                Some(Constant::Utf8("LineNumberTable".to_owned())),
                Some(Constant::Utf8("Exceptions".to_owned())),
                Some(Constant::Utf8("StackMapTable".to_owned())),
                Some(Constant::Utf8("close".to_owned())),
                Some(Constant::Utf8("exists".to_owned())),
                Some(Constant::Utf8("isDirectory".to_owned())),
                Some(Constant::Utf8("fileSize".to_owned())),
                Some(Constant::Utf8("()J".to_owned())),
                Some(Constant::Utf8("lastModified".to_owned())),
                Some(Constant::Utf8("openDataInputStream".to_owned())),
                Some(Constant::Utf8("()Ljava/io/DataInputStream;".to_owned())),
                Some(Constant::Utf8("openDataOutputStream".to_owned())),
                Some(Constant::Utf8("()Ljava/io/DataOutputStream;".to_owned())),
                Some(Constant::Utf8("create".to_owned())),
                Some(Constant::Utf8("mkdir".to_owned())),
                Some(Constant::Utf8("delete".to_owned())),
                Some(Constant::Utf8("rename".to_owned())),
                Some(Constant::Utf8("truncate".to_owned())),
                Some(Constant::Utf8("(J)V".to_owned())),
                Some(Constant::Utf8("directorySize".to_owned())),
                Some(Constant::Utf8("(Z)J".to_owned())),
                Some(Constant::Utf8("totalSize".to_owned())),
                Some(Constant::Utf8("availableSize".to_owned())),
                Some(Constant::Utf8("usedSize".to_owned())),
                Some(Constant::Utf8("setHidden".to_owned())),
                Some(Constant::Utf8("(Z)V".to_owned())),
                Some(Constant::Utf8("setReadable".to_owned())),
                Some(Constant::Utf8("setWritable".to_owned())),
                Some(Constant::Utf8("setFileConnection".to_owned())),
                Some(Constant::Utf8("getURL".to_owned())),
                Some(Constant::Utf8("getPath".to_owned())),
                Some(Constant::Utf8("access$000".to_owned())),
                Some(Constant::Utf8("(Ljavax/microedition/io/file/FileConnectionImpl;)Ljava/lang/String;".to_owned())),
                Some(Constant::Utf8("access$100".to_owned())),
                Some(Constant::Utf8("access$200".to_owned())),
                Some(Constant::Utf8("SourceFile".to_owned())),
                Some(Constant::Utf8("generated_bootstrap.rs".to_owned())),
                Some(Constant::Utf8("InnerClasses".to_owned())),
                Some(Constant::Utf8("FileOutput".to_owned())),
            ],
            access_flags: 49,
            this_class: 2,
            super_class: 16,
            interfaces: vec![239],
            fields: vec![
                Member { access_flags: 2, name_index: 13, descriptor_index: 14, attributes: Vec::new() },
                Member { access_flags: 18, name_index: 27, descriptor_index: 28, attributes: Vec::new() },
                Member { access_flags: 2, name_index: 23, descriptor_index: 24, attributes: Vec::new() },
            ],
            methods: vec![
                Member { access_flags: 1, name_index: 19, descriptor_index: 241, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 242, max_stack: 2, max_locals: 3, code: vec![
                        0x2a, 0xb7, 0x00, 0x0f, 0x2a, 0x04, 0xb5, 0x00, 0x15, 0x2a, 0x2b, 0xb5, 0x00, 0x0b, 0x2a, 0x1c, 0xb5, 0x00, 0x19, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 266, name_index: 50, descriptor_index: 51, attributes: Vec::new() },
                Member { access_flags: 266, name_index: 74, descriptor_index: 75, attributes: Vec::new() },
                Member { access_flags: 266, name_index: 9, descriptor_index: 10, attributes: Vec::new() },
                Member { access_flags: 266, name_index: 5, descriptor_index: 6, attributes: Vec::new() },
                Member { access_flags: 266, name_index: 113, descriptor_index: 35, attributes: Vec::new() },
                Member { access_flags: 266, name_index: 116, descriptor_index: 35, attributes: Vec::new() },
                Member { access_flags: 266, name_index: 119, descriptor_index: 35, attributes: Vec::new() },
                Member { access_flags: 266, name_index: 125, descriptor_index: 126, attributes: Vec::new() },
                Member { access_flags: 266, name_index: 129, descriptor_index: 130, attributes: Vec::new() },
                Member { access_flags: 266, name_index: 139, descriptor_index: 75, attributes: Vec::new() },
                Member { access_flags: 266, name_index: 175, descriptor_index: 176, attributes: Vec::new() },
                Member { access_flags: 266, name_index: 179, descriptor_index: 180, attributes: Vec::new() },
                Member { access_flags: 2, name_index: 38, descriptor_index: 20, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 242, max_stack: 3, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x15, 0x9a, 0x00, 0x0d, 0xbb, 0x00, 0x1d, 0x59, 0x12, 0x1f, 0xb7, 0x00, 0x21, 0xbf, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 2, name_index: 47, descriptor_index: 20, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 242, max_stack: 3, max_locals: 1, code: vec![
                        0x2a, 0xb7, 0x00, 0x24, 0x2a, 0xb4, 0x00, 0x19, 0x04, 0x7e, 0x9a, 0x00, 0x0d, 0xbb, 0x00, 0x1d, 0x59, 0x12, 0x29, 0xb7,
                        0x00, 0x21, 0xbf, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 2, name_index: 94, descriptor_index: 20, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 242, max_stack: 3, max_locals: 1, code: vec![
                        0x2a, 0xb7, 0x00, 0x24, 0x2a, 0xb4, 0x00, 0x19, 0x05, 0x7e, 0x9a, 0x00, 0x0d, 0xbb, 0x00, 0x1d, 0x59, 0x12, 0x2b, 0xb7,
                        0x00, 0x21, 0xbf, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 2, name_index: 54, descriptor_index: 55, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 242, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb7, 0x00, 0x2d, 0x2a, 0xb4, 0x00, 0x0b, 0xb8, 0x00, 0x30, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 246, descriptor_index: 20, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 242, max_stack: 2, max_locals: 1, code: vec![
                        0x2a, 0x03, 0xb5, 0x00, 0x15, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 247, descriptor_index: 186, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 242, max_stack: 4, max_locals: 2, code: vec![
                        0x2a, 0xb7, 0x00, 0x34, 0x03, 0x2f, 0x09, 0x94, 0x99, 0x00, 0x07, 0x04, 0xa7, 0x00, 0x04, 0x03, 0xac, 0x4c, 0x03, 0xac,
                    ], exception_table: vec![
                        ExceptionHandler { start_pc: 0, end_pc: 16, handler_pc: 17, catch_type: 56 },
                    ], attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 248, descriptor_index: 186, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 242, max_stack: 4, max_locals: 2, code: vec![
                        0x2a, 0xb7, 0x00, 0x34, 0x04, 0x2f, 0x09, 0x94, 0x99, 0x00, 0x07, 0x04, 0xa7, 0x00, 0x04, 0x03, 0xac, 0x4c, 0x03, 0xac,
                    ], exception_table: vec![
                        ExceptionHandler { start_pc: 0, end_pc: 16, handler_pc: 17, catch_type: 56 },
                    ], attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 192, descriptor_index: 186, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 242, max_stack: 4, max_locals: 2, code: vec![
                        0x2a, 0xb7, 0x00, 0x34, 0x07, 0x2f, 0x09, 0x94, 0x99, 0x00, 0x07, 0x04, 0xa7, 0x00, 0x04, 0x03, 0xac, 0x4c, 0x03, 0xac,
                    ], exception_table: vec![
                        ExceptionHandler { start_pc: 0, end_pc: 16, handler_pc: 17, catch_type: 56 },
                    ], attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 197, descriptor_index: 186, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 242, max_stack: 4, max_locals: 2, code: vec![
                        0x2a, 0xb7, 0x00, 0x34, 0x08, 0x2f, 0x09, 0x94, 0x99, 0x00, 0x07, 0x04, 0xa7, 0x00, 0x04, 0x03, 0xac, 0x4c, 0x03, 0xac,
                    ], exception_table: vec![
                        ExceptionHandler { start_pc: 0, end_pc: 16, handler_pc: 17, catch_type: 56 },
                    ], attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 185, descriptor_index: 186, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 242, max_stack: 2, max_locals: 1, code: vec![
                        0x2a, 0xb6, 0x00, 0x3a, 0x12, 0x3e, 0xb6, 0x00, 0x40, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 249, descriptor_index: 250, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 242, max_stack: 2, max_locals: 1, code: vec![
                        0x2a, 0xb7, 0x00, 0x34, 0x05, 0x2f, 0xad,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 251, descriptor_index: 250, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 242, max_stack: 2, max_locals: 2, code: vec![
                        0x2a, 0xb7, 0x00, 0x34, 0x06, 0x2f, 0xad, 0x4c, 0x09, 0xad,
                    ], exception_table: vec![
                        ExceptionHandler { start_pc: 0, end_pc: 6, handler_pc: 7, catch_type: 56 },
                    ], attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 83, descriptor_index: 84, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 242, max_stack: 3, max_locals: 1, code: vec![
                        0x2a, 0xb7, 0x00, 0x2d, 0xbb, 0x00, 0x46, 0x59, 0x2a, 0xb4, 0x00, 0x0b, 0xb8, 0x00, 0x48, 0xb7, 0x00, 0x4c, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 252, descriptor_index: 253, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 242, max_stack: 3, max_locals: 1, code: vec![
                        0xbb, 0x00, 0x4f, 0x59, 0x2a, 0xb6, 0x00, 0x51, 0xb7, 0x00, 0x55, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 90, descriptor_index: 107, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 242, max_stack: 3, max_locals: 1, code: vec![
                        0x2a, 0x09, 0xb6, 0x00, 0x58, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 90, descriptor_index: 91, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 242, max_stack: 5, max_locals: 3, code: vec![
                        0x2a, 0xb7, 0x00, 0x5c, 0x1f, 0x09, 0x94, 0x9c, 0x00, 0x0b, 0xbb, 0x00, 0x5f, 0x59, 0xb7, 0x00, 0x61, 0xbf, 0xbb, 0x00,
                        0x62, 0x59, 0x2a, 0x1f, 0xb7, 0x00, 0x64, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 254, descriptor_index: 255, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 242, max_stack: 3, max_locals: 1, code: vec![
                        0xbb, 0x00, 0x67, 0x59, 0x2a, 0xb6, 0x00, 0x69, 0xb7, 0x00, 0x6c, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 256, descriptor_index: 20, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 242, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb7, 0x00, 0x5c, 0x2a, 0xb4, 0x00, 0x0b, 0xb8, 0x00, 0x6f, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 257, descriptor_index: 20, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 242, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb7, 0x00, 0x5c, 0x2a, 0xb4, 0x00, 0x0b, 0xb8, 0x00, 0x72, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 258, descriptor_index: 20, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 242, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb7, 0x00, 0x5c, 0x2a, 0xb4, 0x00, 0x0b, 0xb8, 0x00, 0x75, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 259, descriptor_index: 35, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 242, max_stack: 3, max_locals: 2, code: vec![
                        0x2a, 0xb7, 0x00, 0x5c, 0x2b, 0xc7, 0x00, 0x0b, 0xbb, 0x00, 0x78, 0x59, 0xb7, 0x00, 0x7a, 0xbf, 0x2a, 0x2a, 0xb4, 0x00,
                        0x0b, 0x2b, 0xb8, 0x00, 0x7b, 0xb5, 0x00, 0x0b, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 260, descriptor_index: 261, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 242, max_stack: 4, max_locals: 3, code: vec![
                        0x2a, 0xb7, 0x00, 0x5c, 0x1f, 0x09, 0x94, 0x9c, 0x00, 0x0b, 0xbb, 0x00, 0x5f, 0x59, 0xb7, 0x00, 0x61, 0xbf, 0x2a, 0xb4,
                        0x00, 0x0b, 0x1f, 0xb8, 0x00, 0x7f, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 135, descriptor_index: 161, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 242, max_stack: 3, max_locals: 1, code: vec![
                        0x2a, 0x12, 0x83, 0x03, 0xb6, 0x00, 0x85, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 135, descriptor_index: 136, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 242, max_stack: 5, max_locals: 8, code: vec![
                        0x2a, 0xb7, 0x00, 0x2d, 0x2b, 0xc7, 0x00, 0x0b, 0xbb, 0x00, 0x78, 0x59, 0xb7, 0x00, 0x7a, 0xbf, 0xbb, 0x00, 0x4f, 0x59,
                        0xbb, 0x00, 0x46, 0x59, 0x2a, 0xb4, 0x00, 0x0b, 0xb8, 0x00, 0x89, 0xb7, 0x00, 0x4c, 0xb7, 0x00, 0x55, 0x4e, 0x2d, 0xb6,
                        0x00, 0x8c, 0x36, 0x04, 0xbb, 0x00, 0x90, 0x59, 0xb7, 0x00, 0x92, 0x3a, 0x05, 0x03, 0x36, 0x06, 0x15, 0x06, 0x15, 0x04,
                        0xa2, 0x00, 0x2e, 0x2d, 0xb6, 0x00, 0x93, 0x3a, 0x07, 0x1c, 0x9a, 0x00, 0x0d, 0x19, 0x07, 0x12, 0x3e, 0xb6, 0x00, 0x40,
                        0x9a, 0x00, 0x14, 0x2a, 0x19, 0x07, 0x2b, 0xb7, 0x00, 0x96, 0x99, 0x00, 0x0a, 0x19, 0x05, 0x19, 0x07, 0xb6, 0x00, 0x9a,
                        0x84, 0x06, 0x01, 0xa7, 0xff, 0xd1, 0x19, 0x05, 0xb6, 0x00, 0x9e, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 2, name_index: 152, descriptor_index: 153, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 242, max_stack: 5, max_locals: 3, code: vec![
                        0x2a, 0x2b, 0x03, 0x2c, 0x03, 0xb7, 0x00, 0xa2, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 2, name_index: 164, descriptor_index: 165, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 242, max_stack: 3, max_locals: 10, code: wildcard_code(166, 169), exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 262, descriptor_index: 263, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 242, max_stack: 2, max_locals: 2, code: vec![
                        0x2a, 0xb7, 0x00, 0x2d, 0x2a, 0xb4, 0x00, 0x0b, 0x1b, 0xb8, 0x00, 0xad, 0xad,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 264, descriptor_index: 250, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 242, max_stack: 2, max_locals: 2, code: vec![
                        0x03, 0xb8, 0x00, 0xb1, 0xad, 0x4c, 0x14, 0x00, 0xb5, 0xad,
                    ], exception_table: vec![
                        ExceptionHandler { start_pc: 0, end_pc: 4, handler_pc: 5, catch_type: 56 },
                    ], attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 265, descriptor_index: 250, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 242, max_stack: 2, max_locals: 2, code: vec![
                        0x04, 0xb8, 0x00, 0xb1, 0xad, 0x4c, 0x14, 0x00, 0xb5, 0xad,
                    ], exception_table: vec![
                        ExceptionHandler { start_pc: 0, end_pc: 4, handler_pc: 5, catch_type: 56 },
                    ], attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 266, descriptor_index: 250, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 242, max_stack: 2, max_locals: 2, code: vec![
                        0x05, 0xb8, 0x00, 0xb1, 0xad, 0x4c, 0x14, 0x00, 0xb5, 0xad,
                    ], exception_table: vec![
                        ExceptionHandler { start_pc: 0, end_pc: 4, handler_pc: 5, catch_type: 56 },
                    ], attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 267, descriptor_index: 268, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 242, max_stack: 3, max_locals: 2, code: vec![
                        0x2a, 0xb7, 0x00, 0x5c, 0x1b, 0x2a, 0xb6, 0x00, 0xb7, 0x9f, 0x00, 0x0d, 0xbb, 0x00, 0x38, 0x59, 0x12, 0xbb, 0xb7, 0x00,
                        0xbd, 0xbf, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 269, descriptor_index: 268, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 242, max_stack: 3, max_locals: 2, code: vec![
                        0x2a, 0xb7, 0x00, 0x5c, 0x1b, 0x2a, 0xb6, 0x00, 0xbe, 0x9f, 0x00, 0x0d, 0xbb, 0x00, 0x38, 0x59, 0x12, 0xc1, 0xb7, 0x00,
                        0xbd, 0xbf, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 270, descriptor_index: 268, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 242, max_stack: 3, max_locals: 2, code: vec![
                        0x2a, 0xb7, 0x00, 0x5c, 0x1b, 0x2a, 0xb6, 0x00, 0xc3, 0x9f, 0x00, 0x0d, 0xbb, 0x00, 0x38, 0x59, 0x12, 0xc6, 0xb7, 0x00,
                        0xbd, 0xbf, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 271, descriptor_index: 35, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 242, max_stack: 5, max_locals: 3, code: vec![
                        0x2a, 0xb7, 0x00, 0x2d, 0x2b, 0xc6, 0x00, 0x27, 0x12, 0x3e, 0x2b, 0xb6, 0x00, 0xc8, 0x9a, 0x00, 0x1e, 0x12, 0xcc, 0x2b,
                        0xb6, 0x00, 0xc8, 0x9a, 0x00, 0x15, 0x2b, 0x10, 0x2f, 0xb6, 0x00, 0xce, 0x9c, 0x00, 0x0c, 0x2b, 0x10, 0x5c, 0xb6, 0x00,
                        0xce, 0x9b, 0x00, 0x0b, 0xbb, 0x00, 0x5f, 0x59, 0xb7, 0x00, 0x61, 0xbf, 0x2a, 0xb4, 0x00, 0x0b, 0x12, 0xd2, 0xb6, 0x00,
                        0xd4, 0x99, 0x00, 0x0f, 0x2a, 0xb4, 0x00, 0x0b, 0xb6, 0x00, 0xa6, 0x04, 0x64, 0xa7, 0x00, 0x0c, 0x2a, 0xb4, 0x00, 0x0b,
                        0x10, 0x2f, 0xb6, 0x00, 0xd7, 0x3d, 0x2a, 0x2a, 0xb4, 0x00, 0x0b, 0x03, 0x1c, 0x04, 0x60, 0xb6, 0x00, 0xda, 0x2b, 0xb6,
                        0x00, 0xde, 0xb5, 0x00, 0x0b, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 272, descriptor_index: 61, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 242, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x0b, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 60, descriptor_index: 61, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 242, max_stack: 4, max_locals: 3, code: vec![
                        0x2a, 0xb4, 0x00, 0x0b, 0x12, 0xd2, 0xb6, 0x00, 0xd4, 0x99, 0x00, 0x17, 0x2a, 0xb4, 0x00, 0x0b, 0x03, 0x2a, 0xb4, 0x00,
                        0x0b, 0xb6, 0x00, 0xa6, 0x04, 0x64, 0xb6, 0x00, 0xda, 0xa7, 0x00, 0x07, 0x2a, 0xb4, 0x00, 0x0b, 0x4c, 0x2b, 0x10, 0x2f,
                        0xb6, 0x00, 0xd7, 0x3d, 0x2b, 0x1c, 0x04, 0x60, 0xb6, 0x00, 0xe2, 0x2a, 0xb4, 0x00, 0x0b, 0x12, 0xd2, 0xb6, 0x00, 0xd4,
                        0x99, 0x00, 0x08, 0x12, 0xd2, 0xa7, 0x00, 0x05, 0x12, 0xe5, 0xb6, 0x00, 0xde, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 273, descriptor_index: 61, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 242, max_stack: 4, max_locals: 4, code: vec![
                        0x2a, 0xb4, 0x00, 0x0b, 0x12, 0xe7, 0xb6, 0x00, 0xe9, 0x05, 0x60, 0x3c, 0x2a, 0xb4, 0x00, 0x0b, 0x10, 0x2f, 0x1b, 0xb6,
                        0x00, 0xec, 0x3d, 0x2a, 0xb4, 0x00, 0x0b, 0x10, 0x2f, 0xb6, 0x00, 0xd7, 0x3e, 0x1c, 0x9c, 0x00, 0x08, 0x12, 0xd2, 0xa7,
                        0x00, 0x0e, 0x2a, 0xb4, 0x00, 0x0b, 0x1c, 0x1d, 0x04, 0x60, 0xb6, 0x00, 0xda, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 4104, name_index: 274, descriptor_index: 275, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 242, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x0b, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 4104, name_index: 276, descriptor_index: 10, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 242, max_stack: 3, max_locals: 3, code: vec![
                        0x2a, 0x2b, 0x1c, 0xb8, 0x00, 0x07, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 4104, name_index: 277, descriptor_index: 6, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 242, max_stack: 4, max_locals: 4, code: vec![
                        0x2a, 0x2b, 0x20, 0xb8, 0x00, 0x01, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
            ],
            attributes: Vec::new(),
        },
    );
}
