use super::{
    AxisDirection, GamepadAxis, GamepadButton, HostAction, Key, PhysicalAction, PhysicalControl,
};

#[cfg(test)]
pub(super) const PHONE_ACTIONS: [HostAction; 23] = [
    HostAction::Up,
    HostAction::Down,
    HostAction::Left,
    HostAction::Right,
    HostAction::Fire,
    HostAction::SoftLeft,
    HostAction::SoftRight,
    HostAction::Num1,
    HostAction::Num2,
    HostAction::Num3,
    HostAction::Num4,
    HostAction::Num5,
    HostAction::Num6,
    HostAction::Num7,
    HostAction::Num8,
    HostAction::Num9,
    HostAction::Star,
    HostAction::Num0,
    HostAction::Pound,
    HostAction::Back,
    HostAction::Clear,
    HostAction::GameA,
    HostAction::GameB,
];

pub(super) fn action_label(action: PhysicalAction) -> &'static str {
    match action {
        PhysicalAction::Menu => "App menu / Back",
        PhysicalAction::Fullscreen => "Fullscreen",
        PhysicalAction::FastForward => "Fast-forward",
        PhysicalAction::DebugOverlay => "Debug overlay",
        PhysicalAction::StopGame => "Stop game",
        PhysicalAction::Phone(action) => match action {
            HostAction::Up => "Up",
            HostAction::Down => "Down",
            HostAction::Left => "Left",
            HostAction::Right => "Right",
            HostAction::Fire => "Fire / OK",
            HostAction::SoftLeft => "Left soft key",
            HostAction::SoftRight => "Right soft key",
            HostAction::Back => "Phone Back",
            HostAction::Clear => "Clear",
            HostAction::Num0 => "0",
            HostAction::Num1 => "1",
            HostAction::Num2 => "2",
            HostAction::Num3 => "3",
            HostAction::Num4 => "4",
            HostAction::Num5 => "5",
            HostAction::Num6 => "6",
            HostAction::Num7 => "7",
            HostAction::Num8 => "8",
            HostAction::Num9 => "9",
            HostAction::Star => "*",
            HostAction::Pound => "#",
            HostAction::GameA => "Game A",
            HostAction::GameB => "Game B",
            _ => "Unavailable",
        },
    }
}

pub(super) fn control_label(control: PhysicalControl) -> String {
    match control {
        PhysicalControl::Keyboard { usage } => keyboard_label(usage),
        PhysicalControl::AndroidKey { code: 24 } => "Volume up".to_owned(),
        PhysicalControl::AndroidKey { code: 25 } => "Volume down".to_owned(),
        PhysicalControl::AndroidKey { code } => format!("Hardware key {code}"),
        PhysicalControl::Gamepad { button } => match button {
            GamepadButton::South => "Bottom button (A / Cross)",
            GamepadButton::East => "Right button (B / Circle)",
            GamepadButton::West => "Left button (X / Square)",
            GamepadButton::North => "Top button (Y / Triangle)",
            GamepadButton::DpadUp => "D-pad up",
            GamepadButton::DpadDown => "D-pad down",
            GamepadButton::DpadLeft => "D-pad left",
            GamepadButton::DpadRight => "D-pad right",
            GamepadButton::LeftShoulder => "L1 / LB",
            GamepadButton::RightShoulder => "R1 / RB",
            GamepadButton::LeftTrigger => "L2 / LT button",
            GamepadButton::RightTrigger => "R2 / RT button",
            GamepadButton::LeftStick => "L3 / Left stick click",
            GamepadButton::RightStick => "R3 / Right stick click",
            GamepadButton::Start => "Start / Options",
            GamepadButton::Select => "Select / Create",
            GamepadButton::Extra(number) => return format!("Extra button {number}"),
        }
        .to_owned(),
        PhysicalControl::Axis { axis, direction } => {
            let negative = direction == AxisDirection::Negative;
            let (name, horizontal) = match axis {
                GamepadAxis::LeftX => ("Left stick", true),
                GamepadAxis::LeftY => ("Left stick", false),
                GamepadAxis::RightX => ("Right stick", true),
                GamepadAxis::RightY => ("Right stick", false),
                GamepadAxis::HatX => ("D-pad", true),
                GamepadAxis::HatY => ("D-pad", false),
                GamepadAxis::LeftTrigger => return "L2 / LT axis".to_owned(),
                GamepadAxis::RightTrigger => return "R2 / RT axis".to_owned(),
            };
            let direction = match (horizontal, negative) {
                (true, true) => "left",
                (true, false) => "right",
                (false, true) => "up",
                (false, false) => "down",
            };
            format!("{name} {direction}")
        }
    }
}

fn keyboard_label(usage: u16) -> String {
    format!("Keyboard {}", super::keyboard::key_label(usage))
}

#[allow(clippy::too_many_lines)] // One explicit USB HID mapping table.
pub(crate) fn key_usage(key: Key) -> Option<u16> {
    Some(match key {
        Key::A => 4,
        Key::B => 5,
        Key::C => 6,
        Key::D => 7,
        Key::E => 8,
        Key::F => 9,
        Key::G => 10,
        Key::H => 11,
        Key::I => 12,
        Key::J => 13,
        Key::K => 14,
        Key::L => 15,
        Key::M => 16,
        Key::N => 17,
        Key::O => 18,
        Key::P => 19,
        Key::Q => 20,
        Key::R => 21,
        Key::S => 22,
        Key::T => 23,
        Key::U => 24,
        Key::V => 25,
        Key::W => 26,
        Key::X => 27,
        Key::Y => 28,
        Key::Z => 29,
        Key::Num1 => 30,
        Key::Num2 => 31,
        Key::Num3 => 32,
        Key::Num4 => 33,
        Key::Num5 => 34,
        Key::Num6 => 35,
        Key::Num7 => 36,
        Key::Num8 => 37,
        Key::Num9 => 38,
        Key::Num0 => 39,
        Key::Enter => 40,
        Key::Escape => 41,
        Key::Backspace => 42,
        Key::Tab => 43,
        Key::Space => 44,
        Key::Minus => 45,
        Key::Equals => 46,
        Key::OpenBracket => 47,
        Key::CloseBracket => 48,
        Key::Backslash => 49,
        Key::Semicolon => 51,
        Key::Quote => 52,
        Key::Backtick => 53,
        Key::Comma => 54,
        Key::Period => 55,
        Key::Slash => 56,
        Key::F1 => 58,
        Key::F2 => 59,
        Key::F3 => 60,
        Key::F4 => 61,
        Key::F5 => 62,
        Key::F6 => 63,
        Key::F7 => 64,
        Key::F8 => 65,
        Key::F9 => 66,
        Key::F10 => 67,
        Key::F11 => 68,
        Key::F12 => 69,
        Key::Insert => 73,
        Key::Home => 74,
        Key::PageUp => 75,
        Key::Delete => 76,
        Key::End => 77,
        Key::PageDown => 78,
        Key::ArrowRight => 79,
        Key::ArrowLeft => 80,
        Key::ArrowDown => 81,
        Key::ArrowUp => 82,
        Key::CapsLock => 57,
        Key::PrintScreen => 70,
        Key::ScrollLock => 71,
        Key::Pause => 72,
        Key::NumLock => 83,
        Key::NumpadDivide => 84,
        Key::NumpadMultiply => 85,
        Key::NumpadSubtract => 86,
        Key::NumpadAdd => 87,
        Key::NumpadEnter => 88,
        Key::Numpad1 => 89,
        Key::Numpad2 => 90,
        Key::Numpad3 => 91,
        Key::Numpad4 => 92,
        Key::Numpad5 => 93,
        Key::Numpad6 => 94,
        Key::Numpad7 => 95,
        Key::Numpad8 => 96,
        Key::Numpad9 => 97,
        Key::Numpad0 => 98,
        Key::NumpadDecimal => 99,
        Key::IntlBackslash => 100,
        Key::ContextMenu => 101,
        Key::NumpadEqual => 103,
        Key::ControlLeft => 224,
        Key::ShiftLeft => 225,
        Key::AltLeft => 226,
        Key::SuperLeft => 227,
        Key::ControlRight => 228,
        Key::ShiftRight => 229,
        Key::AltRight => 230,
        Key::SuperRight => 231,
        _ => return None,
    })
}
