//! Record enumeration, filtering and ordering.

use super::super::{
    Attribute, ClassFile, CodeAttribute, Constant, ExceptionHandler, Member,
    append_bootstrap_classes, build_bootstrap_class,
};

mod rebuild;

pub(super) fn append_classes(classes: &mut Vec<ClassFile>) {
    append_bootstrap_classes!(classes;
        // javax/microedition/rms/RecordComparator
        ClassFile {
            minor_version: 0,
            major_version: 48,
            constant_pool: vec![
                None,
                Some(Constant::Class { name_index: 2 }),
                Some(Constant::Utf8("javax/microedition/rms/RecordComparator".to_owned())),
                Some(Constant::Class { name_index: 4 }),
                Some(Constant::Utf8("java/lang/Object".to_owned())),
                Some(Constant::Utf8("PRECEDES".to_owned())),
                Some(Constant::Utf8("I".to_owned())),
                Some(Constant::Utf8("ConstantValue".to_owned())),
                Some(Constant::Integer(-1)),
                Some(Constant::Utf8("EQUIVALENT".to_owned())),
                Some(Constant::Integer(0)),
                Some(Constant::Utf8("FOLLOWS".to_owned())),
                Some(Constant::Integer(1)),
                Some(Constant::Utf8("compare".to_owned())),
                Some(Constant::Utf8("([B[B)I".to_owned())),
                Some(Constant::Utf8("SourceFile".to_owned())),
                Some(Constant::Utf8("generated_bootstrap.rs".to_owned())),
            ],
            access_flags: 1537,
            this_class: 1,
            super_class: 3,
            interfaces: vec![],
            fields: vec![
                Member { access_flags: 25, name_index: 5, descriptor_index: 6, attributes: vec![
                    Attribute::Raw { name_index: 7, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x08,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 9, descriptor_index: 6, attributes: vec![
                    Attribute::Raw { name_index: 7, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x0a,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 11, descriptor_index: 6, attributes: vec![
                    Attribute::Raw { name_index: 7, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x0c,
                    ] },
                ] },
            ],
            methods: vec![
                Member { access_flags: 1025, name_index: 13, descriptor_index: 14, attributes: Vec::new() },
            ],
            attributes: Vec::new(),
        },
        // javax/microedition/rms/RecordEnumeration
        ClassFile {
            minor_version: 0,
            major_version: 48,
            constant_pool: vec![
                None,
                Some(Constant::Class { name_index: 2 }),
                Some(Constant::Utf8("javax/microedition/rms/RecordEnumeration".to_owned())),
                Some(Constant::Class { name_index: 4 }),
                Some(Constant::Utf8("java/lang/Object".to_owned())),
                Some(Constant::Utf8("numRecords".to_owned())),
                Some(Constant::Utf8("()I".to_owned())),
                Some(Constant::Utf8("nextRecord".to_owned())),
                Some(Constant::Utf8("()[B".to_owned())),
                Some(Constant::Utf8("Exceptions".to_owned())),
                Some(Constant::Class { name_index: 11 }),
                Some(Constant::Utf8("javax/microedition/rms/InvalidRecordIDException".to_owned())),
                Some(Constant::Class { name_index: 13 }),
                Some(Constant::Utf8("javax/microedition/rms/RecordStoreNotOpenException".to_owned())),
                Some(Constant::Class { name_index: 15 }),
                Some(Constant::Utf8("javax/microedition/rms/RecordStoreException".to_owned())),
                Some(Constant::Utf8("nextRecordId".to_owned())),
                Some(Constant::Utf8("previousRecord".to_owned())),
                Some(Constant::Utf8("previousRecordId".to_owned())),
                Some(Constant::Utf8("hasNextElement".to_owned())),
                Some(Constant::Utf8("()Z".to_owned())),
                Some(Constant::Utf8("hasPreviousElement".to_owned())),
                Some(Constant::Utf8("reset".to_owned())),
                Some(Constant::Utf8("()V".to_owned())),
                Some(Constant::Utf8("rebuild".to_owned())),
                Some(Constant::Utf8("keepUpdated".to_owned())),
                Some(Constant::Utf8("(Z)V".to_owned())),
                Some(Constant::Utf8("isKeptUpdated".to_owned())),
                Some(Constant::Utf8("destroy".to_owned())),
                Some(Constant::Utf8("SourceFile".to_owned())),
                Some(Constant::Utf8("generated_bootstrap.rs".to_owned())),
            ],
            access_flags: 1537,
            this_class: 1,
            super_class: 3,
            interfaces: vec![],
            fields: Vec::new(),
            methods: vec![
                Member { access_flags: 1025, name_index: 5, descriptor_index: 6, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 7, descriptor_index: 8, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 16, descriptor_index: 6, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 17, descriptor_index: 8, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 18, descriptor_index: 6, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 19, descriptor_index: 20, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 21, descriptor_index: 20, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 22, descriptor_index: 23, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 24, descriptor_index: 23, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 25, descriptor_index: 26, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 27, descriptor_index: 20, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 28, descriptor_index: 23, attributes: Vec::new() },
            ],
            attributes: Vec::new(),
        },
        // javax/microedition/rms/RecordEnumerationImpl
        ClassFile {
            minor_version: 0,
            major_version: 48,
            constant_pool: vec![
                None,
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 3 }),
                Some(Constant::Class { name_index: 4 }),
                Some(Constant::NameAndType { name_index: 5, descriptor_index: 6 }),
                Some(Constant::Utf8("java/lang/Object".to_owned())),
                Some(Constant::Utf8("<init>".to_owned())),
                Some(Constant::Utf8("()V".to_owned())),
                Some(Constant::Fieldref { class_index: 8, name_and_type_index: 9 }),
                Some(Constant::Class { name_index: 10 }),
                Some(Constant::NameAndType { name_index: 11, descriptor_index: 12 }),
                Some(Constant::Utf8("javax/microedition/rms/RecordEnumerationImpl".to_owned())),
                Some(Constant::Utf8("store".to_owned())),
                Some(Constant::Utf8("Ljavax/microedition/rms/RecordStore;".to_owned())),
                Some(Constant::Fieldref { class_index: 8, name_and_type_index: 14 }),
                Some(Constant::NameAndType { name_index: 15, descriptor_index: 16 }),
                Some(Constant::Utf8("filter".to_owned())),
                Some(Constant::Utf8("Ljavax/microedition/rms/RecordFilter;".to_owned())),
                Some(Constant::Fieldref { class_index: 8, name_and_type_index: 18 }),
                Some(Constant::NameAndType { name_index: 19, descriptor_index: 20 }),
                Some(Constant::Utf8("comparator".to_owned())),
                Some(Constant::Utf8("Ljavax/microedition/rms/RecordComparator;".to_owned())),
                Some(Constant::Fieldref { class_index: 8, name_and_type_index: 22 }),
                Some(Constant::NameAndType { name_index: 23, descriptor_index: 24 }),
                Some(Constant::Utf8("keptUpdated".to_owned())),
                Some(Constant::Utf8("Z".to_owned())),
                Some(Constant::Methodref { class_index: 8, name_and_type_index: 26 }),
                Some(Constant::NameAndType { name_index: 27, descriptor_index: 6 }),
                Some(Constant::Utf8("rebuildInternal".to_owned())),
                Some(Constant::Methodref { class_index: 8, name_and_type_index: 29 }),
                Some(Constant::NameAndType { name_index: 30, descriptor_index: 6 }),
                Some(Constant::Utf8("checkAlive".to_owned())),
                Some(Constant::Methodref { class_index: 32, name_and_type_index: 33 }),
                Some(Constant::Class { name_index: 34 }),
                Some(Constant::NameAndType { name_index: 35, descriptor_index: 36 }),
                Some(Constant::Utf8("javax/microedition/rms/RecordStore".to_owned())),
                Some(Constant::Utf8("isOpen".to_owned())),
                Some(Constant::Utf8("()Z".to_owned())),
                Some(Constant::Methodref { class_index: 8, name_and_type_index: 38 }),
                Some(Constant::NameAndType { name_index: 39, descriptor_index: 6 }),
                Some(Constant::Utf8("update".to_owned())),
                Some(Constant::Fieldref { class_index: 8, name_and_type_index: 41 }),
                Some(Constant::NameAndType { name_index: 42, descriptor_index: 43 }),
                Some(Constant::Utf8("ids".to_owned())),
                Some(Constant::Utf8("[I".to_owned())),
                Some(Constant::Methodref { class_index: 8, name_and_type_index: 45 }),
                Some(Constant::NameAndType { name_index: 46, descriptor_index: 47 }),
                Some(Constant::Utf8("nextRecordId".to_owned())),
                Some(Constant::Utf8("()I".to_owned())),
                Some(Constant::Methodref { class_index: 32, name_and_type_index: 49 }),
                Some(Constant::NameAndType { name_index: 50, descriptor_index: 51 }),
                Some(Constant::Utf8("getRecord".to_owned())),
                Some(Constant::Utf8("(I)[B".to_owned())),
                Some(Constant::Class { name_index: 53 }),
                Some(Constant::Utf8("javax/microedition/rms/InvalidRecordIDException".to_owned())),
                Some(Constant::Methodref { class_index: 52, name_and_type_index: 3 }),
                Some(Constant::Fieldref { class_index: 8, name_and_type_index: 56 }),
                Some(Constant::NameAndType { name_index: 57, descriptor_index: 24 }),
                Some(Constant::Utf8("initial".to_owned())),
                Some(Constant::Fieldref { class_index: 8, name_and_type_index: 59 }),
                Some(Constant::NameAndType { name_index: 60, descriptor_index: 61 }),
                Some(Constant::Utf8("cursor".to_owned())),
                Some(Constant::Utf8("I".to_owned())),
                Some(Constant::Methodref { class_index: 8, name_and_type_index: 63 }),
                Some(Constant::NameAndType { name_index: 64, descriptor_index: 47 }),
                Some(Constant::Utf8("previousRecordId".to_owned())),
                Some(Constant::Methodref { class_index: 8, name_and_type_index: 66 }),
                Some(Constant::NameAndType { name_index: 67, descriptor_index: 6 }),
                Some(Constant::Utf8("rebuildUnchecked".to_owned())),
                Some(Constant::Fieldref { class_index: 8, name_and_type_index: 69 }),
                Some(Constant::NameAndType { name_index: 70, descriptor_index: 24 }),
                Some(Constant::Utf8("destroyed".to_owned())),
                Some(Constant::Methodref { class_index: 32, name_and_type_index: 72 }),
                Some(Constant::NameAndType { name_index: 73, descriptor_index: 47 }),
                Some(Constant::Utf8("getVersion".to_owned())),
                Some(Constant::Fieldref { class_index: 8, name_and_type_index: 75 }),
                Some(Constant::NameAndType { name_index: 76, descriptor_index: 61 }),
                Some(Constant::Utf8("version".to_owned())),
                Some(Constant::Class { name_index: 78 }),
                Some(Constant::Utf8("javax/microedition/rms/RecordStoreException".to_owned())),
                Some(Constant::Class { name_index: 80 }),
                Some(Constant::Utf8("java/lang/IllegalStateException".to_owned())),
                Some(Constant::Methodref { class_index: 79, name_and_type_index: 3 }),
                Some(Constant::Methodref { class_index: 32, name_and_type_index: 83 }),
                Some(Constant::NameAndType { name_index: 84, descriptor_index: 6 }),
                Some(Constant::Utf8("ensureOpen".to_owned())),
                Some(Constant::Methodref { class_index: 32, name_and_type_index: 86 }),
                Some(Constant::NameAndType { name_index: 87, descriptor_index: 88 }),
                Some(Constant::Utf8("recordIds".to_owned())),
                Some(Constant::Utf8("()[I".to_owned())),
                Some(Constant::InterfaceMethodref { class_index: 90, name_and_type_index: 91 }),
                Some(Constant::Class { name_index: 92 }),
                Some(Constant::NameAndType { name_index: 93, descriptor_index: 94 }),
                Some(Constant::Utf8("javax/microedition/rms/RecordFilter".to_owned())),
                Some(Constant::Utf8("matches".to_owned())),
                Some(Constant::Utf8("([B)Z".to_owned())),
                Some(Constant::InterfaceMethodref { class_index: 96, name_and_type_index: 97 }),
                Some(Constant::Class { name_index: 98 }),
                Some(Constant::NameAndType { name_index: 99, descriptor_index: 100 }),
                Some(Constant::Utf8("javax/microedition/rms/RecordComparator".to_owned())),
                Some(Constant::Utf8("compare".to_owned())),
                Some(Constant::Utf8("([B[B)I".to_owned())),
                Some(Constant::Class { name_index: 102 }),
                Some(Constant::Utf8("javax/microedition/rms/RecordEnumeration".to_owned())),
                Some(Constant::Utf8("(Ljavax/microedition/rms/RecordStore;Ljavax/microedition/rms/RecordFilter;Ljavax/microedition/rms/RecordComparator;Z)V".to_owned())),
                Some(Constant::Utf8("Code".to_owned())),
                Some(Constant::Utf8("LineNumberTable".to_owned())),
                Some(Constant::Utf8("Exceptions".to_owned())),
                Some(Constant::Utf8("numRecords".to_owned())),
                Some(Constant::Utf8("StackMapTable".to_owned())),
                Some(Constant::Utf8("nextRecord".to_owned())),
                Some(Constant::Utf8("()[B".to_owned())),
                Some(Constant::Class { name_index: 112 }),
                Some(Constant::Utf8("javax/microedition/rms/RecordStoreNotOpenException".to_owned())),
                Some(Constant::Utf8("previousRecord".to_owned())),
                Some(Constant::Utf8("hasNextElement".to_owned())),
                Some(Constant::Utf8("hasPreviousElement".to_owned())),
                Some(Constant::Utf8("reset".to_owned())),
                Some(Constant::Utf8("rebuild".to_owned())),
                Some(Constant::Utf8("keepUpdated".to_owned())),
                Some(Constant::Utf8("(Z)V".to_owned())),
                Some(Constant::Utf8("isKeptUpdated".to_owned())),
                Some(Constant::Utf8("destroy".to_owned())),
                Some(Constant::Class { name_index: 43 }),
                Some(Constant::Class { name_index: 124 }),
                Some(Constant::Utf8("[B".to_owned())),
                Some(Constant::Utf8("SourceFile".to_owned())),
                Some(Constant::Utf8("generated_bootstrap.rs".to_owned())),
            ],
            access_flags: 48,
            this_class: 8,
            super_class: 2,
            interfaces: vec![101],
            fields: vec![
                Member { access_flags: 2, name_index: 11, descriptor_index: 12, attributes: Vec::new() },
                Member { access_flags: 2, name_index: 15, descriptor_index: 16, attributes: Vec::new() },
                Member { access_flags: 2, name_index: 19, descriptor_index: 20, attributes: Vec::new() },
                Member { access_flags: 2, name_index: 23, descriptor_index: 24, attributes: Vec::new() },
                Member { access_flags: 2, name_index: 70, descriptor_index: 24, attributes: Vec::new() },
                Member { access_flags: 2, name_index: 42, descriptor_index: 43, attributes: Vec::new() },
                Member { access_flags: 2, name_index: 60, descriptor_index: 61, attributes: Vec::new() },
                Member { access_flags: 2, name_index: 57, descriptor_index: 24, attributes: Vec::new() },
                Member { access_flags: 2, name_index: 76, descriptor_index: 61, attributes: Vec::new() },
            ],
            methods: vec![
                Member { access_flags: 0, name_index: 5, descriptor_index: 103, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 104, max_stack: 2, max_locals: 5, code: vec![
                        0x2a, 0xb7, 0x00, 0x01, 0x2a, 0x2b, 0xb5, 0x00, 0x07, 0x2a, 0x2c, 0xb5, 0x00, 0x0d, 0x2a, 0x2d, 0xb5, 0x00, 0x11, 0x2a,
                        0x15, 0x04, 0xb5, 0x00, 0x15, 0x2a, 0xb7, 0x00, 0x19, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 107, descriptor_index: 47, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 104, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb7, 0x00, 0x1c, 0x2a, 0xb4, 0x00, 0x07, 0xb6, 0x00, 0x1f, 0x9a, 0x00, 0x05, 0x03, 0xac, 0x2a, 0xb7, 0x00, 0x25,
                        0x2a, 0xb4, 0x00, 0x28, 0xbe, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 109, descriptor_index: 110, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 104, max_stack: 2, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x07, 0x2a, 0xb6, 0x00, 0x2c, 0xb6, 0x00, 0x30, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 46, descriptor_index: 47, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 104, max_stack: 5, max_locals: 1, code: vec![
                        0x2a, 0xb7, 0x00, 0x1c, 0x2a, 0xb4, 0x00, 0x07, 0xb6, 0x00, 0x1f, 0x9a, 0x00, 0x0b, 0xbb, 0x00, 0x34, 0x59, 0xb7, 0x00,
                        0x36, 0xbf, 0x2a, 0xb7, 0x00, 0x25, 0x2a, 0xb4, 0x00, 0x37, 0x99, 0x00, 0x0d, 0x2a, 0x03, 0xb5, 0x00, 0x3a, 0x2a, 0x03,
                        0xb5, 0x00, 0x37, 0x2a, 0xb4, 0x00, 0x3a, 0x9b, 0x00, 0x0f, 0x2a, 0xb4, 0x00, 0x3a, 0x2a, 0xb4, 0x00, 0x28, 0xbe, 0xa1,
                        0x00, 0x14, 0x2a, 0x2a, 0xb4, 0x00, 0x28, 0xbe, 0xb5, 0x00, 0x3a, 0xbb, 0x00, 0x34, 0x59, 0xb7, 0x00, 0x36, 0xbf, 0x2a,
                        0xb4, 0x00, 0x28, 0x2a, 0x59, 0xb4, 0x00, 0x3a, 0x5a, 0x04, 0x60, 0xb5, 0x00, 0x3a, 0x2e, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 113, descriptor_index: 110, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 104, max_stack: 2, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x07, 0x2a, 0xb6, 0x00, 0x3e, 0xb6, 0x00, 0x30, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 64, descriptor_index: 47, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 104, max_stack: 4, max_locals: 1, code: vec![
                        0x2a, 0xb7, 0x00, 0x1c, 0x2a, 0xb4, 0x00, 0x07, 0xb6, 0x00, 0x1f, 0x9a, 0x00, 0x0b, 0xbb, 0x00, 0x34, 0x59, 0xb7, 0x00,
                        0x36, 0xbf, 0x2a, 0xb7, 0x00, 0x25, 0x2a, 0xb4, 0x00, 0x37, 0x99, 0x00, 0x11, 0x2a, 0x2a, 0xb4, 0x00, 0x28, 0xbe, 0xb5,
                        0x00, 0x3a, 0x2a, 0x03, 0xb5, 0x00, 0x37, 0x2a, 0xb4, 0x00, 0x3a, 0x9e, 0x00, 0x0f, 0x2a, 0xb4, 0x00, 0x3a, 0x2a, 0xb4,
                        0x00, 0x28, 0xbe, 0xa4, 0x00, 0x10, 0x2a, 0x02, 0xb5, 0x00, 0x3a, 0xbb, 0x00, 0x34, 0x59, 0xb7, 0x00, 0x36, 0xbf, 0x2a,
                        0xb4, 0x00, 0x28, 0x2a, 0x59, 0xb4, 0x00, 0x3a, 0x04, 0x64, 0x5a, 0xb5, 0x00, 0x3a, 0x2e, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 114, descriptor_index: 36, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 104, max_stack: 2, max_locals: 1, code: vec![
                        0x2a, 0xb7, 0x00, 0x1c, 0x2a, 0xb4, 0x00, 0x07, 0xb6, 0x00, 0x1f, 0x9a, 0x00, 0x05, 0x03, 0xac, 0x2a, 0xb7, 0x00, 0x25,
                        0x2a, 0xb4, 0x00, 0x37, 0x99, 0x00, 0x13, 0x2a, 0xb4, 0x00, 0x28, 0xbe, 0x99, 0x00, 0x07, 0x04, 0xa7, 0x00, 0x1f, 0x03,
                        0xa7, 0x00, 0x1b, 0x2a, 0xb4, 0x00, 0x3a, 0x9b, 0x00, 0x13, 0x2a, 0xb4, 0x00, 0x3a, 0x2a, 0xb4, 0x00, 0x28, 0xbe, 0xa2,
                        0x00, 0x07, 0x04, 0xa7, 0x00, 0x04, 0x03, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 115, descriptor_index: 36, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 104, max_stack: 2, max_locals: 1, code: vec![
                        0x2a, 0xb7, 0x00, 0x1c, 0x2a, 0xb4, 0x00, 0x07, 0xb6, 0x00, 0x1f, 0x9a, 0x00, 0x05, 0x03, 0xac, 0x2a, 0xb7, 0x00, 0x25,
                        0x2a, 0xb4, 0x00, 0x37, 0x99, 0x00, 0x13, 0x2a, 0xb4, 0x00, 0x28, 0xbe, 0x99, 0x00, 0x07, 0x04, 0xa7, 0x00, 0x1f, 0x03,
                        0xa7, 0x00, 0x1b, 0x2a, 0xb4, 0x00, 0x3a, 0x9e, 0x00, 0x13, 0x2a, 0xb4, 0x00, 0x3a, 0x2a, 0xb4, 0x00, 0x28, 0xbe, 0xa3,
                        0x00, 0x07, 0x04, 0xa7, 0x00, 0x04, 0x03, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 116, descriptor_index: 6, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 104, max_stack: 2, max_locals: 1, code: vec![
                        0x2a, 0xb7, 0x00, 0x1c, 0x2a, 0x03, 0xb5, 0x00, 0x3a, 0x2a, 0x04, 0xb5, 0x00, 0x37, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 117, descriptor_index: 6, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 104, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb7, 0x00, 0x1c, 0x2a, 0xb4, 0x00, 0x07, 0xb6, 0x00, 0x1f, 0x9a, 0x00, 0x04, 0xb1, 0x2a, 0xb7, 0x00, 0x41, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 118, descriptor_index: 119, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 104, max_stack: 2, max_locals: 2, code: vec![
                        0x2a, 0xb7, 0x00, 0x1c, 0x2a, 0x1b, 0xb5, 0x00, 0x15, 0x1b, 0x99, 0x00, 0x11, 0x2a, 0xb4, 0x00, 0x07, 0xb6, 0x00, 0x1f,
                        0x99, 0x00, 0x07, 0x2a, 0xb7, 0x00, 0x41, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 120, descriptor_index: 36, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 104, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb7, 0x00, 0x1c, 0x2a, 0xb4, 0x00, 0x15, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 121, descriptor_index: 6, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 104, max_stack: 2, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x44, 0x99, 0x00, 0x04, 0xb1, 0x2a, 0x04, 0xb5, 0x00, 0x44, 0x2a, 0x01, 0xb5, 0x00, 0x28, 0x2a, 0x01,
                        0xb5, 0x00, 0x0d, 0x2a, 0x01, 0xb5, 0x00, 0x11, 0x2a, 0x01, 0xb5, 0x00, 0x07, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 2, name_index: 39, descriptor_index: 6, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 104, max_stack: 2, max_locals: 2, code: vec![
                        0x2a, 0xb4, 0x00, 0x15, 0x99, 0x00, 0x2b, 0x2a, 0xb4, 0x00, 0x07, 0xb6, 0x00, 0x1f, 0x99, 0x00, 0x21, 0x2a, 0xb4, 0x00,
                        0x07, 0xb6, 0x00, 0x47, 0x2a, 0xb4, 0x00, 0x4a, 0x9f, 0x00, 0x07, 0x2a, 0xb7, 0x00, 0x19, 0xa7, 0x00, 0x0c, 0x4c, 0xbb,
                        0x00, 0x4f, 0x59, 0xb7, 0x00, 0x51, 0xbf, 0xb1,
                    ], exception_table: vec![
                        ExceptionHandler { start_pc: 17, end_pc: 35, handler_pc: 38, catch_type: 77 },
                    ], attributes: Vec::new() }),
                ] },
                Member { access_flags: 2, name_index: 67, descriptor_index: 6, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 104, max_stack: 2, max_locals: 2, code: vec![
                        0x2a, 0xb7, 0x00, 0x19, 0xa7, 0x00, 0x0c, 0x4c, 0xbb, 0x00, 0x4f, 0x59, 0xb7, 0x00, 0x51, 0xbf, 0xb1,
                    ], exception_table: vec![
                        ExceptionHandler { start_pc: 0, end_pc: 4, handler_pc: 7, catch_type: 77 },
                    ], attributes: Vec::new() }),
                ] },
                Member { access_flags: 2, name_index: 27, descriptor_index: 6, attributes: vec![
                    Attribute::Code(rebuild::rebuild()),
                ] },
                Member { access_flags: 2, name_index: 30, descriptor_index: 6, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 104, max_stack: 2, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x44, 0x99, 0x00, 0x0b, 0xbb, 0x00, 0x4f, 0x59, 0xb7, 0x00, 0x51, 0xbf, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
            ],
            attributes: Vec::new(),
        },
        // javax/microedition/rms/RecordFilter
        ClassFile {
            minor_version: 0,
            major_version: 48,
            constant_pool: vec![
                None,
                Some(Constant::Class { name_index: 2 }),
                Some(Constant::Utf8("javax/microedition/rms/RecordFilter".to_owned())),
                Some(Constant::Class { name_index: 4 }),
                Some(Constant::Utf8("java/lang/Object".to_owned())),
                Some(Constant::Utf8("matches".to_owned())),
                Some(Constant::Utf8("([B)Z".to_owned())),
                Some(Constant::Utf8("SourceFile".to_owned())),
                Some(Constant::Utf8("generated_bootstrap.rs".to_owned())),
            ],
            access_flags: 1537,
            this_class: 1,
            super_class: 3,
            interfaces: vec![],
            fields: Vec::new(),
            methods: vec![
                Member { access_flags: 1025, name_index: 5, descriptor_index: 6, attributes: Vec::new() },
            ],
            attributes: Vec::new(),
        },
    );
}
