//! Record-store access and listener notifications.

use super::super::{
    Attribute, ClassFile, CodeAttribute, Constant, ExceptionHandler, Member,
    append_bootstrap_classes, build_bootstrap_class,
};

pub(super) fn append_classes(classes: &mut Vec<ClassFile>) {
    append_bootstrap_classes!(classes;
        // javax/microedition/rms/RecordListener
        ClassFile {
            minor_version: 0,
            major_version: 48,
            constant_pool: vec![
                None,
                Some(Constant::Class { name_index: 2 }),
                Some(Constant::Utf8("javax/microedition/rms/RecordListener".to_owned())),
                Some(Constant::Class { name_index: 4 }),
                Some(Constant::Utf8("java/lang/Object".to_owned())),
                Some(Constant::Utf8("recordAdded".to_owned())),
                Some(Constant::Utf8("(Ljavax/microedition/rms/RecordStore;I)V".to_owned())),
                Some(Constant::Utf8("recordChanged".to_owned())),
                Some(Constant::Utf8("recordDeleted".to_owned())),
                Some(Constant::Utf8("SourceFile".to_owned())),
                Some(Constant::Utf8("generated_bootstrap.rs".to_owned())),
            ],
            access_flags: 1537,
            this_class: 1,
            super_class: 3,
            interfaces: vec![],
            fields: Vec::new(),
            methods: vec![
                Member { access_flags: 1025, name_index: 5, descriptor_index: 6, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 7, descriptor_index: 6, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 8, descriptor_index: 6, attributes: Vec::new() },
            ],
            attributes: Vec::new(),
        },
        // javax/microedition/rms/RecordStore
        ClassFile {
            minor_version: 0,
            major_version: 48,
            constant_pool: vec![
                None,
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 3 }),
                Some(Constant::Class { name_index: 4 }),
                Some(Constant::NameAndType { name_index: 5, descriptor_index: 6 }),
                Some(Constant::Utf8("java/lang/Object".to_owned())),
                Some(Constant::Utf8("<init>".to_owned())),
                Some(Constant::Utf8("()V".to_owned())),
                Some(Constant::Fieldref { class_index: 8, name_and_type_index: 9 }),
                Some(Constant::Class { name_index: 10 }),
                Some(Constant::NameAndType { name_index: 11, descriptor_index: 12 }),
                Some(Constant::Utf8("javax/microedition/rms/RecordStore".to_owned())),
                Some(Constant::Utf8("openCount".to_owned())),
                Some(Constant::Utf8("I".to_owned())),
                Some(Constant::Class { name_index: 14 }),
                Some(Constant::Utf8("java/util/Vector".to_owned())),
                Some(Constant::Methodref { class_index: 13, name_and_type_index: 3 }),
                Some(Constant::Fieldref { class_index: 8, name_and_type_index: 17 }),
                Some(Constant::NameAndType { name_index: 18, descriptor_index: 19 }),
                Some(Constant::Utf8("listeners".to_owned())),
                Some(Constant::Utf8("Ljava/util/Vector;".to_owned())),
                Some(Constant::Fieldref { class_index: 8, name_and_type_index: 21 }),
                Some(Constant::NameAndType { name_index: 22, descriptor_index: 23 }),
                Some(Constant::Utf8("name".to_owned())),
                Some(Constant::Utf8("Ljava/lang/String;".to_owned())),
                Some(Constant::Fieldref { class_index: 8, name_and_type_index: 25 }),
                Some(Constant::NameAndType { name_index: 26, descriptor_index: 27 }),
                Some(Constant::Utf8("handle".to_owned())),
                Some(Constant::Utf8("J".to_owned())),
                Some(Constant::Methodref { class_index: 8, name_and_type_index: 29 }),
                Some(Constant::NameAndType { name_index: 30, descriptor_index: 31 }),
                Some(Constant::Utf8("validateName".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;)V".to_owned())),
                Some(Constant::Methodref { class_index: 8, name_and_type_index: 33 }),
                Some(Constant::NameAndType { name_index: 34, descriptor_index: 31 }),
                Some(Constant::Utf8("deleteStore0".to_owned())),
                Some(Constant::Methodref { class_index: 8, name_and_type_index: 36 }),
                Some(Constant::NameAndType { name_index: 37, descriptor_index: 38 }),
                Some(Constant::Utf8("open0".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;Z)J".to_owned())),
                Some(Constant::Methodref { class_index: 8, name_and_type_index: 40 }),
                Some(Constant::NameAndType { name_index: 41, descriptor_index: 42 }),
                Some(Constant::Utf8("finishOpen".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;J)Ljavax/microedition/rms/RecordStore;".to_owned())),
                Some(Constant::Methodref { class_index: 8, name_and_type_index: 44 }),
                Some(Constant::NameAndType { name_index: 45, descriptor_index: 46 }),
                Some(Constant::Utf8("validateMode".to_owned())),
                Some(Constant::Utf8("(I)V".to_owned())),
                Some(Constant::Class { name_index: 48 }),
                Some(Constant::Utf8("java/lang/SecurityException".to_owned())),
                Some(Constant::String { string_index: 50 }),
                Some(Constant::Utf8("cross-suite RMS sharing is disabled".to_owned())),
                Some(Constant::Methodref { class_index: 47, name_and_type_index: 52 }),
                Some(Constant::NameAndType { name_index: 5, descriptor_index: 31 }),
                Some(Constant::Class { name_index: 54 }),
                Some(Constant::Utf8("java/lang/NullPointerException".to_owned())),
                Some(Constant::Methodref { class_index: 53, name_and_type_index: 3 }),
                Some(Constant::Methodref { class_index: 8, name_and_type_index: 57 }),
                Some(Constant::NameAndType { name_index: 58, descriptor_index: 59 }),
                Some(Constant::Utf8("openOwned0".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)J".to_owned())),
                Some(Constant::Fieldref { class_index: 8, name_and_type_index: 61 }),
                Some(Constant::NameAndType { name_index: 62, descriptor_index: 63 }),
                Some(Constant::Utf8("openStores".to_owned())),
                Some(Constant::Utf8("Ljava/util/Hashtable;".to_owned())),
                Some(Constant::Methodref { class_index: 65, name_and_type_index: 66 }),
                Some(Constant::Class { name_index: 67 }),
                Some(Constant::NameAndType { name_index: 68, descriptor_index: 69 }),
                Some(Constant::Utf8("java/util/Hashtable".to_owned())),
                Some(Constant::Utf8("get".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/Object;)Ljava/lang/Object;".to_owned())),
                Some(Constant::Methodref { class_index: 8, name_and_type_index: 71 }),
                Some(Constant::NameAndType { name_index: 5, descriptor_index: 72 }),
                Some(Constant::Utf8("(Ljava/lang/String;J)V".to_owned())),
                Some(Constant::Methodref { class_index: 65, name_and_type_index: 74 }),
                Some(Constant::NameAndType { name_index: 75, descriptor_index: 76 }),
                Some(Constant::Utf8("put".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;".to_owned())),
                Some(Constant::Methodref { class_index: 8, name_and_type_index: 78 }),
                Some(Constant::NameAndType { name_index: 79, descriptor_index: 6 }),
                Some(Constant::Utf8("ensureOpen".to_owned())),
                Some(Constant::Methodref { class_index: 8, name_and_type_index: 81 }),
                Some(Constant::NameAndType { name_index: 82, descriptor_index: 83 }),
                Some(Constant::Utf8("close0".to_owned())),
                Some(Constant::Utf8("(J)V".to_owned())),
                Some(Constant::Methodref { class_index: 65, name_and_type_index: 85 }),
                Some(Constant::NameAndType { name_index: 86, descriptor_index: 69 }),
                Some(Constant::Utf8("remove".to_owned())),
                Some(Constant::Methodref { class_index: 13, name_and_type_index: 88 }),
                Some(Constant::NameAndType { name_index: 89, descriptor_index: 6 }),
                Some(Constant::Utf8("removeAllElements".to_owned())),
                Some(Constant::Methodref { class_index: 8, name_and_type_index: 91 }),
                Some(Constant::NameAndType { name_index: 92, descriptor_index: 93 }),
                Some(Constant::Utf8("list0".to_owned())),
                Some(Constant::Utf8("()Ljava/lang/String;".to_owned())),
                Some(Constant::Methodref { class_index: 95, name_and_type_index: 96 }),
                Some(Constant::Class { name_index: 97 }),
                Some(Constant::NameAndType { name_index: 98, descriptor_index: 99 }),
                Some(Constant::Utf8("java/lang/String".to_owned())),
                Some(Constant::Utf8("charAt".to_owned())),
                Some(Constant::Utf8("(I)C".to_owned())),
                Some(Constant::Methodref { class_index: 95, name_and_type_index: 101 }),
                Some(Constant::NameAndType { name_index: 102, descriptor_index: 103 }),
                Some(Constant::Utf8("substring".to_owned())),
                Some(Constant::Utf8("(II)Ljava/lang/String;".to_owned())),
                Some(Constant::Methodref { class_index: 8, name_and_type_index: 105 }),
                Some(Constant::NameAndType { name_index: 106, descriptor_index: 107 }),
                Some(Constant::Utf8("metadataInt0".to_owned())),
                Some(Constant::Utf8("(JI)I".to_owned())),
                Some(Constant::Methodref { class_index: 8, name_and_type_index: 109 }),
                Some(Constant::NameAndType { name_index: 110, descriptor_index: 111 }),
                Some(Constant::Utf8("lastModified0".to_owned())),
                Some(Constant::Utf8("(J)J".to_owned())),
                Some(Constant::Methodref { class_index: 8, name_and_type_index: 113 }),
                Some(Constant::NameAndType { name_index: 114, descriptor_index: 115 }),
                Some(Constant::Utf8("slice".to_owned())),
                Some(Constant::Utf8("([BII)[B".to_owned())),
                Some(Constant::Methodref { class_index: 8, name_and_type_index: 117 }),
                Some(Constant::NameAndType { name_index: 118, descriptor_index: 119 }),
                Some(Constant::Utf8("add0".to_owned())),
                Some(Constant::Utf8("(J[B)I".to_owned())),
                Some(Constant::Methodref { class_index: 8, name_and_type_index: 121 }),
                Some(Constant::NameAndType { name_index: 122, descriptor_index: 123 }),
                Some(Constant::Utf8("notifyListeners".to_owned())),
                Some(Constant::Utf8("(II)V".to_owned())),
                Some(Constant::Methodref { class_index: 8, name_and_type_index: 125 }),
                Some(Constant::NameAndType { name_index: 126, descriptor_index: 127 }),
                Some(Constant::Utf8("delete0".to_owned())),
                Some(Constant::Utf8("(JI)V".to_owned())),
                Some(Constant::Methodref { class_index: 8, name_and_type_index: 129 }),
                Some(Constant::NameAndType { name_index: 130, descriptor_index: 131 }),
                Some(Constant::Utf8("getRecord".to_owned())),
                Some(Constant::Utf8("(I)[B".to_owned())),
                Some(Constant::Methodref { class_index: 8, name_and_type_index: 133 }),
                Some(Constant::NameAndType { name_index: 134, descriptor_index: 135 }),
                Some(Constant::Utf8("get0".to_owned())),
                Some(Constant::Utf8("(JI)[B".to_owned())),
                Some(Constant::Class { name_index: 137 }),
                Some(Constant::Utf8("java/lang/ArrayIndexOutOfBoundsException".to_owned())),
                Some(Constant::Methodref { class_index: 136, name_and_type_index: 3 }),
                Some(Constant::Methodref { class_index: 140, name_and_type_index: 141 }),
                Some(Constant::Class { name_index: 142 }),
                Some(Constant::NameAndType { name_index: 143, descriptor_index: 144 }),
                Some(Constant::Utf8("java/lang/System".to_owned())),
                Some(Constant::Utf8("arraycopy".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/Object;ILjava/lang/Object;II)V".to_owned())),
                Some(Constant::Methodref { class_index: 8, name_and_type_index: 146 }),
                Some(Constant::NameAndType { name_index: 147, descriptor_index: 148 }),
                Some(Constant::Utf8("set0".to_owned())),
                Some(Constant::Utf8("(JI[B)V".to_owned())),
                Some(Constant::Methodref { class_index: 13, name_and_type_index: 150 }),
                Some(Constant::NameAndType { name_index: 151, descriptor_index: 152 }),
                Some(Constant::Utf8("contains".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/Object;)Z".to_owned())),
                Some(Constant::Methodref { class_index: 13, name_and_type_index: 154 }),
                Some(Constant::NameAndType { name_index: 155, descriptor_index: 156 }),
                Some(Constant::Utf8("addElement".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/Object;)V".to_owned())),
                Some(Constant::Methodref { class_index: 13, name_and_type_index: 158 }),
                Some(Constant::NameAndType { name_index: 159, descriptor_index: 152 }),
                Some(Constant::Utf8("removeElement".to_owned())),
                Some(Constant::Class { name_index: 161 }),
                Some(Constant::Utf8("javax/microedition/rms/RecordEnumerationImpl".to_owned())),
                Some(Constant::Methodref { class_index: 160, name_and_type_index: 163 }),
                Some(Constant::NameAndType { name_index: 5, descriptor_index: 164 }),
                Some(Constant::Utf8("(Ljavax/microedition/rms/RecordStore;Ljavax/microedition/rms/RecordFilter;Ljavax/microedition/rms/RecordComparator;Z)V".to_owned())),
                Some(Constant::Class { name_index: 166 }),
                Some(Constant::Utf8("javax/microedition/rms/RecordStoreNotOpenException".to_owned())),
                Some(Constant::Class { name_index: 168 }),
                Some(Constant::Utf8("javax/microedition/rms/RecordStoreException".to_owned())),
                Some(Constant::Class { name_index: 170 }),
                Some(Constant::Utf8("java/lang/IllegalStateException".to_owned())),
                Some(Constant::Methodref { class_index: 169, name_and_type_index: 3 }),
                Some(Constant::Methodref { class_index: 8, name_and_type_index: 173 }),
                Some(Constant::NameAndType { name_index: 174, descriptor_index: 175 }),
                Some(Constant::Utf8("ids0".to_owned())),
                Some(Constant::Utf8("(J)[I".to_owned())),
                Some(Constant::Methodref { class_index: 165, name_and_type_index: 3 }),
                Some(Constant::Methodref { class_index: 13, name_and_type_index: 178 }),
                Some(Constant::NameAndType { name_index: 179, descriptor_index: 180 }),
                Some(Constant::Utf8("size".to_owned())),
                Some(Constant::Utf8("()I".to_owned())),
                Some(Constant::Methodref { class_index: 13, name_and_type_index: 182 }),
                Some(Constant::NameAndType { name_index: 183, descriptor_index: 184 }),
                Some(Constant::Utf8("copyInto".to_owned())),
                Some(Constant::Utf8("([Ljava/lang/Object;)V".to_owned())),
                Some(Constant::Class { name_index: 186 }),
                Some(Constant::Utf8("javax/microedition/rms/RecordListener".to_owned())),
                Some(Constant::InterfaceMethodref { class_index: 185, name_and_type_index: 188 }),
                Some(Constant::NameAndType { name_index: 189, descriptor_index: 190 }),
                Some(Constant::Utf8("recordAdded".to_owned())),
                Some(Constant::Utf8("(Ljavax/microedition/rms/RecordStore;I)V".to_owned())),
                Some(Constant::InterfaceMethodref { class_index: 185, name_and_type_index: 192 }),
                Some(Constant::NameAndType { name_index: 193, descriptor_index: 190 }),
                Some(Constant::Utf8("recordChanged".to_owned())),
                Some(Constant::InterfaceMethodref { class_index: 185, name_and_type_index: 195 }),
                Some(Constant::NameAndType { name_index: 196, descriptor_index: 190 }),
                Some(Constant::Utf8("recordDeleted".to_owned())),
                Some(Constant::Methodref { class_index: 95, name_and_type_index: 198 }),
                Some(Constant::NameAndType { name_index: 199, descriptor_index: 180 }),
                Some(Constant::Utf8("length".to_owned())),
                Some(Constant::Class { name_index: 201 }),
                Some(Constant::Utf8("java/lang/IllegalArgumentException".to_owned())),
                Some(Constant::Methodref { class_index: 200, name_and_type_index: 3 }),
                Some(Constant::Methodref { class_index: 65, name_and_type_index: 3 }),
                Some(Constant::Utf8("AUTHMODE_PRIVATE".to_owned())),
                Some(Constant::Utf8("ConstantValue".to_owned())),
                Some(Constant::Integer(0)),
                Some(Constant::Utf8("AUTHMODE_ANY".to_owned())),
                Some(Constant::Integer(1)),
                Some(Constant::Utf8("Code".to_owned())),
                Some(Constant::Utf8("LineNumberTable".to_owned())),
                Some(Constant::Utf8("deleteRecordStore".to_owned())),
                Some(Constant::Utf8("Exceptions".to_owned())),
                Some(Constant::Class { name_index: 214 }),
                Some(Constant::Utf8("javax/microedition/rms/RecordStoreNotFoundException".to_owned())),
                Some(Constant::Utf8("openRecordStore".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;Z)Ljavax/microedition/rms/RecordStore;".to_owned())),
                Some(Constant::Class { name_index: 218 }),
                Some(Constant::Utf8("javax/microedition/rms/RecordStoreFullException".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;ZIZ)Ljavax/microedition/rms/RecordStore;".to_owned())),
                Some(Constant::Utf8("StackMapTable".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljavax/microedition/rms/RecordStore;".to_owned())),
                Some(Constant::Utf8("setMode".to_owned())),
                Some(Constant::Utf8("(IZ)V".to_owned())),
                Some(Constant::Utf8("closeRecordStore".to_owned())),
                Some(Constant::Utf8("listRecordStores".to_owned())),
                Some(Constant::Utf8("()[Ljava/lang/String;".to_owned())),
                Some(Constant::Class { name_index: 228 }),
                Some(Constant::Utf8("[Ljava/lang/String;".to_owned())),
                Some(Constant::Utf8("getName".to_owned())),
                Some(Constant::Utf8("getVersion".to_owned())),
                Some(Constant::Utf8("getNumRecords".to_owned())),
                Some(Constant::Utf8("getSize".to_owned())),
                Some(Constant::Utf8("getSizeAvailable".to_owned())),
                Some(Constant::Utf8("getLastModified".to_owned())),
                Some(Constant::Utf8("()J".to_owned())),
                Some(Constant::Utf8("getNextRecordID".to_owned())),
                Some(Constant::Utf8("addRecord".to_owned())),
                Some(Constant::Utf8("([BII)I".to_owned())),
                Some(Constant::Utf8("deleteRecord".to_owned())),
                Some(Constant::Class { name_index: 241 }),
                Some(Constant::Utf8("javax/microedition/rms/InvalidRecordIDException".to_owned())),
                Some(Constant::Utf8("getRecordSize".to_owned())),
                Some(Constant::Utf8("(I)I".to_owned())),
                Some(Constant::Class { name_index: 245 }),
                Some(Constant::Utf8("[B".to_owned())),
                Some(Constant::Utf8("(I[BI)I".to_owned())),
                Some(Constant::Utf8("setRecord".to_owned())),
                Some(Constant::Utf8("(I[BII)V".to_owned())),
                Some(Constant::Utf8("addRecordListener".to_owned())),
                Some(Constant::Utf8("(Ljavax/microedition/rms/RecordListener;)V".to_owned())),
                Some(Constant::Utf8("removeRecordListener".to_owned())),
                Some(Constant::Utf8("enumerateRecords".to_owned())),
                Some(Constant::Utf8("(Ljavax/microedition/rms/RecordFilter;Ljavax/microedition/rms/RecordComparator;Z)Ljavax/microedition/rms/RecordEnumeration;".to_owned())),
                Some(Constant::Utf8("recordIds".to_owned())),
                Some(Constant::Utf8("()[I".to_owned())),
                Some(Constant::Utf8("isOpen".to_owned())),
                Some(Constant::Utf8("()Z".to_owned())),
                Some(Constant::Class { name_index: 259 }),
                Some(Constant::Utf8("[Ljava/lang/Object;".to_owned())),
                Some(Constant::Utf8("<clinit>".to_owned())),
                Some(Constant::Utf8("SourceFile".to_owned())),
                Some(Constant::Utf8("generated_bootstrap.rs".to_owned())),
                Some(Constant::Utf8("recordSize0".to_owned())),
                Some(Constant::NameAndType { name_index: 263, descriptor_index: 107 }),
                Some(Constant::Methodref { class_index: 8, name_and_type_index: 264 }),
            ],
            access_flags: 33,
            this_class: 8,
            super_class: 2,
            interfaces: vec![],
            fields: vec![
                Member { access_flags: 25, name_index: 204, descriptor_index: 12, attributes: vec![
                    Attribute::Raw { name_index: 205, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0xce,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 207, descriptor_index: 12, attributes: vec![
                    Attribute::Raw { name_index: 205, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0xd0,
                    ] },
                ] },
                Member { access_flags: 26, name_index: 62, descriptor_index: 63, attributes: Vec::new() },
                Member { access_flags: 18, name_index: 22, descriptor_index: 23, attributes: Vec::new() },
                Member { access_flags: 18, name_index: 26, descriptor_index: 27, attributes: Vec::new() },
                Member { access_flags: 2, name_index: 11, descriptor_index: 12, attributes: Vec::new() },
                Member { access_flags: 18, name_index: 18, descriptor_index: 19, attributes: Vec::new() },
            ],
            methods: vec![
                Member { access_flags: 2, name_index: 5, descriptor_index: 72, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 209, max_stack: 3, max_locals: 4, code: vec![
                        0x2a, 0xb7, 0x00, 0x01, 0x2a, 0x04, 0xb5, 0x00, 0x07, 0x2a, 0xbb, 0x00, 0x0d, 0x59, 0xb7, 0x00, 0x0f, 0xb5, 0x00, 0x10,
                        0x2a, 0x2b, 0xb5, 0x00, 0x14, 0x2a, 0x20, 0xb5, 0x00, 0x18, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 41, name_index: 211, descriptor_index: 31, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 209, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb8, 0x00, 0x1c, 0x2a, 0xb8, 0x00, 0x20, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 41, name_index: 215, descriptor_index: 216, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 209, max_stack: 3, max_locals: 2, code: vec![
                        0x2a, 0xb8, 0x00, 0x1c, 0x2a, 0x2a, 0x1b, 0xb8, 0x00, 0x23, 0xb8, 0x00, 0x27, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 41, name_index: 215, descriptor_index: 219, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 209, max_stack: 3, max_locals: 4, code: vec![
                        0x2a, 0xb8, 0x00, 0x1c, 0x1c, 0xb8, 0x00, 0x2b, 0x1c, 0x04, 0xa0, 0x00, 0x0d, 0xbb, 0x00, 0x2f, 0x59, 0x12, 0x31, 0xb7,
                        0x00, 0x33, 0xbf, 0x2a, 0x2a, 0x1b, 0xb8, 0x00, 0x23, 0xb8, 0x00, 0x27, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 41, name_index: 215, descriptor_index: 221, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 209, max_stack: 4, max_locals: 3, code: vec![
                        0x2a, 0xb8, 0x00, 0x1c, 0x2b, 0xc6, 0x00, 0x07, 0x2c, 0xc7, 0x00, 0x0b, 0xbb, 0x00, 0x35, 0x59, 0xb7, 0x00, 0x37, 0xbf,
                        0x2a, 0x2a, 0x2b, 0x2c, 0xb8, 0x00, 0x38, 0xb8, 0x00, 0x27, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 10, name_index: 41, descriptor_index: 42, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 209, max_stack: 5, max_locals: 5, code: vec![
                        0xb2, 0x00, 0x3c, 0x2a, 0xb6, 0x00, 0x40, 0xc0, 0x00, 0x08, 0x4e, 0x2d, 0xc6, 0x00, 0x0f, 0x2d, 0x59, 0xb4, 0x00, 0x07,
                        0x04, 0x60, 0xb5, 0x00, 0x07, 0x2d, 0xb0, 0xbb, 0x00, 0x08, 0x59, 0x2a, 0x1f, 0xb7, 0x00, 0x46, 0x3a, 0x04, 0xb2, 0x00,
                        0x3c, 0x2a, 0x19, 0x04, 0xb6, 0x00, 0x49, 0x57, 0x19, 0x04, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 33, name_index: 222, descriptor_index: 223, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 209, max_stack: 3, max_locals: 3, code: vec![
                        0x2a, 0xb6, 0x00, 0x4d, 0x1b, 0xb8, 0x00, 0x2b, 0x1b, 0x04, 0xa0, 0x00, 0x0d, 0xbb, 0x00, 0x2f, 0x59, 0x12, 0x31, 0xb7,
                        0x00, 0x33, 0xbf, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 33, name_index: 224, descriptor_index: 6, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 209, max_stack: 3, max_locals: 1, code: vec![
                        0x2a, 0xb6, 0x00, 0x4d, 0x2a, 0xb4, 0x00, 0x18, 0xb8, 0x00, 0x50, 0x2a, 0x59, 0xb4, 0x00, 0x07, 0x04, 0x64, 0xb5, 0x00,
                        0x07, 0x2a, 0xb4, 0x00, 0x07, 0x9a, 0x00, 0x15, 0xb2, 0x00, 0x3c, 0x2a, 0xb4, 0x00, 0x14, 0xb6, 0x00, 0x54, 0x57, 0x2a,
                        0xb4, 0x00, 0x10, 0xb6, 0x00, 0x57, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 41, name_index: 225, descriptor_index: 226, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 209, max_stack: 6, max_locals: 6, code: vec![
                        0xb8, 0x00, 0x5a, 0x4b, 0x2a, 0xc7, 0x00, 0x05, 0x01, 0xb0, 0x2a, 0x03, 0xb6, 0x00, 0x5e, 0x3c, 0x1b, 0xbd, 0x00, 0x5f,
                        0x4d, 0x04, 0x3e, 0x03, 0x36, 0x04, 0x15, 0x04, 0x1b, 0xa2, 0x00, 0x25, 0x2a, 0x1d, 0x84, 0x03, 0x01, 0xb6, 0x00, 0x5e,
                        0x36, 0x05, 0x2c, 0x15, 0x04, 0x2a, 0x1d, 0x1d, 0x15, 0x05, 0x60, 0xb6, 0x00, 0x64, 0x53, 0x1d, 0x15, 0x05, 0x60, 0x3e,
                        0x84, 0x04, 0x01, 0xa7, 0xff, 0xdb, 0x2c, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 33, name_index: 229, descriptor_index: 93, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 209, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb6, 0x00, 0x4d, 0x2a, 0xb4, 0x00, 0x14, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 33, name_index: 230, descriptor_index: 180, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 209, max_stack: 3, max_locals: 1, code: vec![
                        0x2a, 0xb6, 0x00, 0x4d, 0x2a, 0xb4, 0x00, 0x18, 0x03, 0xb8, 0x00, 0x68, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 33, name_index: 231, descriptor_index: 180, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 209, max_stack: 3, max_locals: 1, code: vec![
                        0x2a, 0xb6, 0x00, 0x4d, 0x2a, 0xb4, 0x00, 0x18, 0x04, 0xb8, 0x00, 0x68, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 33, name_index: 232, descriptor_index: 180, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 209, max_stack: 3, max_locals: 1, code: vec![
                        0x2a, 0xb6, 0x00, 0x4d, 0x2a, 0xb4, 0x00, 0x18, 0x05, 0xb8, 0x00, 0x68, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 33, name_index: 233, descriptor_index: 180, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 209, max_stack: 3, max_locals: 1, code: vec![
                        0x2a, 0xb6, 0x00, 0x4d, 0x2a, 0xb4, 0x00, 0x18, 0x06, 0xb8, 0x00, 0x68, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 33, name_index: 234, descriptor_index: 235, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 209, max_stack: 2, max_locals: 1, code: vec![
                        0x2a, 0xb6, 0x00, 0x4d, 0x2a, 0xb4, 0x00, 0x18, 0xb8, 0x00, 0x6c, 0xad,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 33, name_index: 236, descriptor_index: 180, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 209, max_stack: 3, max_locals: 1, code: vec![
                        0x2a, 0xb6, 0x00, 0x4d, 0x2a, 0xb4, 0x00, 0x18, 0x07, 0xb8, 0x00, 0x68, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 33, name_index: 237, descriptor_index: 238, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 209, max_stack: 5, max_locals: 5, code: vec![
                        0x2a, 0xb6, 0x00, 0x4d, 0x2a, 0xb4, 0x00, 0x18, 0x2b, 0x1c, 0x1d, 0xb8, 0x00, 0x70, 0xb8, 0x00, 0x74, 0x36, 0x04, 0x2a,
                        0x03, 0x15, 0x04, 0xb7, 0x00, 0x78, 0x15, 0x04, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 33, name_index: 239, descriptor_index: 46, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 209, max_stack: 3, max_locals: 2, code: vec![
                        0x2a, 0xb6, 0x00, 0x4d, 0x2a, 0xb4, 0x00, 0x18, 0x1b, 0xb8, 0x00, 0x7c, 0x2a, 0x05, 0x1b, 0xb7, 0x00, 0x78, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 33, name_index: 242, descriptor_index: 243, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 209, max_stack: 3, max_locals: 2, code: vec![
                        // Check the open count, then query length without allocating a record.
                        0x2a, 0xb6, 0x00, 0x4d, 0x2a, 0xb4, 0x00, 0x18, 0x1b, 0xb8, 0x01, 0x09, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 33, name_index: 130, descriptor_index: 246, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 209, max_stack: 5, max_locals: 6, code: vec![
                        0x2a, 0xb6, 0x00, 0x4d, 0x2c, 0xc7, 0x00, 0x0b, 0xbb, 0x00, 0x35, 0x59, 0xb7, 0x00, 0x37, 0xbf, 0x2a, 0xb4, 0x00, 0x18,
                        0x1b, 0xb8, 0x00, 0x84, 0x3a, 0x04, 0x19, 0x04, 0xc7, 0x00, 0x07, 0x03, 0xa7, 0x00, 0x06, 0x19, 0x04, 0xbe, 0x36, 0x05,
                        0x1d, 0x9b, 0x00, 0x0c, 0x1d, 0x2c, 0xbe, 0x15, 0x05, 0x64, 0xa4, 0x00, 0x0b, 0xbb, 0x00, 0x88, 0x59, 0xb7, 0x00, 0x8a,
                        0xbf, 0x15, 0x05, 0x99, 0x00, 0x0d, 0x19, 0x04, 0x03, 0x2c, 0x1d, 0x15, 0x05, 0xb8, 0x00, 0x8b, 0x15, 0x05, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 33, name_index: 130, descriptor_index: 131, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 209, max_stack: 3, max_locals: 2, code: vec![
                        0x2a, 0xb6, 0x00, 0x4d, 0x2a, 0xb4, 0x00, 0x18, 0x1b, 0xb8, 0x00, 0x84, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 33, name_index: 247, descriptor_index: 248, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 209, max_stack: 6, max_locals: 5, code: vec![
                        0x2a, 0xb6, 0x00, 0x4d, 0x2a, 0xb4, 0x00, 0x18, 0x1b, 0x2c, 0x1d, 0x15, 0x04, 0xb8, 0x00, 0x70, 0xb8, 0x00, 0x91, 0x2a,
                        0x04, 0x1b, 0xb7, 0x00, 0x78, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 33, name_index: 249, descriptor_index: 250, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 209, max_stack: 2, max_locals: 2, code: vec![
                        0x2b, 0xc6, 0x00, 0x16, 0x2a, 0xb4, 0x00, 0x10, 0x2b, 0xb6, 0x00, 0x95, 0x9a, 0x00, 0x0b, 0x2a, 0xb4, 0x00, 0x10, 0x2b,
                        0xb6, 0x00, 0x99, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 33, name_index: 251, descriptor_index: 250, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 209, max_stack: 2, max_locals: 2, code: vec![
                        0x2b, 0xc6, 0x00, 0x0c, 0x2a, 0xb4, 0x00, 0x10, 0x2b, 0xb6, 0x00, 0x9d, 0x57, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 33, name_index: 252, descriptor_index: 253, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 209, max_stack: 6, max_locals: 5, code: vec![
                        0x2a, 0xb6, 0x00, 0x4d, 0xbb, 0x00, 0xa0, 0x59, 0x2a, 0x2b, 0x2c, 0x1d, 0xb7, 0x00, 0xa2, 0xb0, 0x3a, 0x04, 0x19, 0x04,
                        0xbf, 0x3a, 0x04, 0xbb, 0x00, 0xa9, 0x59, 0xb7, 0x00, 0xab, 0xbf,
                    ], exception_table: vec![
                        ExceptionHandler { start_pc: 4, end_pc: 15, handler_pc: 16, catch_type: 165 },
                        ExceptionHandler { start_pc: 4, end_pc: 15, handler_pc: 21, catch_type: 167 },
                    ], attributes: Vec::new() }),
                ] },
                Member { access_flags: 32, name_index: 254, descriptor_index: 255, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 209, max_stack: 2, max_locals: 1, code: vec![
                        0x2a, 0xb6, 0x00, 0x4d, 0x2a, 0xb4, 0x00, 0x18, 0xb8, 0x00, 0xac, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 32, name_index: 256, descriptor_index: 257, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 209, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x07, 0x9e, 0x00, 0x07, 0x04, 0xa7, 0x00, 0x04, 0x03, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 32, name_index: 79, descriptor_index: 6, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 209, max_stack: 2, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x07, 0x9a, 0x00, 0x0b, 0xbb, 0x00, 0xa5, 0x59, 0xb7, 0x00, 0xb0, 0xbf, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 2, name_index: 122, descriptor_index: 123, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 209, max_stack: 3, max_locals: 6, code: vec![
                        0x2a, 0xb4, 0x00, 0x10, 0xb6, 0x00, 0xb1, 0xbd, 0x00, 0x02, 0x4e, 0x2a, 0xb4, 0x00, 0x10, 0x2d, 0xb6, 0x00, 0xb5, 0x03,
                        0x36, 0x04, 0x15, 0x04, 0x2d, 0xbe, 0xa2, 0x00, 0x3c, 0x2d, 0x15, 0x04, 0x32, 0xc0, 0x00, 0xb9, 0x3a, 0x05, 0x1b, 0x9a,
                        0x00, 0x0f, 0x19, 0x05, 0x2a, 0x1c, 0xb9, 0x00, 0xbb, 0x03, 0x00, 0xa7, 0x00, 0x1d, 0x1b, 0x04, 0xa0, 0x00, 0x0f, 0x19,
                        0x05, 0x2a, 0x1c, 0xb9, 0x00, 0xbf, 0x03, 0x00, 0xa7, 0x00, 0x0c, 0x19, 0x05, 0x2a, 0x1c, 0xb9, 0x00, 0xc2, 0x03, 0x00,
                        0x84, 0x04, 0x01, 0xa7, 0xff, 0xc3, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 10, name_index: 114, descriptor_index: 115, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 209, max_stack: 5, max_locals: 4, code: vec![
                        0x1c, 0x9b, 0x00, 0x07, 0x1b, 0x9c, 0x00, 0x0b, 0xbb, 0x00, 0x88, 0x59, 0xb7, 0x00, 0x8a, 0xbf, 0x2a, 0xc7, 0x00, 0x11,
                        0x1c, 0x99, 0x00, 0x0b, 0xbb, 0x00, 0x35, 0x59, 0xb7, 0x00, 0x37, 0xbf, 0x01, 0xb0, 0x1b, 0x2a, 0xbe, 0x1c, 0x64, 0xa4,
                        0x00, 0x0b, 0xbb, 0x00, 0x88, 0x59, 0xb7, 0x00, 0x8a, 0xbf, 0x1b, 0x9a, 0x00, 0x0b, 0x1c, 0x2a, 0xbe, 0xa0, 0x00, 0x05,
                        0x2a, 0xb0, 0x1c, 0xbc, 0x08, 0x4e, 0x1c, 0x99, 0x00, 0x0b, 0x2a, 0x1b, 0x2d, 0x03, 0x1c, 0xb8, 0x00, 0x8b, 0x2d, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 10, name_index: 30, descriptor_index: 31, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 209, max_stack: 2, max_locals: 1, code: vec![
                        0x2a, 0xc7, 0x00, 0x0b, 0xbb, 0x00, 0x35, 0x59, 0xb7, 0x00, 0x37, 0xbf, 0x2a, 0xb6, 0x00, 0xc5, 0x04, 0xa1, 0x00, 0x0c,
                        0x2a, 0xb6, 0x00, 0xc5, 0x10, 0x20, 0xa4, 0x00, 0x0b, 0xbb, 0x00, 0xc8, 0x59, 0xb7, 0x00, 0xca, 0xbf, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 10, name_index: 45, descriptor_index: 46, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 209, max_stack: 2, max_locals: 1, code: vec![
                        0x1a, 0x99, 0x00, 0x10, 0x1a, 0x04, 0x9f, 0x00, 0x0b, 0xbb, 0x00, 0xc8, 0x59, 0xb7, 0x00, 0xca, 0xbf, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 266, name_index: 37, descriptor_index: 38, attributes: Vec::new() },
                Member { access_flags: 266, name_index: 58, descriptor_index: 59, attributes: Vec::new() },
                Member { access_flags: 266, name_index: 82, descriptor_index: 83, attributes: Vec::new() },
                Member { access_flags: 266, name_index: 34, descriptor_index: 31, attributes: Vec::new() },
                Member { access_flags: 266, name_index: 92, descriptor_index: 93, attributes: Vec::new() },
                Member { access_flags: 266, name_index: 106, descriptor_index: 107, attributes: Vec::new() },
                Member { access_flags: 266, name_index: 110, descriptor_index: 111, attributes: Vec::new() },
                Member { access_flags: 266, name_index: 174, descriptor_index: 175, attributes: Vec::new() },
                Member { access_flags: 266, name_index: 263, descriptor_index: 107, attributes: Vec::new() },
                Member { access_flags: 266, name_index: 134, descriptor_index: 135, attributes: Vec::new() },
                Member { access_flags: 266, name_index: 118, descriptor_index: 119, attributes: Vec::new() },
                Member { access_flags: 266, name_index: 147, descriptor_index: 148, attributes: Vec::new() },
                Member { access_flags: 266, name_index: 126, descriptor_index: 127, attributes: Vec::new() },
                Member { access_flags: 8, name_index: 260, descriptor_index: 6, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 209, max_stack: 2, max_locals: 0, code: vec![
                        0xbb, 0x00, 0x41, 0x59, 0xb7, 0x00, 0xcb, 0xb3, 0x00, 0x3c, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
            ],
            attributes: Vec::new(),
        },
    );
}
