[package]
name = "cldc"
version = "0.1.0"
edition.workspace = true
license.workspace = true
description = "CLDC library for J2Play"
[dependencies]
device-profile = { path = "../device-profile" }
diagnostics = { path = "../diagnostics" }
natives = { path = "../natives" }
[dev-dependencies]
serde_json = "1"
[lints]
workspace = true
