//! `GameCanvas`, base layers and layer-manager bootstrap declarations.

use super::{
    Attribute, ClassFile, CodeAttribute, Constant, ExceptionHandler, Member,
    append_bootstrap_classes, build_bootstrap_class,
};

mod sprite;
mod tiled_layer;

pub(super) fn append_generated_game(classes: &mut Vec<ClassFile>) {
    append_bootstrap_classes!(classes;
        // javax/microedition/lcdui/game/GameCanvas
        ClassFile {
            minor_version: 0,
            major_version: 48,
            constant_pool: vec![
                None,
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 3 }),
                Some(Constant::Class { name_index: 4 }),
                Some(Constant::NameAndType { name_index: 5, descriptor_index: 6 }),
                Some(Constant::Utf8("javax/microedition/lcdui/Canvas".to_owned())),
                Some(Constant::Utf8("<init>".to_owned())),
                Some(Constant::Utf8("()V".to_owned())),
                Some(Constant::Fieldref { class_index: 8, name_and_type_index: 9 }),
                Some(Constant::Class { name_index: 10 }),
                Some(Constant::NameAndType { name_index: 11, descriptor_index: 12 }),
                Some(Constant::Utf8("javax/microedition/lcdui/game/GameCanvas".to_owned())),
                Some(Constant::Utf8("suppressKeyEvents".to_owned())),
                Some(Constant::Utf8("Z".to_owned())),
                Some(Constant::Methodref { class_index: 8, name_and_type_index: 14 }),
                Some(Constant::NameAndType { name_index: 15, descriptor_index: 16 }),
                Some(Constant::Utf8("__getKeyStates".to_owned())),
                Some(Constant::Utf8("()I".to_owned())),
                Some(Constant::Methodref { class_index: 8, name_and_type_index: 18 }),
                Some(Constant::NameAndType { name_index: 19, descriptor_index: 6 }),
                Some(Constant::Utf8("__flushGameGraphics".to_owned())),
                Some(Constant::Methodref { class_index: 8, name_and_type_index: 21 }),
                Some(Constant::NameAndType { name_index: 22, descriptor_index: 23 }),
                Some(Constant::Utf8("__getGameGraphics".to_owned())),
                Some(Constant::Utf8("()Ljavax/microedition/lcdui/Graphics;".to_owned())),
                Some(Constant::Utf8("UP_PRESSED".to_owned())),
                Some(Constant::Utf8("I".to_owned())),
                Some(Constant::Utf8("ConstantValue".to_owned())),
                Some(Constant::Integer(2)),
                Some(Constant::Utf8("LEFT_PRESSED".to_owned())),
                Some(Constant::Integer(4)),
                Some(Constant::Utf8("RIGHT_PRESSED".to_owned())),
                Some(Constant::Integer(32)),
                Some(Constant::Utf8("DOWN_PRESSED".to_owned())),
                Some(Constant::Integer(64)),
                Some(Constant::Utf8("FIRE_PRESSED".to_owned())),
                Some(Constant::Integer(256)),
                Some(Constant::Utf8("GAME_A_PRESSED".to_owned())),
                Some(Constant::Integer(512)),
                Some(Constant::Utf8("GAME_B_PRESSED".to_owned())),
                Some(Constant::Integer(1024)),
                Some(Constant::Utf8("GAME_C_PRESSED".to_owned())),
                Some(Constant::Integer(2048)),
                Some(Constant::Utf8("GAME_D_PRESSED".to_owned())),
                Some(Constant::Integer(4096)),
                Some(Constant::Utf8("(Z)V".to_owned())),
                Some(Constant::Utf8("Code".to_owned())),
                Some(Constant::Utf8("LineNumberTable".to_owned())),
                Some(Constant::Utf8("paint".to_owned())),
                Some(Constant::Utf8("(Ljavax/microedition/lcdui/Graphics;)V".to_owned())),
                Some(Constant::Utf8("__suppressKeyEvents".to_owned())),
                Some(Constant::Utf8("()Z".to_owned())),
                Some(Constant::Utf8("getKeyStates".to_owned())),
                Some(Constant::Utf8("flushGraphics".to_owned())),
                Some(Constant::Utf8("(IIII)V".to_owned())),
                Some(Constant::Utf8("getGraphics".to_owned())),
                Some(Constant::Utf8("SourceFile".to_owned())),
                Some(Constant::Utf8("generated_bootstrap.rs".to_owned())),
            ],
            access_flags: 1057,
            this_class: 8,
            super_class: 2,
            interfaces: vec![],
            fields: vec![
                Member { access_flags: 25, name_index: 24, descriptor_index: 25, attributes: vec![
                    Attribute::Raw { name_index: 26, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x1b,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 28, descriptor_index: 25, attributes: vec![
                    Attribute::Raw { name_index: 26, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x1d,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 30, descriptor_index: 25, attributes: vec![
                    Attribute::Raw { name_index: 26, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x1f,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 32, descriptor_index: 25, attributes: vec![
                    Attribute::Raw { name_index: 26, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x21,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 34, descriptor_index: 25, attributes: vec![
                    Attribute::Raw { name_index: 26, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x23,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 36, descriptor_index: 25, attributes: vec![
                    Attribute::Raw { name_index: 26, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x25,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 38, descriptor_index: 25, attributes: vec![
                    Attribute::Raw { name_index: 26, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x27,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 40, descriptor_index: 25, attributes: vec![
                    Attribute::Raw { name_index: 26, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x29,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 42, descriptor_index: 25, attributes: vec![
                    Attribute::Raw { name_index: 26, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x2b,
                    ] },
                ] },
                Member { access_flags: 18, name_index: 11, descriptor_index: 12, attributes: Vec::new() },
            ],
            methods: vec![
                Member { access_flags: 4, name_index: 5, descriptor_index: 44, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 45, max_stack: 2, max_locals: 2, code: vec![
                        0x2a, 0xb7, 0x00, 0x01, 0x2a, 0x1b, 0xb5, 0x00, 0x07, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 4, name_index: 47, descriptor_index: 48, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 45, max_stack: 0, max_locals: 2, code: vec![
                        0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 20, name_index: 49, descriptor_index: 50, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 45, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x07, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 20, name_index: 51, descriptor_index: 16, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 45, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb6, 0x00, 0x0d, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 17, name_index: 52, descriptor_index: 6, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 45, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb6, 0x00, 0x11, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 17, name_index: 52, descriptor_index: 53, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 45, max_stack: 1, max_locals: 5, code: vec![
                        0x2a, 0xb6, 0x00, 0x11, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 4, name_index: 54, descriptor_index: 23, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 45, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb6, 0x00, 0x14, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
            ],
            attributes: Vec::new(),
        },
        // javax/microedition/lcdui/game/Layer
        ClassFile {
            minor_version: 0,
            major_version: 48,
            constant_pool: vec![
                None,
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 3 }),
                Some(Constant::Class { name_index: 4 }),
                Some(Constant::NameAndType { name_index: 5, descriptor_index: 6 }),
                Some(Constant::Utf8("java/lang/Object".to_owned())),
                Some(Constant::Utf8("<init>".to_owned())),
                Some(Constant::Utf8("()V".to_owned())),
                Some(Constant::Fieldref { class_index: 8, name_and_type_index: 9 }),
                Some(Constant::Class { name_index: 10 }),
                Some(Constant::NameAndType { name_index: 11, descriptor_index: 12 }),
                Some(Constant::Utf8("javax/microedition/lcdui/game/Layer".to_owned())),
                Some(Constant::Utf8("visible".to_owned())),
                Some(Constant::Utf8("Z".to_owned())),
                Some(Constant::Class { name_index: 14 }),
                Some(Constant::Utf8("java/lang/IllegalArgumentException".to_owned())),
                Some(Constant::Methodref { class_index: 13, name_and_type_index: 3 }),
                Some(Constant::Fieldref { class_index: 8, name_and_type_index: 17 }),
                Some(Constant::NameAndType { name_index: 18, descriptor_index: 19 }),
                Some(Constant::Utf8("width".to_owned())),
                Some(Constant::Utf8("I".to_owned())),
                Some(Constant::Fieldref { class_index: 8, name_and_type_index: 21 }),
                Some(Constant::NameAndType { name_index: 22, descriptor_index: 19 }),
                Some(Constant::Utf8("height".to_owned())),
                Some(Constant::Fieldref { class_index: 8, name_and_type_index: 24 }),
                Some(Constant::NameAndType { name_index: 25, descriptor_index: 19 }),
                Some(Constant::Utf8("x".to_owned())),
                Some(Constant::Fieldref { class_index: 8, name_and_type_index: 27 }),
                Some(Constant::NameAndType { name_index: 28, descriptor_index: 19 }),
                Some(Constant::Utf8("y".to_owned())),
                Some(Constant::Methodref { class_index: 8, name_and_type_index: 30 }),
                Some(Constant::NameAndType { name_index: 31, descriptor_index: 32 }),
                Some(Constant::Utf8("sat".to_owned())),
                Some(Constant::Utf8("(II)I".to_owned())),
                Some(Constant::Long(2147483647)),
                None,
                Some(Constant::Integer(2147483647)),
                Some(Constant::Long(-2147483648)),
                None,
                Some(Constant::Integer(-2147483648)),
                Some(Constant::Utf8("(II)V".to_owned())),
                Some(Constant::Utf8("Code".to_owned())),
                Some(Constant::Utf8("LineNumberTable".to_owned())),
                Some(Constant::Utf8("StackMapTable".to_owned())),
                Some(Constant::Utf8("getX".to_owned())),
                Some(Constant::Utf8("()I".to_owned())),
                Some(Constant::Utf8("getY".to_owned())),
                Some(Constant::Utf8("getWidth".to_owned())),
                Some(Constant::Utf8("getHeight".to_owned())),
                Some(Constant::Utf8("isVisible".to_owned())),
                Some(Constant::Utf8("()Z".to_owned())),
                Some(Constant::Utf8("setVisible".to_owned())),
                Some(Constant::Utf8("(Z)V".to_owned())),
                Some(Constant::Utf8("setPosition".to_owned())),
                Some(Constant::Utf8("move".to_owned())),
                Some(Constant::Utf8("setSize".to_owned())),
                Some(Constant::Utf8("paint".to_owned())),
                Some(Constant::Utf8("(Ljavax/microedition/lcdui/Graphics;)V".to_owned())),
                Some(Constant::Utf8("SourceFile".to_owned())),
                Some(Constant::Utf8("generated_bootstrap.rs".to_owned())),
            ],
            access_flags: 1057,
            this_class: 8,
            super_class: 2,
            interfaces: vec![],
            fields: vec![
                Member { access_flags: 2, name_index: 25, descriptor_index: 19, attributes: Vec::new() },
                Member { access_flags: 2, name_index: 28, descriptor_index: 19, attributes: Vec::new() },
                Member { access_flags: 2, name_index: 18, descriptor_index: 19, attributes: Vec::new() },
                Member { access_flags: 2, name_index: 22, descriptor_index: 19, attributes: Vec::new() },
                Member { access_flags: 2, name_index: 11, descriptor_index: 12, attributes: Vec::new() },
            ],
            methods: vec![
                Member { access_flags: 4, name_index: 5, descriptor_index: 39, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 40, max_stack: 2, max_locals: 3, code: vec![
                        0x2a, 0xb7, 0x00, 0x01, 0x2a, 0x04, 0xb5, 0x00, 0x07, 0x1b, 0x9b, 0x00, 0x07, 0x1c, 0x9c, 0x00, 0x0b, 0xbb, 0x00, 0x0d,
                        0x59, 0xb7, 0x00, 0x0f, 0xbf, 0x2a, 0x1b, 0xb5, 0x00, 0x10, 0x2a, 0x1c, 0xb5, 0x00, 0x14, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 17, name_index: 43, descriptor_index: 44, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 40, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x17, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 17, name_index: 45, descriptor_index: 44, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 40, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x1a, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 17, name_index: 46, descriptor_index: 44, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 40, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x10, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 17, name_index: 47, descriptor_index: 44, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 40, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x14, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 17, name_index: 48, descriptor_index: 49, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 40, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x07, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 17, name_index: 50, descriptor_index: 51, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 40, max_stack: 2, max_locals: 2, code: vec![
                        0x2a, 0x1b, 0xb5, 0x00, 0x07, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 17, name_index: 52, descriptor_index: 39, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 40, max_stack: 2, max_locals: 3, code: vec![
                        0x2a, 0x1b, 0xb5, 0x00, 0x17, 0x2a, 0x1c, 0xb5, 0x00, 0x1a, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 17, name_index: 53, descriptor_index: 39, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 40, max_stack: 3, max_locals: 3, code: vec![
                        0x2a, 0x2a, 0xb4, 0x00, 0x17, 0x1b, 0xb8, 0x00, 0x1d, 0xb5, 0x00, 0x17, 0x2a, 0x2a, 0xb4, 0x00, 0x1a, 0x1c, 0xb8, 0x00,
                        0x1d, 0xb5, 0x00, 0x1a, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 20, name_index: 54, descriptor_index: 39, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 40, max_stack: 2, max_locals: 3, code: vec![
                        0x1b, 0x9b, 0x00, 0x07, 0x1c, 0x9c, 0x00, 0x0b, 0xbb, 0x00, 0x0d, 0x59, 0xb7, 0x00, 0x0f, 0xbf, 0x2a, 0x1b, 0xb5, 0x00,
                        0x10, 0x2a, 0x1c, 0xb5, 0x00, 0x14, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 8, name_index: 31, descriptor_index: 32, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 40, max_stack: 4, max_locals: 4, code: vec![
                        0x1a, 0x85, 0x1b, 0x85, 0x61, 0x41, 0x20, 0x14, 0x00, 0x21, 0x94, 0x9e, 0x00, 0x08, 0x12, 0x23, 0xa7, 0x00, 0x12, 0x20,
                        0x14, 0x00, 0x24, 0x94, 0x9c, 0x00, 0x08, 0x12, 0x26, 0xa7, 0x00, 0x05, 0x20, 0x88, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1025, name_index: 55, descriptor_index: 56, attributes: Vec::new() },
            ],
            attributes: Vec::new(),
        },
        // javax/microedition/lcdui/game/LayerManager
        ClassFile {
            minor_version: 0,
            major_version: 48,
            constant_pool: vec![
                None,
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 3 }),
                Some(Constant::Class { name_index: 4 }),
                Some(Constant::NameAndType { name_index: 5, descriptor_index: 6 }),
                Some(Constant::Utf8("java/lang/Object".to_owned())),
                Some(Constant::Utf8("<init>".to_owned())),
                Some(Constant::Utf8("()V".to_owned())),
                Some(Constant::Class { name_index: 8 }),
                Some(Constant::Utf8("java/util/Vector".to_owned())),
                Some(Constant::Methodref { class_index: 7, name_and_type_index: 3 }),
                Some(Constant::Fieldref { class_index: 11, name_and_type_index: 12 }),
                Some(Constant::Class { name_index: 13 }),
                Some(Constant::NameAndType { name_index: 14, descriptor_index: 15 }),
                Some(Constant::Utf8("javax/microedition/lcdui/game/LayerManager".to_owned())),
                Some(Constant::Utf8("layers".to_owned())),
                Some(Constant::Utf8("Ljava/util/Vector;".to_owned())),
                Some(Constant::Class { name_index: 17 }),
                Some(Constant::Utf8("java/lang/Integer".to_owned())),
                Some(Constant::Integer(2147483647)),
                Some(Constant::Fieldref { class_index: 11, name_and_type_index: 20 }),
                Some(Constant::NameAndType { name_index: 21, descriptor_index: 22 }),
                Some(Constant::Utf8("viewW".to_owned())),
                Some(Constant::Utf8("I".to_owned())),
                Some(Constant::Fieldref { class_index: 11, name_and_type_index: 24 }),
                Some(Constant::NameAndType { name_index: 25, descriptor_index: 22 }),
                Some(Constant::Utf8("viewH".to_owned())),
                Some(Constant::Class { name_index: 27 }),
                Some(Constant::Utf8("java/lang/NullPointerException".to_owned())),
                Some(Constant::Methodref { class_index: 26, name_and_type_index: 3 }),
                Some(Constant::Methodref { class_index: 11, name_and_type_index: 30 }),
                Some(Constant::NameAndType { name_index: 31, descriptor_index: 32 }),
                Some(Constant::Utf8("remove".to_owned())),
                Some(Constant::Utf8("(Ljavax/microedition/lcdui/game/Layer;)V".to_owned())),
                Some(Constant::Methodref { class_index: 7, name_and_type_index: 34 }),
                Some(Constant::NameAndType { name_index: 35, descriptor_index: 36 }),
                Some(Constant::Utf8("addElement".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/Object;)V".to_owned())),
                Some(Constant::Methodref { class_index: 7, name_and_type_index: 38 }),
                Some(Constant::NameAndType { name_index: 39, descriptor_index: 40 }),
                Some(Constant::Utf8("size".to_owned())),
                Some(Constant::Utf8("()I".to_owned())),
                Some(Constant::Class { name_index: 42 }),
                Some(Constant::Utf8("java/lang/IndexOutOfBoundsException".to_owned())),
                Some(Constant::Methodref { class_index: 41, name_and_type_index: 3 }),
                Some(Constant::Methodref { class_index: 7, name_and_type_index: 45 }),
                Some(Constant::NameAndType { name_index: 46, descriptor_index: 47 }),
                Some(Constant::Utf8("indexOf".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/Object;)I".to_owned())),
                Some(Constant::Methodref { class_index: 7, name_and_type_index: 49 }),
                Some(Constant::NameAndType { name_index: 50, descriptor_index: 51 }),
                Some(Constant::Utf8("removeElementAt".to_owned())),
                Some(Constant::Utf8("(I)V".to_owned())),
                Some(Constant::Methodref { class_index: 7, name_and_type_index: 53 }),
                Some(Constant::NameAndType { name_index: 54, descriptor_index: 55 }),
                Some(Constant::Utf8("insertElementAt".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/Object;I)V".to_owned())),
                Some(Constant::Methodref { class_index: 7, name_and_type_index: 57 }),
                Some(Constant::NameAndType { name_index: 58, descriptor_index: 59 }),
                Some(Constant::Utf8("removeElement".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/Object;)Z".to_owned())),
                Some(Constant::Methodref { class_index: 7, name_and_type_index: 61 }),
                Some(Constant::NameAndType { name_index: 62, descriptor_index: 63 }),
                Some(Constant::Utf8("elementAt".to_owned())),
                Some(Constant::Utf8("(I)Ljava/lang/Object;".to_owned())),
                Some(Constant::Class { name_index: 65 }),
                Some(Constant::Utf8("javax/microedition/lcdui/game/Layer".to_owned())),
                Some(Constant::Class { name_index: 67 }),
                Some(Constant::Utf8("java/lang/IllegalArgumentException".to_owned())),
                Some(Constant::Methodref { class_index: 66, name_and_type_index: 3 }),
                Some(Constant::Fieldref { class_index: 11, name_and_type_index: 70 }),
                Some(Constant::NameAndType { name_index: 71, descriptor_index: 22 }),
                Some(Constant::Utf8("viewX".to_owned())),
                Some(Constant::Fieldref { class_index: 11, name_and_type_index: 73 }),
                Some(Constant::NameAndType { name_index: 74, descriptor_index: 22 }),
                Some(Constant::Utf8("viewY".to_owned())),
                Some(Constant::Methodref { class_index: 76, name_and_type_index: 77 }),
                Some(Constant::Class { name_index: 78 }),
                Some(Constant::NameAndType { name_index: 79, descriptor_index: 40 }),
                Some(Constant::Utf8("javax/microedition/lcdui/Graphics".to_owned())),
                Some(Constant::Utf8("getTranslateX".to_owned())),
                Some(Constant::Methodref { class_index: 76, name_and_type_index: 81 }),
                Some(Constant::NameAndType { name_index: 82, descriptor_index: 40 }),
                Some(Constant::Utf8("getTranslateY".to_owned())),
                Some(Constant::Methodref { class_index: 76, name_and_type_index: 84 }),
                Some(Constant::NameAndType { name_index: 85, descriptor_index: 40 }),
                Some(Constant::Utf8("getClipX".to_owned())),
                Some(Constant::Methodref { class_index: 76, name_and_type_index: 87 }),
                Some(Constant::NameAndType { name_index: 88, descriptor_index: 40 }),
                Some(Constant::Utf8("getClipY".to_owned())),
                Some(Constant::Methodref { class_index: 76, name_and_type_index: 90 }),
                Some(Constant::NameAndType { name_index: 91, descriptor_index: 40 }),
                Some(Constant::Utf8("getClipWidth".to_owned())),
                Some(Constant::Methodref { class_index: 76, name_and_type_index: 93 }),
                Some(Constant::NameAndType { name_index: 94, descriptor_index: 40 }),
                Some(Constant::Utf8("getClipHeight".to_owned())),
                Some(Constant::Methodref { class_index: 11, name_and_type_index: 96 }),
                Some(Constant::NameAndType { name_index: 97, descriptor_index: 98 }),
                Some(Constant::Utf8("translateBy".to_owned())),
                Some(Constant::Utf8("(Ljavax/microedition/lcdui/Graphics;JJ)V".to_owned())),
                Some(Constant::Methodref { class_index: 76, name_and_type_index: 100 }),
                Some(Constant::NameAndType { name_index: 101, descriptor_index: 102 }),
                Some(Constant::Utf8("clipRect".to_owned())),
                Some(Constant::Utf8("(IIII)V".to_owned())),
                Some(Constant::Methodref { class_index: 64, name_and_type_index: 104 }),
                Some(Constant::NameAndType { name_index: 105, descriptor_index: 106 }),
                Some(Constant::Utf8("isVisible".to_owned())),
                Some(Constant::Utf8("()Z".to_owned())),
                Some(Constant::Methodref { class_index: 64, name_and_type_index: 108 }),
                Some(Constant::NameAndType { name_index: 109, descriptor_index: 110 }),
                Some(Constant::Utf8("paint".to_owned())),
                Some(Constant::Utf8("(Ljavax/microedition/lcdui/Graphics;)V".to_owned())),
                Some(Constant::Methodref { class_index: 11, name_and_type_index: 112 }),
                Some(Constant::NameAndType { name_index: 113, descriptor_index: 114 }),
                Some(Constant::Utf8("translateTo".to_owned())),
                Some(Constant::Utf8("(Ljavax/microedition/lcdui/Graphics;II)V".to_owned())),
                Some(Constant::Methodref { class_index: 76, name_and_type_index: 116 }),
                Some(Constant::NameAndType { name_index: 117, descriptor_index: 102 }),
                Some(Constant::Utf8("setClip".to_owned())),
                Some(Constant::Long(2147483647)),
                None,
                Some(Constant::Long(-2147483648)),
                None,
                Some(Constant::Integer(-2147483648)),
                Some(Constant::Methodref { class_index: 76, name_and_type_index: 124 }),
                Some(Constant::NameAndType { name_index: 125, descriptor_index: 126 }),
                Some(Constant::Utf8("translate".to_owned())),
                Some(Constant::Utf8("(II)V".to_owned())),
                Some(Constant::Utf8("Code".to_owned())),
                Some(Constant::Utf8("LineNumberTable".to_owned())),
                Some(Constant::Utf8("append".to_owned())),
                Some(Constant::Utf8("StackMapTable".to_owned())),
                Some(Constant::Utf8("insert".to_owned())),
                Some(Constant::Utf8("(Ljavax/microedition/lcdui/game/Layer;I)V".to_owned())),
                Some(Constant::Utf8("getLayerAt".to_owned())),
                Some(Constant::Utf8("(I)Ljavax/microedition/lcdui/game/Layer;".to_owned())),
                Some(Constant::Utf8("getSize".to_owned())),
                Some(Constant::Utf8("setViewWindow".to_owned())),
                Some(Constant::Class { name_index: 138 }),
                Some(Constant::Utf8("java/lang/Throwable".to_owned())),
                Some(Constant::Utf8("SourceFile".to_owned())),
                Some(Constant::Utf8("generated_bootstrap.rs".to_owned())),
            ],
            access_flags: 33,
            this_class: 11,
            super_class: 2,
            interfaces: vec![],
            fields: vec![
                Member { access_flags: 18, name_index: 14, descriptor_index: 15, attributes: Vec::new() },
                Member { access_flags: 2, name_index: 71, descriptor_index: 22, attributes: Vec::new() },
                Member { access_flags: 2, name_index: 74, descriptor_index: 22, attributes: Vec::new() },
                Member { access_flags: 2, name_index: 21, descriptor_index: 22, attributes: Vec::new() },
                Member { access_flags: 2, name_index: 25, descriptor_index: 22, attributes: Vec::new() },
            ],
            methods: vec![
                Member { access_flags: 1, name_index: 5, descriptor_index: 6, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 127, max_stack: 3, max_locals: 1, code: vec![
                        0x2a, 0xb7, 0x00, 0x01, 0x2a, 0xbb, 0x00, 0x07, 0x59, 0xb7, 0x00, 0x09, 0xb5, 0x00, 0x0a, 0x2a, 0x12, 0x12, 0xb5, 0x00,
                        0x13, 0x2a, 0x12, 0x12, 0xb5, 0x00, 0x17, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 129, descriptor_index: 32, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 127, max_stack: 2, max_locals: 2, code: vec![
                        0x2b, 0xc7, 0x00, 0x0b, 0xbb, 0x00, 0x1a, 0x59, 0xb7, 0x00, 0x1c, 0xbf, 0x2a, 0x2b, 0xb6, 0x00, 0x1d, 0x2a, 0xb4, 0x00,
                        0x0a, 0x2b, 0xb6, 0x00, 0x21, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 131, descriptor_index: 132, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 127, max_stack: 3, max_locals: 4, code: vec![
                        0x2b, 0xc7, 0x00, 0x0b, 0xbb, 0x00, 0x1a, 0x59, 0xb7, 0x00, 0x1c, 0xbf, 0x1c, 0x9b, 0x00, 0x0e, 0x1c, 0x2a, 0xb4, 0x00,
                        0x0a, 0xb6, 0x00, 0x25, 0xa4, 0x00, 0x0b, 0xbb, 0x00, 0x29, 0x59, 0xb7, 0x00, 0x2b, 0xbf, 0x2a, 0xb4, 0x00, 0x0a, 0x2b,
                        0xb6, 0x00, 0x2c, 0x3e, 0x1d, 0x9b, 0x00, 0x13, 0x2a, 0xb4, 0x00, 0x0a, 0x1d, 0xb6, 0x00, 0x30, 0x1d, 0x1c, 0xa2, 0x00,
                        0x06, 0x84, 0x02, 0xff, 0x2a, 0xb4, 0x00, 0x0a, 0x2b, 0x1c, 0xb6, 0x00, 0x34, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 31, descriptor_index: 32, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 127, max_stack: 2, max_locals: 2, code: vec![
                        0x2b, 0xc7, 0x00, 0x0b, 0xbb, 0x00, 0x1a, 0x59, 0xb7, 0x00, 0x1c, 0xbf, 0x2a, 0xb4, 0x00, 0x0a, 0x2b, 0xb6, 0x00, 0x38,
                        0x57, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 133, descriptor_index: 134, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 127, max_stack: 2, max_locals: 2, code: vec![
                        0x2a, 0xb4, 0x00, 0x0a, 0x1b, 0xb6, 0x00, 0x3c, 0xc0, 0x00, 0x40, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 135, descriptor_index: 40, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 127, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x0a, 0xb6, 0x00, 0x25, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 136, descriptor_index: 102, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 127, max_stack: 2, max_locals: 5, code: vec![
                        0x1d, 0x9b, 0x00, 0x08, 0x15, 0x04, 0x9c, 0x00, 0x0b, 0xbb, 0x00, 0x42, 0x59, 0xb7, 0x00, 0x44, 0xbf, 0x2a, 0x1b, 0xb5,
                        0x00, 0x45, 0x2a, 0x1c, 0xb5, 0x00, 0x48, 0x2a, 0x1d, 0xb5, 0x00, 0x13, 0x2a, 0x15, 0x04, 0xb5, 0x00, 0x17, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 109, descriptor_index: 114, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 127, max_stack: 7, max_locals: 13, code: vec![
                        0x2b, 0xc7, 0x00, 0x0b, 0xbb, 0x00, 0x1a, 0x59, 0xb7, 0x00, 0x1c, 0xbf, 0x2b, 0xb6, 0x00, 0x4b, 0x36, 0x04, 0x2b, 0xb6,
                        0x00, 0x50, 0x36, 0x05, 0x2b, 0xb6, 0x00, 0x53, 0x36, 0x06, 0x2b, 0xb6, 0x00, 0x56, 0x36, 0x07, 0x2b, 0xb6, 0x00, 0x59,
                        0x36, 0x08, 0x2b, 0xb6, 0x00, 0x5c, 0x36, 0x09, 0x2b, 0x1c, 0x85, 0x2a, 0xb4, 0x00, 0x45, 0x85, 0x65, 0x1d, 0x85, 0x2a,
                        0xb4, 0x00, 0x48, 0x85, 0x65, 0xb8, 0x00, 0x5f, 0x2b, 0x2a, 0xb4, 0x00, 0x45, 0x2a, 0xb4, 0x00, 0x48, 0x2a, 0xb4, 0x00,
                        0x13, 0x2a, 0xb4, 0x00, 0x17, 0xb6, 0x00, 0x63, 0x2a, 0xb4, 0x00, 0x0a, 0xb6, 0x00, 0x25, 0x04, 0x64, 0x36, 0x0a, 0x15,
                        0x0a, 0x9b, 0x00, 0x25, 0x2a, 0xb4, 0x00, 0x0a, 0x15, 0x0a, 0xb6, 0x00, 0x3c, 0xc0, 0x00, 0x40, 0x3a, 0x0b, 0x19, 0x0b,
                        0xb6, 0x00, 0x67, 0x99, 0x00, 0x09, 0x19, 0x0b, 0x2b, 0xb6, 0x00, 0x6b, 0x84, 0x0a, 0xff, 0xa7, 0xff, 0xdc, 0x2b, 0x15,
                        0x04, 0x15, 0x05, 0xb8, 0x00, 0x6f, 0x2b, 0x15, 0x06, 0x15, 0x07, 0x15, 0x08, 0x15, 0x09, 0xb6, 0x00, 0x73, 0xa7, 0x00,
                        0x1c, 0x3a, 0x0c, 0x2b, 0x15, 0x04, 0x15, 0x05, 0xb8, 0x00, 0x6f, 0x2b, 0x15, 0x06, 0x15, 0x07, 0x15, 0x08, 0x15, 0x09,
                        0xb6, 0x00, 0x73, 0x19, 0x0c, 0xbf, 0xb1,
                    ], exception_table: vec![
                        ExceptionHandler { start_pc: 48, end_pc: 138, handler_pc: 161, catch_type: 0 },
                        ExceptionHandler { start_pc: 161, end_pc: 163, handler_pc: 161, catch_type: 0 },
                    ], attributes: Vec::new() }),
                ] },
                Member { access_flags: 10, name_index: 97, descriptor_index: 98, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 127, max_stack: 4, max_locals: 7, code: vec![
                        0x1f, 0x09, 0x94, 0x9a, 0x00, 0x09, 0x21, 0x09, 0x94, 0x99, 0x00, 0x56, 0x1f, 0x14, 0x00, 0x76, 0x94, 0x9e, 0x00, 0x08,
                        0x12, 0x12, 0xa7, 0x00, 0x12, 0x1f, 0x14, 0x00, 0x78, 0x94, 0x9c, 0x00, 0x08, 0x12, 0x7a, 0xa7, 0x00, 0x05, 0x1f, 0x88,
                        0x36, 0x05, 0x21, 0x14, 0x00, 0x76, 0x94, 0x9e, 0x00, 0x08, 0x12, 0x12, 0xa7, 0x00, 0x12, 0x21, 0x14, 0x00, 0x78, 0x94,
                        0x9c, 0x00, 0x08, 0x12, 0x7a, 0xa7, 0x00, 0x05, 0x21, 0x88, 0x36, 0x06, 0x2a, 0x15, 0x05, 0x15, 0x06, 0xb6, 0x00, 0x7b,
                        0x1f, 0x15, 0x05, 0x85, 0x65, 0x40, 0x21, 0x15, 0x06, 0x85, 0x65, 0x42, 0xa7, 0xff, 0xa4, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 10, name_index: 113, descriptor_index: 114, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 127, max_stack: 7, max_locals: 3, code: vec![
                        0x2a, 0x1b, 0x85, 0x2a, 0xb6, 0x00, 0x4b, 0x85, 0x65, 0x1c, 0x85, 0x2a, 0xb6, 0x00, 0x50, 0x85, 0x65, 0xb8, 0x00, 0x5f,
                        0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
            ],
            attributes: Vec::new(),
        },
    );
    sprite::append_sprite(classes);
    tiled_layer::append_tiled_layer(classes);
}
