//! Common GCF connection interfaces and protocol selection.

mod file;
mod http;

use super::{
    Attribute, ClassFile, CodeAttribute, Constant, ExceptionHandler, Member,
    append_bootstrap_classes, build_bootstrap_class,
};

pub(super) fn append_generated_gcf(classes: &mut Vec<ClassFile>) {
    append_bootstrap_classes!(classes;
        // javax/microedition/io/Connection
        ClassFile {
            minor_version: 0,
            major_version: 48,
            constant_pool: vec![
                None,
                Some(Constant::Class { name_index: 2 }),
                Some(Constant::Utf8("javax/microedition/io/Connection".to_owned())),
                Some(Constant::Class { name_index: 4 }),
                Some(Constant::Utf8("java/lang/Object".to_owned())),
                Some(Constant::Utf8("close".to_owned())),
                Some(Constant::Utf8("()V".to_owned())),
                Some(Constant::Utf8("Exceptions".to_owned())),
                Some(Constant::Class { name_index: 9 }),
                Some(Constant::Utf8("java/io/IOException".to_owned())),
                Some(Constant::Utf8("SourceFile".to_owned())),
                Some(Constant::Utf8("generated_bootstrap.rs".to_owned())),
            ],
            access_flags: 1537,
            this_class: 1,
            super_class: 3,
            interfaces: vec![],
            fields: Vec::new(),
            methods: vec![
                Member { access_flags: 1025, name_index: 5, descriptor_index: 6, attributes: Vec::new() },
            ],
            attributes: Vec::new(),
        },
        // javax/microedition/io/ConnectionNotFoundException
        ClassFile {
            minor_version: 0,
            major_version: 48,
            constant_pool: vec![
                None,
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 3 }),
                Some(Constant::Class { name_index: 4 }),
                Some(Constant::NameAndType { name_index: 5, descriptor_index: 6 }),
                Some(Constant::Utf8("java/io/IOException".to_owned())),
                Some(Constant::Utf8("<init>".to_owned())),
                Some(Constant::Utf8("()V".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 8 }),
                Some(Constant::NameAndType { name_index: 5, descriptor_index: 9 }),
                Some(Constant::Utf8("(Ljava/lang/String;)V".to_owned())),
                Some(Constant::Class { name_index: 11 }),
                Some(Constant::Utf8("javax/microedition/io/ConnectionNotFoundException".to_owned())),
                Some(Constant::Utf8("Code".to_owned())),
                Some(Constant::Utf8("LineNumberTable".to_owned())),
                Some(Constant::Utf8("SourceFile".to_owned())),
                Some(Constant::Utf8("generated_bootstrap.rs".to_owned())),
            ],
            access_flags: 33,
            this_class: 10,
            super_class: 2,
            interfaces: vec![],
            fields: Vec::new(),
            methods: vec![
                Member { access_flags: 1, name_index: 5, descriptor_index: 6, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 12, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb7, 0x00, 0x01, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 5, descriptor_index: 9, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 12, max_stack: 2, max_locals: 2, code: vec![
                        0x2a, 0x2b, 0xb7, 0x00, 0x07, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
            ],
            attributes: Vec::new(),
        },
        // javax/microedition/io/Connector
        ClassFile {
            minor_version: 0,
            major_version: 48,
            constant_pool: vec![
                None,
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 3 }),
                Some(Constant::Class { name_index: 4 }),
                Some(Constant::NameAndType { name_index: 5, descriptor_index: 6 }),
                Some(Constant::Utf8("java/lang/Object".to_owned())),
                Some(Constant::Utf8("<init>".to_owned())),
                Some(Constant::Utf8("()V".to_owned())),
                Some(Constant::Class { name_index: 8 }),
                Some(Constant::Utf8("javax/microedition/io/Connector".to_owned())),
                Some(Constant::Methodref { class_index: 7, name_and_type_index: 10 }),
                Some(Constant::NameAndType { name_index: 11, descriptor_index: 12 }),
                Some(Constant::Utf8("open".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;IZ)Ljavax/microedition/io/Connection;".to_owned())),
                Some(Constant::Class { name_index: 14 }),
                Some(Constant::Utf8("java/lang/IllegalArgumentException".to_owned())),
                Some(Constant::String { string_index: 16 }),
                Some(Constant::Utf8("null connection name".to_owned())),
                Some(Constant::Methodref { class_index: 13, name_and_type_index: 18 }),
                Some(Constant::NameAndType { name_index: 5, descriptor_index: 19 }),
                Some(Constant::Utf8("(Ljava/lang/String;)V".to_owned())),
                Some(Constant::String { string_index: 21 }),
                Some(Constant::Utf8("invalid mode".to_owned())),
                Some(Constant::String { string_index: 23 }),
                Some(Constant::Utf8("http://".to_owned())),
                Some(Constant::Methodref { class_index: 25, name_and_type_index: 26 }),
                Some(Constant::Class { name_index: 27 }),
                Some(Constant::NameAndType { name_index: 28, descriptor_index: 29 }),
                Some(Constant::Utf8("java/lang/String".to_owned())),
                Some(Constant::Utf8("startsWith".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;)Z".to_owned())),
                Some(Constant::String { string_index: 31 }),
                Some(Constant::Utf8("https://".to_owned())),
                Some(Constant::Class { name_index: 33 }),
                Some(Constant::Utf8("javax/microedition/io/HttpConnectionImpl".to_owned())),
                Some(Constant::Methodref { class_index: 32, name_and_type_index: 35 }),
                Some(Constant::NameAndType { name_index: 5, descriptor_index: 36 }),
                Some(Constant::Utf8("(Ljava/lang/String;I)V".to_owned())),
                Some(Constant::String { string_index: 38 }),
                Some(Constant::Utf8("file://".to_owned())),
                Some(Constant::Class { name_index: 40 }),
                Some(Constant::Utf8("javax/microedition/io/file/FileConnectionImpl".to_owned())),
                Some(Constant::Methodref { class_index: 39, name_and_type_index: 35 }),
                Some(Constant::Class { name_index: 43 }),
                Some(Constant::Utf8("javax/microedition/io/ConnectionNotFoundException".to_owned())),
                Some(Constant::String { string_index: 45 }),
                Some(Constant::Utf8("unsupported protocol".to_owned())),
                Some(Constant::Methodref { class_index: 42, name_and_type_index: 18 }),
                Some(Constant::Methodref { class_index: 7, name_and_type_index: 48 }),
                Some(Constant::NameAndType { name_index: 11, descriptor_index: 49 }),
                Some(Constant::Utf8("(Ljava/lang/String;I)Ljavax/microedition/io/Connection;".to_owned())),
                Some(Constant::Class { name_index: 51 }),
                Some(Constant::Utf8("javax/microedition/io/InputConnection".to_owned())),
                Some(Constant::InterfaceMethodref { class_index: 50, name_and_type_index: 53 }),
                Some(Constant::NameAndType { name_index: 54, descriptor_index: 55 }),
                Some(Constant::Utf8("openInputStream".to_owned())),
                Some(Constant::Utf8("()Ljava/io/InputStream;".to_owned())),
                Some(Constant::InterfaceMethodref { class_index: 50, name_and_type_index: 57 }),
                Some(Constant::NameAndType { name_index: 58, descriptor_index: 59 }),
                Some(Constant::Utf8("openDataInputStream".to_owned())),
                Some(Constant::Utf8("()Ljava/io/DataInputStream;".to_owned())),
                Some(Constant::Class { name_index: 61 }),
                Some(Constant::Utf8("javax/microedition/io/OutputConnection".to_owned())),
                Some(Constant::InterfaceMethodref { class_index: 60, name_and_type_index: 63 }),
                Some(Constant::NameAndType { name_index: 64, descriptor_index: 65 }),
                Some(Constant::Utf8("openOutputStream".to_owned())),
                Some(Constant::Utf8("()Ljava/io/OutputStream;".to_owned())),
                Some(Constant::InterfaceMethodref { class_index: 60, name_and_type_index: 67 }),
                Some(Constant::NameAndType { name_index: 68, descriptor_index: 69 }),
                Some(Constant::Utf8("openDataOutputStream".to_owned())),
                Some(Constant::Utf8("()Ljava/io/DataOutputStream;".to_owned())),
                Some(Constant::Utf8("READ".to_owned())),
                Some(Constant::Utf8("I".to_owned())),
                Some(Constant::Utf8("ConstantValue".to_owned())),
                Some(Constant::Integer(1)),
                Some(Constant::Utf8("WRITE".to_owned())),
                Some(Constant::Integer(2)),
                Some(Constant::Utf8("READ_WRITE".to_owned())),
                Some(Constant::Integer(3)),
                Some(Constant::Utf8("Code".to_owned())),
                Some(Constant::Utf8("LineNumberTable".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;)Ljavax/microedition/io/Connection;".to_owned())),
                Some(Constant::Utf8("Exceptions".to_owned())),
                Some(Constant::Class { name_index: 83 }),
                Some(Constant::Utf8("java/io/IOException".to_owned())),
                Some(Constant::Utf8("StackMapTable".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;)Ljava/io/InputStream;".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;)Ljava/io/DataInputStream;".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;)Ljava/io/OutputStream;".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;)Ljava/io/DataOutputStream;".to_owned())),
                Some(Constant::Utf8("SourceFile".to_owned())),
                Some(Constant::Utf8("generated_bootstrap.rs".to_owned())),
            ],
            access_flags: 49,
            this_class: 7,
            super_class: 2,
            interfaces: vec![],
            fields: vec![
                Member { access_flags: 25, name_index: 70, descriptor_index: 71, attributes: vec![
                    Attribute::Raw { name_index: 72, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x49,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 74, descriptor_index: 71, attributes: vec![
                    Attribute::Raw { name_index: 72, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x4b,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 76, descriptor_index: 71, attributes: vec![
                    Attribute::Raw { name_index: 72, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x4d,
                    ] },
                ] },
            ],
            methods: vec![
                Member { access_flags: 2, name_index: 5, descriptor_index: 6, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 78, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb7, 0x00, 0x01, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 9, name_index: 11, descriptor_index: 80, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 78, max_stack: 3, max_locals: 1, code: vec![
                        0x2a, 0x06, 0x03, 0xb8, 0x00, 0x09, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 9, name_index: 11, descriptor_index: 49, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 78, max_stack: 3, max_locals: 2, code: vec![
                        0x2a, 0x1b, 0x03, 0xb8, 0x00, 0x09, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 9, name_index: 11, descriptor_index: 12, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 78, max_stack: 4, max_locals: 3, code: vec![
                        0x2a, 0xc7, 0x00, 0x0d, 0xbb, 0x00, 0x0d, 0x59, 0x12, 0x0f, 0xb7, 0x00, 0x11, 0xbf, 0x1b, 0x04, 0x9f, 0x00, 0x17, 0x1b,
                        0x05, 0x9f, 0x00, 0x12, 0x1b, 0x06, 0x9f, 0x00, 0x0d, 0xbb, 0x00, 0x0d, 0x59, 0x12, 0x14, 0xb7, 0x00, 0x11, 0xbf, 0x2a,
                        0x12, 0x16, 0xb6, 0x00, 0x18, 0x9a, 0x00, 0x0c, 0x2a, 0x12, 0x1e, 0xb6, 0x00, 0x18, 0x99, 0x00, 0x0d, 0xbb, 0x00, 0x20,
                        0x59, 0x2a, 0x1b, 0xb7, 0x00, 0x22, 0xb0, 0x2a, 0x12, 0x25, 0xb6, 0x00, 0x18, 0x99, 0x00, 0x0d, 0xbb, 0x00, 0x27, 0x59,
                        0x2a, 0x1b, 0xb7, 0x00, 0x29, 0xb0, 0xbb, 0x00, 0x2a, 0x59, 0x12, 0x2c, 0xb7, 0x00, 0x2e, 0xbf,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 9, name_index: 54, descriptor_index: 85, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 78, max_stack: 2, max_locals: 1, code: vec![
                        0x2a, 0x04, 0xb8, 0x00, 0x2f, 0xc0, 0x00, 0x32, 0xb9, 0x00, 0x34, 0x01, 0x00, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 9, name_index: 58, descriptor_index: 86, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 78, max_stack: 2, max_locals: 1, code: vec![
                        0x2a, 0x04, 0xb8, 0x00, 0x2f, 0xc0, 0x00, 0x32, 0xb9, 0x00, 0x38, 0x01, 0x00, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 9, name_index: 64, descriptor_index: 87, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 78, max_stack: 2, max_locals: 1, code: vec![
                        0x2a, 0x05, 0xb8, 0x00, 0x2f, 0xc0, 0x00, 0x3c, 0xb9, 0x00, 0x3e, 0x01, 0x00, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 9, name_index: 68, descriptor_index: 88, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 78, max_stack: 2, max_locals: 1, code: vec![
                        0x2a, 0x05, 0xb8, 0x00, 0x2f, 0xc0, 0x00, 0x3c, 0xb9, 0x00, 0x42, 0x01, 0x00, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
            ],
            attributes: Vec::new(),
        },
        // javax/microedition/io/ContentConnection
        ClassFile {
            minor_version: 0,
            major_version: 48,
            constant_pool: vec![
                None,
                Some(Constant::Class { name_index: 2 }),
                Some(Constant::Utf8("javax/microedition/io/ContentConnection".to_owned())),
                Some(Constant::Class { name_index: 4 }),
                Some(Constant::Utf8("java/lang/Object".to_owned())),
                Some(Constant::Class { name_index: 6 }),
                Some(Constant::Utf8("javax/microedition/io/StreamConnection".to_owned())),
                Some(Constant::Utf8("getType".to_owned())),
                Some(Constant::Utf8("()Ljava/lang/String;".to_owned())),
                Some(Constant::Utf8("getEncoding".to_owned())),
                Some(Constant::Utf8("getLength".to_owned())),
                Some(Constant::Utf8("()J".to_owned())),
                Some(Constant::Utf8("SourceFile".to_owned())),
                Some(Constant::Utf8("generated_bootstrap.rs".to_owned())),
            ],
            access_flags: 1537,
            this_class: 1,
            super_class: 3,
            interfaces: vec![5],
            fields: Vec::new(),
            methods: vec![
                Member { access_flags: 1025, name_index: 7, descriptor_index: 8, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 9, descriptor_index: 8, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 10, descriptor_index: 11, attributes: Vec::new() },
            ],
            attributes: Vec::new(),
        },
    );
    http::append_classes(classes);
    append_bootstrap_classes!(classes;
        // javax/microedition/io/InputConnection
        ClassFile {
            minor_version: 0,
            major_version: 48,
            constant_pool: vec![
                None,
                Some(Constant::Class { name_index: 2 }),
                Some(Constant::Utf8("javax/microedition/io/InputConnection".to_owned())),
                Some(Constant::Class { name_index: 4 }),
                Some(Constant::Utf8("java/lang/Object".to_owned())),
                Some(Constant::Class { name_index: 6 }),
                Some(Constant::Utf8("javax/microedition/io/Connection".to_owned())),
                Some(Constant::Utf8("openInputStream".to_owned())),
                Some(Constant::Utf8("()Ljava/io/InputStream;".to_owned())),
                Some(Constant::Utf8("Exceptions".to_owned())),
                Some(Constant::Class { name_index: 11 }),
                Some(Constant::Utf8("java/io/IOException".to_owned())),
                Some(Constant::Utf8("openDataInputStream".to_owned())),
                Some(Constant::Utf8("()Ljava/io/DataInputStream;".to_owned())),
                Some(Constant::Utf8("SourceFile".to_owned())),
                Some(Constant::Utf8("generated_bootstrap.rs".to_owned())),
            ],
            access_flags: 1537,
            this_class: 1,
            super_class: 3,
            interfaces: vec![5],
            fields: Vec::new(),
            methods: vec![
                Member { access_flags: 1025, name_index: 7, descriptor_index: 8, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 12, descriptor_index: 13, attributes: Vec::new() },
            ],
            attributes: Vec::new(),
        },
        // javax/microedition/io/OutputConnection
        ClassFile {
            minor_version: 0,
            major_version: 48,
            constant_pool: vec![
                None,
                Some(Constant::Class { name_index: 2 }),
                Some(Constant::Utf8("javax/microedition/io/OutputConnection".to_owned())),
                Some(Constant::Class { name_index: 4 }),
                Some(Constant::Utf8("java/lang/Object".to_owned())),
                Some(Constant::Class { name_index: 6 }),
                Some(Constant::Utf8("javax/microedition/io/Connection".to_owned())),
                Some(Constant::Utf8("openOutputStream".to_owned())),
                Some(Constant::Utf8("()Ljava/io/OutputStream;".to_owned())),
                Some(Constant::Utf8("Exceptions".to_owned())),
                Some(Constant::Class { name_index: 11 }),
                Some(Constant::Utf8("java/io/IOException".to_owned())),
                Some(Constant::Utf8("openDataOutputStream".to_owned())),
                Some(Constant::Utf8("()Ljava/io/DataOutputStream;".to_owned())),
                Some(Constant::Utf8("SourceFile".to_owned())),
                Some(Constant::Utf8("generated_bootstrap.rs".to_owned())),
            ],
            access_flags: 1537,
            this_class: 1,
            super_class: 3,
            interfaces: vec![5],
            fields: Vec::new(),
            methods: vec![
                Member { access_flags: 1025, name_index: 7, descriptor_index: 8, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 12, descriptor_index: 13, attributes: Vec::new() },
            ],
            attributes: Vec::new(),
        },
        // javax/microedition/io/StreamConnection
        ClassFile {
            minor_version: 0,
            major_version: 48,
            constant_pool: vec![
                None,
                Some(Constant::Class { name_index: 2 }),
                Some(Constant::Utf8("javax/microedition/io/StreamConnection".to_owned())),
                Some(Constant::Class { name_index: 4 }),
                Some(Constant::Utf8("java/lang/Object".to_owned())),
                Some(Constant::Class { name_index: 6 }),
                Some(Constant::Utf8("javax/microedition/io/InputConnection".to_owned())),
                Some(Constant::Class { name_index: 8 }),
                Some(Constant::Utf8("javax/microedition/io/OutputConnection".to_owned())),
                Some(Constant::Utf8("SourceFile".to_owned())),
                Some(Constant::Utf8("generated_bootstrap.rs".to_owned())),
            ],
            access_flags: 1537,
            this_class: 1,
            super_class: 3,
            interfaces: vec![5, 7],
            fields: Vec::new(),
            methods: Vec::new(),
            attributes: Vec::new(),
        },
    );
    file::append_classes(classes);
}
