use crate::Image;

#[test]
fn cmyk_jpeg_preserves_midtones_when_color_and_black_ink_are_combined() {
    for (cmyk, rgb) in [
        ([0, 0, 0, 0], 0xffffff),
        ([0, 0, 0, 255], 0x000000),
        ([255, 255, 255, 0], 0x000000),
        ([128, 128, 128, 128], 0x3f3f3f),
        ([0, 128, 255, 128], 0x7f3f00),
        ([32, 96, 160, 64], 0xa77747),
        ([0, 0, 0, 128], 0x7f7f7f),
        ([128, 128, 128, 0], 0x7f7f7f),
    ] {
        let encoded = solid_cmyk_jpeg(cmyk);
        let image = Image::from_encoded(&encoded).unwrap();
        assert_eq!((image.width(), image.height()), (1, 1));
        assert_eq!(image.pixels(), &[0xff000000 | rgb], "CMYK {cmyk:?}");
        assert_eq!(Image::from_midp_encoded(&encoded).unwrap(), image);
    }
}

fn solid_cmyk_jpeg(cmyk: [u8; 4]) -> Vec<u8> {
    use std::fmt::Write as _;

    // Project-owned 1x1 baseline JPEG: four constant, unsubsampled blocks.
    // Adobe APP14 transform 0 stores each CMYK component inverted.
    let mut encoded = vec![0xff, 0xd8, 0xff, 0xee, 0, 14];
    encoded.extend_from_slice(b"Adobe\0\x64\0\0\0\0\0");
    encoded.extend_from_slice(&[0xff, 0xdb, 0, 67, 0]);
    encoded.extend_from_slice(&[1; 64]);
    // DC table: categories 0..11 have four-bit Huffman codes 0000..1011.
    encoded.extend_from_slice(&[0xff, 0xc4, 0, 31, 0, 0, 0, 0, 12]);
    encoded.extend_from_slice(&[0; 12]);
    encoded.extend(0..12);
    // AC table: a single zero bit marks the end of each constant block.
    encoded.extend_from_slice(&[0xff, 0xc4, 0, 20, 0x10, 1]);
    encoded.extend_from_slice(&[0; 16]);
    encoded.extend_from_slice(&[0xff, 0xc0, 0, 20, 8, 0, 1, 0, 1, 4]);
    for component in 1..=4 {
        encoded.extend_from_slice(&[component, 0x11, 0]);
    }
    encoded.extend_from_slice(&[0xff, 0xda, 0, 14, 4]);
    for component in 1..=4 {
        encoded.extend_from_slice(&[component, 0]);
    }
    encoded.extend_from_slice(&[0, 63, 0]);

    let mut bits = String::new();
    for ink in cmyk {
        let dc = (i32::from(255 - ink) - 128) * 8;
        let category = 32 - dc.unsigned_abs().leading_zeros();
        write!(bits, "{category:04b}").unwrap();
        if category != 0 {
            let magnitude = if dc < 0 { dc + (1 << category) - 1 } else { dc };
            write!(bits, "{magnitude:0width$b}", width = category as usize).unwrap();
        }
        bits.push('0');
    }
    while !bits.len().is_multiple_of(8) {
        bits.push('1');
    }
    for group in bits.as_bytes().chunks_exact(8) {
        let byte = group
            .iter()
            .fold(0_u8, |byte, bit| (byte << 1) | (bit - b'0'));
        encoded.push(byte);
        if byte == 0xff {
            encoded.push(0);
        }
    }
    encoded.extend_from_slice(&[0xff, 0xd9]);
    encoded
}

#[test]
fn encoded_image_dispatches_baseline_jpeg() {
    // Project-owned 2x2 red baseline JPEG generated by FFmpeg's encoder.
    const JPEG_HEX: &str = "ffd8ffe000104a46494600010200000100010000fffe000f4c61766336332e312e31303000ffdb0043000804040404040505050505050606060606060606060606060607070708080807070706060707080808080909090808080809090a0a0a0c0c0b0b0e0e0e111114ffc4004c0001010000000000000000000000000000000601010100000000000000000000000000000607100100000000000000000000000000000000110100000000000000000000000000000000ffc00011080002000203012200021100031100ffda000c03010002110311003f008b004d7f7fffd9";
    let jpeg = JPEG_HEX
        .as_bytes()
        .chunks_exact(2)
        .map(|digits| {
            let nibble = |digit| match digit {
                b'0'..=b'9' => digit - b'0',
                b'a'..=b'f' => digit - b'a' + 10,
                _ => unreachable!(),
            };
            nibble(digits[0]) << 4 | nibble(digits[1])
        })
        .collect::<Vec<_>>();

    let image = Image::from_encoded(&jpeg).unwrap();

    assert_eq!((image.width(), image.height()), (2, 2));
    assert_eq!(image.pixels().len(), 4);
    assert!(image.pixels().iter().all(|pixel| pixel >> 24 == 0xff));
    assert!(
        image
            .pixels()
            .iter()
            .all(|pixel| (pixel >> 16 & 0xff) > (pixel >> 8 & 0xff))
    );
}

#[test]
fn sixteen_bit_jpeg_grayscale_uses_the_sample_high_byte() {
    // Project-owned 1x1 lossless JPEGs: predictor 1 starts at 0x8000.
    // One Huffman code (0) carries a zero, negative or positive difference.
    for (category, entropy, expected) in [
        (0, &[0x7f][..], 0xff80_8080),
        (15, &[0x12, 0x33][..], 0xff12_1212),
        (15, &[0x7f, 0xff, 0][..], 0xffff_ffff),
    ] {
        let mut encoded = vec![0xff, 0xd8, 0xff, 0xc4, 0, 20, 0, 1];
        encoded.extend_from_slice(&[0; 15]);
        encoded.push(category);
        // SOF3: 16 bits, 1x1, one component with no subsampling.
        encoded.extend_from_slice(&[0xff, 0xc3, 0, 11, 16, 0, 1, 0, 1, 1, 1, 0x11, 0]);
        // SOS: one component, DC table 0, predictor 1, point transform 0.
        encoded.extend_from_slice(&[0xff, 0xda, 0, 8, 1, 1, 0, 1, 0, 0]);
        encoded.extend_from_slice(entropy);
        encoded.extend_from_slice(&[0xff, 0xd9]);

        let image = Image::from_encoded(&encoded).unwrap();
        assert_eq!((image.width(), image.height()), (1, 1));
        assert_eq!(image.pixels(), &[expected]);
        assert_eq!(Image::from_midp_encoded(&encoded).unwrap(), image);
    }
}

#[test]
fn lossless_jpeg_grayscale_uses_the_declared_sample_precision() {
    for precision in 9..=16_u8 {
        for (category, magnitude, expected) in [
            (0, 0, 0xff80_8080),
            (precision - 1, 0, 0xff00_0000),
            (precision - 1, (1_u32 << (precision - 1)) - 1, 0xffff_ffff),
        ] {
            let mut encoded = vec![0xff, 0xd8];
            // A marker-like sequence inside COM must not supply the precision.
            encoded.extend_from_slice(&[0xff, 0xfe, 0, 6, 0xff, 0xc3, 0, 9]);
            encoded.extend_from_slice(&[0xff, 0xc4, 0, 20, 0, 1]);
            encoded.extend_from_slice(&[0; 15]);
            encoded.push(category);
            // One fill byte precedes SOF3; samples contain their native precision.
            encoded.extend_from_slice(&[
                0xff, 0xff, 0xc3, 0, 11, precision, 0, 1, 0, 1, 1, 1, 0x11, 0,
            ]);
            encoded.extend_from_slice(&[0xff, 0xda, 0, 8, 1, 1, 0, 1, 0, 0]);
            let bit_count = usize::from(category) + 1;
            let padding = (8 - bit_count % 8) % 8;
            let entropy = (magnitude << padding) | ((1 << padding) - 1);
            for offset in (0..bit_count.div_ceil(8)).rev() {
                let byte = (entropy >> (offset * 8)) as u8;
                encoded.push(byte);
                if byte == 0xff {
                    encoded.push(0);
                }
            }
            encoded.extend_from_slice(&[0xff, 0xd9]);
            let image = Image::from_encoded(&encoded).unwrap();
            assert_eq!(image.pixels(), &[expected], "precision={precision}");
        }
    }
}

#[test]
fn lossless_precision_header_scan_rejects_truncated_segments_and_stops_at_entropy() {
    for bytes in [
        &[][..],
        &[0xff],
        &[0xff, 0xff],
        &[0xff, 0xd8, 0xff, 0xfe, 0, 0],
        &[0xff, 0xd8, 0xff, 0xfe, 0, 1],
        &[0xff, 0xd8, 0xff, 0xfe, 0xff, 0xff],
        &[0xff, 0xd8, 0xff, 0xc3, 0, 2],
        &[0xff, 0xd8, 0xff, 0xda, 0xff, 0xc3, 0, 3, 12],
        &[0xff, 0xd8, 0xff, 0xd9, 0xff, 0xc3, 0, 3, 12],
    ] {
        assert_eq!(super::lossless_sample_precision(bytes), None, "{bytes:x?}");
    }
}

#[test]
fn jpeg_rejects_oversized_dimensions_before_reading_pixel_data() {
    for (width, height, expected) in [
        (4096_u16, 4096_u16, "image-size"),
        (u16::MAX, 65, "image-size"),
        (2, 2, "jpeg-decode"),
    ] {
        // SOI and a grayscale baseline frame header, deliberately no scan.
        // Oversized dimensions must win over missing entropy/table errors.
        let mut encoded = vec![0xff, 0xd8, 0xff, 0xc0, 0, 11, 8];
        encoded.extend_from_slice(&height.to_be_bytes());
        encoded.extend_from_slice(&width.to_be_bytes());
        encoded.extend_from_slice(&[1, 1, 0x11, 0]);
        assert_eq!(Image::from_encoded(&encoded).unwrap_err().code(), expected);
    }
}
