//! HTTP connection implementation and its request output stream.

use super::super::{
    Attribute, ClassFile, CodeAttribute, Constant, ExceptionHandler, Member,
    append_bootstrap_classes, build_bootstrap_class,
};

pub(super) fn append_classes(classes: &mut Vec<ClassFile>) {
    append_bootstrap_classes!(classes;
        // javax/microedition/io/HttpConnectionImpl$RequestOutput
        ClassFile {
            minor_version: 0,
            major_version: 48,
            constant_pool: vec![
                None,
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 3 }),
                Some(Constant::Class { name_index: 4 }),
                Some(Constant::NameAndType { name_index: 5, descriptor_index: 6 }),
                Some(Constant::Utf8("java/io/ByteArrayOutputStream".to_owned())),
                Some(Constant::Utf8("<init>".to_owned())),
                Some(Constant::Utf8("()V".to_owned())),
                Some(Constant::Fieldref { class_index: 8, name_and_type_index: 9 }),
                Some(Constant::Class { name_index: 10 }),
                Some(Constant::NameAndType { name_index: 11, descriptor_index: 12 }),
                Some(Constant::Utf8("javax/microedition/io/HttpConnectionImpl$RequestOutput".to_owned())),
                Some(Constant::Utf8("owner".to_owned())),
                Some(Constant::Utf8("Ljavax/microedition/io/HttpConnectionImpl;".to_owned())),
                Some(Constant::Methodref { class_index: 8, name_and_type_index: 14 }),
                Some(Constant::NameAndType { name_index: 15, descriptor_index: 16 }),
                Some(Constant::Utf8("toByteArray".to_owned())),
                Some(Constant::Utf8("()[B".to_owned())),
                Some(Constant::Methodref { class_index: 18, name_and_type_index: 19 }),
                Some(Constant::Class { name_index: 20 }),
                Some(Constant::NameAndType { name_index: 21, descriptor_index: 22 }),
                Some(Constant::Utf8("javax/microedition/io/HttpConnectionImpl".to_owned())),
                Some(Constant::Utf8("access$002".to_owned())),
                Some(Constant::Utf8("(Ljavax/microedition/io/HttpConnectionImpl;[B)[B".to_owned())),
                Some(Constant::Utf8("(Ljavax/microedition/io/HttpConnectionImpl;)V".to_owned())),
                Some(Constant::Utf8("Code".to_owned())),
                Some(Constant::Utf8("LineNumberTable".to_owned())),
                Some(Constant::Utf8("close".to_owned())),
                Some(Constant::Utf8("StackMapTable".to_owned())),
                Some(Constant::Utf8("Exceptions".to_owned())),
                Some(Constant::Class { name_index: 30 }),
                Some(Constant::Utf8("java/io/IOException".to_owned())),
                Some(Constant::Utf8("SourceFile".to_owned())),
                Some(Constant::Utf8("generated_bootstrap.rs".to_owned())),
                Some(Constant::Utf8("InnerClasses".to_owned())),
                Some(Constant::Utf8("RequestOutput".to_owned())),
            ],
            access_flags: 48,
            this_class: 8,
            super_class: 2,
            interfaces: vec![],
            fields: vec![
                Member { access_flags: 2, name_index: 11, descriptor_index: 12, attributes: Vec::new() },
            ],
            methods: vec![
                Member { access_flags: 0, name_index: 5, descriptor_index: 23, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 24, max_stack: 2, max_locals: 2, code: vec![
                        0x2a, 0xb7, 0x00, 0x01, 0x2a, 0x2b, 0xb5, 0x00, 0x07, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 26, descriptor_index: 6, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 24, max_stack: 2, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x07, 0xc6, 0x00, 0x14, 0x2a, 0xb4, 0x00, 0x07, 0x2a, 0xb6, 0x00, 0x0d, 0xb8, 0x00, 0x11, 0x57, 0x2a,
                        0x01, 0xb5, 0x00, 0x07, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
            ],
            attributes: Vec::new(),
        },
        // javax/microedition/io/HttpConnectionImpl
        ClassFile {
            minor_version: 0,
            major_version: 48,
            constant_pool: vec![
                None,
                Some(Constant::Fieldref { class_index: 2, name_and_type_index: 3 }),
                Some(Constant::Class { name_index: 4 }),
                Some(Constant::NameAndType { name_index: 5, descriptor_index: 6 }),
                Some(Constant::Utf8("javax/microedition/io/HttpConnectionImpl".to_owned())),
                Some(Constant::Utf8("requestBody".to_owned())),
                Some(Constant::Utf8("[B".to_owned())),
                Some(Constant::Methodref { class_index: 8, name_and_type_index: 9 }),
                Some(Constant::Class { name_index: 10 }),
                Some(Constant::NameAndType { name_index: 11, descriptor_index: 12 }),
                Some(Constant::Utf8("java/lang/Object".to_owned())),
                Some(Constant::Utf8("<init>".to_owned())),
                Some(Constant::Utf8("()V".to_owned())),
                Some(Constant::Fieldref { class_index: 2, name_and_type_index: 14 }),
                Some(Constant::NameAndType { name_index: 15, descriptor_index: 16 }),
                Some(Constant::Utf8("open".to_owned())),
                Some(Constant::Utf8("Z".to_owned())),
                Some(Constant::Class { name_index: 18 }),
                Some(Constant::Utf8("javax/microedition/io/HttpConnection".to_owned())),
                Some(Constant::String { string_index: 20 }),
                Some(Constant::Utf8("GET".to_owned())),
                Some(Constant::Fieldref { class_index: 2, name_and_type_index: 22 }),
                Some(Constant::NameAndType { name_index: 23, descriptor_index: 24 }),
                Some(Constant::Utf8("method".to_owned())),
                Some(Constant::Utf8("Ljava/lang/String;".to_owned())),
                Some(Constant::Class { name_index: 26 }),
                Some(Constant::Utf8("java/util/Hashtable".to_owned())),
                Some(Constant::Methodref { class_index: 25, name_and_type_index: 9 }),
                Some(Constant::Fieldref { class_index: 2, name_and_type_index: 29 }),
                Some(Constant::NameAndType { name_index: 30, descriptor_index: 31 }),
                Some(Constant::Utf8("requestHeaders".to_owned())),
                Some(Constant::Utf8("Ljava/util/Hashtable;".to_owned())),
                Some(Constant::Fieldref { class_index: 2, name_and_type_index: 33 }),
                Some(Constant::NameAndType { name_index: 34, descriptor_index: 31 }),
                Some(Constant::Utf8("responseHeaders".to_owned())),
                Some(Constant::Class { name_index: 36 }),
                Some(Constant::Utf8("java/util/Vector".to_owned())),
                Some(Constant::Methodref { class_index: 35, name_and_type_index: 9 }),
                Some(Constant::Fieldref { class_index: 2, name_and_type_index: 39 }),
                Some(Constant::NameAndType { name_index: 40, descriptor_index: 41 }),
                Some(Constant::Utf8("responseNames".to_owned())),
                Some(Constant::Utf8("Ljava/util/Vector;".to_owned())),
                Some(Constant::Fieldref { class_index: 2, name_and_type_index: 43 }),
                Some(Constant::NameAndType { name_index: 44, descriptor_index: 24 }),
                Some(Constant::Utf8("url".to_owned())),
                Some(Constant::Fieldref { class_index: 2, name_and_type_index: 46 }),
                Some(Constant::NameAndType { name_index: 47, descriptor_index: 48 }),
                Some(Constant::Utf8("mode".to_owned())),
                Some(Constant::Utf8("I".to_owned())),
                Some(Constant::Class { name_index: 50 }),
                Some(Constant::Utf8("java/io/IOException".to_owned())),
                Some(Constant::String { string_index: 52 }),
                Some(Constant::Utf8("connection closed".to_owned())),
                Some(Constant::Methodref { class_index: 49, name_and_type_index: 54 }),
                Some(Constant::NameAndType { name_index: 11, descriptor_index: 55 }),
                Some(Constant::Utf8("(Ljava/lang/String;)V".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 57 }),
                Some(Constant::NameAndType { name_index: 58, descriptor_index: 12 }),
                Some(Constant::Utf8("requireOpen".to_owned())),
                Some(Constant::Class { name_index: 60 }),
                Some(Constant::Utf8("javax/microedition/io/Connector".to_owned())),
                Some(Constant::String { string_index: 62 }),
                Some(Constant::Utf8("connection is not readable".to_owned())),
                Some(Constant::String { string_index: 64 }),
                Some(Constant::Utf8("connection is not writable".to_owned())),
                Some(Constant::Fieldref { class_index: 2, name_and_type_index: 66 }),
                Some(Constant::NameAndType { name_index: 67, descriptor_index: 16 }),
                Some(Constant::Utf8("connected".to_owned())),
                Some(Constant::Class { name_index: 69 }),
                Some(Constant::Utf8("java/lang/StringBuffer".to_owned())),
                Some(Constant::Methodref { class_index: 68, name_and_type_index: 9 }),
                Some(Constant::Methodref { class_index: 25, name_and_type_index: 72 }),
                Some(Constant::NameAndType { name_index: 73, descriptor_index: 74 }),
                Some(Constant::Utf8("keys".to_owned())),
                Some(Constant::Utf8("()Ljava/util/Enumeration;".to_owned())),
                Some(Constant::InterfaceMethodref { class_index: 76, name_and_type_index: 77 }),
                Some(Constant::Class { name_index: 78 }),
                Some(Constant::NameAndType { name_index: 79, descriptor_index: 80 }),
                Some(Constant::Utf8("java/util/Enumeration".to_owned())),
                Some(Constant::Utf8("hasMoreElements".to_owned())),
                Some(Constant::Utf8("()Z".to_owned())),
                Some(Constant::InterfaceMethodref { class_index: 76, name_and_type_index: 82 }),
                Some(Constant::NameAndType { name_index: 83, descriptor_index: 84 }),
                Some(Constant::Utf8("nextElement".to_owned())),
                Some(Constant::Utf8("()Ljava/lang/Object;".to_owned())),
                Some(Constant::Class { name_index: 86 }),
                Some(Constant::Utf8("java/lang/String".to_owned())),
                Some(Constant::Methodref { class_index: 68, name_and_type_index: 88 }),
                Some(Constant::NameAndType { name_index: 89, descriptor_index: 90 }),
                Some(Constant::Utf8("length".to_owned())),
                Some(Constant::Utf8("()I".to_owned())),
                Some(Constant::Methodref { class_index: 68, name_and_type_index: 92 }),
                Some(Constant::NameAndType { name_index: 93, descriptor_index: 94 }),
                Some(Constant::Utf8("append".to_owned())),
                Some(Constant::Utf8("(C)Ljava/lang/StringBuffer;".to_owned())),
                Some(Constant::Methodref { class_index: 68, name_and_type_index: 96 }),
                Some(Constant::NameAndType { name_index: 93, descriptor_index: 97 }),
                Some(Constant::Utf8("(Ljava/lang/String;)Ljava/lang/StringBuffer;".to_owned())),
                Some(Constant::Methodref { class_index: 25, name_and_type_index: 99 }),
                Some(Constant::NameAndType { name_index: 100, descriptor_index: 101 }),
                Some(Constant::Utf8("get".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/Object;)Ljava/lang/Object;".to_owned())),
                Some(Constant::Class { name_index: 103 }),
                Some(Constant::Utf8("java/io/DataInputStream".to_owned())),
                Some(Constant::Class { name_index: 105 }),
                Some(Constant::Utf8("java/io/ByteArrayInputStream".to_owned())),
                Some(Constant::Methodref { class_index: 68, name_and_type_index: 107 }),
                Some(Constant::NameAndType { name_index: 108, descriptor_index: 109 }),
                Some(Constant::Utf8("toString".to_owned())),
                Some(Constant::Utf8("()Ljava/lang/String;".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 111 }),
                Some(Constant::NameAndType { name_index: 112, descriptor_index: 113 }),
                Some(Constant::Utf8("request0".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[B)[B".to_owned())),
                Some(Constant::Methodref { class_index: 104, name_and_type_index: 115 }),
                Some(Constant::NameAndType { name_index: 11, descriptor_index: 116 }),
                Some(Constant::Utf8("([B)V".to_owned())),
                Some(Constant::Methodref { class_index: 102, name_and_type_index: 118 }),
                Some(Constant::NameAndType { name_index: 11, descriptor_index: 119 }),
                Some(Constant::Utf8("(Ljava/io/InputStream;)V".to_owned())),
                Some(Constant::Methodref { class_index: 102, name_and_type_index: 121 }),
                Some(Constant::NameAndType { name_index: 122, descriptor_index: 90 }),
                Some(Constant::Utf8("readInt".to_owned())),
                Some(Constant::Fieldref { class_index: 2, name_and_type_index: 124 }),
                Some(Constant::NameAndType { name_index: 125, descriptor_index: 48 }),
                Some(Constant::Utf8("status".to_owned())),
                Some(Constant::Methodref { class_index: 102, name_and_type_index: 127 }),
                Some(Constant::NameAndType { name_index: 128, descriptor_index: 109 }),
                Some(Constant::Utf8("readUTF".to_owned())),
                Some(Constant::Fieldref { class_index: 2, name_and_type_index: 130 }),
                Some(Constant::NameAndType { name_index: 131, descriptor_index: 24 }),
                Some(Constant::Utf8("reason".to_owned())),
                Some(Constant::Methodref { class_index: 35, name_and_type_index: 133 }),
                Some(Constant::NameAndType { name_index: 134, descriptor_index: 135 }),
                Some(Constant::Utf8("addElement".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/Object;)V".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 137 }),
                Some(Constant::NameAndType { name_index: 138, descriptor_index: 139 }),
                Some(Constant::Utf8("lower".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;)Ljava/lang/String;".to_owned())),
                Some(Constant::Methodref { class_index: 25, name_and_type_index: 141 }),
                Some(Constant::NameAndType { name_index: 142, descriptor_index: 143 }),
                Some(Constant::Utf8("put".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;".to_owned())),
                Some(Constant::String { string_index: 145 }),
                Some(Constant::Utf8("invalid response length".to_owned())),
                Some(Constant::Fieldref { class_index: 2, name_and_type_index: 147 }),
                Some(Constant::NameAndType { name_index: 148, descriptor_index: 6 }),
                Some(Constant::Utf8("responseBody".to_owned())),
                Some(Constant::Methodref { class_index: 102, name_and_type_index: 150 }),
                Some(Constant::NameAndType { name_index: 151, descriptor_index: 116 }),
                Some(Constant::Utf8("readFully".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 153 }),
                Some(Constant::NameAndType { name_index: 154, descriptor_index: 12 }),
                Some(Constant::Utf8("requireRead".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 156 }),
                Some(Constant::NameAndType { name_index: 157, descriptor_index: 12 }),
                Some(Constant::Utf8("connect".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 159 }),
                Some(Constant::NameAndType { name_index: 160, descriptor_index: 161 }),
                Some(Constant::Utf8("openInputStream".to_owned())),
                Some(Constant::Utf8("()Ljava/io/InputStream;".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 163 }),
                Some(Constant::NameAndType { name_index: 164, descriptor_index: 12 }),
                Some(Constant::Utf8("requireWrite".to_owned())),
                Some(Constant::String { string_index: 166 }),
                Some(Constant::Utf8("already connected".to_owned())),
                Some(Constant::Class { name_index: 168 }),
                Some(Constant::Utf8("javax/microedition/io/HttpConnectionImpl$RequestOutput".to_owned())),
                Some(Constant::Methodref { class_index: 167, name_and_type_index: 170 }),
                Some(Constant::NameAndType { name_index: 11, descriptor_index: 171 }),
                Some(Constant::Utf8("(Ljavax/microedition/io/HttpConnectionImpl;)V".to_owned())),
                Some(Constant::Class { name_index: 173 }),
                Some(Constant::Utf8("java/io/DataOutputStream".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 175 }),
                Some(Constant::NameAndType { name_index: 176, descriptor_index: 177 }),
                Some(Constant::Utf8("openOutputStream".to_owned())),
                Some(Constant::Utf8("()Ljava/io/OutputStream;".to_owned())),
                Some(Constant::Methodref { class_index: 172, name_and_type_index: 179 }),
                Some(Constant::NameAndType { name_index: 11, descriptor_index: 180 }),
                Some(Constant::Utf8("(Ljava/io/OutputStream;)V".to_owned())),
                Some(Constant::Methodref { class_index: 85, name_and_type_index: 182 }),
                Some(Constant::NameAndType { name_index: 183, descriptor_index: 184 }),
                Some(Constant::Utf8("equals".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/Object;)Z".to_owned())),
                Some(Constant::String { string_index: 186 }),
                Some(Constant::Utf8("HEAD".to_owned())),
                Some(Constant::String { string_index: 188 }),
                Some(Constant::Utf8("POST".to_owned())),
                Some(Constant::Class { name_index: 190 }),
                Some(Constant::Utf8("java/lang/IllegalArgumentException".to_owned())),
                Some(Constant::String { string_index: 192 }),
                Some(Constant::Utf8("unsupported method".to_owned())),
                Some(Constant::Methodref { class_index: 189, name_and_type_index: 54 }),
                Some(Constant::Class { name_index: 195 }),
                Some(Constant::Utf8("java/lang/NullPointerException".to_owned())),
                Some(Constant::Methodref { class_index: 194, name_and_type_index: 9 }),
                Some(Constant::Methodref { class_index: 85, name_and_type_index: 198 }),
                Some(Constant::NameAndType { name_index: 199, descriptor_index: 200 }),
                Some(Constant::Utf8("toCharArray".to_owned())),
                Some(Constant::Utf8("()[C".to_owned())),
                Some(Constant::Methodref { class_index: 202, name_and_type_index: 203 }),
                Some(Constant::Class { name_index: 204 }),
                Some(Constant::NameAndType { name_index: 205, descriptor_index: 206 }),
                Some(Constant::Utf8("java/lang/Character".to_owned())),
                Some(Constant::Utf8("toLowerCase".to_owned())),
                Some(Constant::Utf8("(C)C".to_owned())),
                Some(Constant::Methodref { class_index: 85, name_and_type_index: 208 }),
                Some(Constant::NameAndType { name_index: 209, descriptor_index: 210 }),
                Some(Constant::Utf8("fromChars".to_owned())),
                Some(Constant::Utf8("([C)Ljava/lang/String;".to_owned())),
                Some(Constant::String { string_index: 212 }),
                Some(Constant::Utf8("HTTP/1.1 ".to_owned())),
                Some(Constant::Methodref { class_index: 68, name_and_type_index: 54 }),
                Some(Constant::Methodref { class_index: 68, name_and_type_index: 215 }),
                Some(Constant::NameAndType { name_index: 93, descriptor_index: 216 }),
                Some(Constant::Utf8("(I)Ljava/lang/StringBuffer;".to_owned())),
                Some(Constant::Methodref { class_index: 35, name_and_type_index: 218 }),
                Some(Constant::NameAndType { name_index: 219, descriptor_index: 90 }),
                Some(Constant::Utf8("size".to_owned())),
                Some(Constant::Methodref { class_index: 35, name_and_type_index: 221 }),
                Some(Constant::NameAndType { name_index: 222, descriptor_index: 223 }),
                Some(Constant::Utf8("elementAt".to_owned())),
                Some(Constant::Utf8("(I)Ljava/lang/Object;".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 225 }),
                Some(Constant::NameAndType { name_index: 226, descriptor_index: 139 }),
                Some(Constant::Utf8("getHeaderField".to_owned())),
                Some(Constant::Methodref { class_index: 228, name_and_type_index: 229 }),
                Some(Constant::Class { name_index: 230 }),
                Some(Constant::NameAndType { name_index: 231, descriptor_index: 232 }),
                Some(Constant::Utf8("java/lang/Integer".to_owned())),
                Some(Constant::Utf8("parseInt".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;)I".to_owned())),
                Some(Constant::Class { name_index: 234 }),
                Some(Constant::Utf8("java/lang/NumberFormatException".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 236 }),
                Some(Constant::NameAndType { name_index: 237, descriptor_index: 238 }),
                Some(Constant::Utf8("parseDate0".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;)J".to_owned())),
                Some(Constant::String { string_index: 240 }),
                Some(Constant::Utf8("expires".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 242 }),
                Some(Constant::NameAndType { name_index: 243, descriptor_index: 244 }),
                Some(Constant::Utf8("getHeaderFieldDate".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;J)J".to_owned())),
                Some(Constant::String { string_index: 246 }),
                Some(Constant::Utf8("date".to_owned())),
                Some(Constant::String { string_index: 248 }),
                Some(Constant::Utf8("last-modified".to_owned())),
                Some(Constant::String { string_index: 250 }),
                Some(Constant::Utf8("content-type".to_owned())),
                Some(Constant::String { string_index: 252 }),
                Some(Constant::Utf8("content-encoding".to_owned())),
                Some(Constant::Long(-1)),
                None,
                Some(Constant::Methodref { class_index: 85, name_and_type_index: 256 }),
                Some(Constant::NameAndType { name_index: 257, descriptor_index: 258 }),
                Some(Constant::Utf8("indexOf".to_owned())),
                Some(Constant::Utf8("(I)I".to_owned())),
                Some(Constant::Methodref { class_index: 85, name_and_type_index: 260 }),
                Some(Constant::NameAndType { name_index: 261, descriptor_index: 262 }),
                Some(Constant::Utf8("substring".to_owned())),
                Some(Constant::Utf8("(II)Ljava/lang/String;".to_owned())),
                Some(Constant::String { string_index: 264 }),
                Some(Constant::Utf8("//".to_owned())),
                Some(Constant::Methodref { class_index: 85, name_and_type_index: 266 }),
                Some(Constant::NameAndType { name_index: 257, descriptor_index: 232 }),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 268 }),
                Some(Constant::NameAndType { name_index: 269, descriptor_index: 90 }),
                Some(Constant::Utf8("authorityStart".to_owned())),
                Some(Constant::Methodref { class_index: 85, name_and_type_index: 271 }),
                Some(Constant::NameAndType { name_index: 257, descriptor_index: 272 }),
                Some(Constant::Utf8("(II)I".to_owned())),
                Some(Constant::Methodref { class_index: 85, name_and_type_index: 88 }),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 275 }),
                Some(Constant::NameAndType { name_index: 276, descriptor_index: 90 }),
                Some(Constant::Utf8("authorityEnd".to_owned())),
                Some(Constant::String { string_index: 278 }),
                Some(Constant::Utf8("[".to_owned())),
                Some(Constant::Methodref { class_index: 85, name_and_type_index: 280 }),
                Some(Constant::NameAndType { name_index: 281, descriptor_index: 282 }),
                Some(Constant::Utf8("startsWith".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;)Z".to_owned())),
                Some(Constant::Methodref { class_index: 85, name_and_type_index: 284 }),
                Some(Constant::NameAndType { name_index: 285, descriptor_index: 258 }),
                Some(Constant::Utf8("lastIndexOf".to_owned())),
                Some(Constant::Methodref { class_index: 85, name_and_type_index: 287 }),
                Some(Constant::NameAndType { name_index: 288, descriptor_index: 289 }),
                Some(Constant::Utf8("charAt".to_owned())),
                Some(Constant::Utf8("(I)C".to_owned())),
                Some(Constant::Methodref { class_index: 85, name_and_type_index: 291 }),
                Some(Constant::NameAndType { name_index: 261, descriptor_index: 292 }),
                Some(Constant::Utf8("(I)Ljava/lang/String;".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;I)V".to_owned())),
                Some(Constant::Utf8("Code".to_owned())),
                Some(Constant::Utf8("LineNumberTable".to_owned())),
                Some(Constant::Utf8("Exceptions".to_owned())),
                Some(Constant::Utf8("StackMapTable".to_owned())),
                Some(Constant::Utf8("openDataInputStream".to_owned())),
                Some(Constant::Utf8("()Ljava/io/DataInputStream;".to_owned())),
                Some(Constant::Utf8("openDataOutputStream".to_owned())),
                Some(Constant::Utf8("()Ljava/io/DataOutputStream;".to_owned())),
                Some(Constant::Utf8("close".to_owned())),
                Some(Constant::Utf8("getRequestMethod".to_owned())),
                Some(Constant::Utf8("setRequestMethod".to_owned())),
                Some(Constant::Utf8("getRequestProperty".to_owned())),
                Some(Constant::Utf8("setRequestProperty".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;Ljava/lang/String;)V".to_owned())),
                Some(Constant::Utf8("getResponseCode".to_owned())),
                Some(Constant::Utf8("getResponseMessage".to_owned())),
                Some(Constant::Class { name_index: 311 }),
                Some(Constant::Utf8("[C".to_owned())),
                Some(Constant::Utf8("getHeaderFieldKey".to_owned())),
                Some(Constant::Utf8("getHeaderFieldInt".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;I)I".to_owned())),
                Some(Constant::Utf8("getExpiration".to_owned())),
                Some(Constant::Utf8("()J".to_owned())),
                Some(Constant::Utf8("getDate".to_owned())),
                Some(Constant::Utf8("getLastModified".to_owned())),
                Some(Constant::Utf8("getType".to_owned())),
                Some(Constant::Utf8("getEncoding".to_owned())),
                Some(Constant::Utf8("getLength".to_owned())),
                Some(Constant::Utf8("getURL".to_owned())),
                Some(Constant::Utf8("getProtocol".to_owned())),
                Some(Constant::Utf8("getHost".to_owned())),
                Some(Constant::Utf8("getPort".to_owned())),
                Some(Constant::Utf8("getFile".to_owned())),
                Some(Constant::Utf8("getRef".to_owned())),
                Some(Constant::Utf8("getQuery".to_owned())),
                Some(Constant::Utf8("access$002".to_owned())),
                Some(Constant::Utf8("(Ljavax/microedition/io/HttpConnectionImpl;[B)[B".to_owned())),
                Some(Constant::Utf8("SourceFile".to_owned())),
                Some(Constant::Utf8("generated_bootstrap.rs".to_owned())),
                Some(Constant::Utf8("InnerClasses".to_owned())),
                Some(Constant::Utf8("RequestOutput".to_owned())),
            ],
            access_flags: 48,
            this_class: 2,
            super_class: 8,
            interfaces: vec![17],
            fields: vec![
                Member { access_flags: 18, name_index: 44, descriptor_index: 24, attributes: Vec::new() },
                Member { access_flags: 18, name_index: 47, descriptor_index: 48, attributes: Vec::new() },
                Member { access_flags: 2, name_index: 15, descriptor_index: 16, attributes: Vec::new() },
                Member { access_flags: 2, name_index: 23, descriptor_index: 24, attributes: Vec::new() },
                Member { access_flags: 18, name_index: 30, descriptor_index: 31, attributes: Vec::new() },
                Member { access_flags: 2, name_index: 5, descriptor_index: 6, attributes: Vec::new() },
                Member { access_flags: 2, name_index: 67, descriptor_index: 16, attributes: Vec::new() },
                Member { access_flags: 2, name_index: 125, descriptor_index: 48, attributes: Vec::new() },
                Member { access_flags: 2, name_index: 131, descriptor_index: 24, attributes: Vec::new() },
                Member { access_flags: 2, name_index: 148, descriptor_index: 6, attributes: Vec::new() },
                Member { access_flags: 18, name_index: 34, descriptor_index: 31, attributes: Vec::new() },
                Member { access_flags: 18, name_index: 40, descriptor_index: 41, attributes: Vec::new() },
            ],
            methods: vec![
                Member { access_flags: 0, name_index: 11, descriptor_index: 293, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 294, max_stack: 3, max_locals: 3, code: vec![
                        0x2a, 0xb7, 0x00, 0x07, 0x2a, 0x04, 0xb5, 0x00, 0x0d, 0x2a, 0x12, 0x13, 0xb5, 0x00, 0x15, 0x2a, 0xbb, 0x00, 0x19, 0x59,
                        0xb7, 0x00, 0x1b, 0xb5, 0x00, 0x1c, 0x2a, 0x03, 0xbc, 0x08, 0xb5, 0x00, 0x01, 0x2a, 0xbb, 0x00, 0x19, 0x59, 0xb7, 0x00,
                        0x1b, 0xb5, 0x00, 0x20, 0x2a, 0xbb, 0x00, 0x23, 0x59, 0xb7, 0x00, 0x25, 0xb5, 0x00, 0x26, 0x2a, 0x2b, 0xb5, 0x00, 0x2a,
                        0x2a, 0x1c, 0xb5, 0x00, 0x2d, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 266, name_index: 112, descriptor_index: 113, attributes: Vec::new() },
                Member { access_flags: 266, name_index: 237, descriptor_index: 238, attributes: Vec::new() },
                Member { access_flags: 2, name_index: 58, descriptor_index: 12, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 294, max_stack: 3, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x0d, 0x9a, 0x00, 0x0d, 0xbb, 0x00, 0x31, 0x59, 0x12, 0x33, 0xb7, 0x00, 0x35, 0xbf, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 2, name_index: 154, descriptor_index: 12, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 294, max_stack: 3, max_locals: 1, code: vec![
                        0x2a, 0xb7, 0x00, 0x38, 0x2a, 0xb4, 0x00, 0x2d, 0x04, 0x7e, 0x9a, 0x00, 0x0d, 0xbb, 0x00, 0x31, 0x59, 0x12, 0x3d, 0xb7,
                        0x00, 0x35, 0xbf, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 2, name_index: 164, descriptor_index: 12, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 294, max_stack: 3, max_locals: 1, code: vec![
                        0x2a, 0xb7, 0x00, 0x38, 0x2a, 0xb4, 0x00, 0x2d, 0x05, 0x7e, 0x9a, 0x00, 0x0d, 0xbb, 0x00, 0x31, 0x59, 0x12, 0x3f, 0xb7,
                        0x00, 0x35, 0xbf, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 2, name_index: 157, descriptor_index: 12, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 294, max_stack: 8, max_locals: 8, code: vec![
                        0x2a, 0xb7, 0x00, 0x38, 0x2a, 0xb4, 0x00, 0x41, 0x99, 0x00, 0x04, 0xb1, 0xbb, 0x00, 0x44, 0x59, 0xb7, 0x00, 0x46, 0x4c,
                        0x2a, 0xb4, 0x00, 0x1c, 0xb6, 0x00, 0x47, 0x4d, 0x2c, 0xb9, 0x00, 0x4b, 0x01, 0x00, 0x99, 0x00, 0x37, 0x2c, 0xb9, 0x00,
                        0x51, 0x01, 0x00, 0xc0, 0x00, 0x55, 0x4e, 0x2b, 0xb6, 0x00, 0x57, 0x99, 0x00, 0x0a, 0x2b, 0x10, 0x0a, 0xb6, 0x00, 0x5b,
                        0x57, 0x2b, 0x2d, 0xb6, 0x00, 0x5f, 0x10, 0x3a, 0xb6, 0x00, 0x5b, 0x2a, 0xb4, 0x00, 0x1c, 0x2d, 0xb6, 0x00, 0x62, 0xc0,
                        0x00, 0x55, 0xb6, 0x00, 0x5f, 0x57, 0xa7, 0xff, 0xc6, 0xbb, 0x00, 0x66, 0x59, 0xbb, 0x00, 0x68, 0x59, 0x2a, 0xb4, 0x00,
                        0x2a, 0x2a, 0xb4, 0x00, 0x15, 0x2b, 0xb6, 0x00, 0x6a, 0x2a, 0xb4, 0x00, 0x01, 0xb8, 0x00, 0x6e, 0xb7, 0x00, 0x72, 0xb7,
                        0x00, 0x75, 0x4e, 0x2a, 0x2d, 0xb6, 0x00, 0x78, 0xb5, 0x00, 0x7b, 0x2a, 0x2d, 0xb6, 0x00, 0x7e, 0xb5, 0x00, 0x81, 0x2d,
                        0xb6, 0x00, 0x78, 0x36, 0x04, 0x03, 0x36, 0x05, 0x15, 0x05, 0x15, 0x04, 0xa2, 0x00, 0x2d, 0x2d, 0xb6, 0x00, 0x7e, 0x3a,
                        0x06, 0x2d, 0xb6, 0x00, 0x7e, 0x3a, 0x07, 0x2a, 0xb4, 0x00, 0x26, 0x19, 0x06, 0xb6, 0x00, 0x84, 0x2a, 0xb4, 0x00, 0x20,
                        0x19, 0x06, 0xb8, 0x00, 0x88, 0x19, 0x07, 0xb6, 0x00, 0x8c, 0x57, 0x84, 0x05, 0x01, 0xa7, 0xff, 0xd2, 0x2d, 0xb6, 0x00,
                        0x78, 0x36, 0x05, 0x15, 0x05, 0x9c, 0x00, 0x0d, 0xbb, 0x00, 0x31, 0x59, 0x12, 0x90, 0xb7, 0x00, 0x35, 0xbf, 0x2a, 0x15,
                        0x05, 0xbc, 0x08, 0xb5, 0x00, 0x92, 0x2d, 0x2a, 0xb4, 0x00, 0x92, 0xb6, 0x00, 0x95, 0x2a, 0x04, 0xb5, 0x00, 0x41, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 160, descriptor_index: 161, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 294, max_stack: 3, max_locals: 1, code: vec![
                        0x2a, 0xb7, 0x00, 0x98, 0x2a, 0xb7, 0x00, 0x9b, 0xbb, 0x00, 0x68, 0x59, 0x2a, 0xb4, 0x00, 0x92, 0xb7, 0x00, 0x72, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 298, descriptor_index: 299, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 294, max_stack: 3, max_locals: 1, code: vec![
                        0xbb, 0x00, 0x66, 0x59, 0x2a, 0xb6, 0x00, 0x9e, 0xb7, 0x00, 0x75, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 176, descriptor_index: 177, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 294, max_stack: 3, max_locals: 1, code: vec![
                        0x2a, 0xb7, 0x00, 0xa2, 0x2a, 0xb4, 0x00, 0x41, 0x99, 0x00, 0x0d, 0xbb, 0x00, 0x31, 0x59, 0x12, 0xa5, 0xb7, 0x00, 0x35,
                        0xbf, 0xbb, 0x00, 0xa7, 0x59, 0x2a, 0xb7, 0x00, 0xa9, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 300, descriptor_index: 301, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 294, max_stack: 3, max_locals: 1, code: vec![
                        0xbb, 0x00, 0xac, 0x59, 0x2a, 0xb6, 0x00, 0xae, 0xb7, 0x00, 0xb2, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 302, descriptor_index: 12, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 294, max_stack: 2, max_locals: 1, code: vec![
                        0x2a, 0x03, 0xb5, 0x00, 0x0d, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 303, descriptor_index: 109, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 294, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x15, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 304, descriptor_index: 55, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 294, max_stack: 3, max_locals: 2, code: vec![
                        0x2a, 0xb7, 0x00, 0x38, 0x2a, 0xb4, 0x00, 0x41, 0x99, 0x00, 0x0d, 0xbb, 0x00, 0x31, 0x59, 0x12, 0xa5, 0xb7, 0x00, 0x35,
                        0xbf, 0x12, 0x13, 0x2b, 0xb6, 0x00, 0xb5, 0x9a, 0x00, 0x1f, 0x12, 0xb9, 0x2b, 0xb6, 0x00, 0xb5, 0x9a, 0x00, 0x16, 0x12,
                        0xbb, 0x2b, 0xb6, 0x00, 0xb5, 0x9a, 0x00, 0x0d, 0xbb, 0x00, 0xbd, 0x59, 0x12, 0xbf, 0xb7, 0x00, 0xc1, 0xbf, 0x2a, 0x2b,
                        0xb5, 0x00, 0x15, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 305, descriptor_index: 139, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 294, max_stack: 2, max_locals: 2, code: vec![
                        0x2b, 0xc7, 0x00, 0x07, 0x01, 0xa7, 0x00, 0x11, 0x2a, 0xb4, 0x00, 0x1c, 0x2b, 0xb8, 0x00, 0x88, 0xb6, 0x00, 0x62, 0xc0,
                        0x00, 0x55, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 306, descriptor_index: 307, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 294, max_stack: 3, max_locals: 3, code: vec![
                        0x2a, 0xb7, 0x00, 0x38, 0x2a, 0xb4, 0x00, 0x41, 0x99, 0x00, 0x0d, 0xbb, 0x00, 0x31, 0x59, 0x12, 0xa5, 0xb7, 0x00, 0x35,
                        0xbf, 0x2b, 0xc6, 0x00, 0x07, 0x2c, 0xc7, 0x00, 0x0b, 0xbb, 0x00, 0xc2, 0x59, 0xb7, 0x00, 0xc4, 0xbf, 0x2a, 0xb4, 0x00,
                        0x1c, 0x2b, 0xb8, 0x00, 0x88, 0x2c, 0xb6, 0x00, 0x8c, 0x57, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 308, descriptor_index: 90, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 294, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb7, 0x00, 0x9b, 0x2a, 0xb4, 0x00, 0x7b, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 309, descriptor_index: 109, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 294, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb7, 0x00, 0x9b, 0x2a, 0xb4, 0x00, 0x81, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 10, name_index: 138, descriptor_index: 139, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 294, max_stack: 4, max_locals: 3, code: vec![
                        0x2a, 0xb6, 0x00, 0xc5, 0x4c, 0x03, 0x3d, 0x1c, 0x2b, 0xbe, 0xa2, 0x00, 0x12, 0x2b, 0x1c, 0x2b, 0x1c, 0x34, 0xb8, 0x00,
                        0xc9, 0x55, 0x84, 0x02, 0x01, 0xa7, 0xff, 0xee, 0x2b, 0xb8, 0x00, 0xcf, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 226, descriptor_index: 139, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 294, max_stack: 2, max_locals: 2, code: vec![
                        0x2a, 0xb7, 0x00, 0x9b, 0x2b, 0xc7, 0x00, 0x07, 0x01, 0xa7, 0x00, 0x11, 0x2a, 0xb4, 0x00, 0x20, 0x2b, 0xb8, 0x00, 0x88,
                        0xb6, 0x00, 0x62, 0xc0, 0x00, 0x55, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 226, descriptor_index: 292, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 294, max_stack: 4, max_locals: 2, code: vec![
                        0x2a, 0xb7, 0x00, 0x9b, 0x1b, 0x9a, 0x00, 0x23, 0xbb, 0x00, 0x44, 0x59, 0x12, 0xd3, 0xb7, 0x00, 0xd5, 0x2a, 0xb4, 0x00,
                        0x7b, 0xb6, 0x00, 0xd6, 0x10, 0x20, 0xb6, 0x00, 0x5b, 0x2a, 0xb4, 0x00, 0x81, 0xb6, 0x00, 0x5f, 0xb6, 0x00, 0x6a, 0xb0,
                        0x1b, 0x04, 0xa1, 0x00, 0x0e, 0x1b, 0x2a, 0xb4, 0x00, 0x26, 0xb6, 0x00, 0xd9, 0xa4, 0x00, 0x07, 0x01, 0xa7, 0x00, 0x14,
                        0x2a, 0x2a, 0xb4, 0x00, 0x26, 0x1b, 0x04, 0x64, 0xb6, 0x00, 0xdc, 0xc0, 0x00, 0x55, 0xb6, 0x00, 0xe0, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 312, descriptor_index: 292, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 294, max_stack: 3, max_locals: 2, code: vec![
                        0x2a, 0xb7, 0x00, 0x9b, 0x1b, 0x04, 0xa1, 0x00, 0x0e, 0x1b, 0x2a, 0xb4, 0x00, 0x26, 0xb6, 0x00, 0xd9, 0xa4, 0x00, 0x07,
                        0x01, 0xa7, 0x00, 0x10, 0x2a, 0xb4, 0x00, 0x26, 0x1b, 0x04, 0x64, 0xb6, 0x00, 0xdc, 0xc0, 0x00, 0x55, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 313, descriptor_index: 314, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 294, max_stack: 2, max_locals: 5, code: vec![
                        0x2a, 0x2b, 0xb6, 0x00, 0xe0, 0x4e, 0x2d, 0xc7, 0x00, 0x05, 0x1c, 0xac, 0x2d, 0xb8, 0x00, 0xe3, 0xac, 0x3a, 0x04, 0x1c,
                        0xac,
                    ], exception_table: vec![
                        ExceptionHandler { start_pc: 12, end_pc: 16, handler_pc: 17, catch_type: 233 },
                    ], attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 243, descriptor_index: 244, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 294, max_stack: 2, max_locals: 6, code: vec![
                        0x2a, 0x2b, 0xb6, 0x00, 0xe0, 0x3a, 0x04, 0x19, 0x04, 0xc7, 0x00, 0x05, 0x20, 0xad, 0x19, 0x04, 0xb8, 0x00, 0xeb, 0xad,
                        0x3a, 0x05, 0x20, 0xad,
                    ], exception_table: vec![
                        ExceptionHandler { start_pc: 14, end_pc: 19, handler_pc: 20, catch_type: 49 },
                    ], attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 315, descriptor_index: 316, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 294, max_stack: 4, max_locals: 1, code: vec![
                        0x2a, 0x12, 0xef, 0x09, 0xb6, 0x00, 0xf1, 0xad,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 317, descriptor_index: 316, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 294, max_stack: 4, max_locals: 1, code: vec![
                        0x2a, 0x12, 0xf5, 0x09, 0xb6, 0x00, 0xf1, 0xad,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 318, descriptor_index: 316, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 294, max_stack: 4, max_locals: 1, code: vec![
                        0x2a, 0x12, 0xf7, 0x09, 0xb6, 0x00, 0xf1, 0xad,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 319, descriptor_index: 109, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 294, max_stack: 2, max_locals: 2, code: vec![
                        0x2a, 0x12, 0xf9, 0xb6, 0x00, 0xe0, 0xb0, 0x4c, 0x01, 0xb0,
                    ], exception_table: vec![
                        ExceptionHandler { start_pc: 0, end_pc: 6, handler_pc: 7, catch_type: 49 },
                    ], attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 320, descriptor_index: 109, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 294, max_stack: 2, max_locals: 2, code: vec![
                        0x2a, 0x12, 0xfb, 0xb6, 0x00, 0xe0, 0xb0, 0x4c, 0x01, 0xb0,
                    ], exception_table: vec![
                        ExceptionHandler { start_pc: 0, end_pc: 6, handler_pc: 7, catch_type: 49 },
                    ], attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 321, descriptor_index: 316, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 294, max_stack: 2, max_locals: 2, code: vec![
                        0x2a, 0xb7, 0x00, 0x9b, 0x2a, 0xb4, 0x00, 0x92, 0xbe, 0x85, 0xad, 0x4c, 0x14, 0x00, 0xfd, 0xad,
                    ], exception_table: vec![
                        ExceptionHandler { start_pc: 0, end_pc: 10, handler_pc: 11, catch_type: 49 },
                    ], attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 322, descriptor_index: 109, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 294, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x2a, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 323, descriptor_index: 109, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 294, max_stack: 3, max_locals: 2, code: vec![
                        0x2a, 0xb4, 0x00, 0x2a, 0x10, 0x3a, 0xb6, 0x00, 0xff, 0x3c, 0x1b, 0x9c, 0x00, 0x07, 0x01, 0xa7, 0x00, 0x0c, 0x2a, 0xb4,
                        0x00, 0x2a, 0x03, 0x1b, 0xb6, 0x01, 0x03, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 2, name_index: 269, descriptor_index: 90, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 294, max_stack: 2, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x2a, 0x13, 0x01, 0x07, 0xb6, 0x01, 0x09, 0x05, 0x60, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 2, name_index: 276, descriptor_index: 90, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 294, max_stack: 3, max_locals: 4, code: vec![
                        0x2a, 0xb4, 0x00, 0x2a, 0x10, 0x2f, 0x2a, 0xb7, 0x01, 0x0b, 0xb6, 0x01, 0x0e, 0x3c, 0x2a, 0xb4, 0x00, 0x2a, 0x10, 0x3f,
                        0x2a, 0xb7, 0x01, 0x0b, 0xb6, 0x01, 0x0e, 0x3d, 0x1b, 0x9c, 0x00, 0x0d, 0x2a, 0xb4, 0x00, 0x2a, 0xb6, 0x01, 0x11, 0xa7,
                        0x00, 0x04, 0x1b, 0x3e, 0x1c, 0x9b, 0x00, 0x0c, 0x1c, 0x1d, 0xa2, 0x00, 0x07, 0x1c, 0xa7, 0x00, 0x04, 0x1d, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 324, descriptor_index: 109, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 294, max_stack: 3, max_locals: 3, code: vec![
                        0x2a, 0xb4, 0x00, 0x2a, 0x2a, 0xb7, 0x01, 0x0b, 0x2a, 0xb7, 0x01, 0x12, 0xb6, 0x01, 0x03, 0x4c, 0x2b, 0x13, 0x01, 0x15,
                        0xb6, 0x01, 0x17, 0x99, 0x00, 0x19, 0x2b, 0x10, 0x5d, 0xb6, 0x00, 0xff, 0x3d, 0x1c, 0x9c, 0x00, 0x07, 0x2b, 0xa7, 0x00,
                        0x09, 0x2b, 0x04, 0x1c, 0xb6, 0x01, 0x03, 0xb0, 0x2b, 0x10, 0x3a, 0xb6, 0x01, 0x1b, 0x3d, 0x1c, 0x9e, 0x00, 0x0c, 0x2b,
                        0x03, 0x1c, 0xb6, 0x01, 0x03, 0xa7, 0x00, 0x04, 0x2b, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 325, descriptor_index: 90, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 294, max_stack: 3, max_locals: 4, code: vec![
                        0x2a, 0xb4, 0x00, 0x2a, 0x2a, 0xb7, 0x01, 0x0b, 0x2a, 0xb7, 0x01, 0x12, 0xb6, 0x01, 0x03, 0x4c, 0x2b, 0x13, 0x01, 0x15,
                        0xb6, 0x01, 0x17, 0x99, 0x00, 0x0e, 0x2b, 0x10, 0x5d, 0xb6, 0x00, 0xff, 0x04, 0x60, 0xa7, 0x00, 0x09, 0x2b, 0x10, 0x3a,
                        0xb6, 0x01, 0x1b, 0x3d, 0x1c, 0x9b, 0x00, 0x15, 0x1c, 0x2b, 0xb6, 0x01, 0x11, 0xa2, 0x00, 0x0d, 0x2b, 0x1c, 0xb6, 0x01,
                        0x1e, 0x10, 0x3a, 0x9f, 0x00, 0x05, 0x02, 0xac, 0x2b, 0x1c, 0x04, 0x60, 0xb6, 0x01, 0x22, 0xb8, 0x00, 0xe3, 0xac, 0x4e,
                        0x02, 0xac,
                    ], exception_table: vec![
                        ExceptionHandler { start_pc: 68, end_pc: 78, handler_pc: 79, catch_type: 233 },
                    ], attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 326, descriptor_index: 109, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 294, max_stack: 3, max_locals: 5, code: vec![
                        0x2a, 0xb7, 0x01, 0x12, 0x3c, 0x2a, 0xb4, 0x00, 0x2a, 0x10, 0x3f, 0x1b, 0xb6, 0x01, 0x0e, 0x3d, 0x2a, 0xb4, 0x00, 0x2a,
                        0x10, 0x23, 0x1b, 0xb6, 0x01, 0x0e, 0x3e, 0x1c, 0x9c, 0x00, 0x0d, 0x2a, 0xb4, 0x00, 0x2a, 0xb6, 0x01, 0x11, 0xa7, 0x00,
                        0x04, 0x1c, 0x36, 0x04, 0x1d, 0x9b, 0x00, 0x0c, 0x1d, 0x15, 0x04, 0xa2, 0x00, 0x06, 0x1d, 0x36, 0x04, 0x2a, 0xb4, 0x00,
                        0x2a, 0x1b, 0x15, 0x04, 0xb6, 0x01, 0x03, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 327, descriptor_index: 109, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 294, max_stack: 3, max_locals: 2, code: vec![
                        0x2a, 0xb4, 0x00, 0x2a, 0x10, 0x23, 0xb6, 0x00, 0xff, 0x3c, 0x1b, 0x9c, 0x00, 0x07, 0x01, 0xa7, 0x00, 0x0d, 0x2a, 0xb4,
                        0x00, 0x2a, 0x1b, 0x04, 0x60, 0xb6, 0x01, 0x22, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 328, descriptor_index: 109, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 294, max_stack: 3, max_locals: 3, code: vec![
                        0x2a, 0xb4, 0x00, 0x2a, 0x10, 0x3f, 0xb6, 0x00, 0xff, 0x3c, 0x1b, 0x9c, 0x00, 0x05, 0x01, 0xb0, 0x2a, 0xb4, 0x00, 0x2a,
                        0x10, 0x23, 0x1b, 0xb6, 0x01, 0x0e, 0x3d, 0x2a, 0xb4, 0x00, 0x2a, 0x1b, 0x04, 0x60, 0x1c, 0x9c, 0x00, 0x0d, 0x2a, 0xb4,
                        0x00, 0x2a, 0xb6, 0x01, 0x11, 0xa7, 0x00, 0x04, 0x1c, 0xb6, 0x01, 0x03, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 4104, name_index: 329, descriptor_index: 330, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 294, max_stack: 3, max_locals: 2, code: vec![
                        0x2a, 0x2b, 0x5a, 0xb5, 0x00, 0x01, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
            ],
            attributes: Vec::new(),
        },
    );
}
