use super::{
    Attribute, ClassFile, CodeAttribute, Constant, Member, append_bootstrap_classes,
    build_bootstrap_class,
};

pub(super) fn append_image(classes: &mut Vec<ClassFile>) {
    append_bootstrap_classes!(classes;
        // javax/microedition/lcdui/Image
        ClassFile {
            minor_version: 0,
            major_version: 48,
            constant_pool: vec![
                None,
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 3 }),
                Some(Constant::Class { name_index: 4 }),
                Some(Constant::NameAndType { name_index: 5, descriptor_index: 6 }),
                Some(Constant::Utf8("java/lang/Object".to_owned())),
                Some(Constant::Utf8("<init>".to_owned())),
                Some(Constant::Utf8("()V".to_owned())),
                Some(Constant::Fieldref { class_index: 8, name_and_type_index: 9 }),
                Some(Constant::Class { name_index: 10 }),
                Some(Constant::NameAndType { name_index: 11, descriptor_index: 12 }),
                Some(Constant::Utf8("javax/microedition/lcdui/Image".to_owned())),
                Some(Constant::Utf8("width".to_owned())),
                Some(Constant::Utf8("I".to_owned())),
                Some(Constant::Fieldref { class_index: 8, name_and_type_index: 14 }),
                Some(Constant::NameAndType { name_index: 15, descriptor_index: 12 }),
                Some(Constant::Utf8("height".to_owned())),
                Some(Constant::Fieldref { class_index: 8, name_and_type_index: 17 }),
                Some(Constant::NameAndType { name_index: 18, descriptor_index: 19 }),
                Some(Constant::Utf8("pixels".to_owned())),
                Some(Constant::Utf8("[I".to_owned())),
                Some(Constant::Fieldref { class_index: 8, name_and_type_index: 21 }),
                Some(Constant::NameAndType { name_index: 22, descriptor_index: 23 }),
                Some(Constant::Utf8("mutable".to_owned())),
                Some(Constant::Utf8("Z".to_owned())),
                Some(Constant::Methodref { class_index: 8, name_and_type_index: 25 }),
                Some(Constant::NameAndType { name_index: 26, descriptor_index: 27 }),
                Some(Constant::Utf8("checkSize".to_owned())),
                Some(Constant::Utf8("(II)V".to_owned())),
                Some(Constant::Methodref { class_index: 8, name_and_type_index: 29 }),
                Some(Constant::NameAndType { name_index: 30, descriptor_index: 31 }),
                Some(Constant::Utf8("createMutablePixels".to_owned())),
                Some(Constant::Utf8("(II)[I".to_owned())),
                Some(Constant::Methodref { class_index: 8, name_and_type_index: 33 }),
                Some(Constant::NameAndType { name_index: 5, descriptor_index: 34 }),
                Some(Constant::Utf8("(II[IZ)V".to_owned())),
                Some(Constant::Class { name_index: 36 }),
                Some(Constant::Utf8("java/lang/IllegalArgumentException".to_owned())),
                Some(Constant::Methodref { class_index: 35, name_and_type_index: 3 }),
                Some(Constant::Methodref { class_index: 8, name_and_type_index: 39 }),
                Some(Constant::NameAndType { name_index: 40, descriptor_index: 41 }),
                Some(Constant::Utf8("copyPixels".to_owned())),
                Some(Constant::Utf8("([IIIZ)[I".to_owned())),
                Some(Constant::Class { name_index: 43 }),
                Some(Constant::Utf8("java/lang/NullPointerException".to_owned())),
                Some(Constant::Methodref { class_index: 42, name_and_type_index: 3 }),
                Some(Constant::Methodref { class_index: 8, name_and_type_index: 46 }),
                Some(Constant::NameAndType { name_index: 47, descriptor_index: 48 }),
                Some(Constant::Utf8("decodePng".to_owned())),
                Some(Constant::Utf8("([BII)[I".to_owned())),
                Some(Constant::Methodref { class_index: 8, name_and_type_index: 50 }),
                Some(Constant::NameAndType { name_index: 51, descriptor_index: 52 }),
                Some(Constant::Utf8("createImage".to_owned())),
                Some(Constant::Utf8("([BII)Ljavax/microedition/lcdui/Image;".to_owned())),
                Some(Constant::Methodref { class_index: 8, name_and_type_index: 54 }),
                Some(Constant::NameAndType { name_index: 55, descriptor_index: 56 }),
                Some(Constant::Utf8("readResource".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;)[B".to_owned())),
                Some(Constant::Class { name_index: 58 }),
                Some(Constant::Utf8("java/io/IOException".to_owned())),
                Some(Constant::Methodref { class_index: 57, name_and_type_index: 3 }),
                Some(Constant::Methodref { class_index: 8, name_and_type_index: 61 }),
                Some(Constant::NameAndType { name_index: 51, descriptor_index: 62 }),
                Some(Constant::Utf8("([B)Ljavax/microedition/lcdui/Image;".to_owned())),
                Some(Constant::Integer(4194304)),
                Some(Constant::Class { name_index: 65 }),
                Some(Constant::Utf8("java/lang/IllegalStateException".to_owned())),
                Some(Constant::Methodref { class_index: 64, name_and_type_index: 3 }),
                Some(Constant::Class { name_index: 68 }),
                Some(Constant::Utf8("javax/microedition/lcdui/Graphics".to_owned())),
                Some(Constant::Methodref { class_index: 67, name_and_type_index: 70 }),
                Some(Constant::NameAndType { name_index: 5, descriptor_index: 71 }),
                Some(Constant::Utf8("(Ljavax/microedition/lcdui/Image;)V".to_owned())),
                Some(Constant::Class { name_index: 73 }),
                Some(Constant::Utf8("java/lang/ArrayIndexOutOfBoundsException".to_owned())),
                Some(Constant::Methodref { class_index: 72, name_and_type_index: 3 }),
                Some(Constant::Methodref { class_index: 8, name_and_type_index: 76 }),
                Some(Constant::NameAndType { name_index: 77, descriptor_index: 78 }),
                Some(Constant::Utf8("getRGBPixels".to_owned())),
                Some(Constant::Utf8("([IIIIIII)V".to_owned())),
                Some(Constant::Utf8("Code".to_owned())),
                Some(Constant::Utf8("LineNumberTable".to_owned())),
                Some(Constant::Utf8("(II)Ljavax/microedition/lcdui/Image;".to_owned())),
                Some(Constant::Utf8("createRGBImage".to_owned())),
                Some(Constant::Utf8("([IIIZ)Ljavax/microedition/lcdui/Image;".to_owned())),
                Some(Constant::Utf8("StackMapTable".to_owned())),
                Some(Constant::Class { name_index: 19 }),
                Some(Constant::Utf8("(Ljava/lang/String;)Ljavax/microedition/lcdui/Image;".to_owned())),
                Some(Constant::Class { name_index: 88 }),
                Some(Constant::Utf8("[B".to_owned())),
                Some(Constant::Utf8("Exceptions".to_owned())),
                Some(Constant::Utf8("getWidth".to_owned())),
                Some(Constant::Utf8("()I".to_owned())),
                Some(Constant::Utf8("getHeight".to_owned())),
                Some(Constant::Utf8("isMutable".to_owned())),
                Some(Constant::Utf8("()Z".to_owned())),
                Some(Constant::Utf8("getGraphics".to_owned())),
                Some(Constant::Utf8("()Ljavax/microedition/lcdui/Graphics;".to_owned())),
                Some(Constant::Utf8("getRGB".to_owned())),
                Some(Constant::Utf8("SourceFile".to_owned())),
                Some(Constant::Utf8("generated_bootstrap.rs".to_owned())),
            ],
            access_flags: 49,
            this_class: 8,
            super_class: 2,
            interfaces: vec![],
            fields: vec![
                Member { access_flags: 16, name_index: 11, descriptor_index: 12, attributes: Vec::new() },
                Member { access_flags: 16, name_index: 15, descriptor_index: 12, attributes: Vec::new() },
                Member { access_flags: 16, name_index: 18, descriptor_index: 19, attributes: Vec::new() },
                Member { access_flags: 16, name_index: 22, descriptor_index: 23, attributes: Vec::new() },
            ],
            methods: vec![
                Member { access_flags: 2, name_index: 5, descriptor_index: 34, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 79, max_stack: 2, max_locals: 5, code: vec![
                        0x2a, 0xb7, 0x00, 0x01, 0x2a, 0x1b, 0xb5, 0x00, 0x07, 0x2a, 0x1c, 0xb5, 0x00, 0x0d, 0x2a, 0x2d, 0xb5, 0x00, 0x10, 0x2a,
                        0x15, 0x04, 0xb5, 0x00, 0x14, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 9, name_index: 51, descriptor_index: 81, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 79, max_stack: 6, max_locals: 2, code: vec![
                        0x1a, 0x1b, 0xb8, 0x00, 0x18, 0xbb, 0x00, 0x08, 0x59, 0x1a, 0x1b, 0x1a, 0x1b, 0xb8, 0x00, 0x1c, 0x04, 0xb7, 0x00, 0x20,
                        0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 9, name_index: 82, descriptor_index: 83, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 79, max_stack: 8, max_locals: 4, code: vec![
                        0x1b, 0x1c, 0xb8, 0x00, 0x18, 0x2a, 0xc6, 0x00, 0x0b, 0x2a, 0xbe, 0x1b, 0x1c, 0x68, 0xa2, 0x00, 0x0b, 0xbb, 0x00, 0x23,
                        0x59, 0xb7, 0x00, 0x25, 0xbf, 0xbb, 0x00, 0x08, 0x59, 0x1b, 0x1c, 0x2a, 0x03, 0x1b, 0x1c, 0x68, 0x1d, 0xb8, 0x00, 0x26,
                        0x03, 0xb7, 0x00, 0x20, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 9, name_index: 51, descriptor_index: 52, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 79, max_stack: 6, max_locals: 7, code: vec![
                        0x2a, 0xc7, 0x00, 0x0b, 0xbb, 0x00, 0x2a, 0x59, 0xb7, 0x00, 0x2c, 0xbf, 0x2a, 0x1b, 0x1c, 0xb8, 0x00, 0x2d, 0x4e, 0x2d,
                        0x03, 0x2e, 0x36, 0x04, 0x2d, 0x04, 0x2e, 0x36, 0x05, 0x15, 0x04, 0x15, 0x05, 0xb8, 0x00, 0x18, 0x2d, 0xbe, 0x15, 0x04,
                        0x15, 0x05, 0x68, 0x05, 0x60, 0x9f, 0x00, 0x0b, 0xbb, 0x00, 0x23, 0x59, 0xb7, 0x00, 0x25, 0xbf, 0x2d, 0x05, 0x15, 0x04,
                        0x15, 0x05, 0x68, 0x04, 0xb8, 0x00, 0x26, 0x3a, 0x06, 0xbb, 0x00, 0x08, 0x59, 0x15, 0x04, 0x15, 0x05, 0x19, 0x06, 0x03,
                        0xb7, 0x00, 0x20, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 9, name_index: 51, descriptor_index: 62, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 79, max_stack: 3, max_locals: 1, code: vec![
                        0x2a, 0x03, 0x2a, 0xbe, 0xb8, 0x00, 0x31, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 9, name_index: 51, descriptor_index: 86, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 79, max_stack: 2, max_locals: 2, code: vec![
                        0x2a, 0xc7, 0x00, 0x0b, 0xbb, 0x00, 0x2a, 0x59, 0xb7, 0x00, 0x2c, 0xbf, 0x2a, 0xb8, 0x00, 0x35, 0x4c, 0x2b, 0xc7, 0x00,
                        0x0b, 0xbb, 0x00, 0x39, 0x59, 0xb7, 0x00, 0x3b, 0xbf, 0x2b, 0xb8, 0x00, 0x3c, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 266, name_index: 55, descriptor_index: 56, attributes: Vec::new() },
                Member { access_flags: 266, name_index: 47, descriptor_index: 48, attributes: Vec::new() },
                Member { access_flags: 266, name_index: 30, descriptor_index: 31, attributes: Vec::new() },
                Member { access_flags: 266, name_index: 40, descriptor_index: 41, attributes: Vec::new() },
                Member { access_flags: 10, name_index: 26, descriptor_index: 27, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 79, max_stack: 3, max_locals: 2, code: vec![
                        0x1a, 0x9e, 0x00, 0x1d, 0x1b, 0x9e, 0x00, 0x19, 0x1a, 0x11, 0x10, 0x00, 0xa3, 0x00, 0x12, 0x1b, 0x11, 0x10, 0x00, 0xa3,
                        0x00, 0x0b, 0x1a, 0x12, 0x3f, 0x1b, 0x6c, 0xa4, 0x00, 0x0b, 0xbb, 0x00, 0x23, 0x59, 0xb7, 0x00, 0x25, 0xbf, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 90, descriptor_index: 91, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 79, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x07, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 92, descriptor_index: 91, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 79, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x0d, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 93, descriptor_index: 94, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 79, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x14, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 95, descriptor_index: 96, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 79, max_stack: 3, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x14, 0x9a, 0x00, 0x0b, 0xbb, 0x00, 0x40, 0x59, 0xb7, 0x00, 0x42, 0xbf, 0xbb, 0x00, 0x43, 0x59, 0x2a,
                        0xb7, 0x00, 0x45, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 97, descriptor_index: 78, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 79, max_stack: 8, max_locals: 14, code: vec![
                        0x2b, 0xc6, 0x00, 0x2f, 0x15, 0x06, 0x9e, 0x00, 0x2a, 0x15, 0x07, 0x9e, 0x00, 0x25, 0x15, 0x04, 0x9b, 0x00, 0x20, 0x15,
                        0x05, 0x9b, 0x00, 0x1b, 0x15, 0x04, 0x2a, 0xb4, 0x00, 0x07, 0x15, 0x06, 0x64, 0xa3, 0x00, 0x0f, 0x15, 0x05, 0x2a, 0xb4,
                        0x00, 0x0d, 0x15, 0x07, 0x64, 0xa4, 0x00, 0x0b, 0xbb, 0x00, 0x23, 0x59, 0xb7, 0x00, 0x25, 0xbf, 0x1c, 0x85, 0x15, 0x07,
                        0x04, 0x64, 0x85, 0x1d, 0x85, 0x69, 0x61, 0x37, 0x08, 0x1c, 0x85, 0x16, 0x08, 0x94, 0x9c, 0x00, 0x08, 0x1c, 0x85, 0xa7,
                        0x00, 0x05, 0x16, 0x08, 0x37, 0x0a, 0x1c, 0x85, 0x16, 0x08, 0x94, 0x9e, 0x00, 0x08, 0x1c, 0x85, 0xa7, 0x00, 0x05, 0x16,
                        0x08, 0x15, 0x06, 0x85, 0x61, 0x37, 0x0c, 0x16, 0x0a, 0x09, 0x94, 0x9b, 0x00, 0x0c, 0x16, 0x0c, 0x2b, 0xbe, 0x85, 0x94,
                        0x9e, 0x00, 0x0b, 0xbb, 0x00, 0x48, 0x59, 0xb7, 0x00, 0x4a, 0xbf, 0x2a, 0x2b, 0x1c, 0x1d, 0x15, 0x04, 0x15, 0x05, 0x15,
                        0x06, 0x15, 0x07, 0xb7, 0x00, 0x4b, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 258, name_index: 77, descriptor_index: 78, attributes: Vec::new() },
            ],
            attributes: Vec::new(),
        },
    );
}
