use super::{
    Attribute, ClassFile, CodeAttribute, Constant, Member, append_bootstrap_classes,
    build_bootstrap_class,
};

pub(super) fn append_items(classes: &mut Vec<ClassFile>) {
    append_bootstrap_classes!(classes;
        // javax/microedition/lcdui/ImageItem
        ClassFile {
            minor_version: 0,
            major_version: 48,
            constant_pool: vec![
                None,
                Some(Constant::Class { name_index: 2 }),
                Some(Constant::Utf8("javax/microedition/lcdui/Item".to_owned())),
                Some(Constant::Methodref { class_index: 4, name_and_type_index: 5 }),
                Some(Constant::Class { name_index: 6 }),
                Some(Constant::NameAndType { name_index: 7, descriptor_index: 8 }),
                Some(Constant::Utf8("javax/microedition/lcdui/ImageItem".to_owned())),
                Some(Constant::Utf8("<init>".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;Ljavax/microedition/lcdui/Image;ILjava/lang/String;I)V".to_owned())),
                Some(Constant::Methodref { class_index: 1, name_and_type_index: 10 }),
                Some(Constant::NameAndType { name_index: 7, descriptor_index: 11 }),
                Some(Constant::Utf8("(Ljava/lang/String;)V".to_owned())),
                Some(Constant::Class { name_index: 13 }),
                Some(Constant::Utf8("java/lang/IllegalArgumentException".to_owned())),
                Some(Constant::Methodref { class_index: 12, name_and_type_index: 15 }),
                Some(Constant::NameAndType { name_index: 7, descriptor_index: 16 }),
                Some(Constant::Utf8("()V".to_owned())),
                Some(Constant::Fieldref { class_index: 4, name_and_type_index: 18 }),
                Some(Constant::NameAndType { name_index: 19, descriptor_index: 20 }),
                Some(Constant::Utf8("image".to_owned())),
                Some(Constant::Utf8("Ljavax/microedition/lcdui/Image;".to_owned())),
                Some(Constant::Fieldref { class_index: 4, name_and_type_index: 22 }),
                Some(Constant::NameAndType { name_index: 23, descriptor_index: 24 }),
                Some(Constant::Utf8("altText".to_owned())),
                Some(Constant::Utf8("Ljava/lang/String;".to_owned())),
                Some(Constant::Fieldref { class_index: 4, name_and_type_index: 26 }),
                Some(Constant::NameAndType { name_index: 27, descriptor_index: 28 }),
                Some(Constant::Utf8("appearance".to_owned())),
                Some(Constant::Utf8("I".to_owned())),
                Some(Constant::Methodref { class_index: 4, name_and_type_index: 30 }),
                Some(Constant::NameAndType { name_index: 31, descriptor_index: 32 }),
                Some(Constant::Utf8("setLayout".to_owned())),
                Some(Constant::Utf8("(I)V".to_owned())),
                Some(Constant::Methodref { class_index: 4, name_and_type_index: 34 }),
                Some(Constant::NameAndType { name_index: 35, descriptor_index: 16 }),
                Some(Constant::Utf8("invalidate".to_owned())),
                Some(Constant::Methodref { class_index: 4, name_and_type_index: 37 }),
                Some(Constant::NameAndType { name_index: 38, descriptor_index: 39 }),
                Some(Constant::Utf8("getLabel".to_owned())),
                Some(Constant::Utf8("()Ljava/lang/String;".to_owned())),
                Some(Constant::Methodref { class_index: 41, name_and_type_index: 42 }),
                Some(Constant::Class { name_index: 43 }),
                Some(Constant::NameAndType { name_index: 44, descriptor_index: 45 }),
                Some(Constant::Utf8("javax/microedition/lcdui/Font".to_owned())),
                Some(Constant::Utf8("getDefaultFont".to_owned())),
                Some(Constant::Utf8("()Ljavax/microedition/lcdui/Font;".to_owned())),
                Some(Constant::Methodref { class_index: 41, name_and_type_index: 47 }),
                Some(Constant::NameAndType { name_index: 48, descriptor_index: 49 }),
                Some(Constant::Utf8("getHeight".to_owned())),
                Some(Constant::Utf8("()I".to_owned())),
                Some(Constant::Methodref { class_index: 51, name_and_type_index: 47 }),
                Some(Constant::Class { name_index: 52 }),
                Some(Constant::Utf8("javax/microedition/lcdui/Image".to_owned())),
                Some(Constant::Methodref { class_index: 51, name_and_type_index: 54 }),
                Some(Constant::NameAndType { name_index: 55, descriptor_index: 49 }),
                Some(Constant::Utf8("getWidth".to_owned())),
                Some(Constant::Methodref { class_index: 57, name_and_type_index: 58 }),
                Some(Constant::Class { name_index: 59 }),
                Some(Constant::NameAndType { name_index: 60, descriptor_index: 32 }),
                Some(Constant::Utf8("javax/microedition/lcdui/Graphics".to_owned())),
                Some(Constant::Utf8("setColor".to_owned())),
                Some(Constant::Methodref { class_index: 57, name_and_type_index: 62 }),
                Some(Constant::NameAndType { name_index: 63, descriptor_index: 64 }),
                Some(Constant::Utf8("drawString".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;III)V".to_owned())),
                Some(Constant::Methodref { class_index: 57, name_and_type_index: 66 }),
                Some(Constant::NameAndType { name_index: 67, descriptor_index: 68 }),
                Some(Constant::Utf8("drawImage".to_owned())),
                Some(Constant::Utf8("(Ljavax/microedition/lcdui/Image;III)V".to_owned())),
                Some(Constant::Integer(2379678)),
                Some(Constant::Methodref { class_index: 4, name_and_type_index: 71 }),
                Some(Constant::NameAndType { name_index: 72, descriptor_index: 73 }),
                Some(Constant::Utf8("__height".to_owned())),
                Some(Constant::Utf8("(I)I".to_owned())),
                Some(Constant::Methodref { class_index: 57, name_and_type_index: 75 }),
                Some(Constant::NameAndType { name_index: 76, descriptor_index: 77 }),
                Some(Constant::Utf8("drawRect".to_owned())),
                Some(Constant::Utf8("(IIII)V".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;Ljavax/microedition/lcdui/Image;ILjava/lang/String;)V".to_owned())),
                Some(Constant::Utf8("Code".to_owned())),
                Some(Constant::Utf8("LineNumberTable".to_owned())),
                Some(Constant::Utf8("StackMapTable".to_owned())),
                Some(Constant::Class { name_index: 83 }),
                Some(Constant::Utf8("java/lang/String".to_owned())),
                Some(Constant::Utf8("getImage".to_owned())),
                Some(Constant::Utf8("()Ljavax/microedition/lcdui/Image;".to_owned())),
                Some(Constant::Utf8("setImage".to_owned())),
                Some(Constant::Utf8("(Ljavax/microedition/lcdui/Image;)V".to_owned())),
                Some(Constant::Utf8("getAltText".to_owned())),
                Some(Constant::Utf8("setAltText".to_owned())),
                Some(Constant::Utf8("getAppearanceMode".to_owned())),
                Some(Constant::Utf8("__minimumWidth".to_owned())),
                Some(Constant::Utf8("__paint".to_owned())),
                Some(Constant::Utf8("(Ljavax/microedition/lcdui/Graphics;IIIZ)V".to_owned())),
                Some(Constant::Utf8("SourceFile".to_owned())),
                Some(Constant::Utf8("generated_bootstrap.rs".to_owned())),
            ],
            access_flags: 33,
            this_class: 4,
            super_class: 1,
            interfaces: vec![],
            fields: vec![
                Member { access_flags: 2, name_index: 19, descriptor_index: 20, attributes: Vec::new() },
                Member { access_flags: 2, name_index: 23, descriptor_index: 24, attributes: Vec::new() },
                Member { access_flags: 2, name_index: 27, descriptor_index: 28, attributes: Vec::new() },
            ],
            methods: vec![
                Member { access_flags: 1, name_index: 7, descriptor_index: 78, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 79, max_stack: 6, max_locals: 5, code: vec![
                        0x2a, 0x2b, 0x2c, 0x1d, 0x19, 0x04, 0x03, 0xb7, 0x00, 0x03, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 7, descriptor_index: 8, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 79, max_stack: 2, max_locals: 6, code: vec![
                        0x2a, 0x2b, 0xb7, 0x00, 0x09, 0x15, 0x05, 0x9b, 0x00, 0x09, 0x15, 0x05, 0x05, 0xa4, 0x00, 0x0b, 0xbb, 0x00, 0x0c, 0x59,
                        0xb7, 0x00, 0x0e, 0xbf, 0x2a, 0x2c, 0xb5, 0x00, 0x11, 0x2a, 0x19, 0x04, 0xb5, 0x00, 0x15, 0x2a, 0x15, 0x05, 0xb5, 0x00,
                        0x19, 0x2a, 0x1d, 0xb6, 0x00, 0x1d, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 84, descriptor_index: 85, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 79, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x11, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 86, descriptor_index: 87, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 79, max_stack: 2, max_locals: 2, code: vec![
                        0x2a, 0x2b, 0xb5, 0x00, 0x11, 0x2a, 0xb6, 0x00, 0x21, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 88, descriptor_index: 39, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 79, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x15, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 89, descriptor_index: 11, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 79, max_stack: 2, max_locals: 2, code: vec![
                        0x2a, 0x2b, 0xb5, 0x00, 0x15, 0x2a, 0xb6, 0x00, 0x21, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 90, descriptor_index: 49, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 79, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x19, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 0, name_index: 72, descriptor_index: 73, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 79, max_stack: 2, max_locals: 2, code: vec![
                        0x2a, 0xb6, 0x00, 0x24, 0xc7, 0x00, 0x07, 0x03, 0xa7, 0x00, 0x0b, 0xb8, 0x00, 0x28, 0xb6, 0x00, 0x2e, 0x04, 0x60, 0x2a,
                        0xb4, 0x00, 0x11, 0xc7, 0x00, 0x0c, 0xb8, 0x00, 0x28, 0xb6, 0x00, 0x2e, 0xa7, 0x00, 0x0a, 0x2a, 0xb4, 0x00, 0x11, 0xb6,
                        0x00, 0x32, 0x60, 0x07, 0x60, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 0, name_index: 91, descriptor_index: 49, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 79, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x11, 0xc7, 0x00, 0x07, 0x04, 0xa7, 0x00, 0x0a, 0x2a, 0xb4, 0x00, 0x11, 0xb6, 0x00, 0x35, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 0, name_index: 92, descriptor_index: 93, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 79, max_stack: 6, max_locals: 6, code: vec![
                        0x2b, 0x03, 0xb6, 0x00, 0x38, 0x2a, 0xb6, 0x00, 0x24, 0xc6, 0x00, 0x1a, 0x2b, 0x2a, 0xb6, 0x00, 0x24, 0x1c, 0x1d, 0x10,
                        0x14, 0xb6, 0x00, 0x3d, 0x1d, 0xb8, 0x00, 0x28, 0xb6, 0x00, 0x2e, 0x04, 0x60, 0x60, 0x3e, 0x2a, 0xb4, 0x00, 0x11, 0xc6,
                        0x00, 0x12, 0x2b, 0x2a, 0xb4, 0x00, 0x11, 0x1c, 0x1d, 0x10, 0x14, 0xb6, 0x00, 0x41, 0xa7, 0x00, 0x16, 0x2a, 0xb4, 0x00,
                        0x15, 0xc6, 0x00, 0x0f, 0x2b, 0x2a, 0xb4, 0x00, 0x15, 0x1c, 0x1d, 0x10, 0x14, 0xb6, 0x00, 0x3d, 0x15, 0x05, 0x99, 0x00,
                        0x24, 0x2a, 0xb4, 0x00, 0x19, 0x99, 0x00, 0x1d, 0x2b, 0x12, 0x45, 0xb6, 0x00, 0x38, 0x2b, 0x1c, 0x05, 0x64, 0x1d, 0x05,
                        0x64, 0x15, 0x04, 0x05, 0x60, 0x2a, 0x15, 0x04, 0xb6, 0x00, 0x46, 0xb6, 0x00, 0x4a, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
            ],
            attributes: Vec::new(),
        },
        // javax/microedition/lcdui/Item
        ClassFile {
            minor_version: 0,
            major_version: 48,
            constant_pool: vec![
                None,
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 3 }),
                Some(Constant::Class { name_index: 4 }),
                Some(Constant::NameAndType { name_index: 5, descriptor_index: 6 }),
                Some(Constant::Utf8("java/lang/Object".to_owned())),
                Some(Constant::Utf8("<init>".to_owned())),
                Some(Constant::Utf8("()V".to_owned())),
                Some(Constant::Fieldref { class_index: 8, name_and_type_index: 9 }),
                Some(Constant::Class { name_index: 10 }),
                Some(Constant::NameAndType { name_index: 11, descriptor_index: 12 }),
                Some(Constant::Utf8("javax/microedition/lcdui/Item".to_owned())),
                Some(Constant::Utf8("preferredWidth".to_owned())),
                Some(Constant::Utf8("I".to_owned())),
                Some(Constant::Fieldref { class_index: 8, name_and_type_index: 14 }),
                Some(Constant::NameAndType { name_index: 15, descriptor_index: 12 }),
                Some(Constant::Utf8("preferredHeight".to_owned())),
                Some(Constant::Class { name_index: 17 }),
                Some(Constant::Utf8("java/util/Vector".to_owned())),
                Some(Constant::Methodref { class_index: 16, name_and_type_index: 3 }),
                Some(Constant::Fieldref { class_index: 8, name_and_type_index: 20 }),
                Some(Constant::NameAndType { name_index: 21, descriptor_index: 22 }),
                Some(Constant::Utf8("commands".to_owned())),
                Some(Constant::Utf8("Ljava/util/Vector;".to_owned())),
                Some(Constant::Fieldref { class_index: 8, name_and_type_index: 24 }),
                Some(Constant::NameAndType { name_index: 25, descriptor_index: 26 }),
                Some(Constant::Utf8("label".to_owned())),
                Some(Constant::Utf8("Ljava/lang/String;".to_owned())),
                Some(Constant::Methodref { class_index: 8, name_and_type_index: 28 }),
                Some(Constant::NameAndType { name_index: 29, descriptor_index: 6 }),
                Some(Constant::Utf8("invalidate".to_owned())),
                Some(Constant::Fieldref { class_index: 8, name_and_type_index: 31 }),
                Some(Constant::NameAndType { name_index: 32, descriptor_index: 12 }),
                Some(Constant::Utf8("layout".to_owned())),
                Some(Constant::Class { name_index: 34 }),
                Some(Constant::Utf8("java/lang/NullPointerException".to_owned())),
                Some(Constant::Methodref { class_index: 33, name_and_type_index: 3 }),
                Some(Constant::Methodref { class_index: 16, name_and_type_index: 37 }),
                Some(Constant::NameAndType { name_index: 38, descriptor_index: 39 }),
                Some(Constant::Utf8("contains".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/Object;)Z".to_owned())),
                Some(Constant::Methodref { class_index: 16, name_and_type_index: 41 }),
                Some(Constant::NameAndType { name_index: 42, descriptor_index: 43 }),
                Some(Constant::Utf8("addElement".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/Object;)V".to_owned())),
                Some(Constant::Methodref { class_index: 16, name_and_type_index: 45 }),
                Some(Constant::NameAndType { name_index: 46, descriptor_index: 39 }),
                Some(Constant::Utf8("removeElement".to_owned())),
                Some(Constant::Fieldref { class_index: 8, name_and_type_index: 48 }),
                Some(Constant::NameAndType { name_index: 49, descriptor_index: 50 }),
                Some(Constant::Utf8("defaultCommand".to_owned())),
                Some(Constant::Utf8("Ljavax/microedition/lcdui/Command;".to_owned())),
                Some(Constant::Methodref { class_index: 8, name_and_type_index: 52 }),
                Some(Constant::NameAndType { name_index: 53, descriptor_index: 54 }),
                Some(Constant::Utf8("addCommand".to_owned())),
                Some(Constant::Utf8("(Ljavax/microedition/lcdui/Command;)V".to_owned())),
                Some(Constant::Fieldref { class_index: 8, name_and_type_index: 56 }),
                Some(Constant::NameAndType { name_index: 57, descriptor_index: 58 }),
                Some(Constant::Utf8("listener".to_owned())),
                Some(Constant::Utf8("Ljavax/microedition/lcdui/ItemCommandListener;".to_owned())),
                Some(Constant::Methodref { class_index: 8, name_and_type_index: 60 }),
                Some(Constant::NameAndType { name_index: 61, descriptor_index: 62 }),
                Some(Constant::Utf8("__minimumWidth".to_owned())),
                Some(Constant::Utf8("()I".to_owned())),
                Some(Constant::Methodref { class_index: 8, name_and_type_index: 64 }),
                Some(Constant::NameAndType { name_index: 65, descriptor_index: 66 }),
                Some(Constant::Utf8("__height".to_owned())),
                Some(Constant::Utf8("(I)I".to_owned())),
                Some(Constant::Class { name_index: 68 }),
                Some(Constant::Utf8("java/lang/IllegalArgumentException".to_owned())),
                Some(Constant::Methodref { class_index: 67, name_and_type_index: 3 }),
                Some(Constant::InterfaceMethodref { class_index: 71, name_and_type_index: 72 }),
                Some(Constant::Class { name_index: 73 }),
                Some(Constant::NameAndType { name_index: 74, descriptor_index: 75 }),
                Some(Constant::Utf8("javax/microedition/lcdui/ItemCommandListener".to_owned())),
                Some(Constant::Utf8("commandAction".to_owned())),
                Some(Constant::Utf8("(Ljavax/microedition/lcdui/Command;Ljavax/microedition/lcdui/Item;)V".to_owned())),
                Some(Constant::Fieldref { class_index: 8, name_and_type_index: 77 }),
                Some(Constant::NameAndType { name_index: 78, descriptor_index: 79 }),
                Some(Constant::Utf8("owner".to_owned())),
                Some(Constant::Utf8("Ljavax/microedition/lcdui/Form;".to_owned())),
                Some(Constant::Methodref { class_index: 81, name_and_type_index: 82 }),
                Some(Constant::Class { name_index: 83 }),
                Some(Constant::NameAndType { name_index: 84, descriptor_index: 85 }),
                Some(Constant::Utf8("javax/microedition/lcdui/Form".to_owned())),
                Some(Constant::Utf8("__notifyStateChanged".to_owned())),
                Some(Constant::Utf8("(Ljavax/microedition/lcdui/Item;)V".to_owned())),
                Some(Constant::Methodref { class_index: 81, name_and_type_index: 87 }),
                Some(Constant::NameAndType { name_index: 88, descriptor_index: 6 }),
                Some(Constant::Utf8("__itemInvalidated".to_owned())),
                Some(Constant::Utf8("LAYOUT_DEFAULT".to_owned())),
                Some(Constant::Utf8("ConstantValue".to_owned())),
                Some(Constant::Integer(0)),
                Some(Constant::Utf8("LAYOUT_LEFT".to_owned())),
                Some(Constant::Integer(1)),
                Some(Constant::Utf8("LAYOUT_RIGHT".to_owned())),
                Some(Constant::Integer(2)),
                Some(Constant::Utf8("LAYOUT_CENTER".to_owned())),
                Some(Constant::Integer(3)),
                Some(Constant::Utf8("LAYOUT_TOP".to_owned())),
                Some(Constant::Integer(16)),
                Some(Constant::Utf8("LAYOUT_BOTTOM".to_owned())),
                Some(Constant::Integer(32)),
                Some(Constant::Utf8("LAYOUT_VCENTER".to_owned())),
                Some(Constant::Integer(48)),
                Some(Constant::Utf8("LAYOUT_NEWLINE_BEFORE".to_owned())),
                Some(Constant::Integer(256)),
                Some(Constant::Utf8("LAYOUT_NEWLINE_AFTER".to_owned())),
                Some(Constant::Integer(512)),
                Some(Constant::Utf8("LAYOUT_SHRINK".to_owned())),
                Some(Constant::Integer(1024)),
                Some(Constant::Utf8("LAYOUT_EXPAND".to_owned())),
                Some(Constant::Integer(2048)),
                Some(Constant::Utf8("LAYOUT_VSHRINK".to_owned())),
                Some(Constant::Integer(4096)),
                Some(Constant::Utf8("LAYOUT_VEXPAND".to_owned())),
                Some(Constant::Integer(8192)),
                Some(Constant::Utf8("PLAIN".to_owned())),
                Some(Constant::Utf8("HYPERLINK".to_owned())),
                Some(Constant::Utf8("BUTTON".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;)V".to_owned())),
                Some(Constant::Utf8("Code".to_owned())),
                Some(Constant::Utf8("LineNumberTable".to_owned())),
                Some(Constant::Utf8("getLabel".to_owned())),
                Some(Constant::Utf8("()Ljava/lang/String;".to_owned())),
                Some(Constant::Utf8("setLabel".to_owned())),
                Some(Constant::Utf8("getLayout".to_owned())),
                Some(Constant::Utf8("setLayout".to_owned())),
                Some(Constant::Utf8("(I)V".to_owned())),
                Some(Constant::Utf8("StackMapTable".to_owned())),
                Some(Constant::Utf8("removeCommand".to_owned())),
                Some(Constant::Utf8("setDefaultCommand".to_owned())),
                Some(Constant::Utf8("setItemCommandListener".to_owned())),
                Some(Constant::Utf8("(Ljavax/microedition/lcdui/ItemCommandListener;)V".to_owned())),
                Some(Constant::Utf8("getPreferredWidth".to_owned())),
                Some(Constant::Utf8("getPreferredHeight".to_owned())),
                Some(Constant::Utf8("getMinimumWidth".to_owned())),
                Some(Constant::Utf8("getMinimumHeight".to_owned())),
                Some(Constant::Utf8("setPreferredSize".to_owned())),
                Some(Constant::Utf8("(II)V".to_owned())),
                Some(Constant::Utf8("__activate".to_owned())),
                Some(Constant::Utf8("notifyStateChanged".to_owned())),
                Some(Constant::Utf8("__key".to_owned())),
                Some(Constant::Utf8("__paint".to_owned())),
                Some(Constant::Utf8("(Ljavax/microedition/lcdui/Graphics;IIIZ)V".to_owned())),
                Some(Constant::Utf8("SourceFile".to_owned())),
                Some(Constant::Utf8("generated_bootstrap.rs".to_owned())),
            ],
            access_flags: 1057,
            this_class: 8,
            super_class: 2,
            interfaces: vec![],
            fields: vec![
                Member { access_flags: 25, name_index: 89, descriptor_index: 12, attributes: vec![
                    Attribute::Raw { name_index: 90, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x5b,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 92, descriptor_index: 12, attributes: vec![
                    Attribute::Raw { name_index: 90, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x5d,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 94, descriptor_index: 12, attributes: vec![
                    Attribute::Raw { name_index: 90, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x5f,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 96, descriptor_index: 12, attributes: vec![
                    Attribute::Raw { name_index: 90, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x61,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 98, descriptor_index: 12, attributes: vec![
                    Attribute::Raw { name_index: 90, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x63,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 100, descriptor_index: 12, attributes: vec![
                    Attribute::Raw { name_index: 90, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x65,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 102, descriptor_index: 12, attributes: vec![
                    Attribute::Raw { name_index: 90, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x67,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 104, descriptor_index: 12, attributes: vec![
                    Attribute::Raw { name_index: 90, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x69,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 106, descriptor_index: 12, attributes: vec![
                    Attribute::Raw { name_index: 90, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x6b,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 108, descriptor_index: 12, attributes: vec![
                    Attribute::Raw { name_index: 90, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x6d,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 110, descriptor_index: 12, attributes: vec![
                    Attribute::Raw { name_index: 90, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x6f,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 112, descriptor_index: 12, attributes: vec![
                    Attribute::Raw { name_index: 90, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x71,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 114, descriptor_index: 12, attributes: vec![
                    Attribute::Raw { name_index: 90, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x73,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 116, descriptor_index: 12, attributes: vec![
                    Attribute::Raw { name_index: 90, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x5b,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 117, descriptor_index: 12, attributes: vec![
                    Attribute::Raw { name_index: 90, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x5d,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 118, descriptor_index: 12, attributes: vec![
                    Attribute::Raw { name_index: 90, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x5f,
                    ] },
                ] },
                Member { access_flags: 2, name_index: 25, descriptor_index: 26, attributes: Vec::new() },
                Member { access_flags: 2, name_index: 32, descriptor_index: 12, attributes: Vec::new() },
                Member { access_flags: 2, name_index: 11, descriptor_index: 12, attributes: Vec::new() },
                Member { access_flags: 2, name_index: 15, descriptor_index: 12, attributes: Vec::new() },
                Member { access_flags: 18, name_index: 21, descriptor_index: 22, attributes: Vec::new() },
                Member { access_flags: 2, name_index: 49, descriptor_index: 50, attributes: Vec::new() },
                Member { access_flags: 2, name_index: 57, descriptor_index: 58, attributes: Vec::new() },
                Member { access_flags: 0, name_index: 78, descriptor_index: 79, attributes: Vec::new() },
            ],
            methods: vec![
                Member { access_flags: 0, name_index: 5, descriptor_index: 119, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 120, max_stack: 3, max_locals: 2, code: vec![
                        0x2a, 0xb7, 0x00, 0x01, 0x2a, 0x02, 0xb5, 0x00, 0x07, 0x2a, 0x02, 0xb5, 0x00, 0x0d, 0x2a, 0xbb, 0x00, 0x10, 0x59, 0xb7,
                        0x00, 0x12, 0xb5, 0x00, 0x13, 0x2a, 0x2b, 0xb5, 0x00, 0x17, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 122, descriptor_index: 123, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 120, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x17, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 124, descriptor_index: 119, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 120, max_stack: 2, max_locals: 2, code: vec![
                        0x2a, 0x2b, 0xb5, 0x00, 0x17, 0x2a, 0xb6, 0x00, 0x1b, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 125, descriptor_index: 62, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 120, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x1e, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 126, descriptor_index: 127, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 120, max_stack: 2, max_locals: 2, code: vec![
                        0x2a, 0x1b, 0xb5, 0x00, 0x1e, 0x2a, 0xb6, 0x00, 0x1b, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 53, descriptor_index: 54, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 120, max_stack: 2, max_locals: 2, code: vec![
                        0x2b, 0xc7, 0x00, 0x0b, 0xbb, 0x00, 0x21, 0x59, 0xb7, 0x00, 0x23, 0xbf, 0x2a, 0xb4, 0x00, 0x13, 0x2b, 0xb6, 0x00, 0x24,
                        0x9a, 0x00, 0x0b, 0x2a, 0xb4, 0x00, 0x13, 0x2b, 0xb6, 0x00, 0x28, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 129, descriptor_index: 54, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 120, max_stack: 2, max_locals: 2, code: vec![
                        0x2a, 0xb4, 0x00, 0x13, 0x2b, 0xb6, 0x00, 0x2c, 0x57, 0x2a, 0xb4, 0x00, 0x2f, 0x2b, 0xa6, 0x00, 0x08, 0x2a, 0x01, 0xb5,
                        0x00, 0x2f, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 130, descriptor_index: 54, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 120, max_stack: 2, max_locals: 2, code: vec![
                        0x2b, 0xc6, 0x00, 0x08, 0x2a, 0x2b, 0xb6, 0x00, 0x33, 0x2a, 0x2b, 0xb5, 0x00, 0x2f, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 131, descriptor_index: 132, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 120, max_stack: 2, max_locals: 2, code: vec![
                        0x2a, 0x2b, 0xb5, 0x00, 0x37, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 133, descriptor_index: 62, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 120, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x07, 0x9c, 0x00, 0x0a, 0x2a, 0xb6, 0x00, 0x3b, 0xa7, 0x00, 0x07, 0x2a, 0xb4, 0x00, 0x07, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 134, descriptor_index: 62, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 120, max_stack: 2, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x0d, 0x9c, 0x00, 0x0d, 0x2a, 0x11, 0x00, 0xe6, 0xb6, 0x00, 0x3f, 0xa7, 0x00, 0x07, 0x2a, 0xb4, 0x00,
                        0x0d, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 135, descriptor_index: 62, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 120, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb6, 0x00, 0x3b, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 136, descriptor_index: 62, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 120, max_stack: 2, max_locals: 1, code: vec![
                        0x2a, 0x11, 0x00, 0xe6, 0xb6, 0x00, 0x3f, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 137, descriptor_index: 138, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 120, max_stack: 2, max_locals: 3, code: vec![
                        0x1b, 0x02, 0xa1, 0x00, 0x08, 0x1c, 0x02, 0xa2, 0x00, 0x0b, 0xbb, 0x00, 0x43, 0x59, 0xb7, 0x00, 0x45, 0xbf, 0x2a, 0x1b,
                        0xb5, 0x00, 0x07, 0x2a, 0x1c, 0xb5, 0x00, 0x0d, 0x2a, 0xb6, 0x00, 0x1b, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 0, name_index: 139, descriptor_index: 6, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 120, max_stack: 3, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x2f, 0xc6, 0x00, 0x18, 0x2a, 0xb4, 0x00, 0x37, 0xc6, 0x00, 0x11, 0x2a, 0xb4, 0x00, 0x37, 0x2a, 0xb4,
                        0x00, 0x2f, 0x2a, 0xb9, 0x00, 0x46, 0x03, 0x00, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 20, name_index: 140, descriptor_index: 6, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 120, max_stack: 2, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x4c, 0xc6, 0x00, 0x0b, 0x2a, 0xb4, 0x00, 0x4c, 0x2a, 0xb6, 0x00, 0x50, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 0, name_index: 141, descriptor_index: 127, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 120, max_stack: 0, max_locals: 2, code: vec![
                        0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 0, name_index: 61, descriptor_index: 62, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 120, max_stack: 1, max_locals: 1, code: vec![
                        0x04, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1024, name_index: 65, descriptor_index: 66, attributes: Vec::new() },
                Member { access_flags: 1024, name_index: 142, descriptor_index: 143, attributes: Vec::new() },
                Member { access_flags: 16, name_index: 29, descriptor_index: 6, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 120, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x4c, 0xc6, 0x00, 0x0a, 0x2a, 0xb4, 0x00, 0x4c, 0xb6, 0x00, 0x56, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
            ],
            attributes: Vec::new(),
        },
        // javax/microedition/lcdui/ItemCommandListener
        ClassFile {
            minor_version: 0,
            major_version: 48,
            constant_pool: vec![
                None,
                Some(Constant::Class { name_index: 2 }),
                Some(Constant::Utf8("javax/microedition/lcdui/ItemCommandListener".to_owned())),
                Some(Constant::Class { name_index: 4 }),
                Some(Constant::Utf8("java/lang/Object".to_owned())),
                Some(Constant::Utf8("commandAction".to_owned())),
                Some(Constant::Utf8("(Ljavax/microedition/lcdui/Command;Ljavax/microedition/lcdui/Item;)V".to_owned())),
                Some(Constant::Utf8("SourceFile".to_owned())),
                Some(Constant::Utf8("generated_bootstrap.rs".to_owned())),
            ],
            access_flags: 1537,
            this_class: 1,
            super_class: 3,
            interfaces: vec![],
            fields: Vec::new(),
            methods: vec![
                Member { access_flags: 1025, name_index: 5, descriptor_index: 6, attributes: Vec::new() },
            ],
            attributes: Vec::new(),
        },
        // javax/microedition/lcdui/ItemStateListener
        ClassFile {
            minor_version: 0,
            major_version: 48,
            constant_pool: vec![
                None,
                Some(Constant::Class { name_index: 2 }),
                Some(Constant::Utf8("javax/microedition/lcdui/ItemStateListener".to_owned())),
                Some(Constant::Class { name_index: 4 }),
                Some(Constant::Utf8("java/lang/Object".to_owned())),
                Some(Constant::Utf8("itemStateChanged".to_owned())),
                Some(Constant::Utf8("(Ljavax/microedition/lcdui/Item;)V".to_owned())),
                Some(Constant::Utf8("SourceFile".to_owned())),
                Some(Constant::Utf8("generated_bootstrap.rs".to_owned())),
            ],
            access_flags: 1537,
            this_class: 1,
            super_class: 3,
            interfaces: vec![],
            fields: Vec::new(),
            methods: vec![
                Member { access_flags: 1025, name_index: 5, descriptor_index: 6, attributes: Vec::new() },
            ],
            attributes: Vec::new(),
        },
    );
}
