use super::{
    Attribute, ClassFile, CodeAttribute, Constant, ExceptionHandler, Member,
    append_bootstrap_classes, build_bootstrap_class,
};

use super::super::choice_flags::ChoiceFlags;

const FLAGS: ChoiceFlags = ChoiceFlags {
    code_name: 190,
    entries: 10,
    size: 46,
    entry: 50,
    kind: 28,
    cursor: 81,
    selected: 97,
    is_selected: 101,
    invalidate: 71,
    null_exception: (39, 41),
    argument_exception: (25, 27),
};

pub(super) fn append_lists_screens(classes: &mut Vec<ClassFile>) {
    append_bootstrap_classes!(classes;
        // javax/microedition/lcdui/List
        ClassFile {
            minor_version: 0,
            major_version: 48,
            constant_pool: vec![
                None,
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 3 }),
                Some(Constant::Class { name_index: 4 }),
                Some(Constant::NameAndType { name_index: 5, descriptor_index: 6 }),
                Some(Constant::Utf8("javax/microedition/lcdui/Screen".to_owned())),
                Some(Constant::Utf8("<init>".to_owned())),
                Some(Constant::Utf8("()V".to_owned())),
                Some(Constant::Class { name_index: 8 }),
                Some(Constant::Utf8("java/util/Vector".to_owned())),
                Some(Constant::Methodref { class_index: 7, name_and_type_index: 3 }),
                Some(Constant::Fieldref { class_index: 11, name_and_type_index: 12 }),
                Some(Constant::Class { name_index: 13 }),
                Some(Constant::NameAndType { name_index: 14, descriptor_index: 15 }),
                Some(Constant::Utf8("javax/microedition/lcdui/List".to_owned())),
                Some(Constant::Utf8("entries".to_owned())),
                Some(Constant::Utf8("Ljava/util/Vector;".to_owned())),
                Some(Constant::Fieldref { class_index: 11, name_and_type_index: 17 }),
                Some(Constant::NameAndType { name_index: 18, descriptor_index: 19 }),
                Some(Constant::Utf8("SELECT_COMMAND".to_owned())),
                Some(Constant::Utf8("Ljavax/microedition/lcdui/Command;".to_owned())),
                Some(Constant::Fieldref { class_index: 11, name_and_type_index: 21 }),
                Some(Constant::NameAndType { name_index: 22, descriptor_index: 19 }),
                Some(Constant::Utf8("selectCommand".to_owned())),
                Some(Constant::Class { name_index: 24 }),
                Some(Constant::Utf8("javax/microedition/lcdui/Choice".to_owned())),
                Some(Constant::Class { name_index: 26 }),
                Some(Constant::Utf8("java/lang/IllegalArgumentException".to_owned())),
                Some(Constant::Methodref { class_index: 25, name_and_type_index: 3 }),
                Some(Constant::Fieldref { class_index: 11, name_and_type_index: 29 }),
                Some(Constant::NameAndType { name_index: 30, descriptor_index: 31 }),
                Some(Constant::Utf8("type".to_owned())),
                Some(Constant::Utf8("I".to_owned())),
                Some(Constant::Methodref { class_index: 11, name_and_type_index: 33 }),
                Some(Constant::NameAndType { name_index: 34, descriptor_index: 35 }),
                Some(Constant::Utf8("setTitle".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;)V".to_owned())),
                Some(Constant::Methodref { class_index: 11, name_and_type_index: 37 }),
                Some(Constant::NameAndType { name_index: 5, descriptor_index: 38 }),
                Some(Constant::Utf8("(Ljava/lang/String;I)V".to_owned())),
                Some(Constant::Class { name_index: 40 }),
                Some(Constant::Utf8("java/lang/NullPointerException".to_owned())),
                Some(Constant::Methodref { class_index: 39, name_and_type_index: 3 }),
                Some(Constant::Methodref { class_index: 11, name_and_type_index: 43 }),
                Some(Constant::NameAndType { name_index: 44, descriptor_index: 45 }),
                Some(Constant::Utf8("append".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;Ljavax/microedition/lcdui/Image;)I".to_owned())),
                Some(Constant::Methodref { class_index: 7, name_and_type_index: 47 }),
                Some(Constant::NameAndType { name_index: 48, descriptor_index: 49 }),
                Some(Constant::Utf8("size".to_owned())),
                Some(Constant::Utf8("()I".to_owned())),
                Some(Constant::Methodref { class_index: 11, name_and_type_index: 51 }),
                Some(Constant::NameAndType { name_index: 52, descriptor_index: 53 }),
                Some(Constant::Utf8("entry".to_owned())),
                Some(Constant::Utf8("(I)Ljavax/microedition/lcdui/ChoiceData;".to_owned())),
                Some(Constant::Fieldref { class_index: 55, name_and_type_index: 56 }),
                Some(Constant::Class { name_index: 57 }),
                Some(Constant::NameAndType { name_index: 58, descriptor_index: 59 }),
                Some(Constant::Utf8("javax/microedition/lcdui/ChoiceData".to_owned())),
                Some(Constant::Utf8("text".to_owned())),
                Some(Constant::Utf8("Ljava/lang/String;".to_owned())),
                Some(Constant::Fieldref { class_index: 55, name_and_type_index: 61 }),
                Some(Constant::NameAndType { name_index: 62, descriptor_index: 63 }),
                Some(Constant::Utf8("image".to_owned())),
                Some(Constant::Utf8("Ljavax/microedition/lcdui/Image;".to_owned())),
                Some(Constant::Methodref { class_index: 55, name_and_type_index: 65 }),
                Some(Constant::NameAndType { name_index: 5, descriptor_index: 66 }),
                Some(Constant::Utf8("(Ljava/lang/String;Ljavax/microedition/lcdui/Image;)V".to_owned())),
                Some(Constant::Methodref { class_index: 7, name_and_type_index: 68 }),
                Some(Constant::NameAndType { name_index: 69, descriptor_index: 70 }),
                Some(Constant::Utf8("addElement".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/Object;)V".to_owned())),
                Some(Constant::Methodref { class_index: 11, name_and_type_index: 72 }),
                Some(Constant::NameAndType { name_index: 73, descriptor_index: 6 }),
                Some(Constant::Utf8("__requestRepaint".to_owned())),
                Some(Constant::Class { name_index: 75 }),
                Some(Constant::Utf8("java/lang/IndexOutOfBoundsException".to_owned())),
                Some(Constant::Methodref { class_index: 74, name_and_type_index: 3 }),
                Some(Constant::Methodref { class_index: 7, name_and_type_index: 78 }),
                Some(Constant::NameAndType { name_index: 79, descriptor_index: 80 }),
                Some(Constant::Utf8("insertElementAt".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/Object;I)V".to_owned())),
                Some(Constant::Fieldref { class_index: 11, name_and_type_index: 82 }),
                Some(Constant::NameAndType { name_index: 83, descriptor_index: 31 }),
                Some(Constant::Utf8("cursor".to_owned())),
                Some(Constant::Methodref { class_index: 7, name_and_type_index: 85 }),
                Some(Constant::NameAndType { name_index: 86, descriptor_index: 87 }),
                Some(Constant::Utf8("removeElementAt".to_owned())),
                Some(Constant::Utf8("(I)V".to_owned())),
                Some(Constant::Methodref { class_index: 11, name_and_type_index: 89 }),
                Some(Constant::NameAndType { name_index: 90, descriptor_index: 6 }),
                Some(Constant::Utf8("normalize".to_owned())),
                Some(Constant::Methodref { class_index: 7, name_and_type_index: 92 }),
                Some(Constant::NameAndType { name_index: 93, descriptor_index: 6 }),
                Some(Constant::Utf8("removeAllElements".to_owned())),
                Some(Constant::Methodref { class_index: 7, name_and_type_index: 95 }),
                Some(Constant::NameAndType { name_index: 96, descriptor_index: 80 }),
                Some(Constant::Utf8("setElementAt".to_owned())),
                Some(Constant::Fieldref { class_index: 55, name_and_type_index: 98 }),
                Some(Constant::NameAndType { name_index: 99, descriptor_index: 100 }),
                Some(Constant::Utf8("selected".to_owned())),
                Some(Constant::Utf8("Z".to_owned())),
                Some(Constant::Methodref { class_index: 11, name_and_type_index: 102 }),
                Some(Constant::NameAndType { name_index: 103, descriptor_index: 104 }),
                Some(Constant::Utf8("isSelected".to_owned())),
                Some(Constant::Utf8("(I)Z".to_owned())),
                Some(Constant::Fieldref { class_index: 11, name_and_type_index: 106 }),
                Some(Constant::NameAndType { name_index: 107, descriptor_index: 31 }),
                Some(Constant::Utf8("fitPolicy".to_owned())),
                Some(Constant::Fieldref { class_index: 55, name_and_type_index: 109 }),
                Some(Constant::NameAndType { name_index: 110, descriptor_index: 111 }),
                Some(Constant::Utf8("font".to_owned())),
                Some(Constant::Utf8("Ljavax/microedition/lcdui/Font;".to_owned())),
                Some(Constant::Methodref { class_index: 113, name_and_type_index: 114 }),
                Some(Constant::Class { name_index: 115 }),
                Some(Constant::NameAndType { name_index: 116, descriptor_index: 117 }),
                Some(Constant::Utf8("javax/microedition/lcdui/Font".to_owned())),
                Some(Constant::Utf8("getDefaultFont".to_owned())),
                Some(Constant::Utf8("()Ljavax/microedition/lcdui/Font;".to_owned())),
                Some(Constant::Methodref { class_index: 11, name_and_type_index: 119 }),
                Some(Constant::NameAndType { name_index: 120, descriptor_index: 6 }),
                Some(Constant::Utf8("ensureVisible".to_owned())),
                Some(Constant::Methodref { class_index: 11, name_and_type_index: 122 }),
                Some(Constant::NameAndType { name_index: 123, descriptor_index: 124 }),
                Some(Constant::Utf8("addCommand".to_owned())),
                Some(Constant::Utf8("(Ljavax/microedition/lcdui/Command;)V".to_owned())),
                Some(Constant::Methodref { class_index: 11, name_and_type_index: 126 }),
                Some(Constant::NameAndType { name_index: 127, descriptor_index: 87 }),
                Some(Constant::Utf8("__dispatchSoftKey".to_owned())),
                Some(Constant::Methodref { class_index: 11, name_and_type_index: 129 }),
                Some(Constant::NameAndType { name_index: 130, descriptor_index: 124 }),
                Some(Constant::Utf8("removeCommand".to_owned())),
                Some(Constant::Methodref { class_index: 11, name_and_type_index: 132 }),
                Some(Constant::NameAndType { name_index: 133, descriptor_index: 134 }),
                Some(Constant::Utf8("getFont".to_owned())),
                Some(Constant::Utf8("(I)Ljavax/microedition/lcdui/Font;".to_owned())),
                Some(Constant::Methodref { class_index: 113, name_and_type_index: 136 }),
                Some(Constant::NameAndType { name_index: 137, descriptor_index: 49 }),
                Some(Constant::Utf8("getHeight".to_owned())),
                Some(Constant::Methodref { class_index: 139, name_and_type_index: 140 }),
                Some(Constant::Class { name_index: 141 }),
                Some(Constant::NameAndType { name_index: 142, descriptor_index: 143 }),
                Some(Constant::Utf8("javax/microedition/lcdui/Graphics".to_owned())),
                Some(Constant::Utf8("setFont".to_owned())),
                Some(Constant::Utf8("(Ljavax/microedition/lcdui/Font;)V".to_owned())),
                Some(Constant::Integer(2379678)),
                Some(Constant::Methodref { class_index: 139, name_and_type_index: 146 }),
                Some(Constant::NameAndType { name_index: 147, descriptor_index: 87 }),
                Some(Constant::Utf8("setColor".to_owned())),
                Some(Constant::Methodref { class_index: 139, name_and_type_index: 149 }),
                Some(Constant::NameAndType { name_index: 150, descriptor_index: 151 }),
                Some(Constant::Utf8("fillRect".to_owned())),
                Some(Constant::Utf8("(IIII)V".to_owned())),
                Some(Constant::Integer(16777215)),
                Some(Constant::String { string_index: 154 }),
                Some(Constant::Utf8("[x] ".to_owned())),
                Some(Constant::String { string_index: 156 }),
                Some(Constant::Utf8("[ ] ".to_owned())),
                Some(Constant::String { string_index: 158 }),
                Some(Constant::Utf8("".to_owned())),
                Some(Constant::Methodref { class_index: 160, name_and_type_index: 161 }),
                Some(Constant::Class { name_index: 162 }),
                Some(Constant::NameAndType { name_index: 163, descriptor_index: 164 }),
                Some(Constant::Utf8("java/lang/String".to_owned())),
                Some(Constant::Utf8("concat".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;)Ljava/lang/String;".to_owned())),
                Some(Constant::Methodref { class_index: 139, name_and_type_index: 166 }),
                Some(Constant::NameAndType { name_index: 167, descriptor_index: 168 }),
                Some(Constant::Utf8("drawString".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;III)V".to_owned())),
                Some(Constant::Methodref { class_index: 139, name_and_type_index: 170 }),
                Some(Constant::NameAndType { name_index: 171, descriptor_index: 172 }),
                Some(Constant::Utf8("drawImage".to_owned())),
                Some(Constant::Utf8("(Ljavax/microedition/lcdui/Image;III)V".to_owned())),
                Some(Constant::Methodref { class_index: 7, name_and_type_index: 174 }),
                Some(Constant::NameAndType { name_index: 175, descriptor_index: 176 }),
                Some(Constant::Utf8("elementAt".to_owned())),
                Some(Constant::Utf8("(I)Ljava/lang/Object;".to_owned())),
                Some(Constant::Methodref { class_index: 11, name_and_type_index: 178 }),
                Some(Constant::NameAndType { name_index: 179, descriptor_index: 49 }),
                Some(Constant::Utf8("__getScroll".to_owned())),
                Some(Constant::Methodref { class_index: 11, name_and_type_index: 181 }),
                Some(Constant::NameAndType { name_index: 182, descriptor_index: 87 }),
                Some(Constant::Utf8("__setScroll".to_owned())),
                Some(Constant::Class { name_index: 184 }),
                Some(Constant::Utf8("javax/microedition/lcdui/Command".to_owned())),
                Some(Constant::String { string_index: 186 }),
                Some(Constant::Utf8("Select".to_owned())),
                Some(Constant::Methodref { class_index: 183, name_and_type_index: 188 }),
                Some(Constant::NameAndType { name_index: 5, descriptor_index: 189 }),
                Some(Constant::Utf8("(Ljava/lang/String;II)V".to_owned())),
                Some(Constant::Utf8("Code".to_owned())),
                Some(Constant::Utf8("LineNumberTable".to_owned())),
                Some(Constant::Utf8("StackMapTable".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;I[Ljava/lang/String;[Ljavax/microedition/lcdui/Image;)V".to_owned())),
                Some(Constant::Class { name_index: 195 }),
                Some(Constant::Utf8("[Ljava/lang/String;".to_owned())),
                Some(Constant::Class { name_index: 197 }),
                Some(Constant::Utf8("[Ljavax/microedition/lcdui/Image;".to_owned())),
                Some(Constant::Class { name_index: 199 }),
                Some(Constant::Utf8("javax/microedition/lcdui/Image".to_owned())),
                Some(Constant::Utf8("getString".to_owned())),
                Some(Constant::Utf8("(I)Ljava/lang/String;".to_owned())),
                Some(Constant::Utf8("getImage".to_owned())),
                Some(Constant::Utf8("(I)Ljavax/microedition/lcdui/Image;".to_owned())),
                Some(Constant::Utf8("insert".to_owned())),
                Some(Constant::Utf8("(ILjava/lang/String;Ljavax/microedition/lcdui/Image;)V".to_owned())),
                Some(Constant::Utf8("delete".to_owned())),
                Some(Constant::Utf8("deleteAll".to_owned())),
                Some(Constant::Utf8("set".to_owned())),
                Some(Constant::Utf8("getSelectedIndex".to_owned())),
                Some(Constant::Utf8("getSelectedFlags".to_owned())),
                Some(Constant::Utf8("([Z)I".to_owned())),
                Some(Constant::Class { name_index: 213 }),
                Some(Constant::Utf8("[Z".to_owned())),
                Some(Constant::Utf8("setSelectedIndex".to_owned())),
                Some(Constant::Utf8("(IZ)V".to_owned())),
                Some(Constant::Utf8("setSelectedFlags".to_owned())),
                Some(Constant::Utf8("([Z)V".to_owned())),
                Some(Constant::Utf8("setFitPolicy".to_owned())),
                Some(Constant::Utf8("getFitPolicy".to_owned())),
                Some(Constant::Utf8("(ILjavax/microedition/lcdui/Font;)V".to_owned())),
                Some(Constant::Utf8("setSelectCommand".to_owned())),
                Some(Constant::Utf8("__keyPressed".to_owned())),
                Some(Constant::Utf8("__paintContent".to_owned())),
                Some(Constant::Utf8("(Ljavax/microedition/lcdui/Graphics;II)V".to_owned())),
                Some(Constant::Utf8("<clinit>".to_owned())),
                Some(Constant::Utf8("SourceFile".to_owned())),
                Some(Constant::Utf8("generated_bootstrap.rs".to_owned())),
            ],
            access_flags: 33,
            this_class: 11,
            super_class: 2,
            interfaces: vec![23],
            fields: vec![
                Member { access_flags: 25, name_index: 18, descriptor_index: 19, attributes: Vec::new() },
                Member { access_flags: 18, name_index: 30, descriptor_index: 31, attributes: Vec::new() },
                Member { access_flags: 18, name_index: 14, descriptor_index: 15, attributes: Vec::new() },
                Member { access_flags: 2, name_index: 83, descriptor_index: 31, attributes: Vec::new() },
                Member { access_flags: 2, name_index: 107, descriptor_index: 31, attributes: Vec::new() },
                Member { access_flags: 2, name_index: 22, descriptor_index: 19, attributes: Vec::new() },
            ],
            methods: vec![
                Member { access_flags: 1, name_index: 5, descriptor_index: 38, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 190, max_stack: 3, max_locals: 3, code: vec![
                        0x2a, 0xb7, 0x00, 0x01, 0x2a, 0xbb, 0x00, 0x07, 0x59, 0xb7, 0x00, 0x09, 0xb5, 0x00, 0x0a, 0x2a, 0xb2, 0x00, 0x10, 0xb5,
                        0x00, 0x14, 0x1c, 0x04, 0x9f, 0x00, 0x15, 0x1c, 0x05, 0x9f, 0x00, 0x10, 0x1c, 0x06, 0x9f, 0x00, 0x0b, 0xbb, 0x00, 0x19,
                        0x59, 0xb7, 0x00, 0x1b, 0xbf, 0x2a, 0x1c, 0xb5, 0x00, 0x1c, 0x2a, 0x2b, 0xb6, 0x00, 0x20, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 5, descriptor_index: 193, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 190, max_stack: 4, max_locals: 6, code: vec![
                        0x2a, 0x2b, 0x1c, 0xb7, 0x00, 0x24, 0x2d, 0xc7, 0x00, 0x0b, 0xbb, 0x00, 0x27, 0x59, 0xb7, 0x00, 0x29, 0xbf, 0x19, 0x04,
                        0xc6, 0x00, 0x13, 0x19, 0x04, 0xbe, 0x2d, 0xbe, 0x9f, 0x00, 0x0b, 0xbb, 0x00, 0x19, 0x59, 0xb7, 0x00, 0x1b, 0xbf, 0x03,
                        0x36, 0x05, 0x15, 0x05, 0x2d, 0xbe, 0xa2, 0x00, 0x20, 0x2a, 0x2d, 0x15, 0x05, 0x32, 0x19, 0x04, 0xc7, 0x00, 0x07, 0x01,
                        0xa7, 0x00, 0x08, 0x19, 0x04, 0x15, 0x05, 0x32, 0xb6, 0x00, 0x2a, 0x57, 0x84, 0x05, 0x01, 0xa7, 0xff, 0xdf, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 48, descriptor_index: 49, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 190, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x0a, 0xb6, 0x00, 0x2e, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 200, descriptor_index: 201, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 190, max_stack: 2, max_locals: 2, code: vec![
                        0x2a, 0x1b, 0xb7, 0x00, 0x32, 0xb4, 0x00, 0x36, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 202, descriptor_index: 203, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 190, max_stack: 2, max_locals: 2, code: vec![
                        0x2a, 0x1b, 0xb7, 0x00, 0x32, 0xb4, 0x00, 0x3c, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 44, descriptor_index: 45, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 190, max_stack: 5, max_locals: 3, code: vec![
                        0x2a, 0xb4, 0x00, 0x0a, 0xbb, 0x00, 0x37, 0x59, 0x2b, 0x2c, 0xb7, 0x00, 0x40, 0xb6, 0x00, 0x43, 0x2a, 0xb6, 0x00, 0x47,
                        0x2a, 0xb4, 0x00, 0x0a, 0xb6, 0x00, 0x2e, 0x04, 0x64, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 204, descriptor_index: 205, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 190, max_stack: 5, max_locals: 4, code: vec![
                        0x1b, 0x9b, 0x00, 0x0e, 0x1b, 0x2a, 0xb4, 0x00, 0x0a, 0xb6, 0x00, 0x2e, 0xa4, 0x00, 0x0b, 0xbb, 0x00, 0x4a, 0x59, 0xb7,
                        0x00, 0x4c, 0xbf, 0x2a, 0xb4, 0x00, 0x0a, 0xbb, 0x00, 0x37, 0x59, 0x2c, 0x2d, 0xb7, 0x00, 0x40, 0x1b, 0xb6, 0x00, 0x4d,
                        0x1b, 0x2a, 0xb4, 0x00, 0x51, 0xa3, 0x00, 0x18, 0x2a, 0xb4, 0x00, 0x0a, 0xb6, 0x00, 0x2e, 0x04, 0xa4, 0x00, 0x0d, 0x2a,
                        0x59, 0xb4, 0x00, 0x51, 0x04, 0x60, 0xb5, 0x00, 0x51, 0x2a, 0xb6, 0x00, 0x47, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 206, descriptor_index: 87, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 190, max_stack: 2, max_locals: 2, code: vec![
                        0x2a, 0x1b, 0xb7, 0x00, 0x32, 0x57, 0x2a, 0xb4, 0x00, 0x0a, 0x1b, 0xb6, 0x00, 0x54, 0x2a, 0xb7, 0x00, 0x58, 0x2a, 0xb6,
                        0x00, 0x47, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 207, descriptor_index: 6, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 190, max_stack: 2, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x0a, 0xb6, 0x00, 0x5b, 0x2a, 0x03, 0xb5, 0x00, 0x51, 0x2a, 0xb6, 0x00, 0x47, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 208, descriptor_index: 205, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 190, max_stack: 5, max_locals: 4, code: vec![
                        0x2a, 0xb4, 0x00, 0x0a, 0xbb, 0x00, 0x37, 0x59, 0x2c, 0x2d, 0xb7, 0x00, 0x40, 0x1b, 0xb6, 0x00, 0x5e, 0x2a, 0xb6, 0x00,
                        0x47, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 103, descriptor_index: 104, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 190, max_stack: 2, max_locals: 3, code: vec![
                        0x2a, 0x1b, 0xb7, 0x00, 0x32, 0x4d, 0x2a, 0xb4, 0x00, 0x1c, 0x05, 0xa0, 0x00, 0x0a, 0x2c, 0xb4, 0x00, 0x61, 0xa7, 0x00,
                        0x10, 0x1b, 0x2a, 0xb4, 0x00, 0x51, 0xa0, 0x00, 0x07, 0x04, 0xa7, 0x00, 0x04, 0x03, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 209, descriptor_index: 49, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 190, max_stack: 2, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x1c, 0x05, 0x9f, 0x00, 0x0d, 0x2a, 0xb4, 0x00, 0x0a, 0xb6, 0x00, 0x2e, 0x9a, 0x00, 0x07, 0x02, 0xa7,
                        0x00, 0x07, 0x2a, 0xb4, 0x00, 0x51, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 210, descriptor_index: 211, attributes: vec![
                    Attribute::Code(FLAGS.get()),
                ] },
                Member { access_flags: 1, name_index: 214, descriptor_index: 215, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 190, max_stack: 2, max_locals: 4, code: vec![
                        0x2a, 0x1b, 0xb7, 0x00, 0x32, 0x4e, 0x2a, 0xb4, 0x00, 0x1c, 0x05, 0xa0, 0x00, 0x0b, 0x2d, 0x1c, 0xb5, 0x00, 0x61, 0xa7,
                        0x00, 0x0c, 0x1c, 0x99, 0x00, 0x08, 0x2a, 0x1b, 0xb5, 0x00, 0x51, 0x2a, 0xb6, 0x00, 0x47, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 216, descriptor_index: 217, attributes: vec![
                    Attribute::Code(FLAGS.set()),
                ] },
                Member { access_flags: 1, name_index: 218, descriptor_index: 87, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 190, max_stack: 2, max_locals: 2, code: vec![
                        0x1b, 0x9b, 0x00, 0x08, 0x1b, 0x05, 0xa4, 0x00, 0x0b, 0xbb, 0x00, 0x19, 0x59, 0xb7, 0x00, 0x1b, 0xbf, 0x2a, 0x1b, 0xb5,
                        0x00, 0x69, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 219, descriptor_index: 49, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 190, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x69, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 142, descriptor_index: 220, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 190, max_stack: 2, max_locals: 3, code: vec![
                        0x2a, 0x1b, 0xb7, 0x00, 0x32, 0x2c, 0xb5, 0x00, 0x6c, 0x2a, 0xb6, 0x00, 0x47, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 133, descriptor_index: 134, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 190, max_stack: 2, max_locals: 3, code: vec![
                        0x2a, 0x1b, 0xb7, 0x00, 0x32, 0xb4, 0x00, 0x6c, 0x4d, 0x2c, 0xc7, 0x00, 0x09, 0xb8, 0x00, 0x70, 0xa7, 0x00, 0x04, 0x2c,
                        0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 221, descriptor_index: 124, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 190, max_stack: 2, max_locals: 2, code: vec![
                        0x2a, 0x2b, 0xb5, 0x00, 0x14, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 0, name_index: 222, descriptor_index: 87, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 190, max_stack: 3, max_locals: 2, code: vec![
                        0x2a, 0xb4, 0x00, 0x0a, 0xb6, 0x00, 0x2e, 0x9a, 0x00, 0x04, 0xb1, 0x1b, 0x02, 0x9f, 0x00, 0x09, 0x1b, 0x10, 0x32, 0xa0,
                        0x00, 0x24, 0x2a, 0x2a, 0xb4, 0x00, 0x51, 0x2a, 0xb4, 0x00, 0x0a, 0xb6, 0x00, 0x2e, 0x60, 0x04, 0x64, 0x2a, 0xb4, 0x00,
                        0x0a, 0xb6, 0x00, 0x2e, 0x70, 0xb5, 0x00, 0x51, 0x2a, 0xb7, 0x00, 0x76, 0xa7, 0x00, 0x7d, 0x1b, 0x10, 0xfe, 0x9f, 0x00,
                        0x09, 0x1b, 0x10, 0x38, 0xa0, 0x00, 0x1c, 0x2a, 0x2a, 0xb4, 0x00, 0x51, 0x04, 0x60, 0x2a, 0xb4, 0x00, 0x0a, 0xb6, 0x00,
                        0x2e, 0x70, 0xb5, 0x00, 0x51, 0x2a, 0xb7, 0x00, 0x76, 0xa7, 0x00, 0x58, 0x1b, 0x10, 0xfb, 0x9f, 0x00, 0x0f, 0x1b, 0x10,
                        0x35, 0x9f, 0x00, 0x09, 0x1b, 0x10, 0x0a, 0xa0, 0x00, 0x46, 0x2a, 0xb4, 0x00, 0x1c, 0x05, 0xa0, 0x00, 0x21, 0x2a, 0x2a,
                        0xb4, 0x00, 0x51, 0xb7, 0x00, 0x32, 0x2a, 0x2a, 0xb4, 0x00, 0x51, 0xb7, 0x00, 0x32, 0xb4, 0x00, 0x61, 0x9a, 0x00, 0x07,
                        0x04, 0xa7, 0x00, 0x04, 0x03, 0xb5, 0x00, 0x61, 0x2a, 0xb4, 0x00, 0x14, 0xc6, 0x00, 0x19, 0x2a, 0x2a, 0xb4, 0x00, 0x14,
                        0xb6, 0x00, 0x79, 0x2a, 0x10, 0xfa, 0xb6, 0x00, 0x7d, 0x2a, 0x2a, 0xb4, 0x00, 0x14, 0xb6, 0x00, 0x80, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 0, name_index: 223, descriptor_index: 224, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 190, max_stack: 5, max_locals: 10, code: vec![
                        0x1c, 0x36, 0x04, 0x03, 0x36, 0x05, 0x15, 0x05, 0x2a, 0xb4, 0x00, 0x0a, 0xb6, 0x00, 0x2e, 0xa2, 0x00, 0xb4, 0x2a, 0x15,
                        0x05, 0xb7, 0x00, 0x32, 0x3a, 0x06, 0x2a, 0x15, 0x05, 0xb6, 0x00, 0x83, 0x3a, 0x07, 0x19, 0x07, 0xb6, 0x00, 0x87, 0x08,
                        0x60, 0x36, 0x08, 0x15, 0x04, 0x15, 0x08, 0x60, 0x9b, 0x00, 0x86, 0x15, 0x04, 0x1d, 0xa2, 0x00, 0x80, 0x2b, 0x19, 0x07,
                        0xb6, 0x00, 0x8a, 0x15, 0x05, 0x2a, 0xb4, 0x00, 0x51, 0xa0, 0x00, 0x1e, 0x2b, 0x12, 0x90, 0xb6, 0x00, 0x91, 0x2b, 0x05,
                        0x15, 0x04, 0x11, 0x00, 0xec, 0x15, 0x08, 0xb6, 0x00, 0x94, 0x2b, 0x12, 0x98, 0xb6, 0x00, 0x91, 0xa7, 0x00, 0x08, 0x2b,
                        0x03, 0xb6, 0x00, 0x91, 0x2a, 0xb4, 0x00, 0x1c, 0x05, 0xa0, 0x00, 0x15, 0x19, 0x06, 0xb4, 0x00, 0x61, 0x99, 0x00, 0x08,
                        0x12, 0x99, 0xa7, 0x00, 0x0a, 0x12, 0x9b, 0xa7, 0x00, 0x05, 0x12, 0x9d, 0x3a, 0x09, 0x2b, 0x19, 0x09, 0x19, 0x06, 0xb4,
                        0x00, 0x36, 0xb6, 0x00, 0x9f, 0x10, 0x07, 0x15, 0x04, 0x05, 0x60, 0x10, 0x14, 0xb6, 0x00, 0xa5, 0x19, 0x06, 0xb4, 0x00,
                        0x3c, 0xc6, 0x00, 0x15, 0x2b, 0x19, 0x06, 0xb4, 0x00, 0x3c, 0x11, 0x00, 0xeb, 0x15, 0x04, 0x05, 0x60, 0x10, 0x18, 0xb6,
                        0x00, 0xa9, 0x15, 0x04, 0x15, 0x08, 0x60, 0x36, 0x04, 0x84, 0x05, 0x01, 0xa7, 0xff, 0x46, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 2, name_index: 52, descriptor_index: 53, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 190, max_stack: 2, max_locals: 2, code: vec![
                        0x2a, 0xb4, 0x00, 0x0a, 0x1b, 0xb6, 0x00, 0xad, 0xc0, 0x00, 0x37, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 2, name_index: 90, descriptor_index: 6, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 190, max_stack: 3, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x51, 0x2a, 0xb4, 0x00, 0x0a, 0xb6, 0x00, 0x2e, 0xa1, 0x00, 0x10, 0x2a, 0x2a, 0xb4, 0x00, 0x0a, 0xb6,
                        0x00, 0x2e, 0x04, 0x64, 0xb5, 0x00, 0x51, 0x2a, 0xb4, 0x00, 0x51, 0x9c, 0x00, 0x08, 0x2a, 0x03, 0xb5, 0x00, 0x51, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 2, name_index: 120, descriptor_index: 6, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 190, max_stack: 3, max_locals: 3, code: vec![
                        0x2a, 0xb4, 0x00, 0x51, 0xb8, 0x00, 0x70, 0xb6, 0x00, 0x87, 0x08, 0x60, 0x68, 0x3c, 0x11, 0x01, 0x0e, 0x3d, 0x1b, 0x2a,
                        0xb6, 0x00, 0xb1, 0xa2, 0x00, 0x0b, 0x2a, 0x1b, 0xb6, 0x00, 0xb4, 0xa7, 0x00, 0x1a, 0x1b, 0x10, 0x11, 0x60, 0x2a, 0xb6,
                        0x00, 0xb1, 0x1c, 0x60, 0xa4, 0x00, 0x0d, 0x2a, 0x1b, 0x10, 0x11, 0x60, 0x1c, 0x64, 0xb6, 0x00, 0xb4, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 8, name_index: 225, descriptor_index: 6, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 190, max_stack: 5, max_locals: 0, code: vec![
                        0xbb, 0x00, 0xb7, 0x59, 0x12, 0xb9, 0x07, 0x03, 0xb7, 0x00, 0xbb, 0xb3, 0x00, 0x10, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
            ],
            attributes: Vec::new(),
        },
        // javax/microedition/lcdui/Screen
        ClassFile {
            minor_version: 0,
            major_version: 48,
            constant_pool: vec![
                None,
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 3 }),
                Some(Constant::Class { name_index: 4 }),
                Some(Constant::NameAndType { name_index: 5, descriptor_index: 6 }),
                Some(Constant::Utf8("javax/microedition/lcdui/Displayable".to_owned())),
                Some(Constant::Utf8("<init>".to_owned())),
                Some(Constant::Utf8("()V".to_owned())),
                Some(Constant::Methodref { class_index: 8, name_and_type_index: 9 }),
                Some(Constant::Class { name_index: 10 }),
                Some(Constant::NameAndType { name_index: 11, descriptor_index: 12 }),
                Some(Constant::Utf8("javax/microedition/lcdui/Image".to_owned())),
                Some(Constant::Utf8("createImage".to_owned())),
                Some(Constant::Utf8("(II)Ljavax/microedition/lcdui/Image;".to_owned())),
                Some(Constant::Fieldref { class_index: 14, name_and_type_index: 15 }),
                Some(Constant::Class { name_index: 16 }),
                Some(Constant::NameAndType { name_index: 17, descriptor_index: 18 }),
                Some(Constant::Utf8("javax/microedition/lcdui/Screen".to_owned())),
                Some(Constant::Utf8("framebuffer".to_owned())),
                Some(Constant::Utf8("Ljavax/microedition/lcdui/Image;".to_owned())),
                Some(Constant::Methodref { class_index: 14, name_and_type_index: 20 }),
                Some(Constant::NameAndType { name_index: 21, descriptor_index: 6 }),
                Some(Constant::Utf8("showNotify".to_owned())),
                Some(Constant::Methodref { class_index: 14, name_and_type_index: 23 }),
                Some(Constant::NameAndType { name_index: 24, descriptor_index: 6 }),
                Some(Constant::Utf8("__render".to_owned())),
                Some(Constant::Methodref { class_index: 14, name_and_type_index: 26 }),
                Some(Constant::NameAndType { name_index: 27, descriptor_index: 6 }),
                Some(Constant::Utf8("hideNotify".to_owned())),
                Some(Constant::Fieldref { class_index: 14, name_and_type_index: 29 }),
                Some(Constant::NameAndType { name_index: 30, descriptor_index: 31 }),
                Some(Constant::Utf8("handling".to_owned())),
                Some(Constant::Utf8("Z".to_owned())),
                Some(Constant::Methodref { class_index: 14, name_and_type_index: 33 }),
                Some(Constant::NameAndType { name_index: 34, descriptor_index: 35 }),
                Some(Constant::Utf8("__dispatchSoftKey".to_owned())),
                Some(Constant::Utf8("(I)V".to_owned())),
                Some(Constant::Methodref { class_index: 14, name_and_type_index: 37 }),
                Some(Constant::NameAndType { name_index: 38, descriptor_index: 35 }),
                Some(Constant::Utf8("__keyPressed".to_owned())),
                Some(Constant::Fieldref { class_index: 14, name_and_type_index: 40 }),
                Some(Constant::NameAndType { name_index: 41, descriptor_index: 31 }),
                Some(Constant::Utf8("dirty".to_owned())),
                Some(Constant::Fieldref { class_index: 14, name_and_type_index: 43 }),
                Some(Constant::NameAndType { name_index: 44, descriptor_index: 31 }),
                Some(Constant::Utf8("painting".to_owned())),
                Some(Constant::Methodref { class_index: 14, name_and_type_index: 46 }),
                Some(Constant::NameAndType { name_index: 47, descriptor_index: 48 }),
                Some(Constant::Utf8("isShown".to_owned())),
                Some(Constant::Utf8("()Z".to_owned())),
                Some(Constant::Methodref { class_index: 8, name_and_type_index: 50 }),
                Some(Constant::NameAndType { name_index: 51, descriptor_index: 52 }),
                Some(Constant::Utf8("getGraphics".to_owned())),
                Some(Constant::Utf8("()Ljavax/microedition/lcdui/Graphics;".to_owned())),
                Some(Constant::Integer(16777215)),
                Some(Constant::Methodref { class_index: 55, name_and_type_index: 56 }),
                Some(Constant::Class { name_index: 57 }),
                Some(Constant::NameAndType { name_index: 58, descriptor_index: 35 }),
                Some(Constant::Utf8("javax/microedition/lcdui/Graphics".to_owned())),
                Some(Constant::Utf8("setColor".to_owned())),
                Some(Constant::Methodref { class_index: 55, name_and_type_index: 60 }),
                Some(Constant::NameAndType { name_index: 61, descriptor_index: 62 }),
                Some(Constant::Utf8("fillRect".to_owned())),
                Some(Constant::Utf8("(IIII)V".to_owned())),
                Some(Constant::Class { name_index: 64 }),
                Some(Constant::Utf8("javax/microedition/lcdui/Font".to_owned())),
                Some(Constant::Methodref { class_index: 63, name_and_type_index: 66 }),
                Some(Constant::NameAndType { name_index: 67, descriptor_index: 68 }),
                Some(Constant::Utf8("getFont".to_owned())),
                Some(Constant::Utf8("(III)Ljavax/microedition/lcdui/Font;".to_owned())),
                Some(Constant::Methodref { class_index: 55, name_and_type_index: 70 }),
                Some(Constant::NameAndType { name_index: 71, descriptor_index: 72 }),
                Some(Constant::Utf8("setFont".to_owned())),
                Some(Constant::Utf8("(Ljavax/microedition/lcdui/Font;)V".to_owned())),
                Some(Constant::Methodref { class_index: 14, name_and_type_index: 74 }),
                Some(Constant::NameAndType { name_index: 75, descriptor_index: 76 }),
                Some(Constant::Utf8("getTitle".to_owned())),
                Some(Constant::Utf8("()Ljava/lang/String;".to_owned())),
                Some(Constant::Methodref { class_index: 55, name_and_type_index: 78 }),
                Some(Constant::NameAndType { name_index: 79, descriptor_index: 80 }),
                Some(Constant::Utf8("drawString".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;III)V".to_owned())),
                Some(Constant::Methodref { class_index: 63, name_and_type_index: 82 }),
                Some(Constant::NameAndType { name_index: 83, descriptor_index: 84 }),
                Some(Constant::Utf8("getHeight".to_owned())),
                Some(Constant::Utf8("()I".to_owned())),
                Some(Constant::Methodref { class_index: 14, name_and_type_index: 86 }),
                Some(Constant::NameAndType { name_index: 87, descriptor_index: 88 }),
                Some(Constant::Utf8("getTicker".to_owned())),
                Some(Constant::Utf8("()Ljavax/microedition/lcdui/Ticker;".to_owned())),
                Some(Constant::Integer(15132390)),
                Some(Constant::Methodref { class_index: 63, name_and_type_index: 91 }),
                Some(Constant::NameAndType { name_index: 92, descriptor_index: 93 }),
                Some(Constant::Utf8("getDefaultFont".to_owned())),
                Some(Constant::Utf8("()Ljavax/microedition/lcdui/Font;".to_owned())),
                Some(Constant::Methodref { class_index: 95, name_and_type_index: 96 }),
                Some(Constant::Class { name_index: 97 }),
                Some(Constant::NameAndType { name_index: 98, descriptor_index: 76 }),
                Some(Constant::Utf8("javax/microedition/lcdui/Ticker".to_owned())),
                Some(Constant::Utf8("getString".to_owned())),
                Some(Constant::Methodref { class_index: 55, name_and_type_index: 100 }),
                Some(Constant::NameAndType { name_index: 101, descriptor_index: 62 }),
                Some(Constant::Utf8("setClip".to_owned())),
                Some(Constant::Fieldref { class_index: 14, name_and_type_index: 103 }),
                Some(Constant::NameAndType { name_index: 104, descriptor_index: 105 }),
                Some(Constant::Utf8("scroll".to_owned())),
                Some(Constant::Utf8("I".to_owned())),
                Some(Constant::Methodref { class_index: 14, name_and_type_index: 107 }),
                Some(Constant::NameAndType { name_index: 108, descriptor_index: 109 }),
                Some(Constant::Utf8("__paintContent".to_owned())),
                Some(Constant::Utf8("(Ljavax/microedition/lcdui/Graphics;II)V".to_owned())),
                Some(Constant::Integer(14079702)),
                Some(Constant::Methodref { class_index: 14, name_and_type_index: 112 }),
                Some(Constant::NameAndType { name_index: 113, descriptor_index: 114 }),
                Some(Constant::Utf8("__leftCommand".to_owned())),
                Some(Constant::Utf8("()Ljavax/microedition/lcdui/Command;".to_owned())),
                Some(Constant::Methodref { class_index: 14, name_and_type_index: 116 }),
                Some(Constant::NameAndType { name_index: 117, descriptor_index: 114 }),
                Some(Constant::Utf8("__rightCommand".to_owned())),
                Some(Constant::Methodref { class_index: 119, name_and_type_index: 120 }),
                Some(Constant::Class { name_index: 121 }),
                Some(Constant::NameAndType { name_index: 122, descriptor_index: 76 }),
                Some(Constant::Utf8("javax/microedition/lcdui/Command".to_owned())),
                Some(Constant::Utf8("getLabel".to_owned())),
                Some(Constant::Fieldref { class_index: 8, name_and_type_index: 124 }),
                Some(Constant::NameAndType { name_index: 125, descriptor_index: 126 }),
                Some(Constant::Utf8("pixels".to_owned())),
                Some(Constant::Utf8("[I".to_owned())),
                Some(Constant::Methodref { class_index: 14, name_and_type_index: 128 }),
                Some(Constant::NameAndType { name_index: 129, descriptor_index: 130 }),
                Some(Constant::Utf8("present".to_owned())),
                Some(Constant::Utf8("([I)V".to_owned())),
                Some(Constant::Methodref { class_index: 8, name_and_type_index: 132 }),
                Some(Constant::NameAndType { name_index: 133, descriptor_index: 134 }),
                Some(Constant::Utf8("getRGB".to_owned())),
                Some(Constant::Utf8("([IIIIIII)V".to_owned())),
                Some(Constant::Utf8("Code".to_owned())),
                Some(Constant::Utf8("LineNumberTable".to_owned())),
                Some(Constant::Utf8("__show".to_owned())),
                Some(Constant::Utf8("__hide".to_owned())),
                Some(Constant::Utf8("__hostKeyPressed".to_owned())),
                Some(Constant::Utf8("StackMapTable".to_owned())),
                Some(Constant::Class { name_index: 142 }),
                Some(Constant::Utf8("java/lang/Throwable".to_owned())),
                Some(Constant::Utf8("__hostIdle".to_owned())),
                Some(Constant::Utf8("__setScroll".to_owned())),
                Some(Constant::Utf8("__getScroll".to_owned())),
                Some(Constant::Utf8("__requestRepaint".to_owned())),
                Some(Constant::Utf8("__getFramebufferRGB".to_owned())),
                Some(Constant::Utf8("SourceFile".to_owned())),
                Some(Constant::Utf8("generated_bootstrap.rs".to_owned())),
            ],
            access_flags: 1057,
            this_class: 14,
            super_class: 2,
            interfaces: vec![],
            fields: vec![
                Member { access_flags: 18, name_index: 17, descriptor_index: 18, attributes: Vec::new() },
                Member { access_flags: 2, name_index: 104, descriptor_index: 105, attributes: Vec::new() },
                Member { access_flags: 2, name_index: 44, descriptor_index: 31, attributes: Vec::new() },
                Member { access_flags: 2, name_index: 30, descriptor_index: 31, attributes: Vec::new() },
                Member { access_flags: 2, name_index: 41, descriptor_index: 31, attributes: Vec::new() },
            ],
            methods: vec![
                Member { access_flags: 1, name_index: 5, descriptor_index: 6, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 135, max_stack: 3, max_locals: 1, code: vec![
                        0x2a, 0xb7, 0x00, 0x01, 0x2a, 0x11, crate::LCDUI_WIDTH_MARKER_BYTES[0], crate::LCDUI_WIDTH_MARKER_BYTES[1], 0x11, crate::LCDUI_HEIGHT_MARKER_BYTES[0], crate::LCDUI_HEIGHT_MARKER_BYTES[1], 0xb8, 0x00, 0x07, 0xb5, 0x00, 0x0d, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 16, name_index: 137, descriptor_index: 6, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 135, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb6, 0x00, 0x13, 0x2a, 0xb6, 0x00, 0x16, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 16, name_index: 138, descriptor_index: 6, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 135, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb6, 0x00, 0x19, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 16, name_index: 139, descriptor_index: 35, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 135, max_stack: 2, max_locals: 3, code: vec![
                        0x2a, 0x04, 0xb5, 0x00, 0x1c, 0x1b, 0x10, 0xfa, 0x9f, 0x00, 0x09, 0x1b, 0x10, 0xf9, 0xa0, 0x00, 0x0b, 0x2a, 0x1b, 0xb6,
                        0x00, 0x20, 0xa7, 0x00, 0x08, 0x2a, 0x1b, 0xb6, 0x00, 0x24, 0x2a, 0x03, 0xb5, 0x00, 0x1c, 0xa7, 0x00, 0x0b, 0x4d, 0x2a,
                        0x03, 0xb5, 0x00, 0x1c, 0x2c, 0xbf, 0x2a, 0x03, 0xb5, 0x00, 0x27, 0x2a, 0xb6, 0x00, 0x16, 0xb1,
                    ], exception_table: vec![
                        ExceptionHandler { start_pc: 5, end_pc: 30, handler_pc: 38, catch_type: 0 },
                    ], attributes: Vec::new() }),
                ] },
                Member { access_flags: 0, name_index: 143, descriptor_index: 6, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 135, max_stack: 0, max_locals: 1, code: vec![
                        0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 0, name_index: 38, descriptor_index: 35, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 135, max_stack: 0, max_locals: 2, code: vec![
                        0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1024, name_index: 108, descriptor_index: 109, attributes: Vec::new() },
                Member { access_flags: 16, name_index: 24, descriptor_index: 6, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 135, max_stack: 6, max_locals: 8, code: vec![
                        0x2a, 0xb4, 0x00, 0x2a, 0x9a, 0x00, 0x0a, 0x2a, 0xb6, 0x00, 0x2d, 0x9a, 0x00, 0x04, 0xb1, 0x2a, 0x04, 0xb5, 0x00, 0x2a,
                        0x2a, 0xb4, 0x00, 0x0d, 0xb6, 0x00, 0x31, 0x4c, 0x2b, 0x12, 0x35, 0xb6, 0x00, 0x36, 0x2b, 0x03, 0x03, 0x11, crate::LCDUI_WIDTH_MARKER_BYTES[0], crate::LCDUI_WIDTH_MARKER_BYTES[1],
                        0x11, crate::LCDUI_HEIGHT_MARKER_BYTES[0], crate::LCDUI_HEIGHT_MARKER_BYTES[1], 0xb6, 0x00, 0x3b, 0x03, 0x04, 0x03, 0xb8, 0x00, 0x41, 0x4d, 0x2b, 0x2c, 0xb6, 0x00, 0x45, 0x2b, 0x03,
                        0xb6, 0x00, 0x36, 0x05, 0x3e, 0x2a, 0xb6, 0x00, 0x49, 0xc6, 0x00, 0x18, 0x2b, 0x2a, 0xb6, 0x00, 0x49, 0x07, 0x1d, 0x10,
                        0x14, 0xb6, 0x00, 0x4d, 0x1d, 0x2c, 0xb6, 0x00, 0x51, 0x06, 0x60, 0x60, 0x3e, 0x2a, 0xb6, 0x00, 0x55, 0xc6, 0x00, 0x42,
                        0x2b, 0x12, 0x59, 0xb6, 0x00, 0x36, 0x2b, 0x03, 0x1d, 0x11, crate::LCDUI_WIDTH_MARKER_BYTES[0], crate::LCDUI_WIDTH_MARKER_BYTES[1], 0xb8, 0x00, 0x5a, 0xb6, 0x00, 0x51, 0x05, 0x60,
                        0xb6, 0x00, 0x3b, 0x2b, 0x03, 0xb6, 0x00, 0x36, 0x2b, 0xb8, 0x00, 0x5a, 0xb6, 0x00, 0x45, 0x2b, 0x2a, 0xb6, 0x00, 0x55,
                        0xb6, 0x00, 0x5e, 0x06, 0x1d, 0x04, 0x60, 0x10, 0x14, 0xb6, 0x00, 0x4d, 0x1d, 0xb8, 0x00, 0x5a, 0xb6, 0x00, 0x51, 0x06,
                        0x60, 0x60, 0x3e, 0x11, 0x01, 0x2e, 0x36, 0x04, 0x2b, 0x03, 0x1d, 0x11, crate::LCDUI_WIDTH_MARKER_BYTES[0], crate::LCDUI_WIDTH_MARKER_BYTES[1], 0x15, 0x04, 0x1d, 0x64, 0xb6, 0x00,
                        0x63, 0x2a, 0x2b, 0x1d, 0x2a, 0xb4, 0x00, 0x66, 0x64, 0x15, 0x04, 0xb6, 0x00, 0x6a, 0x2b, 0x03, 0x11, 0x01, 0x2e, 0x11,
                        crate::LCDUI_WIDTH_MARKER_BYTES[0], crate::LCDUI_WIDTH_MARKER_BYTES[1], 0x10, 0x12, 0xb6, 0x00, 0x63, 0x2b, 0x12, 0x6e, 0xb6, 0x00, 0x36, 0x2b, 0x03, 0x11, 0x01, 0x2e, 0x11,
                        crate::LCDUI_WIDTH_MARKER_BYTES[0], crate::LCDUI_WIDTH_MARKER_BYTES[1], 0x10, 0x12, 0xb6, 0x00, 0x3b, 0x2b, 0x03, 0xb6, 0x00, 0x36, 0x2b, 0xb8, 0x00, 0x5a, 0xb6, 0x00, 0x45, 0x2a, 0xb6,
                        0x00, 0x6f, 0x3a, 0x05, 0x2a, 0xb6, 0x00, 0x73, 0x3a, 0x06, 0x19, 0x05, 0xc6, 0x00, 0x12, 0x2b, 0x19, 0x05, 0xb6, 0x00,
                        0x76, 0x06, 0x11, 0x01, 0x31, 0x10, 0x14, 0xb6, 0x00, 0x4d, 0x19, 0x06, 0xc6, 0x00, 0x14, 0x2b, 0x19, 0x06, 0xb6, 0x00,
                        0x76, 0x11, 0x00, 0xed, 0x11, 0x01, 0x31, 0x10, 0x18, 0xb6, 0x00, 0x4d, 0x2a, 0xb4, 0x00, 0x0d, 0xb4, 0x00, 0x7b, 0xb8,
                        0x00, 0x7f, 0x2a, 0x03, 0xb5, 0x00, 0x2a, 0xa7, 0x00, 0x0d, 0x3a, 0x07, 0x2a, 0x03, 0xb5, 0x00, 0x2a, 0x19, 0x07, 0xbf,
                        0xb1,
                    ], exception_table: vec![
                        ExceptionHandler { start_pc: 20, end_pc: 302, handler_pc: 310, catch_type: 0 },
                        ExceptionHandler { start_pc: 310, end_pc: 312, handler_pc: 310, catch_type: 0 },
                    ], attributes: Vec::new() }),
                ] },
                Member { access_flags: 16, name_index: 144, descriptor_index: 35, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 135, max_stack: 2, max_locals: 2, code: vec![
                        0x2a, 0x1b, 0x9c, 0x00, 0x07, 0x03, 0xa7, 0x00, 0x04, 0x1b, 0xb5, 0x00, 0x66, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 16, name_index: 145, descriptor_index: 84, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 135, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x66, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 0, name_index: 146, descriptor_index: 6, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 135, max_stack: 2, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x1c, 0x99, 0x00, 0x0b, 0x2a, 0x04, 0xb5, 0x00, 0x27, 0xa7, 0x00, 0x07, 0x2a, 0xb6, 0x00, 0x16, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 17, name_index: 147, descriptor_index: 130, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 135, max_stack: 8, max_locals: 2, code: vec![
                        0x2a, 0xb4, 0x00, 0x0d, 0x2b, 0x03, 0x11, crate::LCDUI_WIDTH_MARKER_BYTES[0], crate::LCDUI_WIDTH_MARKER_BYTES[1], 0x03, 0x03, 0x11, crate::LCDUI_WIDTH_MARKER_BYTES[0], crate::LCDUI_WIDTH_MARKER_BYTES[1], 0x11, crate::LCDUI_HEIGHT_MARKER_BYTES[0], crate::LCDUI_HEIGHT_MARKER_BYTES[1], 0xb6, 0x00, 0x83,
                        0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 266, name_index: 129, descriptor_index: 130, attributes: Vec::new() },
            ],
            attributes: Vec::new(),
        },
        // javax/microedition/lcdui/Spacer
        ClassFile {
            minor_version: 0,
            major_version: 48,
            constant_pool: vec![
                None,
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 3 }),
                Some(Constant::Class { name_index: 4 }),
                Some(Constant::NameAndType { name_index: 5, descriptor_index: 6 }),
                Some(Constant::Utf8("javax/microedition/lcdui/Item".to_owned())),
                Some(Constant::Utf8("<init>".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;)V".to_owned())),
                Some(Constant::Methodref { class_index: 8, name_and_type_index: 9 }),
                Some(Constant::Class { name_index: 10 }),
                Some(Constant::NameAndType { name_index: 11, descriptor_index: 12 }),
                Some(Constant::Utf8("javax/microedition/lcdui/Spacer".to_owned())),
                Some(Constant::Utf8("setMinimumSize".to_owned())),
                Some(Constant::Utf8("(II)V".to_owned())),
                Some(Constant::Class { name_index: 14 }),
                Some(Constant::Utf8("java/lang/IllegalArgumentException".to_owned())),
                Some(Constant::Methodref { class_index: 13, name_and_type_index: 16 }),
                Some(Constant::NameAndType { name_index: 5, descriptor_index: 17 }),
                Some(Constant::Utf8("()V".to_owned())),
                Some(Constant::Fieldref { class_index: 8, name_and_type_index: 19 }),
                Some(Constant::NameAndType { name_index: 20, descriptor_index: 21 }),
                Some(Constant::Utf8("width".to_owned())),
                Some(Constant::Utf8("I".to_owned())),
                Some(Constant::Fieldref { class_index: 8, name_and_type_index: 23 }),
                Some(Constant::NameAndType { name_index: 24, descriptor_index: 21 }),
                Some(Constant::Utf8("height".to_owned())),
                Some(Constant::Methodref { class_index: 8, name_and_type_index: 26 }),
                Some(Constant::NameAndType { name_index: 27, descriptor_index: 17 }),
                Some(Constant::Utf8("invalidate".to_owned())),
                Some(Constant::Utf8("Code".to_owned())),
                Some(Constant::Utf8("LineNumberTable".to_owned())),
                Some(Constant::Utf8("StackMapTable".to_owned())),
                Some(Constant::Utf8("__minimumWidth".to_owned())),
                Some(Constant::Utf8("()I".to_owned())),
                Some(Constant::Utf8("__height".to_owned())),
                Some(Constant::Utf8("(I)I".to_owned())),
                Some(Constant::Utf8("__paint".to_owned())),
                Some(Constant::Utf8("(Ljavax/microedition/lcdui/Graphics;IIIZ)V".to_owned())),
                Some(Constant::Utf8("SourceFile".to_owned())),
                Some(Constant::Utf8("generated_bootstrap.rs".to_owned())),
            ],
            access_flags: 33,
            this_class: 8,
            super_class: 2,
            interfaces: vec![],
            fields: vec![
                Member { access_flags: 2, name_index: 20, descriptor_index: 21, attributes: Vec::new() },
                Member { access_flags: 2, name_index: 24, descriptor_index: 21, attributes: Vec::new() },
            ],
            methods: vec![
                Member { access_flags: 1, name_index: 5, descriptor_index: 12, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 28, max_stack: 3, max_locals: 3, code: vec![
                        0x2a, 0x01, 0xb7, 0x00, 0x01, 0x2a, 0x1b, 0x1c, 0xb6, 0x00, 0x07, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 11, descriptor_index: 12, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 28, max_stack: 2, max_locals: 3, code: vec![
                        0x1b, 0x9b, 0x00, 0x07, 0x1c, 0x9c, 0x00, 0x0b, 0xbb, 0x00, 0x0d, 0x59, 0xb7, 0x00, 0x0f, 0xbf, 0x2a, 0x1b, 0xb5, 0x00,
                        0x12, 0x2a, 0x1c, 0xb5, 0x00, 0x16, 0x2a, 0xb6, 0x00, 0x19, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 0, name_index: 31, descriptor_index: 32, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 28, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x12, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 0, name_index: 33, descriptor_index: 34, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 28, max_stack: 1, max_locals: 2, code: vec![
                        0x2a, 0xb4, 0x00, 0x16, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 0, name_index: 35, descriptor_index: 36, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 28, max_stack: 0, max_locals: 6, code: vec![
                        0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
            ],
            attributes: Vec::new(),
        },
    );
}
