use super::{
    Attribute, ClassFile, CodeAttribute, Constant, Member, append_bootstrap_classes,
    build_bootstrap_class,
};

pub(super) fn append_text_components(classes: &mut Vec<ClassFile>) {
    append_bootstrap_classes!(classes;
        // javax/microedition/lcdui/StringItem
        ClassFile {
            minor_version: 0,
            major_version: 48,
            constant_pool: vec![
                None,
                Some(Constant::Class { name_index: 2 }),
                Some(Constant::Utf8("javax/microedition/lcdui/Item".to_owned())),
                Some(Constant::Methodref { class_index: 4, name_and_type_index: 5 }),
                Some(Constant::Class { name_index: 6 }),
                Some(Constant::NameAndType { name_index: 7, descriptor_index: 8 }),
                Some(Constant::Utf8("javax/microedition/lcdui/StringItem".to_owned())),
                Some(Constant::Utf8("<init>".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;Ljava/lang/String;I)V".to_owned())),
                Some(Constant::Methodref { class_index: 1, name_and_type_index: 10 }),
                Some(Constant::NameAndType { name_index: 7, descriptor_index: 11 }),
                Some(Constant::Utf8("(Ljava/lang/String;)V".to_owned())),
                Some(Constant::Methodref { class_index: 13, name_and_type_index: 14 }),
                Some(Constant::Class { name_index: 15 }),
                Some(Constant::NameAndType { name_index: 16, descriptor_index: 17 }),
                Some(Constant::Utf8("javax/microedition/lcdui/Font".to_owned())),
                Some(Constant::Utf8("getDefaultFont".to_owned())),
                Some(Constant::Utf8("()Ljavax/microedition/lcdui/Font;".to_owned())),
                Some(Constant::Fieldref { class_index: 4, name_and_type_index: 19 }),
                Some(Constant::NameAndType { name_index: 20, descriptor_index: 21 }),
                Some(Constant::Utf8("font".to_owned())),
                Some(Constant::Utf8("Ljavax/microedition/lcdui/Font;".to_owned())),
                Some(Constant::Class { name_index: 23 }),
                Some(Constant::Utf8("java/lang/IllegalArgumentException".to_owned())),
                Some(Constant::Methodref { class_index: 22, name_and_type_index: 25 }),
                Some(Constant::NameAndType { name_index: 7, descriptor_index: 26 }),
                Some(Constant::Utf8("()V".to_owned())),
                Some(Constant::Fieldref { class_index: 4, name_and_type_index: 28 }),
                Some(Constant::NameAndType { name_index: 29, descriptor_index: 30 }),
                Some(Constant::Utf8("text".to_owned())),
                Some(Constant::Utf8("Ljava/lang/String;".to_owned())),
                Some(Constant::Fieldref { class_index: 4, name_and_type_index: 32 }),
                Some(Constant::NameAndType { name_index: 33, descriptor_index: 34 }),
                Some(Constant::Utf8("appearance".to_owned())),
                Some(Constant::Utf8("I".to_owned())),
                Some(Constant::Methodref { class_index: 4, name_and_type_index: 36 }),
                Some(Constant::NameAndType { name_index: 37, descriptor_index: 26 }),
                Some(Constant::Utf8("invalidate".to_owned())),
                Some(Constant::Methodref { class_index: 39, name_and_type_index: 40 }),
                Some(Constant::Class { name_index: 41 }),
                Some(Constant::NameAndType { name_index: 42, descriptor_index: 43 }),
                Some(Constant::Utf8("java/lang/String".to_owned())),
                Some(Constant::Utf8("length".to_owned())),
                Some(Constant::Utf8("()I".to_owned())),
                Some(Constant::Methodref { class_index: 13, name_and_type_index: 45 }),
                Some(Constant::NameAndType { name_index: 46, descriptor_index: 47 }),
                Some(Constant::Utf8("stringWidth".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;)I".to_owned())),
                Some(Constant::Methodref { class_index: 4, name_and_type_index: 49 }),
                Some(Constant::NameAndType { name_index: 50, descriptor_index: 51 }),
                Some(Constant::Utf8("getLabel".to_owned())),
                Some(Constant::Utf8("()Ljava/lang/String;".to_owned())),
                Some(Constant::Methodref { class_index: 13, name_and_type_index: 53 }),
                Some(Constant::NameAndType { name_index: 54, descriptor_index: 43 }),
                Some(Constant::Utf8("getHeight".to_owned())),
                Some(Constant::Methodref { class_index: 56, name_and_type_index: 57 }),
                Some(Constant::Class { name_index: 58 }),
                Some(Constant::NameAndType { name_index: 59, descriptor_index: 60 }),
                Some(Constant::Utf8("javax/microedition/lcdui/Graphics".to_owned())),
                Some(Constant::Utf8("setFont".to_owned())),
                Some(Constant::Utf8("(Ljavax/microedition/lcdui/Font;)V".to_owned())),
                Some(Constant::Integer(2379678)),
                Some(Constant::Methodref { class_index: 56, name_and_type_index: 63 }),
                Some(Constant::NameAndType { name_index: 64, descriptor_index: 65 }),
                Some(Constant::Utf8("setColor".to_owned())),
                Some(Constant::Utf8("(I)V".to_owned())),
                Some(Constant::Methodref { class_index: 4, name_and_type_index: 67 }),
                Some(Constant::NameAndType { name_index: 68, descriptor_index: 69 }),
                Some(Constant::Utf8("__height".to_owned())),
                Some(Constant::Utf8("(I)I".to_owned())),
                Some(Constant::Methodref { class_index: 56, name_and_type_index: 71 }),
                Some(Constant::NameAndType { name_index: 72, descriptor_index: 73 }),
                Some(Constant::Utf8("fillRect".to_owned())),
                Some(Constant::Utf8("(IIII)V".to_owned())),
                Some(Constant::Integer(16777215)),
                Some(Constant::Methodref { class_index: 56, name_and_type_index: 76 }),
                Some(Constant::NameAndType { name_index: 77, descriptor_index: 78 }),
                Some(Constant::Utf8("drawString".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;III)V".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;Ljava/lang/String;)V".to_owned())),
                Some(Constant::Utf8("Code".to_owned())),
                Some(Constant::Utf8("LineNumberTable".to_owned())),
                Some(Constant::Utf8("StackMapTable".to_owned())),
                Some(Constant::Utf8("getText".to_owned())),
                Some(Constant::Utf8("setText".to_owned())),
                Some(Constant::Utf8("getAppearanceMode".to_owned())),
                Some(Constant::Utf8("getFont".to_owned())),
                Some(Constant::Utf8("__paint".to_owned())),
                Some(Constant::Utf8("(Ljavax/microedition/lcdui/Graphics;IIIZ)V".to_owned())),
                Some(Constant::Utf8("SourceFile".to_owned())),
                Some(Constant::Utf8("generated_bootstrap.rs".to_owned())),
            ],
            access_flags: 33,
            this_class: 4,
            super_class: 1,
            interfaces: vec![],
            fields: vec![
                Member { access_flags: 2, name_index: 29, descriptor_index: 30, attributes: Vec::new() },
                Member { access_flags: 2, name_index: 33, descriptor_index: 34, attributes: Vec::new() },
                Member { access_flags: 2, name_index: 20, descriptor_index: 21, attributes: Vec::new() },
            ],
            methods: vec![
                Member { access_flags: 1, name_index: 7, descriptor_index: 79, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 80, max_stack: 4, max_locals: 3, code: vec![
                        0x2a, 0x2b, 0x2c, 0x03, 0xb7, 0x00, 0x03, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 7, descriptor_index: 8, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 80, max_stack: 2, max_locals: 4, code: vec![
                        0x2a, 0x2b, 0xb7, 0x00, 0x09, 0x2a, 0xb8, 0x00, 0x0c, 0xb5, 0x00, 0x12, 0x1d, 0x9b, 0x00, 0x08, 0x1d, 0x05, 0xa4, 0x00,
                        0x0b, 0xbb, 0x00, 0x16, 0x59, 0xb7, 0x00, 0x18, 0xbf, 0x2a, 0x2c, 0xb5, 0x00, 0x1b, 0x2a, 0x1d, 0xb5, 0x00, 0x1f, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 83, descriptor_index: 51, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 80, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x1b, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 84, descriptor_index: 11, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 80, max_stack: 2, max_locals: 2, code: vec![
                        0x2a, 0x2b, 0xb5, 0x00, 0x1b, 0x2a, 0xb6, 0x00, 0x23, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 85, descriptor_index: 43, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 80, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x1f, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 59, descriptor_index: 60, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 80, max_stack: 2, max_locals: 2, code: vec![
                        0x2a, 0x2b, 0xc7, 0x00, 0x09, 0xb8, 0x00, 0x0c, 0xa7, 0x00, 0x04, 0x2b, 0xb5, 0x00, 0x12, 0x2a, 0xb6, 0x00, 0x23, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 86, descriptor_index: 17, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 80, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x12, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 0, name_index: 68, descriptor_index: 69, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 80, max_stack: 3, max_locals: 3, code: vec![
                        0x2a, 0xb4, 0x00, 0x1b, 0xc6, 0x00, 0x0d, 0x2a, 0xb4, 0x00, 0x1b, 0xb6, 0x00, 0x26, 0x9a, 0x00, 0x07, 0x04, 0xa7, 0x00,
                        0x14, 0x2a, 0xb4, 0x00, 0x12, 0x2a, 0xb4, 0x00, 0x1b, 0xb6, 0x00, 0x2c, 0x1b, 0x60, 0x04, 0x64, 0x1b, 0x6c, 0x3d, 0x2a,
                        0xb6, 0x00, 0x30, 0xc7, 0x00, 0x07, 0x03, 0xa7, 0x00, 0x0c, 0x2a, 0xb4, 0x00, 0x12, 0xb6, 0x00, 0x34, 0x04, 0x60, 0x1c,
                        0x2a, 0xb4, 0x00, 0x12, 0xb6, 0x00, 0x34, 0x68, 0x60, 0x07, 0x60, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 0, name_index: 87, descriptor_index: 88, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 80, max_stack: 6, max_locals: 6, code: vec![
                        0x2b, 0x2a, 0xb4, 0x00, 0x12, 0xb6, 0x00, 0x37, 0x15, 0x05, 0x99, 0x00, 0x2d, 0x2a, 0xb4, 0x00, 0x1f, 0x99, 0x00, 0x26,
                        0x2b, 0x12, 0x3d, 0xb6, 0x00, 0x3e, 0x2b, 0x1c, 0x05, 0x64, 0x1d, 0x04, 0x64, 0x15, 0x04, 0x07, 0x60, 0x2a, 0x15, 0x04,
                        0xb6, 0x00, 0x42, 0xb6, 0x00, 0x46, 0x2b, 0x12, 0x4a, 0xb6, 0x00, 0x3e, 0xa7, 0x00, 0x08, 0x2b, 0x03, 0xb6, 0x00, 0x3e,
                        0x2a, 0xb6, 0x00, 0x30, 0xc6, 0x00, 0x1b, 0x2b, 0x2a, 0xb6, 0x00, 0x30, 0x1c, 0x1d, 0x10, 0x14, 0xb6, 0x00, 0x4b, 0x1d,
                        0x2a, 0xb4, 0x00, 0x12, 0xb6, 0x00, 0x34, 0x04, 0x60, 0x60, 0x3e, 0x2a, 0xb4, 0x00, 0x1b, 0xc6, 0x00, 0x0f, 0x2b, 0x2a,
                        0xb4, 0x00, 0x1b, 0x1c, 0x1d, 0x10, 0x14, 0xb6, 0x00, 0x4b, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
            ],
            attributes: Vec::new(),
        },
        // javax/microedition/lcdui/TextBox
        ClassFile {
            minor_version: 0,
            major_version: 48,
            constant_pool: vec![
                None,
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 3 }),
                Some(Constant::Class { name_index: 4 }),
                Some(Constant::NameAndType { name_index: 5, descriptor_index: 6 }),
                Some(Constant::Utf8("javax/microedition/lcdui/Screen".to_owned())),
                Some(Constant::Utf8("<init>".to_owned())),
                Some(Constant::Utf8("()V".to_owned())),
                Some(Constant::Methodref { class_index: 8, name_and_type_index: 9 }),
                Some(Constant::Class { name_index: 10 }),
                Some(Constant::NameAndType { name_index: 11, descriptor_index: 12 }),
                Some(Constant::Utf8("javax/microedition/lcdui/TextBox".to_owned())),
                Some(Constant::Utf8("setTitle".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;)V".to_owned())),
                Some(Constant::Class { name_index: 14 }),
                Some(Constant::Utf8("javax/microedition/lcdui/TextField".to_owned())),
                Some(Constant::Methodref { class_index: 13, name_and_type_index: 16 }),
                Some(Constant::NameAndType { name_index: 5, descriptor_index: 17 }),
                Some(Constant::Utf8("(Ljava/lang/String;Ljava/lang/String;II)V".to_owned())),
                Some(Constant::Fieldref { class_index: 8, name_and_type_index: 19 }),
                Some(Constant::NameAndType { name_index: 20, descriptor_index: 21 }),
                Some(Constant::Utf8("field".to_owned())),
                Some(Constant::Utf8("Ljavax/microedition/lcdui/TextField;".to_owned())),
                Some(Constant::Methodref { class_index: 13, name_and_type_index: 23 }),
                Some(Constant::NameAndType { name_index: 24, descriptor_index: 25 }),
                Some(Constant::Utf8("getString".to_owned())),
                Some(Constant::Utf8("()Ljava/lang/String;".to_owned())),
                Some(Constant::Methodref { class_index: 13, name_and_type_index: 27 }),
                Some(Constant::NameAndType { name_index: 28, descriptor_index: 12 }),
                Some(Constant::Utf8("setString".to_owned())),
                Some(Constant::Methodref { class_index: 8, name_and_type_index: 30 }),
                Some(Constant::NameAndType { name_index: 31, descriptor_index: 6 }),
                Some(Constant::Utf8("__requestRepaint".to_owned())),
                Some(Constant::Methodref { class_index: 13, name_and_type_index: 33 }),
                Some(Constant::NameAndType { name_index: 34, descriptor_index: 35 }),
                Some(Constant::Utf8("getChars".to_owned())),
                Some(Constant::Utf8("([C)I".to_owned())),
                Some(Constant::Methodref { class_index: 13, name_and_type_index: 37 }),
                Some(Constant::NameAndType { name_index: 38, descriptor_index: 39 }),
                Some(Constant::Utf8("setChars".to_owned())),
                Some(Constant::Utf8("([CII)V".to_owned())),
                Some(Constant::Methodref { class_index: 13, name_and_type_index: 41 }),
                Some(Constant::NameAndType { name_index: 42, descriptor_index: 43 }),
                Some(Constant::Utf8("insert".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;I)V".to_owned())),
                Some(Constant::Methodref { class_index: 13, name_and_type_index: 45 }),
                Some(Constant::NameAndType { name_index: 42, descriptor_index: 46 }),
                Some(Constant::Utf8("([CIII)V".to_owned())),
                Some(Constant::Methodref { class_index: 13, name_and_type_index: 48 }),
                Some(Constant::NameAndType { name_index: 49, descriptor_index: 50 }),
                Some(Constant::Utf8("delete".to_owned())),
                Some(Constant::Utf8("(II)V".to_owned())),
                Some(Constant::Methodref { class_index: 13, name_and_type_index: 52 }),
                Some(Constant::NameAndType { name_index: 53, descriptor_index: 54 }),
                Some(Constant::Utf8("getMaxSize".to_owned())),
                Some(Constant::Utf8("()I".to_owned())),
                Some(Constant::Methodref { class_index: 13, name_and_type_index: 56 }),
                Some(Constant::NameAndType { name_index: 57, descriptor_index: 58 }),
                Some(Constant::Utf8("setMaxSize".to_owned())),
                Some(Constant::Utf8("(I)I".to_owned())),
                Some(Constant::Methodref { class_index: 13, name_and_type_index: 60 }),
                Some(Constant::NameAndType { name_index: 61, descriptor_index: 54 }),
                Some(Constant::Utf8("size".to_owned())),
                Some(Constant::Methodref { class_index: 13, name_and_type_index: 63 }),
                Some(Constant::NameAndType { name_index: 64, descriptor_index: 54 }),
                Some(Constant::Utf8("getCaretPosition".to_owned())),
                Some(Constant::Methodref { class_index: 13, name_and_type_index: 66 }),
                Some(Constant::NameAndType { name_index: 67, descriptor_index: 54 }),
                Some(Constant::Utf8("getConstraints".to_owned())),
                Some(Constant::Methodref { class_index: 13, name_and_type_index: 69 }),
                Some(Constant::NameAndType { name_index: 70, descriptor_index: 71 }),
                Some(Constant::Utf8("setConstraints".to_owned())),
                Some(Constant::Utf8("(I)V".to_owned())),
                Some(Constant::Methodref { class_index: 13, name_and_type_index: 73 }),
                Some(Constant::NameAndType { name_index: 74, descriptor_index: 71 }),
                Some(Constant::Utf8("__key".to_owned())),
                Some(Constant::Methodref { class_index: 13, name_and_type_index: 76 }),
                Some(Constant::NameAndType { name_index: 77, descriptor_index: 78 }),
                Some(Constant::Utf8("__paint".to_owned())),
                Some(Constant::Utf8("(Ljavax/microedition/lcdui/Graphics;IIIZ)V".to_owned())),
                Some(Constant::Utf8("Code".to_owned())),
                Some(Constant::Utf8("LineNumberTable".to_owned())),
                Some(Constant::Utf8("__keyPressed".to_owned())),
                Some(Constant::Utf8("__paintContent".to_owned())),
                Some(Constant::Utf8("(Ljavax/microedition/lcdui/Graphics;II)V".to_owned())),
                Some(Constant::Utf8("SourceFile".to_owned())),
                Some(Constant::Utf8("generated_bootstrap.rs".to_owned())),
            ],
            access_flags: 33,
            this_class: 8,
            super_class: 2,
            interfaces: vec![],
            fields: vec![
                Member { access_flags: 18, name_index: 20, descriptor_index: 21, attributes: Vec::new() },
            ],
            methods: vec![
                Member { access_flags: 1, name_index: 5, descriptor_index: 17, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 79, max_stack: 7, max_locals: 5, code: vec![
                        0x2a, 0xb7, 0x00, 0x01, 0x2a, 0x2b, 0xb6, 0x00, 0x07, 0x2a, 0xbb, 0x00, 0x0d, 0x59, 0x01, 0x2c, 0x1d, 0x15, 0x04, 0xb7,
                        0x00, 0x0f, 0xb5, 0x00, 0x12, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 24, descriptor_index: 25, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 79, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x12, 0xb6, 0x00, 0x16, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 28, descriptor_index: 12, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 79, max_stack: 2, max_locals: 2, code: vec![
                        0x2a, 0xb4, 0x00, 0x12, 0x2b, 0xb6, 0x00, 0x1a, 0x2a, 0xb6, 0x00, 0x1d, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 34, descriptor_index: 35, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 79, max_stack: 2, max_locals: 2, code: vec![
                        0x2a, 0xb4, 0x00, 0x12, 0x2b, 0xb6, 0x00, 0x20, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 38, descriptor_index: 39, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 79, max_stack: 4, max_locals: 4, code: vec![
                        0x2a, 0xb4, 0x00, 0x12, 0x2b, 0x1c, 0x1d, 0xb6, 0x00, 0x24, 0x2a, 0xb6, 0x00, 0x1d, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 42, descriptor_index: 43, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 79, max_stack: 3, max_locals: 3, code: vec![
                        0x2a, 0xb4, 0x00, 0x12, 0x2b, 0x1c, 0xb6, 0x00, 0x28, 0x2a, 0xb6, 0x00, 0x1d, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 42, descriptor_index: 46, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 79, max_stack: 5, max_locals: 5, code: vec![
                        0x2a, 0xb4, 0x00, 0x12, 0x2b, 0x1c, 0x1d, 0x15, 0x04, 0xb6, 0x00, 0x2c, 0x2a, 0xb6, 0x00, 0x1d, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 49, descriptor_index: 50, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 79, max_stack: 3, max_locals: 3, code: vec![
                        0x2a, 0xb4, 0x00, 0x12, 0x1b, 0x1c, 0xb6, 0x00, 0x2f, 0x2a, 0xb6, 0x00, 0x1d, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 53, descriptor_index: 54, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 79, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x12, 0xb6, 0x00, 0x33, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 57, descriptor_index: 58, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 79, max_stack: 2, max_locals: 3, code: vec![
                        0x2a, 0xb4, 0x00, 0x12, 0x1b, 0xb6, 0x00, 0x37, 0x3d, 0x2a, 0xb6, 0x00, 0x1d, 0x1c, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 61, descriptor_index: 54, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 79, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x12, 0xb6, 0x00, 0x3b, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 64, descriptor_index: 54, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 79, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x12, 0xb6, 0x00, 0x3e, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 67, descriptor_index: 54, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 79, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x12, 0xb6, 0x00, 0x41, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 70, descriptor_index: 71, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 79, max_stack: 2, max_locals: 2, code: vec![
                        0x2a, 0xb4, 0x00, 0x12, 0x1b, 0xb6, 0x00, 0x44, 0x2a, 0xb6, 0x00, 0x1d, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 0, name_index: 81, descriptor_index: 71, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 79, max_stack: 2, max_locals: 2, code: vec![
                        0x2a, 0xb4, 0x00, 0x12, 0x1b, 0xb6, 0x00, 0x48, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 0, name_index: 82, descriptor_index: 83, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 79, max_stack: 6, max_locals: 4, code: vec![
                        0x2a, 0xb4, 0x00, 0x12, 0x2b, 0x08, 0x1c, 0x08, 0x60, 0x11, 0x00, 0xe6, 0x04, 0xb6, 0x00, 0x4b, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
            ],
            attributes: Vec::new(),
        },
        // javax/microedition/lcdui/TextField
        ClassFile {
            minor_version: 0,
            major_version: 48,
            constant_pool: vec![
                None,
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 3 }),
                Some(Constant::Class { name_index: 4 }),
                Some(Constant::NameAndType { name_index: 5, descriptor_index: 6 }),
                Some(Constant::Utf8("javax/microedition/lcdui/Item".to_owned())),
                Some(Constant::Utf8("<init>".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;)V".to_owned())),
                Some(Constant::String { string_index: 8 }),
                Some(Constant::Utf8("".to_owned())),
                Some(Constant::Fieldref { class_index: 10, name_and_type_index: 11 }),
                Some(Constant::Class { name_index: 12 }),
                Some(Constant::NameAndType { name_index: 13, descriptor_index: 14 }),
                Some(Constant::Utf8("javax/microedition/lcdui/TextField".to_owned())),
                Some(Constant::Utf8("text".to_owned())),
                Some(Constant::Utf8("Ljava/lang/String;".to_owned())),
                Some(Constant::Class { name_index: 16 }),
                Some(Constant::Utf8("java/lang/IllegalArgumentException".to_owned())),
                Some(Constant::Methodref { class_index: 15, name_and_type_index: 18 }),
                Some(Constant::NameAndType { name_index: 5, descriptor_index: 19 }),
                Some(Constant::Utf8("()V".to_owned())),
                Some(Constant::Fieldref { class_index: 10, name_and_type_index: 21 }),
                Some(Constant::NameAndType { name_index: 22, descriptor_index: 23 }),
                Some(Constant::Utf8("maximum".to_owned())),
                Some(Constant::Utf8("I".to_owned())),
                Some(Constant::Methodref { class_index: 10, name_and_type_index: 25 }),
                Some(Constant::NameAndType { name_index: 26, descriptor_index: 27 }),
                Some(Constant::Utf8("setConstraints".to_owned())),
                Some(Constant::Utf8("(I)V".to_owned())),
                Some(Constant::Methodref { class_index: 10, name_and_type_index: 29 }),
                Some(Constant::NameAndType { name_index: 30, descriptor_index: 6 }),
                Some(Constant::Utf8("setString".to_owned())),
                Some(Constant::Methodref { class_index: 32, name_and_type_index: 33 }),
                Some(Constant::Class { name_index: 34 }),
                Some(Constant::NameAndType { name_index: 35, descriptor_index: 36 }),
                Some(Constant::Utf8("java/lang/String".to_owned())),
                Some(Constant::Utf8("length".to_owned())),
                Some(Constant::Utf8("()I".to_owned())),
                Some(Constant::Fieldref { class_index: 10, name_and_type_index: 38 }),
                Some(Constant::NameAndType { name_index: 39, descriptor_index: 23 }),
                Some(Constant::Utf8("constraints".to_owned())),
                Some(Constant::Methodref { class_index: 10, name_and_type_index: 41 }),
                Some(Constant::NameAndType { name_index: 42, descriptor_index: 43 }),
                Some(Constant::Utf8("valid".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;I)Z".to_owned())),
                Some(Constant::Fieldref { class_index: 10, name_and_type_index: 45 }),
                Some(Constant::NameAndType { name_index: 46, descriptor_index: 23 }),
                Some(Constant::Utf8("caret".to_owned())),
                Some(Constant::Methodref { class_index: 10, name_and_type_index: 48 }),
                Some(Constant::NameAndType { name_index: 49, descriptor_index: 19 }),
                Some(Constant::Utf8("invalidate".to_owned())),
                Some(Constant::Class { name_index: 51 }),
                Some(Constant::Utf8("java/lang/NullPointerException".to_owned())),
                Some(Constant::Methodref { class_index: 50, name_and_type_index: 18 }),
                Some(Constant::Class { name_index: 54 }),
                Some(Constant::Utf8("java/lang/ArrayIndexOutOfBoundsException".to_owned())),
                Some(Constant::Methodref { class_index: 53, name_and_type_index: 18 }),
                Some(Constant::Methodref { class_index: 32, name_and_type_index: 57 }),
                Some(Constant::NameAndType { name_index: 58, descriptor_index: 59 }),
                Some(Constant::Utf8("getChars".to_owned())),
                Some(Constant::Utf8("(II[CI)V".to_owned())),
                Some(Constant::Methodref { class_index: 10, name_and_type_index: 61 }),
                Some(Constant::NameAndType { name_index: 62, descriptor_index: 63 }),
                Some(Constant::Utf8("check".to_owned())),
                Some(Constant::Utf8("(III)V".to_owned())),
                Some(Constant::Methodref { class_index: 32, name_and_type_index: 65 }),
                Some(Constant::NameAndType { name_index: 66, descriptor_index: 67 }),
                Some(Constant::Utf8("valueOf".to_owned())),
                Some(Constant::Utf8("([CII)Ljava/lang/String;".to_owned())),
                Some(Constant::Class { name_index: 69 }),
                Some(Constant::Utf8("java/lang/StringIndexOutOfBoundsException".to_owned())),
                Some(Constant::Methodref { class_index: 68, name_and_type_index: 18 }),
                Some(Constant::Methodref { class_index: 32, name_and_type_index: 72 }),
                Some(Constant::NameAndType { name_index: 73, descriptor_index: 74 }),
                Some(Constant::Utf8("substring".to_owned())),
                Some(Constant::Utf8("(II)Ljava/lang/String;".to_owned())),
                Some(Constant::Methodref { class_index: 32, name_and_type_index: 76 }),
                Some(Constant::NameAndType { name_index: 77, descriptor_index: 78 }),
                Some(Constant::Utf8("concat".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;)Ljava/lang/String;".to_owned())),
                Some(Constant::Methodref { class_index: 32, name_and_type_index: 80 }),
                Some(Constant::NameAndType { name_index: 73, descriptor_index: 81 }),
                Some(Constant::Utf8("(I)Ljava/lang/String;".to_owned())),
                Some(Constant::Methodref { class_index: 10, name_and_type_index: 83 }),
                Some(Constant::NameAndType { name_index: 84, descriptor_index: 85 }),
                Some(Constant::Utf8("insert".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;I)V".to_owned())),
                Some(Constant::Integer(65535)),
                Some(Constant::Methodref { class_index: 10, name_and_type_index: 88 }),
                Some(Constant::NameAndType { name_index: 89, descriptor_index: 90 }),
                Some(Constant::Utf8("getLabel".to_owned())),
                Some(Constant::Utf8("()Ljava/lang/String;".to_owned())),
                Some(Constant::Methodref { class_index: 92, name_and_type_index: 93 }),
                Some(Constant::Class { name_index: 94 }),
                Some(Constant::NameAndType { name_index: 95, descriptor_index: 96 }),
                Some(Constant::Utf8("javax/microedition/lcdui/Font".to_owned())),
                Some(Constant::Utf8("getDefaultFont".to_owned())),
                Some(Constant::Utf8("()Ljavax/microedition/lcdui/Font;".to_owned())),
                Some(Constant::Methodref { class_index: 92, name_and_type_index: 98 }),
                Some(Constant::NameAndType { name_index: 99, descriptor_index: 36 }),
                Some(Constant::Utf8("getHeight".to_owned())),
                Some(Constant::Methodref { class_index: 101, name_and_type_index: 102 }),
                Some(Constant::Class { name_index: 103 }),
                Some(Constant::NameAndType { name_index: 104, descriptor_index: 105 }),
                Some(Constant::Utf8("javax/microedition/lcdui/Graphics".to_owned())),
                Some(Constant::Utf8("setFont".to_owned())),
                Some(Constant::Utf8("(Ljavax/microedition/lcdui/Font;)V".to_owned())),
                Some(Constant::Methodref { class_index: 101, name_and_type_index: 107 }),
                Some(Constant::NameAndType { name_index: 108, descriptor_index: 27 }),
                Some(Constant::Utf8("setColor".to_owned())),
                Some(Constant::Methodref { class_index: 101, name_and_type_index: 110 }),
                Some(Constant::NameAndType { name_index: 111, descriptor_index: 112 }),
                Some(Constant::Utf8("drawString".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;III)V".to_owned())),
                Some(Constant::Integer(2379678)),
                Some(Constant::Integer(7829367)),
                Some(Constant::Methodref { class_index: 101, name_and_type_index: 116 }),
                Some(Constant::NameAndType { name_index: 117, descriptor_index: 118 }),
                Some(Constant::Utf8("drawRect".to_owned())),
                Some(Constant::Utf8("(IIII)V".to_owned())),
                Some(Constant::Integer(16777215)),
                Some(Constant::Integer(65536)),
                Some(Constant::Methodref { class_index: 10, name_and_type_index: 122 }),
                Some(Constant::NameAndType { name_index: 123, descriptor_index: 81 }),
                Some(Constant::Utf8("stars".to_owned())),
                Some(Constant::Integer(131072)),
                Some(Constant::Methodref { class_index: 10, name_and_type_index: 126 }),
                Some(Constant::NameAndType { name_index: 127, descriptor_index: 128 }),
                Some(Constant::Utf8("delete".to_owned())),
                Some(Constant::Utf8("(II)V".to_owned())),
                Some(Constant::Methodref { class_index: 32, name_and_type_index: 130 }),
                Some(Constant::NameAndType { name_index: 66, descriptor_index: 131 }),
                Some(Constant::Utf8("(C)Ljava/lang/String;".to_owned())),
                Some(Constant::Methodref { class_index: 32, name_and_type_index: 133 }),
                Some(Constant::NameAndType { name_index: 134, descriptor_index: 135 }),
                Some(Constant::Utf8("charAt".to_owned())),
                Some(Constant::Utf8("(I)C".to_owned())),
                Some(Constant::Methodref { class_index: 32, name_and_type_index: 137 }),
                Some(Constant::NameAndType { name_index: 66, descriptor_index: 138 }),
                Some(Constant::Utf8("([C)Ljava/lang/String;".to_owned())),
                Some(Constant::Utf8("ANY".to_owned())),
                Some(Constant::Utf8("ConstantValue".to_owned())),
                Some(Constant::Integer(0)),
                Some(Constant::Utf8("EMAILADDR".to_owned())),
                Some(Constant::Integer(1)),
                Some(Constant::Utf8("NUMERIC".to_owned())),
                Some(Constant::Integer(2)),
                Some(Constant::Utf8("PHONENUMBER".to_owned())),
                Some(Constant::Integer(3)),
                Some(Constant::Utf8("URL".to_owned())),
                Some(Constant::Integer(4)),
                Some(Constant::Utf8("DECIMAL".to_owned())),
                Some(Constant::Integer(5)),
                Some(Constant::Utf8("CONSTRAINT_MASK".to_owned())),
                Some(Constant::Utf8("PASSWORD".to_owned())),
                Some(Constant::Utf8("UNEDITABLE".to_owned())),
                Some(Constant::Utf8("SENSITIVE".to_owned())),
                Some(Constant::Integer(262144)),
                Some(Constant::Utf8("NON_PREDICTIVE".to_owned())),
                Some(Constant::Integer(524288)),
                Some(Constant::Utf8("INITIAL_CAPS_WORD".to_owned())),
                Some(Constant::Integer(1048576)),
                Some(Constant::Utf8("INITIAL_CAPS_SENTENCE".to_owned())),
                Some(Constant::Integer(2097152)),
                Some(Constant::Utf8("(Ljava/lang/String;Ljava/lang/String;II)V".to_owned())),
                Some(Constant::Utf8("Code".to_owned())),
                Some(Constant::Utf8("LineNumberTable".to_owned())),
                Some(Constant::Utf8("StackMapTable".to_owned())),
                Some(Constant::Utf8("getString".to_owned())),
                Some(Constant::Utf8("([C)I".to_owned())),
                Some(Constant::Utf8("setChars".to_owned())),
                Some(Constant::Utf8("([CII)V".to_owned())),
                Some(Constant::Utf8("([CIII)V".to_owned())),
                Some(Constant::Utf8("getMaxSize".to_owned())),
                Some(Constant::Utf8("setMaxSize".to_owned())),
                Some(Constant::Utf8("(I)I".to_owned())),
                Some(Constant::Utf8("size".to_owned())),
                Some(Constant::Utf8("getCaretPosition".to_owned())),
                Some(Constant::Utf8("getConstraints".to_owned())),
                Some(Constant::Utf8("__height".to_owned())),
                Some(Constant::Utf8("__paint".to_owned())),
                Some(Constant::Utf8("(Ljavax/microedition/lcdui/Graphics;IIIZ)V".to_owned())),
                Some(Constant::Utf8("__key".to_owned())),
                Some(Constant::Class { name_index: 183 }),
                Some(Constant::Utf8("[C".to_owned())),
                Some(Constant::Utf8("SourceFile".to_owned())),
                Some(Constant::Utf8("generated_bootstrap.rs".to_owned())),
            ],
            access_flags: 33,
            this_class: 10,
            super_class: 2,
            interfaces: vec![],
            fields: vec![
                Member { access_flags: 25, name_index: 139, descriptor_index: 23, attributes: vec![
                    Attribute::Raw { name_index: 140, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x8d,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 142, descriptor_index: 23, attributes: vec![
                    Attribute::Raw { name_index: 140, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x8f,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 144, descriptor_index: 23, attributes: vec![
                    Attribute::Raw { name_index: 140, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x91,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 146, descriptor_index: 23, attributes: vec![
                    Attribute::Raw { name_index: 140, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x93,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 148, descriptor_index: 23, attributes: vec![
                    Attribute::Raw { name_index: 140, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x95,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 150, descriptor_index: 23, attributes: vec![
                    Attribute::Raw { name_index: 140, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x97,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 152, descriptor_index: 23, attributes: vec![
                    Attribute::Raw { name_index: 140, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x56,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 153, descriptor_index: 23, attributes: vec![
                    Attribute::Raw { name_index: 140, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x78,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 154, descriptor_index: 23, attributes: vec![
                    Attribute::Raw { name_index: 140, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x7c,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 155, descriptor_index: 23, attributes: vec![
                    Attribute::Raw { name_index: 140, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x9c,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 157, descriptor_index: 23, attributes: vec![
                    Attribute::Raw { name_index: 140, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x9e,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 159, descriptor_index: 23, attributes: vec![
                    Attribute::Raw { name_index: 140, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0xa0,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 161, descriptor_index: 23, attributes: vec![
                    Attribute::Raw { name_index: 140, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0xa2,
                    ] },
                ] },
                Member { access_flags: 2, name_index: 13, descriptor_index: 14, attributes: Vec::new() },
                Member { access_flags: 2, name_index: 22, descriptor_index: 23, attributes: Vec::new() },
                Member { access_flags: 2, name_index: 39, descriptor_index: 23, attributes: Vec::new() },
                Member { access_flags: 2, name_index: 46, descriptor_index: 23, attributes: Vec::new() },
            ],
            methods: vec![
                Member { access_flags: 1, name_index: 5, descriptor_index: 163, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 164, max_stack: 2, max_locals: 5, code: vec![
                        0x2a, 0x2b, 0xb7, 0x00, 0x01, 0x2a, 0x12, 0x07, 0xb5, 0x00, 0x09, 0x1d, 0x9d, 0x00, 0x0b, 0xbb, 0x00, 0x0f, 0x59, 0xb7,
                        0x00, 0x11, 0xbf, 0x2a, 0x1d, 0xb5, 0x00, 0x14, 0x2a, 0x15, 0x04, 0xb6, 0x00, 0x18, 0x2a, 0x2c, 0xb6, 0x00, 0x1c, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 167, descriptor_index: 90, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 164, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x09, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 30, descriptor_index: 6, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 164, max_stack: 2, max_locals: 2, code: vec![
                        0x2b, 0xc7, 0x00, 0x06, 0x12, 0x07, 0x4c, 0x2b, 0xb6, 0x00, 0x1f, 0x2a, 0xb4, 0x00, 0x14, 0xa3, 0x00, 0x0e, 0x2b, 0x2a,
                        0xb4, 0x00, 0x25, 0xb8, 0x00, 0x28, 0x9a, 0x00, 0x0b, 0xbb, 0x00, 0x0f, 0x59, 0xb7, 0x00, 0x11, 0xbf, 0x2a, 0x2b, 0xb5,
                        0x00, 0x09, 0x2a, 0x2b, 0xb6, 0x00, 0x1f, 0xb5, 0x00, 0x2c, 0x2a, 0xb6, 0x00, 0x2f, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 58, descriptor_index: 168, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 164, max_stack: 5, max_locals: 2, code: vec![
                        0x2b, 0xc7, 0x00, 0x0b, 0xbb, 0x00, 0x32, 0x59, 0xb7, 0x00, 0x34, 0xbf, 0x2b, 0xbe, 0x2a, 0xb4, 0x00, 0x09, 0xb6, 0x00,
                        0x1f, 0xa2, 0x00, 0x0b, 0xbb, 0x00, 0x35, 0x59, 0xb7, 0x00, 0x37, 0xbf, 0x2a, 0xb4, 0x00, 0x09, 0x03, 0x2a, 0xb4, 0x00,
                        0x09, 0xb6, 0x00, 0x1f, 0x2b, 0x03, 0xb6, 0x00, 0x38, 0x2a, 0xb4, 0x00, 0x09, 0xb6, 0x00, 0x1f, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 169, descriptor_index: 170, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 164, max_stack: 4, max_locals: 4, code: vec![
                        0x2b, 0xc7, 0x00, 0x09, 0x2a, 0x01, 0xb6, 0x00, 0x1c, 0xb1, 0x2b, 0xbe, 0x1c, 0x1d, 0xb8, 0x00, 0x3c, 0x2a, 0x2b, 0x1c,
                        0x1d, 0xb8, 0x00, 0x40, 0xb6, 0x00, 0x1c, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 84, descriptor_index: 85, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 164, max_stack: 4, max_locals: 3, code: vec![
                        0x2b, 0xc7, 0x00, 0x0b, 0xbb, 0x00, 0x32, 0x59, 0xb7, 0x00, 0x34, 0xbf, 0x1c, 0x9b, 0x00, 0x0e, 0x1c, 0x2a, 0xb4, 0x00,
                        0x09, 0xb6, 0x00, 0x1f, 0xa4, 0x00, 0x0b, 0xbb, 0x00, 0x44, 0x59, 0xb7, 0x00, 0x46, 0xbf, 0x2a, 0x2a, 0xb4, 0x00, 0x09,
                        0x03, 0x1c, 0xb6, 0x00, 0x47, 0x2b, 0xb6, 0x00, 0x4b, 0x2a, 0xb4, 0x00, 0x09, 0x1c, 0xb6, 0x00, 0x4f, 0xb6, 0x00, 0x4b,
                        0xb6, 0x00, 0x1c, 0x2a, 0x1c, 0x2b, 0xb6, 0x00, 0x1f, 0x60, 0xb5, 0x00, 0x2c, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 84, descriptor_index: 171, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 164, max_stack: 4, max_locals: 5, code: vec![
                        0x2b, 0xc7, 0x00, 0x0b, 0xbb, 0x00, 0x32, 0x59, 0xb7, 0x00, 0x34, 0xbf, 0x2b, 0xbe, 0x1c, 0x1d, 0xb8, 0x00, 0x3c, 0x2a,
                        0x2b, 0x1c, 0x1d, 0xb8, 0x00, 0x40, 0x15, 0x04, 0xb6, 0x00, 0x52, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 127, descriptor_index: 128, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 164, max_stack: 5, max_locals: 3, code: vec![
                        0x2a, 0xb4, 0x00, 0x09, 0xb6, 0x00, 0x1f, 0x1b, 0x1c, 0xb8, 0x00, 0x3c, 0x2a, 0x2a, 0xb4, 0x00, 0x09, 0x03, 0x1b, 0xb6,
                        0x00, 0x47, 0x2a, 0xb4, 0x00, 0x09, 0x1b, 0x1c, 0x60, 0xb6, 0x00, 0x4f, 0xb6, 0x00, 0x4b, 0xb6, 0x00, 0x1c, 0x2a, 0x1b,
                        0xb5, 0x00, 0x2c, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 172, descriptor_index: 36, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 164, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x14, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 173, descriptor_index: 174, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 164, max_stack: 4, max_locals: 2, code: vec![
                        0x1b, 0x9d, 0x00, 0x0b, 0xbb, 0x00, 0x0f, 0x59, 0xb7, 0x00, 0x11, 0xbf, 0x2a, 0xb4, 0x00, 0x09, 0xb6, 0x00, 0x1f, 0x1b,
                        0xa4, 0x00, 0x10, 0x2a, 0x2a, 0xb4, 0x00, 0x09, 0x03, 0x1b, 0xb6, 0x00, 0x47, 0xb5, 0x00, 0x09, 0x2a, 0x1b, 0xb5, 0x00,
                        0x14, 0x2a, 0x2a, 0xb4, 0x00, 0x09, 0xb6, 0x00, 0x1f, 0xb5, 0x00, 0x2c, 0x2a, 0xb6, 0x00, 0x2f, 0x1b, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 175, descriptor_index: 36, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 164, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x09, 0xb6, 0x00, 0x1f, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 176, descriptor_index: 36, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 164, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x2c, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 177, descriptor_index: 36, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 164, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x25, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 26, descriptor_index: 27, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 164, max_stack: 2, max_locals: 3, code: vec![
                        0x1b, 0x12, 0x56, 0x7e, 0x3d, 0x1c, 0x9b, 0x00, 0x08, 0x1c, 0x08, 0xa4, 0x00, 0x0b, 0xbb, 0x00, 0x0f, 0x59, 0xb7, 0x00,
                        0x11, 0xbf, 0x2a, 0xb4, 0x00, 0x09, 0x1b, 0xb8, 0x00, 0x28, 0x9a, 0x00, 0x09, 0x2a, 0x12, 0x07, 0xb5, 0x00, 0x09, 0x2a,
                        0x1b, 0xb5, 0x00, 0x25, 0x2a, 0x2a, 0xb4, 0x00, 0x09, 0xb6, 0x00, 0x1f, 0xb5, 0x00, 0x2c, 0x2a, 0xb6, 0x00, 0x2f, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 0, name_index: 178, descriptor_index: 174, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 164, max_stack: 2, max_locals: 2, code: vec![
                        0x2a, 0xb6, 0x00, 0x57, 0xc7, 0x00, 0x07, 0x03, 0xa7, 0x00, 0x0b, 0xb8, 0x00, 0x5b, 0xb6, 0x00, 0x61, 0x04, 0x60, 0xb8,
                        0x00, 0x5b, 0xb6, 0x00, 0x61, 0x60, 0x10, 0x08, 0x60, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 0, name_index: 179, descriptor_index: 180, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 164, max_stack: 6, max_locals: 8, code: vec![
                        0xb8, 0x00, 0x5b, 0x3a, 0x06, 0x2b, 0x19, 0x06, 0xb6, 0x00, 0x64, 0x2b, 0x03, 0xb6, 0x00, 0x6a, 0x2a, 0xb6, 0x00, 0x57,
                        0xc6, 0x00, 0x19, 0x2b, 0x2a, 0xb6, 0x00, 0x57, 0x1c, 0x1d, 0x10, 0x14, 0xb6, 0x00, 0x6d, 0x1d, 0x19, 0x06, 0xb6, 0x00,
                        0x61, 0x04, 0x60, 0x60, 0x3e, 0x2b, 0x15, 0x05, 0x99, 0x00, 0x08, 0x12, 0x71, 0xa7, 0x00, 0x05, 0x12, 0x72, 0xb6, 0x00,
                        0x6a, 0x2b, 0x1c, 0x1d, 0x15, 0x04, 0x04, 0x64, 0x19, 0x06, 0xb6, 0x00, 0x61, 0x08, 0x60, 0xb6, 0x00, 0x73, 0x2b, 0x15,
                        0x05, 0x99, 0x00, 0x08, 0x12, 0x77, 0xa7, 0x00, 0x04, 0x03, 0xb6, 0x00, 0x6a, 0x2a, 0xb4, 0x00, 0x25, 0x12, 0x78, 0x7e,
                        0x9a, 0x00, 0x0a, 0x2a, 0xb4, 0x00, 0x09, 0xa7, 0x00, 0x0d, 0x2a, 0xb4, 0x00, 0x09, 0xb6, 0x00, 0x1f, 0xb8, 0x00, 0x79,
                        0x3a, 0x07, 0x2b, 0x19, 0x07, 0x1c, 0x06, 0x60, 0x1d, 0x05, 0x60, 0x10, 0x14, 0xb6, 0x00, 0x6d, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 0, name_index: 181, descriptor_index: 27, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 164, max_stack: 3, max_locals: 3, code: vec![
                        0x2a, 0xb4, 0x00, 0x25, 0x12, 0x7c, 0x7e, 0x99, 0x00, 0x04, 0xb1, 0x1b, 0x10, 0xf9, 0x9f, 0x00, 0x09, 0x1b, 0x10, 0x08,
                        0xa0, 0x00, 0x1c, 0x2a, 0xb4, 0x00, 0x09, 0xb6, 0x00, 0x1f, 0x9e, 0x00, 0x11, 0x2a, 0x2a, 0xb4, 0x00, 0x09, 0xb6, 0x00,
                        0x1f, 0x04, 0x64, 0x04, 0xb6, 0x00, 0x7d, 0xb1, 0x1b, 0x10, 0x20, 0xa1, 0x00, 0x17, 0x1b, 0x10, 0x7e, 0xa3, 0x00, 0x11,
                        0x2a, 0xb4, 0x00, 0x09, 0xb6, 0x00, 0x1f, 0x2a, 0xb4, 0x00, 0x14, 0xa0, 0x00, 0x04, 0xb1, 0x2a, 0xb4, 0x00, 0x09, 0x1b,
                        0x92, 0xb8, 0x00, 0x81, 0xb6, 0x00, 0x4b, 0x4d, 0x2c, 0x2a, 0xb4, 0x00, 0x25, 0xb8, 0x00, 0x28, 0x99, 0x00, 0x17, 0x2a,
                        0x2c, 0xb5, 0x00, 0x09, 0x2a, 0x2a, 0xb4, 0x00, 0x09, 0xb6, 0x00, 0x1f, 0xb5, 0x00, 0x2c, 0x2a, 0xb6, 0x00, 0x2f, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 10, name_index: 42, descriptor_index: 43, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 164, max_stack: 2, max_locals: 6, code: vec![
                        0x1b, 0x12, 0x56, 0x7e, 0x3d, 0x2a, 0xb6, 0x00, 0x1f, 0x9a, 0x00, 0x05, 0x04, 0xac, 0x03, 0x36, 0x04, 0x03, 0x3e, 0x1d,
                        0x2a, 0xb6, 0x00, 0x1f, 0xa2, 0x00, 0x9c, 0x2a, 0x1d, 0xb6, 0x00, 0x84, 0x36, 0x05, 0x1c, 0x05, 0xa0, 0x00, 0x1e, 0x15,
                        0x05, 0x10, 0x30, 0xa1, 0x00, 0x0a, 0x15, 0x05, 0x10, 0x39, 0xa4, 0x00, 0x7c, 0x1d, 0x9a, 0x00, 0x0a, 0x15, 0x05, 0x10,
                        0x2d, 0x9f, 0x00, 0x71, 0x03, 0xac, 0x1c, 0x08, 0xa0, 0x00, 0x32, 0x15, 0x05, 0x10, 0x2e, 0xa0, 0x00, 0x10, 0x15, 0x04,
                        0x99, 0x00, 0x05, 0x03, 0xac, 0x04, 0x36, 0x04, 0xa7, 0x00, 0x56, 0x15, 0x05, 0x10, 0x30, 0xa1, 0x00, 0x0a, 0x15, 0x05,
                        0x10, 0x39, 0xa4, 0x00, 0x48, 0x1d, 0x9a, 0x00, 0x0a, 0x15, 0x05, 0x10, 0x2d, 0x9f, 0x00, 0x3d, 0x03, 0xac, 0x1c, 0x06,
                        0xa0, 0x00, 0x36, 0x15, 0x05, 0x10, 0x30, 0xa1, 0x00, 0x0a, 0x15, 0x05, 0x10, 0x39, 0xa4, 0x00, 0x28, 0x15, 0x05, 0x10,
                        0x2b, 0x9f, 0x00, 0x21, 0x15, 0x05, 0x10, 0x2a, 0x9f, 0x00, 0x1a, 0x15, 0x05, 0x10, 0x23, 0x9f, 0x00, 0x13, 0x15, 0x05,
                        0x10, 0x20, 0x9f, 0x00, 0x0c, 0x15, 0x05, 0x10, 0x2d, 0x9f, 0x00, 0x05, 0x03, 0xac, 0x84, 0x03, 0x01, 0xa7, 0xff, 0x62,
                        0x04, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 10, name_index: 62, descriptor_index: 63, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 164, max_stack: 3, max_locals: 3, code: vec![
                        0x1b, 0x9b, 0x00, 0x0e, 0x1c, 0x9b, 0x00, 0x0a, 0x1b, 0x1a, 0x1c, 0x64, 0xa4, 0x00, 0x0b, 0xbb, 0x00, 0x35, 0x59, 0xb7,
                        0x00, 0x37, 0xbf, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 10, name_index: 123, descriptor_index: 81, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 164, max_stack: 3, max_locals: 3, code: vec![
                        0x1a, 0xbc, 0x05, 0x4c, 0x03, 0x3d, 0x1c, 0x1a, 0xa2, 0x00, 0x0e, 0x2b, 0x1c, 0x10, 0x2a, 0x55, 0x84, 0x02, 0x01, 0xa7,
                        0xff, 0xf3, 0x2b, 0xb8, 0x00, 0x88, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
            ],
            attributes: Vec::new(),
        },
        // javax/microedition/lcdui/Ticker
        ClassFile {
            minor_version: 0,
            major_version: 48,
            constant_pool: vec![
                None,
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 3 }),
                Some(Constant::Class { name_index: 4 }),
                Some(Constant::NameAndType { name_index: 5, descriptor_index: 6 }),
                Some(Constant::Utf8("java/lang/Object".to_owned())),
                Some(Constant::Utf8("<init>".to_owned())),
                Some(Constant::Utf8("()V".to_owned())),
                Some(Constant::Methodref { class_index: 8, name_and_type_index: 9 }),
                Some(Constant::Class { name_index: 10 }),
                Some(Constant::NameAndType { name_index: 11, descriptor_index: 12 }),
                Some(Constant::Utf8("javax/microedition/lcdui/Ticker".to_owned())),
                Some(Constant::Utf8("setString".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;)V".to_owned())),
                Some(Constant::Fieldref { class_index: 8, name_and_type_index: 14 }),
                Some(Constant::NameAndType { name_index: 15, descriptor_index: 16 }),
                Some(Constant::Utf8("value".to_owned())),
                Some(Constant::Utf8("Ljava/lang/String;".to_owned())),
                Some(Constant::Class { name_index: 18 }),
                Some(Constant::Utf8("java/lang/NullPointerException".to_owned())),
                Some(Constant::Methodref { class_index: 17, name_and_type_index: 3 }),
                Some(Constant::Utf8("Code".to_owned())),
                Some(Constant::Utf8("LineNumberTable".to_owned())),
                Some(Constant::Utf8("getString".to_owned())),
                Some(Constant::Utf8("()Ljava/lang/String;".to_owned())),
                Some(Constant::Utf8("StackMapTable".to_owned())),
                Some(Constant::Utf8("SourceFile".to_owned())),
                Some(Constant::Utf8("generated_bootstrap.rs".to_owned())),
            ],
            access_flags: 33,
            this_class: 8,
            super_class: 2,
            interfaces: vec![],
            fields: vec![
                Member { access_flags: 2, name_index: 15, descriptor_index: 16, attributes: Vec::new() },
            ],
            methods: vec![
                Member { access_flags: 1, name_index: 5, descriptor_index: 12, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 20, max_stack: 2, max_locals: 2, code: vec![
                        0x2a, 0xb7, 0x00, 0x01, 0x2a, 0x2b, 0xb6, 0x00, 0x07, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 22, descriptor_index: 23, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 20, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x0d, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 11, descriptor_index: 12, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 20, max_stack: 2, max_locals: 2, code: vec![
                        0x2b, 0xc7, 0x00, 0x0b, 0xbb, 0x00, 0x11, 0x59, 0xb7, 0x00, 0x13, 0xbf, 0x2a, 0x2b, 0xb5, 0x00, 0x0d, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
            ],
            attributes: Vec::new(),
        },
    );
}
