//! Typed data output interface and stream encoding.

use super::super::{
    Attribute, ClassFile, CodeAttribute, Constant, Member, append_bootstrap_classes,
    build_bootstrap_class,
};

pub(super) fn append_classes(classes: &mut Vec<ClassFile>) {
    append_bootstrap_classes!(classes;
        // java/io/DataOutput
        ClassFile {
            minor_version: 0,
            major_version: 48,
            constant_pool: vec![
                None,
                Some(Constant::Class { name_index: 2 }),
                Some(Constant::Utf8("java/io/DataOutput".to_owned())),
                Some(Constant::Class { name_index: 4 }),
                Some(Constant::Utf8("java/lang/Object".to_owned())),
                Some(Constant::Utf8("write".to_owned())),
                Some(Constant::Utf8("(I)V".to_owned())),
                Some(Constant::Utf8("Exceptions".to_owned())),
                Some(Constant::Class { name_index: 9 }),
                Some(Constant::Utf8("java/io/IOException".to_owned())),
                Some(Constant::Utf8("([B)V".to_owned())),
                Some(Constant::Utf8("([BII)V".to_owned())),
                Some(Constant::Utf8("writeBoolean".to_owned())),
                Some(Constant::Utf8("(Z)V".to_owned())),
                Some(Constant::Utf8("writeByte".to_owned())),
                Some(Constant::Utf8("writeShort".to_owned())),
                Some(Constant::Utf8("writeChar".to_owned())),
                Some(Constant::Utf8("writeInt".to_owned())),
                Some(Constant::Utf8("writeLong".to_owned())),
                Some(Constant::Utf8("(J)V".to_owned())),
                Some(Constant::Utf8("writeFloat".to_owned())),
                Some(Constant::Utf8("(F)V".to_owned())),
                Some(Constant::Utf8("writeDouble".to_owned())),
                Some(Constant::Utf8("(D)V".to_owned())),
                Some(Constant::Utf8("writeBytes".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;)V".to_owned())),
                Some(Constant::Utf8("writeChars".to_owned())),
                Some(Constant::Utf8("writeUTF".to_owned())),
                Some(Constant::Utf8("SourceFile".to_owned())),
                Some(Constant::Utf8("generated_bootstrap.rs".to_owned())),
            ],
            access_flags: 1537,
            this_class: 1,
            super_class: 3,
            interfaces: vec![],
            fields: Vec::new(),
            methods: vec![
                Member { access_flags: 1025, name_index: 5, descriptor_index: 6, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 5, descriptor_index: 10, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 5, descriptor_index: 11, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 12, descriptor_index: 13, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 14, descriptor_index: 6, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 15, descriptor_index: 6, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 16, descriptor_index: 6, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 17, descriptor_index: 6, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 18, descriptor_index: 19, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 20, descriptor_index: 21, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 22, descriptor_index: 23, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 24, descriptor_index: 25, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 26, descriptor_index: 25, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 27, descriptor_index: 25, attributes: Vec::new() },
            ],
            attributes: Vec::new(),
        },
        // java/io/DataOutputStream
        ClassFile {
            minor_version: 0,
            major_version: 48,
            constant_pool: vec![
                None,
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 3 }),
                Some(Constant::Class { name_index: 4 }),
                Some(Constant::NameAndType { name_index: 5, descriptor_index: 6 }),
                Some(Constant::Utf8("java/io/OutputStream".to_owned())),
                Some(Constant::Utf8("<init>".to_owned())),
                Some(Constant::Utf8("()V".to_owned())),
                Some(Constant::Class { name_index: 8 }),
                Some(Constant::Utf8("java/lang/NullPointerException".to_owned())),
                Some(Constant::Methodref { class_index: 7, name_and_type_index: 3 }),
                Some(Constant::Fieldref { class_index: 11, name_and_type_index: 12 }),
                Some(Constant::Class { name_index: 13 }),
                Some(Constant::NameAndType { name_index: 14, descriptor_index: 15 }),
                Some(Constant::Utf8("java/io/DataOutputStream".to_owned())),
                Some(Constant::Utf8("out".to_owned())),
                Some(Constant::Utf8("Ljava/io/OutputStream;".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 17 }),
                Some(Constant::NameAndType { name_index: 18, descriptor_index: 19 }),
                Some(Constant::Utf8("write".to_owned())),
                Some(Constant::Utf8("(I)V".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 21 }),
                Some(Constant::NameAndType { name_index: 18, descriptor_index: 22 }),
                Some(Constant::Utf8("([BII)V".to_owned())),
                Some(Constant::Methodref { class_index: 11, name_and_type_index: 17 }),
                Some(Constant::Methodref { class_index: 11, name_and_type_index: 25 }),
                Some(Constant::NameAndType { name_index: 26, descriptor_index: 19 }),
                Some(Constant::Utf8("writeShort".to_owned())),
                Some(Constant::Methodref { class_index: 28, name_and_type_index: 29 }),
                Some(Constant::Class { name_index: 30 }),
                Some(Constant::NameAndType { name_index: 31, descriptor_index: 32 }),
                Some(Constant::Utf8("java/lang/Float".to_owned())),
                Some(Constant::Utf8("floatToIntBits".to_owned())),
                Some(Constant::Utf8("(F)I".to_owned())),
                Some(Constant::Methodref { class_index: 11, name_and_type_index: 34 }),
                Some(Constant::NameAndType { name_index: 35, descriptor_index: 19 }),
                Some(Constant::Utf8("writeInt".to_owned())),
                Some(Constant::Methodref { class_index: 37, name_and_type_index: 38 }),
                Some(Constant::Class { name_index: 39 }),
                Some(Constant::NameAndType { name_index: 40, descriptor_index: 41 }),
                Some(Constant::Utf8("java/lang/Double".to_owned())),
                Some(Constant::Utf8("doubleToLongBits".to_owned())),
                Some(Constant::Utf8("(D)J".to_owned())),
                Some(Constant::Methodref { class_index: 11, name_and_type_index: 43 }),
                Some(Constant::NameAndType { name_index: 44, descriptor_index: 45 }),
                Some(Constant::Utf8("writeLong".to_owned())),
                Some(Constant::Utf8("(J)V".to_owned())),
                Some(Constant::Methodref { class_index: 47, name_and_type_index: 48 }),
                Some(Constant::Class { name_index: 49 }),
                Some(Constant::NameAndType { name_index: 50, descriptor_index: 51 }),
                Some(Constant::Utf8("java/lang/String".to_owned())),
                Some(Constant::Utf8("length".to_owned())),
                Some(Constant::Utf8("()I".to_owned())),
                Some(Constant::Methodref { class_index: 47, name_and_type_index: 53 }),
                Some(Constant::NameAndType { name_index: 54, descriptor_index: 55 }),
                Some(Constant::Utf8("charAt".to_owned())),
                Some(Constant::Utf8("(I)C".to_owned())),
                Some(Constant::Methodref { class_index: 11, name_and_type_index: 57 }),
                Some(Constant::NameAndType { name_index: 58, descriptor_index: 19 }),
                Some(Constant::Utf8("writeByte".to_owned())),
                Some(Constant::Methodref { class_index: 11, name_and_type_index: 60 }),
                Some(Constant::NameAndType { name_index: 61, descriptor_index: 19 }),
                Some(Constant::Utf8("writeChar".to_owned())),
                Some(Constant::Integer(65535)),
                Some(Constant::Class { name_index: 64 }),
                Some(Constant::Utf8("java/io/IOException".to_owned())),
                Some(Constant::String { string_index: 66 }),
                Some(Constant::Utf8("encoded string too long".to_owned())),
                Some(Constant::Methodref { class_index: 63, name_and_type_index: 68 }),
                Some(Constant::NameAndType { name_index: 5, descriptor_index: 69 }),
                Some(Constant::Utf8("(Ljava/lang/String;)V".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 71 }),
                Some(Constant::NameAndType { name_index: 72, descriptor_index: 6 }),
                Some(Constant::Utf8("flush".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 74 }),
                Some(Constant::NameAndType { name_index: 75, descriptor_index: 6 }),
                Some(Constant::Utf8("close".to_owned())),
                Some(Constant::Class { name_index: 77 }),
                Some(Constant::Utf8("java/io/DataOutput".to_owned())),
                Some(Constant::Utf8("(Ljava/io/OutputStream;)V".to_owned())),
                Some(Constant::Utf8("Code".to_owned())),
                Some(Constant::Utf8("LineNumberTable".to_owned())),
                Some(Constant::Utf8("StackMapTable".to_owned())),
                Some(Constant::Utf8("Exceptions".to_owned())),
                Some(Constant::Utf8("writeBoolean".to_owned())),
                Some(Constant::Utf8("(Z)V".to_owned())),
                Some(Constant::Utf8("writeFloat".to_owned())),
                Some(Constant::Utf8("(F)V".to_owned())),
                Some(Constant::Utf8("writeDouble".to_owned())),
                Some(Constant::Utf8("(D)V".to_owned())),
                Some(Constant::Utf8("writeBytes".to_owned())),
                Some(Constant::Utf8("writeChars".to_owned())),
                Some(Constant::Utf8("writeUTF".to_owned())),
                Some(Constant::Utf8("SourceFile".to_owned())),
                Some(Constant::Utf8("generated_bootstrap.rs".to_owned())),
            ],
            access_flags: 33,
            this_class: 11,
            super_class: 2,
            interfaces: vec![76],
            fields: vec![
                Member { access_flags: 4, name_index: 14, descriptor_index: 15, attributes: Vec::new() },
            ],
            methods: vec![
                Member { access_flags: 1, name_index: 5, descriptor_index: 78, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 79, max_stack: 2, max_locals: 2, code: vec![
                        0x2a, 0xb7, 0x00, 0x01, 0x2b, 0xc7, 0x00, 0x0b, 0xbb, 0x00, 0x07, 0x59, 0xb7, 0x00, 0x09, 0xbf, 0x2a, 0x2b, 0xb5, 0x00,
                        0x0a, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 18, descriptor_index: 19, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 79, max_stack: 2, max_locals: 2, code: vec![
                        0x2a, 0xb4, 0x00, 0x0a, 0x1b, 0xb6, 0x00, 0x10, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 18, descriptor_index: 22, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 79, max_stack: 4, max_locals: 4, code: vec![
                        0x2a, 0xb4, 0x00, 0x0a, 0x2b, 0x1c, 0x1d, 0xb6, 0x00, 0x14, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 83, descriptor_index: 84, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 79, max_stack: 2, max_locals: 2, code: vec![
                        0x2a, 0x1b, 0x99, 0x00, 0x07, 0x04, 0xa7, 0x00, 0x04, 0x03, 0xb6, 0x00, 0x17, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 58, descriptor_index: 19, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 79, max_stack: 2, max_locals: 2, code: vec![
                        0x2a, 0x1b, 0xb6, 0x00, 0x17, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 26, descriptor_index: 19, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 79, max_stack: 3, max_locals: 2, code: vec![
                        0x2a, 0x1b, 0x10, 0x08, 0x7c, 0xb6, 0x00, 0x17, 0x2a, 0x1b, 0xb6, 0x00, 0x17, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 61, descriptor_index: 19, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 79, max_stack: 2, max_locals: 2, code: vec![
                        0x2a, 0x1b, 0xb6, 0x00, 0x18, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 35, descriptor_index: 19, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 79, max_stack: 3, max_locals: 2, code: vec![
                        0x2a, 0x1b, 0x10, 0x18, 0x7c, 0xb6, 0x00, 0x17, 0x2a, 0x1b, 0x10, 0x10, 0x7c, 0xb6, 0x00, 0x17, 0x2a, 0x1b, 0x10, 0x08,
                        0x7c, 0xb6, 0x00, 0x17, 0x2a, 0x1b, 0xb6, 0x00, 0x17, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 44, descriptor_index: 45, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 79, max_stack: 4, max_locals: 3, code: vec![
                        0x2a, 0x1f, 0x10, 0x38, 0x7d, 0x88, 0xb6, 0x00, 0x17, 0x2a, 0x1f, 0x10, 0x30, 0x7d, 0x88, 0xb6, 0x00, 0x17, 0x2a, 0x1f,
                        0x10, 0x28, 0x7d, 0x88, 0xb6, 0x00, 0x17, 0x2a, 0x1f, 0x10, 0x20, 0x7d, 0x88, 0xb6, 0x00, 0x17, 0x2a, 0x1f, 0x10, 0x18,
                        0x7d, 0x88, 0xb6, 0x00, 0x17, 0x2a, 0x1f, 0x10, 0x10, 0x7d, 0x88, 0xb6, 0x00, 0x17, 0x2a, 0x1f, 0x10, 0x08, 0x7d, 0x88,
                        0xb6, 0x00, 0x17, 0x2a, 0x1f, 0x88, 0xb6, 0x00, 0x17, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 85, descriptor_index: 86, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 79, max_stack: 2, max_locals: 2, code: vec![
                        0x2a, 0x23, 0xb8, 0x00, 0x1b, 0xb6, 0x00, 0x21, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 87, descriptor_index: 88, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 79, max_stack: 3, max_locals: 3, code: vec![
                        0x2a, 0x27, 0xb8, 0x00, 0x24, 0xb6, 0x00, 0x2a, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 89, descriptor_index: 69, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 79, max_stack: 3, max_locals: 3, code: vec![
                        0x03, 0x3d, 0x1c, 0x2b, 0xb6, 0x00, 0x2e, 0xa2, 0x00, 0x12, 0x2a, 0x2b, 0x1c, 0xb6, 0x00, 0x34, 0xb6, 0x00, 0x38, 0x84,
                        0x02, 0x01, 0xa7, 0xff, 0xec, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 90, descriptor_index: 69, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 79, max_stack: 3, max_locals: 3, code: vec![
                        0x03, 0x3d, 0x1c, 0x2b, 0xb6, 0x00, 0x2e, 0xa2, 0x00, 0x12, 0x2a, 0x2b, 0x1c, 0xb6, 0x00, 0x34, 0xb6, 0x00, 0x3b, 0x84,
                        0x02, 0x01, 0xa7, 0xff, 0xec, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 91, descriptor_index: 69, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 79, max_stack: 4, max_locals: 6, code: vec![
                        0x03, 0x3d, 0x03, 0x3e, 0x1d, 0x2b, 0xb6, 0x00, 0x2e, 0xa2, 0x00, 0x48, 0x2b, 0x1d, 0xb6, 0x00, 0x34, 0x36, 0x04, 0x15,
                        0x04, 0x04, 0xa1, 0x00, 0x0e, 0x15, 0x04, 0x10, 0x7f, 0xa3, 0x00, 0x07, 0x04, 0xa7, 0x00, 0x10, 0x15, 0x04, 0x11, 0x07,
                        0xff, 0xa3, 0x00, 0x07, 0x05, 0xa7, 0x00, 0x04, 0x06, 0x36, 0x05, 0x1c, 0x12, 0x3e, 0x15, 0x05, 0x64, 0xa4, 0x00, 0x0d,
                        0xbb, 0x00, 0x3f, 0x59, 0x12, 0x41, 0xb7, 0x00, 0x43, 0xbf, 0x1c, 0x15, 0x05, 0x60, 0x3d, 0x84, 0x03, 0x01, 0xa7, 0xff,
                        0xb6, 0x2a, 0x1c, 0xb6, 0x00, 0x18, 0x03, 0x3e, 0x1d, 0x2b, 0xb6, 0x00, 0x2e, 0xa2, 0x00, 0x75, 0x2b, 0x1d, 0xb6, 0x00,
                        0x34, 0x36, 0x04, 0x15, 0x04, 0x04, 0xa1, 0x00, 0x13, 0x15, 0x04, 0x10, 0x7f, 0xa3, 0x00, 0x0c, 0x2a, 0x15, 0x04, 0xb6,
                        0x00, 0x17, 0xa7, 0x00, 0x52, 0x15, 0x04, 0x11, 0x07, 0xff, 0xa3, 0x00, 0x20, 0x2a, 0x11, 0x00, 0xc0, 0x15, 0x04, 0x10,
                        0x06, 0x7a, 0x80, 0xb6, 0x00, 0x17, 0x2a, 0x11, 0x00, 0x80, 0x15, 0x04, 0x10, 0x3f, 0x7e, 0x80, 0xb6, 0x00, 0x17, 0xa7,
                        0x00, 0x2d, 0x2a, 0x11, 0x00, 0xe0, 0x15, 0x04, 0x10, 0x0c, 0x7a, 0x80, 0xb6, 0x00, 0x17, 0x2a, 0x11, 0x00, 0x80, 0x15,
                        0x04, 0x10, 0x06, 0x7a, 0x10, 0x3f, 0x7e, 0x80, 0xb6, 0x00, 0x17, 0x2a, 0x11, 0x00, 0x80, 0x15, 0x04, 0x10, 0x3f, 0x7e,
                        0x80, 0xb6, 0x00, 0x17, 0x84, 0x03, 0x01, 0xa7, 0xff, 0x89, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 72, descriptor_index: 6, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 79, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x0a, 0xb6, 0x00, 0x46, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 75, descriptor_index: 6, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 79, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x0a, 0xb6, 0x00, 0x49, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
            ],
            attributes: Vec::new(),
        },
    );
}
