//! Typed data input interface and stream decoding.

use super::super::{
    Attribute, ClassFile, CodeAttribute, Constant, Member, append_bootstrap_classes,
    build_bootstrap_class,
};

pub(super) fn append_classes(classes: &mut Vec<ClassFile>) {
    append_bootstrap_classes!(classes;
        // java/io/DataInput
        ClassFile {
            minor_version: 0,
            major_version: 48,
            constant_pool: vec![
                None,
                Some(Constant::Class { name_index: 2 }),
                Some(Constant::Utf8("java/io/DataInput".to_owned())),
                Some(Constant::Class { name_index: 4 }),
                Some(Constant::Utf8("java/lang/Object".to_owned())),
                Some(Constant::Utf8("readFully".to_owned())),
                Some(Constant::Utf8("([B)V".to_owned())),
                Some(Constant::Utf8("Exceptions".to_owned())),
                Some(Constant::Class { name_index: 9 }),
                Some(Constant::Utf8("java/io/IOException".to_owned())),
                Some(Constant::Utf8("([BII)V".to_owned())),
                Some(Constant::Utf8("skipBytes".to_owned())),
                Some(Constant::Utf8("(I)I".to_owned())),
                Some(Constant::Utf8("readBoolean".to_owned())),
                Some(Constant::Utf8("()Z".to_owned())),
                Some(Constant::Utf8("readByte".to_owned())),
                Some(Constant::Utf8("()B".to_owned())),
                Some(Constant::Utf8("readUnsignedByte".to_owned())),
                Some(Constant::Utf8("()I".to_owned())),
                Some(Constant::Utf8("readShort".to_owned())),
                Some(Constant::Utf8("()S".to_owned())),
                Some(Constant::Utf8("readUnsignedShort".to_owned())),
                Some(Constant::Utf8("readChar".to_owned())),
                Some(Constant::Utf8("()C".to_owned())),
                Some(Constant::Utf8("readInt".to_owned())),
                Some(Constant::Utf8("readLong".to_owned())),
                Some(Constant::Utf8("()J".to_owned())),
                Some(Constant::Utf8("readFloat".to_owned())),
                Some(Constant::Utf8("()F".to_owned())),
                Some(Constant::Utf8("readDouble".to_owned())),
                Some(Constant::Utf8("()D".to_owned())),
                Some(Constant::Utf8("readUTF".to_owned())),
                Some(Constant::Utf8("()Ljava/lang/String;".to_owned())),
                Some(Constant::Utf8("SourceFile".to_owned())),
                Some(Constant::Utf8("generated_bootstrap.rs".to_owned())),
            ],
            access_flags: 1537,
            this_class: 1,
            super_class: 3,
            interfaces: vec![],
            fields: Vec::new(),
            methods: vec![
                Member { access_flags: 1025, name_index: 5, descriptor_index: 6, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 5, descriptor_index: 10, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 11, descriptor_index: 12, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 13, descriptor_index: 14, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 15, descriptor_index: 16, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 17, descriptor_index: 18, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 19, descriptor_index: 20, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 21, descriptor_index: 18, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 22, descriptor_index: 23, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 24, descriptor_index: 18, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 25, descriptor_index: 26, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 27, descriptor_index: 28, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 29, descriptor_index: 30, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 31, descriptor_index: 32, attributes: Vec::new() },
            ],
            attributes: Vec::new(),
        },
        // java/io/DataInputStream
        ClassFile {
            minor_version: 0,
            major_version: 48,
            constant_pool: vec![
                None,
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 3 }),
                Some(Constant::Class { name_index: 4 }),
                Some(Constant::NameAndType { name_index: 5, descriptor_index: 6 }),
                Some(Constant::Utf8("java/io/InputStream".to_owned())),
                Some(Constant::Utf8("<init>".to_owned())),
                Some(Constant::Utf8("()V".to_owned())),
                Some(Constant::Class { name_index: 8 }),
                Some(Constant::Utf8("java/lang/NullPointerException".to_owned())),
                Some(Constant::Methodref { class_index: 7, name_and_type_index: 3 }),
                Some(Constant::Fieldref { class_index: 11, name_and_type_index: 12 }),
                Some(Constant::Class { name_index: 13 }),
                Some(Constant::NameAndType { name_index: 14, descriptor_index: 15 }),
                Some(Constant::Utf8("java/io/DataInputStream".to_owned())),
                Some(Constant::Utf8("in".to_owned())),
                Some(Constant::Utf8("Ljava/io/InputStream;".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 17 }),
                Some(Constant::NameAndType { name_index: 18, descriptor_index: 19 }),
                Some(Constant::Utf8("read".to_owned())),
                Some(Constant::Utf8("()I".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 21 }),
                Some(Constant::NameAndType { name_index: 18, descriptor_index: 22 }),
                Some(Constant::Utf8("([BII)I".to_owned())),
                Some(Constant::Methodref { class_index: 11, name_and_type_index: 17 }),
                Some(Constant::Class { name_index: 25 }),
                Some(Constant::Utf8("java/io/EOFException".to_owned())),
                Some(Constant::Methodref { class_index: 24, name_and_type_index: 3 }),
                Some(Constant::Methodref { class_index: 11, name_and_type_index: 28 }),
                Some(Constant::NameAndType { name_index: 29, descriptor_index: 19 }),
                Some(Constant::Utf8("required".to_owned())),
                Some(Constant::Methodref { class_index: 11, name_and_type_index: 31 }),
                Some(Constant::NameAndType { name_index: 32, descriptor_index: 19 }),
                Some(Constant::Utf8("readUnsignedShort".to_owned())),
                Some(Constant::Methodref { class_index: 11, name_and_type_index: 34 }),
                Some(Constant::NameAndType { name_index: 35, descriptor_index: 19 }),
                Some(Constant::Utf8("readInt".to_owned())),
                Some(Constant::Long(4294967295)),
                None,
                Some(Constant::Methodref { class_index: 39, name_and_type_index: 40 }),
                Some(Constant::Class { name_index: 41 }),
                Some(Constant::NameAndType { name_index: 42, descriptor_index: 43 }),
                Some(Constant::Utf8("java/lang/Float".to_owned())),
                Some(Constant::Utf8("intBitsToFloat".to_owned())),
                Some(Constant::Utf8("(I)F".to_owned())),
                Some(Constant::Methodref { class_index: 11, name_and_type_index: 45 }),
                Some(Constant::NameAndType { name_index: 46, descriptor_index: 47 }),
                Some(Constant::Utf8("readLong".to_owned())),
                Some(Constant::Utf8("()J".to_owned())),
                Some(Constant::Methodref { class_index: 49, name_and_type_index: 50 }),
                Some(Constant::Class { name_index: 51 }),
                Some(Constant::NameAndType { name_index: 52, descriptor_index: 53 }),
                Some(Constant::Utf8("java/lang/Double".to_owned())),
                Some(Constant::Utf8("longBitsToDouble".to_owned())),
                Some(Constant::Utf8("(J)D".to_owned())),
                Some(Constant::Methodref { class_index: 11, name_and_type_index: 55 }),
                Some(Constant::NameAndType { name_index: 56, descriptor_index: 57 }),
                Some(Constant::Utf8("readFully".to_owned())),
                Some(Constant::Utf8("([BII)V".to_owned())),
                Some(Constant::Class { name_index: 59 }),
                Some(Constant::Utf8("java/lang/IndexOutOfBoundsException".to_owned())),
                Some(Constant::Methodref { class_index: 58, name_and_type_index: 3 }),
                Some(Constant::Methodref { class_index: 11, name_and_type_index: 21 }),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 63 }),
                Some(Constant::NameAndType { name_index: 64, descriptor_index: 65 }),
                Some(Constant::Utf8("skip".to_owned())),
                Some(Constant::Utf8("(J)J".to_owned())),
                Some(Constant::Class { name_index: 67 }),
                Some(Constant::Utf8("java/io/UTFDataFormatException".to_owned())),
                Some(Constant::Methodref { class_index: 66, name_and_type_index: 3 }),
                Some(Constant::Methodref { class_index: 70, name_and_type_index: 71 }),
                Some(Constant::Class { name_index: 72 }),
                Some(Constant::NameAndType { name_index: 73, descriptor_index: 74 }),
                Some(Constant::Utf8("java/lang/String".to_owned())),
                Some(Constant::Utf8("fromChars".to_owned())),
                Some(Constant::Utf8("([C)Ljava/lang/String;".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 76 }),
                Some(Constant::NameAndType { name_index: 77, descriptor_index: 19 }),
                Some(Constant::Utf8("available".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 79 }),
                Some(Constant::NameAndType { name_index: 80, descriptor_index: 81 }),
                Some(Constant::Utf8("markSupported".to_owned())),
                Some(Constant::Utf8("()Z".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 83 }),
                Some(Constant::NameAndType { name_index: 84, descriptor_index: 85 }),
                Some(Constant::Utf8("mark".to_owned())),
                Some(Constant::Utf8("(I)V".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 87 }),
                Some(Constant::NameAndType { name_index: 88, descriptor_index: 6 }),
                Some(Constant::Utf8("reset".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 90 }),
                Some(Constant::NameAndType { name_index: 91, descriptor_index: 6 }),
                Some(Constant::Utf8("close".to_owned())),
                Some(Constant::Class { name_index: 93 }),
                Some(Constant::Utf8("java/io/DataInput".to_owned())),
                Some(Constant::Utf8("(Ljava/io/InputStream;)V".to_owned())),
                Some(Constant::Utf8("Code".to_owned())),
                Some(Constant::Utf8("LineNumberTable".to_owned())),
                Some(Constant::Utf8("StackMapTable".to_owned())),
                Some(Constant::Utf8("Exceptions".to_owned())),
                Some(Constant::Class { name_index: 100 }),
                Some(Constant::Utf8("java/io/IOException".to_owned())),
                Some(Constant::Utf8("readBoolean".to_owned())),
                Some(Constant::Utf8("readByte".to_owned())),
                Some(Constant::Utf8("()B".to_owned())),
                Some(Constant::Utf8("readUnsignedByte".to_owned())),
                Some(Constant::Utf8("readShort".to_owned())),
                Some(Constant::Utf8("()S".to_owned())),
                Some(Constant::Utf8("readChar".to_owned())),
                Some(Constant::Utf8("()C".to_owned())),
                Some(Constant::Utf8("readFloat".to_owned())),
                Some(Constant::Utf8("()F".to_owned())),
                Some(Constant::Utf8("readDouble".to_owned())),
                Some(Constant::Utf8("()D".to_owned())),
                Some(Constant::Utf8("([B)V".to_owned())),
                Some(Constant::Utf8("skipBytes".to_owned())),
                Some(Constant::Utf8("(I)I".to_owned())),
                Some(Constant::Utf8("readUTF".to_owned())),
                Some(Constant::Utf8("()Ljava/lang/String;".to_owned())),
                Some(Constant::Class { name_index: 119 }),
                Some(Constant::Utf8("[C".to_owned())),
                Some(Constant::Utf8("SourceFile".to_owned())),
                Some(Constant::Utf8("generated_bootstrap.rs".to_owned())),
            ],
            access_flags: 33,
            this_class: 11,
            super_class: 2,
            interfaces: vec![92],
            fields: vec![
                Member { access_flags: 4, name_index: 14, descriptor_index: 15, attributes: Vec::new() },
            ],
            methods: vec![
                Member { access_flags: 1, name_index: 5, descriptor_index: 94, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 95, max_stack: 2, max_locals: 2, code: vec![
                        0x2a, 0xb7, 0x00, 0x01, 0x2a, 0x2b, 0xb5, 0x00, 0x0a, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 18, descriptor_index: 19, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 95, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x0a, 0xb6, 0x00, 0x10, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 18, descriptor_index: 22, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 95, max_stack: 4, max_locals: 4, code: vec![
                        0x2a, 0xb4, 0x00, 0x0a, 0x2b, 0x1c, 0x1d, 0xb6, 0x00, 0x14, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 2, name_index: 29, descriptor_index: 19, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 95, max_stack: 2, max_locals: 2, code: vec![
                        0x2a, 0xb6, 0x00, 0x17, 0x3c, 0x1b, 0x9c, 0x00, 0x0b, 0xbb, 0x00, 0x18, 0x59, 0xb7, 0x00, 0x1a, 0xbf, 0x1b, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 101, descriptor_index: 81, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 95, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb7, 0x00, 0x1b, 0x99, 0x00, 0x07, 0x04, 0xa7, 0x00, 0x04, 0x03, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 102, descriptor_index: 103, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 95, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb7, 0x00, 0x1b, 0x91, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 104, descriptor_index: 19, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 95, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb7, 0x00, 0x1b, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 105, descriptor_index: 106, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 95, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb6, 0x00, 0x1e, 0x93, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 32, descriptor_index: 19, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 95, max_stack: 2, max_locals: 1, code: vec![
                        0x2a, 0xb7, 0x00, 0x1b, 0x10, 0x08, 0x78, 0x2a, 0xb7, 0x00, 0x1b, 0x80, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 107, descriptor_index: 108, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 95, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb6, 0x00, 0x1e, 0x92, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 35, descriptor_index: 19, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 95, max_stack: 3, max_locals: 1, code: vec![
                        0x2a, 0xb7, 0x00, 0x1b, 0x10, 0x18, 0x78, 0x2a, 0xb7, 0x00, 0x1b, 0x10, 0x10, 0x78, 0x80, 0x2a, 0xb7, 0x00, 0x1b, 0x10,
                        0x08, 0x78, 0x80, 0x2a, 0xb7, 0x00, 0x1b, 0x80, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 46, descriptor_index: 47, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 95, max_stack: 6, max_locals: 1, code: vec![
                        0x2a, 0xb6, 0x00, 0x21, 0x85, 0x10, 0x20, 0x79, 0x2a, 0xb6, 0x00, 0x21, 0x85, 0x14, 0x00, 0x24, 0x7f, 0x81, 0xad,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 109, descriptor_index: 110, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 95, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb6, 0x00, 0x21, 0xb8, 0x00, 0x26, 0xae,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 111, descriptor_index: 112, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 95, max_stack: 2, max_locals: 1, code: vec![
                        0x2a, 0xb6, 0x00, 0x2c, 0xb8, 0x00, 0x30, 0xaf,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 56, descriptor_index: 113, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 95, max_stack: 4, max_locals: 2, code: vec![
                        0x2a, 0x2b, 0x03, 0x2b, 0xbe, 0xb6, 0x00, 0x36, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 56, descriptor_index: 57, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 95, max_stack: 4, max_locals: 5, code: vec![
                        0x2b, 0xc7, 0x00, 0x0b, 0xbb, 0x00, 0x07, 0x59, 0xb7, 0x00, 0x09, 0xbf, 0x1c, 0x9b, 0x00, 0x0f, 0x1d, 0x9b, 0x00, 0x0b,
                        0x1c, 0x2b, 0xbe, 0x1d, 0x64, 0xa4, 0x00, 0x0b, 0xbb, 0x00, 0x3a, 0x59, 0xb7, 0x00, 0x3c, 0xbf, 0x1d, 0x9e, 0x00, 0x3c,
                        0x2a, 0x2b, 0x1c, 0x1d, 0xb6, 0x00, 0x3d, 0x36, 0x04, 0x15, 0x04, 0x9c, 0x00, 0x0b, 0xbb, 0x00, 0x18, 0x59, 0xb7, 0x00,
                        0x1a, 0xbf, 0x15, 0x04, 0x9a, 0x00, 0x14, 0x2b, 0x1c, 0x84, 0x02, 0x01, 0x2a, 0xb7, 0x00, 0x1b, 0x91, 0x54, 0x84, 0x03,
                        0xff, 0xa7, 0xff, 0xd3, 0x1c, 0x15, 0x04, 0x60, 0x3d, 0x1d, 0x15, 0x04, 0x64, 0x3e, 0xa7, 0xff, 0xc6, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 114, descriptor_index: 115, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 95, max_stack: 4, max_locals: 5, code: vec![
                        0x03, 0x3d, 0x1c, 0x1b, 0xa2, 0x00, 0x20, 0x2a, 0xb4, 0x00, 0x0a, 0x1b, 0x1c, 0x64, 0x85, 0xb6, 0x00, 0x3e, 0x42, 0x21,
                        0x09, 0x94, 0x9d, 0x00, 0x06, 0xa7, 0x00, 0x0b, 0x1c, 0x21, 0x88, 0x60, 0x3d, 0xa7, 0xff, 0xe1, 0x1c, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 116, descriptor_index: 117, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 95, max_stack: 5, max_locals: 8, code: vec![
                        0x2a, 0xb6, 0x00, 0x1e, 0x3c, 0x1b, 0xbc, 0x05, 0x4d, 0x03, 0x3e, 0x03, 0x36, 0x04, 0x15, 0x04, 0x1b, 0xa2, 0x01, 0x13,
                        0x2a, 0xb7, 0x00, 0x1b, 0x36, 0x05, 0x84, 0x04, 0x01, 0x15, 0x05, 0x04, 0xa1, 0x00, 0x16, 0x15, 0x05, 0x10, 0x7f, 0xa3,
                        0x00, 0x0f, 0x2c, 0x1d, 0x84, 0x03, 0x01, 0x15, 0x05, 0x92, 0x55, 0xa7, 0x00, 0xee, 0x15, 0x05, 0x11, 0x00, 0xe0, 0x7e,
                        0x11, 0x00, 0xc0, 0xa0, 0x00, 0x5e, 0x15, 0x04, 0x1b, 0xa1, 0x00, 0x0b, 0xbb, 0x00, 0x42, 0x59, 0xb7, 0x00, 0x44, 0xbf,
                        0x2a, 0xb7, 0x00, 0x1b, 0x36, 0x06, 0x84, 0x04, 0x01, 0x15, 0x06, 0x11, 0x00, 0xc0, 0x7e, 0x11, 0x00, 0x80, 0xa0, 0x00,
                        0x1b, 0x15, 0x05, 0x11, 0x00, 0xc2, 0xa2, 0x00, 0x1b, 0x15, 0x05, 0x11, 0x00, 0xc0, 0xa0, 0x00, 0x0b, 0x15, 0x06, 0x11,
                        0x00, 0x80, 0x9f, 0x00, 0x0b, 0xbb, 0x00, 0x42, 0x59, 0xb7, 0x00, 0x44, 0xbf, 0x2c, 0x1d, 0x84, 0x03, 0x01, 0x15, 0x05,
                        0x10, 0x1f, 0x7e, 0x10, 0x06, 0x78, 0x15, 0x06, 0x10, 0x3f, 0x7e, 0x80, 0x92, 0x55, 0xa7, 0x00, 0x87, 0x15, 0x05, 0x11,
                        0x00, 0xf0, 0x7e, 0x11, 0x00, 0xe0, 0xa0, 0x00, 0x73, 0x15, 0x04, 0x1b, 0x05, 0x64, 0xa4, 0x00, 0x0b, 0xbb, 0x00, 0x42,
                        0x59, 0xb7, 0x00, 0x44, 0xbf, 0x2a, 0xb7, 0x00, 0x1b, 0x36, 0x06, 0x2a, 0xb7, 0x00, 0x1b, 0x36, 0x07, 0x84, 0x04, 0x02,
                        0x15, 0x06, 0x11, 0x00, 0xc0, 0x7e, 0x11, 0x00, 0x80, 0xa0, 0x00, 0x1f, 0x15, 0x07, 0x11, 0x00, 0xc0, 0x7e, 0x11, 0x00,
                        0x80, 0xa0, 0x00, 0x13, 0x15, 0x05, 0x11, 0x00, 0xe0, 0xa0, 0x00, 0x13, 0x15, 0x06, 0x11, 0x00, 0xa0, 0xa2, 0x00, 0x0b,
                        0xbb, 0x00, 0x42, 0x59, 0xb7, 0x00, 0x44, 0xbf, 0x2c, 0x1d, 0x84, 0x03, 0x01, 0x15, 0x05, 0x10, 0x0f, 0x7e, 0x10, 0x0c,
                        0x78, 0x15, 0x06, 0x10, 0x3f, 0x7e, 0x10, 0x06, 0x78, 0x80, 0x15, 0x07, 0x10, 0x3f, 0x7e, 0x80, 0x92, 0x55, 0xa7, 0x00,
                        0x0b, 0xbb, 0x00, 0x42, 0x59, 0xb7, 0x00, 0x44, 0xbf, 0xa7, 0xfe, 0xed, 0x1d, 0x2c, 0xbe, 0xa0, 0x00, 0x08, 0x2c, 0xb8,
                        0x00, 0x45, 0xb0, 0x1d, 0xbc, 0x05, 0x3a, 0x05, 0x03, 0x36, 0x06, 0x15, 0x06, 0x1d, 0xa2, 0x00, 0x12, 0x19, 0x05, 0x15,
                        0x06, 0x2c, 0x15, 0x06, 0x34, 0x55, 0x84, 0x06, 0x01, 0xa7, 0xff, 0xee, 0x19, 0x05, 0xb8, 0x00, 0x45, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 64, descriptor_index: 65, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 95, max_stack: 3, max_locals: 3, code: vec![
                        0x2a, 0xb4, 0x00, 0x0a, 0x1f, 0xb6, 0x00, 0x3e, 0xad,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 77, descriptor_index: 19, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 95, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x0a, 0xb6, 0x00, 0x4b, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 80, descriptor_index: 81, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 95, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x0a, 0xb6, 0x00, 0x4e, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 84, descriptor_index: 85, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 95, max_stack: 2, max_locals: 2, code: vec![
                        0x2a, 0xb4, 0x00, 0x0a, 0x1b, 0xb6, 0x00, 0x52, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 88, descriptor_index: 6, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 95, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x0a, 0xb6, 0x00, 0x56, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 91, descriptor_index: 6, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 95, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x0a, 0xb6, 0x00, 0x59, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
            ],
            attributes: Vec::new(),
        },
    );
}
