#!/usr/bin/env python3
"""Prepare the locked UI patches for Cargo, with or without Nix (Python 3.11+)."""

import argparse
import fcntl
import hashlib
import io
import json
import os
from pathlib import Path, PurePosixPath
import re
import stat
import subprocess
import sys
import tarfile
import tempfile
import tomllib
import urllib.request


ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "crates/frontend-ui/build-support/sources.json"
STAMP = ".j2play-ui-sources.json"
CONFIG_HEADER = "# Generated by J2Play tools/prepare_ui_sources.py.\n"
MAX_ARCHIVE = 16 * 1024 * 1024
MAX_EXPANDED = 64 * 1024 * 1024
MAX_FILES = 4096


def digest(data):
    return hashlib.sha256(data).hexdigest()


def read_bounded_file(path, limit):
    # O_NONBLOCK lets a broken cache entry fail instead of waiting on a FIFO.
    # Follow regular-file links: Nix supplies archives through a link farm.
    with os.fdopen(os.open(path, os.O_RDONLY | os.O_NONBLOCK), "rb") as source:
        if not stat.S_ISREG(os.fstat(source.fileno()).st_mode):
            raise ValueError(f"Expected a regular UI input file: {path}")
        data = source.read(limit + 1)
    if len(data) > limit:
        raise ValueError(f"UI input exceeds the size limit: {path}")
    return data


def read_manifest(path):
    raw = read_bounded_file(path, MAX_ARCHIVE)
    manifest = json.loads(raw)
    if (not isinstance(manifest, dict) or manifest.get("schema") != 1
            or not isinstance(manifest.get("crates"), list) or not manifest["crates"]):
        raise ValueError("Unsupported UI source manifest")
    fingerprint = hashlib.sha256(Path(__file__).read_bytes() + raw)
    names = set()
    for crate in manifest["crates"]:
        if not isinstance(crate, dict) or any(
                not isinstance(crate.get(key), str) for key in ("name", "version", "sha256")):
            raise ValueError("Invalid UI crate declaration")
        name = crate["name"]
        if not re.fullmatch(r"[a-z][a-z0-9-]*", name) or name in names:
            raise ValueError("Invalid or duplicate UI crate name")
        names.add(name)
        if not re.fullmatch(r"[0-9]+\.[0-9]+\.[0-9]+", crate["version"]):
            raise ValueError("UI crate versions must be exact")
        if not re.fullmatch(r"[0-9a-f]{64}", crate["sha256"]):
            raise ValueError("Invalid UI crate checksum")
        if not isinstance(crate.get("patches"), list) or not crate["patches"]:
            raise ValueError("UI source manifest must declare its patches")
        if crate.get("cargo_override", "path") not in ("path", "patch"):
            raise ValueError("Unknown Cargo override kind")
        crate["patch_bytes"] = []
        for patch in crate["patches"]:
            if not isinstance(patch, str) or Path(patch).name != patch or not patch.endswith(".patch"):
                raise ValueError("UI patches must be files beside the manifest")
            data = read_bounded_file(path.parent / patch, MAX_ARCHIVE)
            fingerprint.update(patch.encode() + b"\0" + data)
            crate["patch_bytes"].append(data)
    return manifest["crates"], fingerprint.hexdigest()


def archive_bytes(crate, directory, offline):
    name = f"{crate['name']}-{crate['version']}.crate"
    cached = directory / name
    if cached.exists():
        data = read_bounded_file(cached, MAX_ARCHIVE)
    else:
        if offline:
            raise ValueError(f"Missing offline UI archive: {cached}")
        url = f"https://static.crates.io/crates/{crate['name']}/{name}"
        print(f"Fetching {url}", file=sys.stderr)
        with urllib.request.urlopen(url, timeout=30) as response:
            data = response.read(MAX_ARCHIVE + 1)
        if len(data) > MAX_ARCHIVE:
            raise ValueError(f"UI archive exceeds the size limit: {name}")
    if digest(data) != crate["sha256"]:
        raise ValueError(f"UI archive checksum mismatch: {name}")
    if not cached.exists():
        directory.mkdir(parents=True, exist_ok=True)
        with tempfile.NamedTemporaryFile(dir=directory, delete=False) as temporary:
            temporary.write(data)
            temporary_path = Path(temporary.name)
        temporary_path.replace(cached)
    return data


def extract_crate(archive, crate, destination):
    """Accept only regular files below the one declared crate root."""
    prefix = f"{crate['name']}-{crate['version']}"
    total = 0
    seen = set()
    with tarfile.open(fileobj=io.BytesIO(archive), mode="r:gz") as contents:
        for count, member in enumerate(contents, 1):
            parts = PurePosixPath(member.name).parts
            if (count > MAX_FILES or not parts or parts[0] != prefix
                    or ".." in parts or PurePosixPath(member.name).is_absolute()
                    or not (member.isfile() or member.isdir())):
                raise ValueError("Unsafe or oversized UI source archive")
            relative = PurePosixPath(*parts[1:])
            if relative in seen:
                raise ValueError("Duplicate UI source archive entry")
            seen.add(relative)
            target = destination.joinpath(*parts[1:])
            if member.isdir():
                target.mkdir(parents=True, exist_ok=True)
                continue
            total += member.size
            if len(parts) < 2 or member.size < 0 or total > MAX_EXPANDED:
                raise ValueError("UI source archive exceeds the expanded size limit")
            target.parent.mkdir(parents=True, exist_ok=True)
            with contents.extractfile(member) as source:
                target.write_bytes(source.read())
    if not (destination / "Cargo.toml").is_file():
        raise ValueError("UI source archive has no Cargo manifest")


def inventory(sources):
    result = {}
    count = total = 0

    def walk_error(error):
        raise error

    for directory, directories, files in os.walk(sources, onerror=walk_error):
        count += len(directories) + len(files) - (Path(directory) == sources and STAMP in files)
        if count > MAX_FILES:
            raise ValueError("Prepared UI sources exceed the file count limit")
        for name in directories + files:
            path = Path(directory) / name
            mode = path.lstat().st_mode
            if stat.S_ISLNK(mode) or not (stat.S_ISREG(mode) or stat.S_ISDIR(mode)):
                raise ValueError("Prepared UI sources must contain only regular files and directories")
            if stat.S_ISREG(mode) and path != sources / STAMP:
                data = read_bounded_file(path, MAX_EXPANDED - total)
                total += len(data)
                result[path.relative_to(sources).as_posix()] = digest(data)
    return result


def verify_sources(sources, fingerprint):
    stamp = json.loads(read_bounded_file(sources / STAMP, MAX_ARCHIVE))
    if (not isinstance(stamp, dict) or stamp.get("fingerprint") != fingerprint
            or stamp.get("files") != inventory(sources)):
        raise ValueError("Prepared UI sources do not match the locked inputs; "
                         "rerun preparation or reopen the dev shell. "
                         "If the cached generation was modified, use a fresh --output directory")


def prepare_sources(manifest_path, output, archives=None, offline=False):
    crates, fingerprint = read_manifest(manifest_path)
    output.mkdir(parents=True, exist_ok=True)
    # Serialize publication and downloads across shells using this build cache.
    with (output / ".lock").open("a") as lock:
        fcntl.flock(lock, fcntl.LOCK_EX)
        sources = output / fingerprint
        if sources.exists():
            verify_sources(sources, fingerprint)
            return sources
        with tempfile.TemporaryDirectory(prefix=".prepare-", dir=output) as temporary:
            staging = Path(temporary) / "sources"
            staging.mkdir()
            for crate in crates:
                archive = archive_bytes(crate, archives or output / "archives", offline)
                destination = staging / crate["name"]
                extract_crate(archive, crate, destination)
                for patch_data in crate["patch_bytes"]:
                    subprocess.run(
                        ["patch", "--batch", "--forward", "--fuzz=0", "--no-backup-if-mismatch",
                         "-p1", "-d", str(destination)],
                        input=patch_data, check=True, timeout=30, stdout=sys.stderr,
                    )
            stamp = {"fingerprint": fingerprint, "files": inventory(staging)}
            (staging / STAMP).write_text(json.dumps(stamp, sort_keys=True, indent=2) + "\n")
            staging.rename(sources)
        return sources


def configure_cargo(sources, cargo_home, extra_paths=(), patch_names=()):
    paths = sorted(path.resolve() for path in sources.iterdir() if path.is_dir())
    paths.extend(path.resolve(strict=True) for path in extra_paths)
    if not paths or any(not (path / "Cargo.toml").is_file() for path in paths):
        raise ValueError("Each Cargo source override must have a Cargo.toml")
    cargo_home.mkdir(parents=True, exist_ok=True)
    config = cargo_home / "config.toml"
    if (cargo_home / "config").exists():
        raise ValueError("The build Cargo home has a legacy config; use a dedicated Cargo home")
    if config.exists():
        previous = read_bounded_file(config, MAX_ARCHIVE).decode("utf-8")
        settings = tomllib.loads(previous)
        # Preserve custom overrides even when they are the only Cargo setting.
        # The old Android script generated only its winit path: migration is
        # safe when every old override is retained in the new configuration.
        retained = settings.get("paths", [])
        owned_patch = settings.get("patch", {})
        valid_patch = (owned_patch == {} or (
            previous.startswith(CONFIG_HEADER)
            and isinstance(owned_patch, dict) and set(owned_patch) == {"crates-io"}
            and isinstance(owned_patch["crates-io"], dict)
            and set(owned_patch["crates-io"]).issubset(patch_names)
            and all(isinstance(value, dict) and set(value) == {"path"}
                    and isinstance(value["path"], str)
                    for value in owned_patch["crates-io"].values())))
        if (set(settings) - {"paths", "patch"} or not valid_patch or not isinstance(retained, list)
                or any(not isinstance(path, str) for path in retained)
                or (not previous.startswith(CONFIG_HEADER)
                    and not set(retained).issubset(str(path) for path in paths))):
            raise ValueError("Refusing to replace custom Cargo settings; use a dedicated Cargo home")
    content = CONFIG_HEADER + "paths = "
    content += json.dumps([str(path) for path in paths if path.name not in patch_names], ensure_ascii=False) + "\n"
    for path in paths:
        if path.name in patch_names:
            content += f'\n[patch.crates-io.{path.name}]\npath = {json.dumps(str(path), ensure_ascii=False)}\n'
    if not config.exists() or config.read_text() != content:
        with tempfile.NamedTemporaryFile(mode="w", encoding="utf-8", dir=cargo_home, delete=False) as temporary:
            temporary.write(content)
            temporary_path = Path(temporary.name)
        temporary_path.replace(config)


def check_cargo_home(manifest_path, cargo_home):
    """Fail before Cargo can silently use missing, stale or damaged overrides."""
    crates, fingerprint = read_manifest(manifest_path)
    if (cargo_home / "config").exists():
        raise ValueError("The build Cargo home has a legacy config; use a dedicated Cargo home")
    settings = tomllib.loads(read_bounded_file(cargo_home / "config.toml", MAX_ARCHIVE).decode("utf-8"))
    paths = settings.get("paths")
    patch_names = {crate["name"] for crate in crates if crate.get("cargo_override") == "patch"}
    patch_tables = settings.get("patch", {})
    if not isinstance(patch_tables, dict):
        raise ValueError("Cargo UI dependency patches are invalid; rerun preparation")
    patches = patch_tables.get("crates-io", {})
    if (not isinstance(patches, dict) or set(patches) != patch_names
            or any(not isinstance(value, dict) or set(value) != {"path"}
                   or not isinstance(value["path"], str) for value in patches.values())):
        raise ValueError("Cargo UI dependency patches are incomplete; rerun preparation")
    if isinstance(paths, list):
        paths = paths + [value["path"] for value in patches.values()]
    if (not isinstance(paths, list) or not paths
            or any(not isinstance(path, str) or not Path(path).is_absolute() for path in paths)):
        raise ValueError("Cargo has no absolute UI overrides; rerun preparation or reopen the dev shell")
    names = {crate["name"] for crate in crates}
    overrides = [Path(path) for path in paths if Path(path).name in names]
    roots = {path.parent for path in overrides}
    if (len(overrides) != len(names) or {path.name for path in overrides} != names
            or len(roots) != 1 or any(not (Path(path) / "Cargo.toml").is_file() for path in paths)):
        raise ValueError("Cargo UI overrides are incomplete; rerun preparation or reopen the dev shell")
    sources = roots.pop()
    verify_sources(sources, fingerprint)
    return sources


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", type=Path, default=MANIFEST)
    parser.add_argument("--output", type=Path, default=ROOT / "target/build-inputs/ui")
    parser.add_argument("--archive-dir", type=Path, help="directory of checksum-verified .crate archives")
    parser.add_argument("--offline", action="store_true", help="require all archives to be cached")
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--prepared", type=Path, help="verify an existing immutable source input, e.g. from Nix")
    mode.add_argument("--check-cargo", action="store_true", help="verify the active build Cargo home without preparing sources")
    parser.add_argument("--cargo-home", type=Path, help="configure a dedicated build Cargo home")
    parser.add_argument("--extra-path", type=Path, action="append", default=[], help="additional Cargo override (Android winit)")
    args = parser.parse_args(argv)
    try:
        manifest = args.manifest.resolve(strict=True)
        if args.extra_path and not args.cargo_home:
            raise ValueError("--extra-path requires --cargo-home")
        if args.check_cargo:
            home = args.cargo_home or os.environ.get("CARGO_HOME")
            if not home:
                raise ValueError("CARGO_HOME is unset; enter the dev shell or configure a dedicated build Cargo home")
            sources = check_cargo_home(manifest, Path(home).resolve(strict=True))
        elif args.prepared:
            sources = args.prepared.resolve(strict=True)
            _, fingerprint = read_manifest(manifest)
            verify_sources(sources, fingerprint)
        else:
            sources = prepare_sources(
                manifest, args.output.resolve(),
                args.archive_dir.resolve() if args.archive_dir else None, args.offline,
            )
        if args.cargo_home and not args.check_cargo:
            configure_cargo(sources, args.cargo_home.resolve(), args.extra_path,
                            [crate["name"] for crate in read_manifest(manifest)[0]
                             if crate.get("cargo_override") == "patch"])
        print(sources)
        return 0
    except (OSError, ValueError, KeyError, tarfile.TarError, subprocess.SubprocessError) as error:
        print(f"Cannot prepare J2Play UI sources: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
