//! Player creation and standalone tone playback.

use super::{
    Attribute, ClassFile, CodeAttribute, Constant, Member, append_bootstrap_classes,
    build_bootstrap_class,
};

pub(super) fn append_manager(classes: &mut Vec<ClassFile>) {
    append_bootstrap_classes!(classes;
        // javax/microedition/media/Manager$TonePump
        ClassFile {
            minor_version: 0,
            major_version: 48,
            constant_pool: vec![
                None,
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 3 }),
                Some(Constant::Class { name_index: 4 }),
                Some(Constant::NameAndType { name_index: 5, descriptor_index: 6 }),
                Some(Constant::Utf8("java/util/TimerTask".to_owned())),
                Some(Constant::Utf8("<init>".to_owned())),
                Some(Constant::Utf8("()V".to_owned())),
                Some(Constant::Fieldref { class_index: 8, name_and_type_index: 9 }),
                Some(Constant::Class { name_index: 10 }),
                Some(Constant::NameAndType { name_index: 11, descriptor_index: 12 }),
                Some(Constant::Utf8("javax/microedition/media/Manager$TonePump".to_owned())),
                Some(Constant::Utf8("generation".to_owned())),
                Some(Constant::Utf8("I".to_owned())),
                Some(Constant::Fieldref { class_index: 8, name_and_type_index: 14 }),
                Some(Constant::NameAndType { name_index: 15, descriptor_index: 12 }),
                Some(Constant::Utf8("remaining".to_owned())),
                Some(Constant::Fieldref { class_index: 8, name_and_type_index: 17 }),
                Some(Constant::NameAndType { name_index: 18, descriptor_index: 19 }),
                Some(Constant::Utf8("timer".to_owned())),
                Some(Constant::Utf8("Ljava/util/Timer;".to_owned())),
                Some(Constant::Methodref { class_index: 21, name_and_type_index: 22 }),
                Some(Constant::Class { name_index: 23 }),
                Some(Constant::NameAndType { name_index: 24, descriptor_index: 6 }),
                Some(Constant::Utf8("javax/microedition/media/Manager".to_owned())),
                Some(Constant::Utf8("access$000".to_owned())),
                Some(Constant::Methodref { class_index: 21, name_and_type_index: 26 }),
                Some(Constant::NameAndType { name_index: 27, descriptor_index: 28 }),
                Some(Constant::Utf8("access$100".to_owned())),
                Some(Constant::Utf8("(ILjava/util/Timer;)V".to_owned())),
                Some(Constant::Utf8("(IILjava/util/Timer;)V".to_owned())),
                Some(Constant::Utf8("Code".to_owned())),
                Some(Constant::Utf8("LineNumberTable".to_owned())),
                Some(Constant::Utf8("run".to_owned())),
                Some(Constant::Utf8("StackMapTable".to_owned())),
                Some(Constant::Utf8("SourceFile".to_owned())),
                Some(Constant::Utf8("generated_bootstrap.rs".to_owned())),
                Some(Constant::Utf8("InnerClasses".to_owned())),
                Some(Constant::Utf8("TonePump".to_owned())),
            ],
            access_flags: 48,
            this_class: 8,
            super_class: 2,
            interfaces: vec![],
            fields: vec![
                Member { access_flags: 18, name_index: 11, descriptor_index: 12, attributes: Vec::new() },
                Member { access_flags: 2, name_index: 15, descriptor_index: 12, attributes: Vec::new() },
                Member { access_flags: 18, name_index: 18, descriptor_index: 19, attributes: Vec::new() },
            ],
            methods: vec![
                Member { access_flags: 0, name_index: 5, descriptor_index: 29, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 30, max_stack: 2, max_locals: 4, code: vec![
                        0x2a, 0xb7, 0x00, 0x01, 0x2a, 0x1b, 0xb5, 0x00, 0x07, 0x2a, 0x1c, 0xb5, 0x00, 0x0d, 0x2a, 0x2d, 0xb5, 0x00, 0x10, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 32, descriptor_index: 6, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 30, max_stack: 3, max_locals: 1, code: vec![
                        0xb8, 0x00, 0x14, 0x2a, 0x59, 0xb4, 0x00, 0x0d, 0x10, 0x0a, 0x64, 0xb5, 0x00, 0x0d, 0x2a, 0xb4, 0x00, 0x0d, 0x9d, 0x00,
                        0x0e, 0x2a, 0xb4, 0x00, 0x07, 0x2a, 0xb4, 0x00, 0x10, 0xb8, 0x00, 0x19, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
            ],
            attributes: Vec::new(),
        },
        // javax/microedition/media/Manager
        ClassFile {
            minor_version: 0,
            major_version: 48,
            constant_pool: vec![
                None,
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 3 }),
                Some(Constant::Class { name_index: 4 }),
                Some(Constant::NameAndType { name_index: 5, descriptor_index: 6 }),
                Some(Constant::Utf8("javax/microedition/media/Manager".to_owned())),
                Some(Constant::Utf8("finishTone".to_owned())),
                Some(Constant::Utf8("(ILjava/util/Timer;)V".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 8 }),
                Some(Constant::NameAndType { name_index: 9, descriptor_index: 10 }),
                Some(Constant::Utf8("pumpTone0".to_owned())),
                Some(Constant::Utf8("()V".to_owned())),
                Some(Constant::Methodref { class_index: 12, name_and_type_index: 13 }),
                Some(Constant::Class { name_index: 14 }),
                Some(Constant::NameAndType { name_index: 15, descriptor_index: 10 }),
                Some(Constant::Utf8("java/lang/Object".to_owned())),
                Some(Constant::Utf8("<init>".to_owned())),
                Some(Constant::Class { name_index: 17 }),
                Some(Constant::Utf8("java/lang/IllegalArgumentException".to_owned())),
                Some(Constant::Methodref { class_index: 16, name_and_type_index: 13 }),
                Some(Constant::Methodref { class_index: 20, name_and_type_index: 21 }),
                Some(Constant::Class { name_index: 22 }),
                Some(Constant::NameAndType { name_index: 23, descriptor_index: 24 }),
                Some(Constant::Utf8("javax/microedition/media/PlayerImpl".to_owned())),
                Some(Constant::Utf8("fromLocator".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;)Ljavax/microedition/media/Player;".to_owned())),
                Some(Constant::Class { name_index: 26 }),
                Some(Constant::Utf8("java/io/ByteArrayOutputStream".to_owned())),
                Some(Constant::Methodref { class_index: 25, name_and_type_index: 13 }),
                Some(Constant::Methodref { class_index: 29, name_and_type_index: 30 }),
                Some(Constant::Class { name_index: 31 }),
                Some(Constant::NameAndType { name_index: 32, descriptor_index: 33 }),
                Some(Constant::Utf8("java/io/InputStream".to_owned())),
                Some(Constant::Utf8("read".to_owned())),
                Some(Constant::Utf8("([B)I".to_owned())),
                Some(Constant::Methodref { class_index: 29, name_and_type_index: 35 }),
                Some(Constant::NameAndType { name_index: 32, descriptor_index: 36 }),
                Some(Constant::Utf8("()I".to_owned())),
                Some(Constant::Methodref { class_index: 25, name_and_type_index: 38 }),
                Some(Constant::NameAndType { name_index: 39, descriptor_index: 36 }),
                Some(Constant::Utf8("size".to_owned())),
                Some(Constant::Integer(8388608)),
                Some(Constant::Class { name_index: 42 }),
                Some(Constant::Utf8("java/io/IOException".to_owned())),
                Some(Constant::String { string_index: 44 }),
                Some(Constant::Utf8("media stream exceeds byte limit".to_owned())),
                Some(Constant::Methodref { class_index: 41, name_and_type_index: 46 }),
                Some(Constant::NameAndType { name_index: 15, descriptor_index: 47 }),
                Some(Constant::Utf8("(Ljava/lang/String;)V".to_owned())),
                Some(Constant::Methodref { class_index: 25, name_and_type_index: 49 }),
                Some(Constant::NameAndType { name_index: 50, descriptor_index: 51 }),
                Some(Constant::Utf8("write".to_owned())),
                Some(Constant::Utf8("(I)V".to_owned())),
                Some(Constant::Methodref { class_index: 25, name_and_type_index: 53 }),
                Some(Constant::NameAndType { name_index: 50, descriptor_index: 54 }),
                Some(Constant::Utf8("([BII)V".to_owned())),
                Some(Constant::Methodref { class_index: 25, name_and_type_index: 56 }),
                Some(Constant::NameAndType { name_index: 57, descriptor_index: 58 }),
                Some(Constant::Utf8("toByteArray".to_owned())),
                Some(Constant::Utf8("()[B".to_owned())),
                Some(Constant::Methodref { class_index: 20, name_and_type_index: 60 }),
                Some(Constant::NameAndType { name_index: 61, descriptor_index: 62 }),
                Some(Constant::Utf8("fromBytes".to_owned())),
                Some(Constant::Utf8("([BLjava/lang/String;)Ljavax/microedition/media/Player;".to_owned())),
                Some(Constant::String { string_index: 64 }),
                Some(Constant::Utf8("resource".to_owned())),
                Some(Constant::Methodref { class_index: 66, name_and_type_index: 67 }),
                Some(Constant::Class { name_index: 68 }),
                Some(Constant::NameAndType { name_index: 69, descriptor_index: 70 }),
                Some(Constant::Utf8("java/lang/String".to_owned())),
                Some(Constant::Utf8("equalsIgnoreCase".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;)Z".to_owned())),
                Some(Constant::String { string_index: 72 }),
                Some(Constant::Utf8("audio/x-wav".to_owned())),
                Some(Constant::String { string_index: 74 }),
                Some(Constant::Utf8("audio/midi".to_owned())),
                Some(Constant::String { string_index: 76 }),
                Some(Constant::Utf8("audio/sp-midi".to_owned())),
                Some(Constant::String { string_index: 78 }),
                Some(Constant::Utf8("audio/x-tone-seq".to_owned())),
                Some(Constant::String { string_index: 80 }),
                Some(Constant::Utf8("audio/mpeg".to_owned())),
                Some(Constant::String { string_index: 82 }),
                Some(Constant::Utf8("audio/mp4a-latm".to_owned())),
                Some(Constant::String { string_index: 84 }),
                Some(Constant::Utf8("device".to_owned())),
                Some(Constant::String { string_index: 86 }),
                Some(Constant::Utf8("audio/wav".to_owned())),
                Some(Constant::String { string_index: 88 }),
                Some(Constant::Utf8("audio/wave".to_owned())),
                Some(Constant::String { string_index: 90 }),
                Some(Constant::Utf8("audio/vnd.wave".to_owned())),
                Some(Constant::String { string_index: 92 }),
                Some(Constant::Utf8("audio/mp3".to_owned())),
                Some(Constant::String { string_index: 94 }),
                Some(Constant::Utf8("audio/x-mp3".to_owned())),
                Some(Constant::String { string_index: 96 }),
                Some(Constant::Utf8("audio/mpeg3".to_owned())),
                Some(Constant::String { string_index: 98 }),
                Some(Constant::Utf8("audio/x-mpeg".to_owned())),
                Some(Constant::String { string_index: 100 }),
                Some(Constant::Utf8("audio/mp4".to_owned())),
                Some(Constant::String { string_index: 102 }),
                Some(Constant::Utf8("audio/aac".to_owned())),
                Some(Constant::String { string_index: 104 }),
                Some(Constant::Utf8("audio/x-aac".to_owned())),
                Some(Constant::String { string_index: 106 }),
                Some(Constant::Utf8("audio/x-midi".to_owned())),
                Some(Constant::Fieldref { class_index: 108, name_and_type_index: 109 }),
                Some(Constant::Class { name_index: 110 }),
                Some(Constant::NameAndType { name_index: 111, descriptor_index: 112 }),
                Some(Constant::Utf8("javax/microedition/media/SystemTimeBase".to_owned())),
                Some(Constant::Utf8("INSTANCE".to_owned())),
                Some(Constant::Utf8("Ljavax/microedition/media/SystemTimeBase;".to_owned())),
                Some(Constant::Fieldref { class_index: 2, name_and_type_index: 114 }),
                Some(Constant::NameAndType { name_index: 115, descriptor_index: 116 }),
                Some(Constant::Utf8("toneTimer".to_owned())),
                Some(Constant::Utf8("Ljava/util/Timer;".to_owned())),
                Some(Constant::Methodref { class_index: 118, name_and_type_index: 119 }),
                Some(Constant::Class { name_index: 120 }),
                Some(Constant::NameAndType { name_index: 121, descriptor_index: 10 }),
                Some(Constant::Utf8("java/util/Timer".to_owned())),
                Some(Constant::Utf8("cancel".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 123 }),
                Some(Constant::NameAndType { name_index: 124, descriptor_index: 125 }),
                Some(Constant::Utf8("playTone0".to_owned())),
                Some(Constant::Utf8("(III)V".to_owned())),
                Some(Constant::Fieldref { class_index: 2, name_and_type_index: 127 }),
                Some(Constant::NameAndType { name_index: 128, descriptor_index: 129 }),
                Some(Constant::Utf8("toneGeneration".to_owned())),
                Some(Constant::Utf8("I".to_owned())),
                Some(Constant::Methodref { class_index: 118, name_and_type_index: 13 }),
                Some(Constant::Class { name_index: 132 }),
                Some(Constant::Utf8("javax/microedition/media/Manager$TonePump".to_owned())),
                Some(Constant::Methodref { class_index: 131, name_and_type_index: 134 }),
                Some(Constant::NameAndType { name_index: 15, descriptor_index: 135 }),
                Some(Constant::Utf8("(IILjava/util/Timer;)V".to_owned())),
                Some(Constant::Long(10)),
                None,
                Some(Constant::Methodref { class_index: 118, name_and_type_index: 139 }),
                Some(Constant::NameAndType { name_index: 140, descriptor_index: 141 }),
                Some(Constant::Utf8("schedule".to_owned())),
                Some(Constant::Utf8("(Ljava/util/TimerTask;JJ)V".to_owned())),
                Some(Constant::Utf8("TONE_DEVICE_LOCATOR".to_owned())),
                Some(Constant::Utf8("Ljava/lang/String;".to_owned())),
                Some(Constant::Utf8("ConstantValue".to_owned())),
                Some(Constant::String { string_index: 146 }),
                Some(Constant::Utf8("device://tone".to_owned())),
                Some(Constant::Utf8("MIDI_DEVICE_LOCATOR".to_owned())),
                Some(Constant::String { string_index: 149 }),
                Some(Constant::Utf8("device://midi".to_owned())),
                Some(Constant::Utf8("MAX_STREAM_BYTES".to_owned())),
                Some(Constant::Utf8("Code".to_owned())),
                Some(Constant::Utf8("LineNumberTable".to_owned())),
                Some(Constant::Utf8("createPlayer".to_owned())),
                Some(Constant::Utf8("StackMapTable".to_owned())),
                Some(Constant::Utf8("Exceptions".to_owned())),
                Some(Constant::Class { name_index: 157 }),
                Some(Constant::Utf8("javax/microedition/media/MediaException".to_owned())),
                Some(Constant::Utf8("(Ljava/io/InputStream;Ljava/lang/String;)Ljavax/microedition/media/Player;".to_owned())),
                Some(Constant::Class { name_index: 160 }),
                Some(Constant::Utf8("[B".to_owned())),
                Some(Constant::Utf8("getSupportedContentTypes".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;)[Ljava/lang/String;".to_owned())),
                Some(Constant::Utf8("getSupportedProtocols".to_owned())),
                Some(Constant::Utf8("getSystemTimeBase".to_owned())),
                Some(Constant::Utf8("()Ljavax/microedition/media/TimeBase;".to_owned())),
                Some(Constant::Utf8("playTone".to_owned())),
                Some(Constant::Utf8("access$000".to_owned())),
                Some(Constant::Utf8("access$100".to_owned())),
                Some(Constant::Utf8("SourceFile".to_owned())),
                Some(Constant::Utf8("generated_bootstrap.rs".to_owned())),
                Some(Constant::Utf8("InnerClasses".to_owned())),
                Some(Constant::Utf8("TonePump".to_owned())),
            ],
            access_flags: 49,
            this_class: 2,
            super_class: 12,
            interfaces: vec![],
            fields: vec![
                Member { access_flags: 25, name_index: 142, descriptor_index: 143, attributes: vec![
                    Attribute::Raw { name_index: 144, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x91,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 147, descriptor_index: 143, attributes: vec![
                    Attribute::Raw { name_index: 144, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x94,
                    ] },
                ] },
                Member { access_flags: 26, name_index: 150, descriptor_index: 129, attributes: vec![
                    Attribute::Raw { name_index: 144, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x28,
                    ] },
                ] },
                Member { access_flags: 10, name_index: 115, descriptor_index: 116, attributes: Vec::new() },
                Member { access_flags: 10, name_index: 128, descriptor_index: 129, attributes: Vec::new() },
            ],
            methods: vec![
                Member { access_flags: 2, name_index: 15, descriptor_index: 10, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 151, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb7, 0x00, 0x0b, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 9, name_index: 153, descriptor_index: 24, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 151, max_stack: 2, max_locals: 1, code: vec![
                        0x2a, 0xc7, 0x00, 0x0b, 0xbb, 0x00, 0x10, 0x59, 0xb7, 0x00, 0x12, 0xbf, 0x2a, 0xb8, 0x00, 0x13, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 9, name_index: 153, descriptor_index: 158, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 151, max_stack: 4, max_locals: 6, code: vec![
                        0x2a, 0xc6, 0x00, 0x07, 0x2b, 0xc7, 0x00, 0x0b, 0xbb, 0x00, 0x10, 0x59, 0xb7, 0x00, 0x12, 0xbf, 0xbb, 0x00, 0x19, 0x59,
                        0xb7, 0x00, 0x1b, 0x4d, 0x11, 0x04, 0x00, 0xbc, 0x08, 0x4e, 0x2a, 0x2d, 0xb6, 0x00, 0x1c, 0x59, 0x36, 0x04, 0x9b, 0x00,
                        0x53, 0x15, 0x04, 0x9a, 0x00, 0x2d, 0x2a, 0xb6, 0x00, 0x22, 0x36, 0x05, 0x15, 0x05, 0x9c, 0x00, 0x06, 0xa7, 0x00, 0x40,
                        0x2c, 0xb6, 0x00, 0x25, 0x12, 0x28, 0xa0, 0x00, 0x0d, 0xbb, 0x00, 0x29, 0x59, 0x12, 0x2b, 0xb7, 0x00, 0x2d, 0xbf, 0x2c,
                        0x15, 0x05, 0xb6, 0x00, 0x30, 0xa7, 0xff, 0xc9, 0x2c, 0xb6, 0x00, 0x25, 0x12, 0x28, 0x15, 0x04, 0x64, 0xa4, 0x00, 0x0d,
                        0xbb, 0x00, 0x29, 0x59, 0x12, 0x2b, 0xb7, 0x00, 0x2d, 0xbf, 0x2c, 0x2d, 0x03, 0x15, 0x04, 0xb6, 0x00, 0x34, 0xa7, 0xff,
                        0xa8, 0x2c, 0xb6, 0x00, 0x37, 0x2b, 0xb8, 0x00, 0x3b, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 9, name_index: 161, descriptor_index: 162, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 151, max_stack: 4, max_locals: 1, code: vec![
                        0x2a, 0xc6, 0x00, 0x0c, 0x2a, 0x12, 0x3f, 0xb6, 0x00, 0x41, 0x99, 0x00, 0x27, 0x10, 0x06, 0xbd, 0x00, 0x42, 0x59, 0x03,
                        0x12, 0x47, 0x53, 0x59, 0x04, 0x12, 0x49, 0x53, 0x59, 0x05, 0x12, 0x4b, 0x53, 0x59, 0x06, 0x12, 0x4d, 0x53, 0x59, 0x07,
                        0x12, 0x4f, 0x53, 0x59, 0x08, 0x12, 0x51, 0x53, 0xb0, 0x2a, 0x12, 0x53, 0xb6, 0x00, 0x41, 0x99, 0x00, 0x12, 0x05, 0xbd,
                        0x00, 0x42, 0x59, 0x03, 0x12, 0x49, 0x53, 0x59, 0x04, 0x12, 0x4d, 0x53, 0xb0, 0x03, 0xbd, 0x00, 0x42, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 9, name_index: 163, descriptor_index: 162, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 151, max_stack: 4, max_locals: 1, code: vec![
                        0x2a, 0xc7, 0x00, 0x12, 0x05, 0xbd, 0x00, 0x42, 0x59, 0x03, 0x12, 0x53, 0x53, 0x59, 0x04, 0x12, 0x3f, 0x53, 0xb0, 0x2a,
                        0x12, 0x47, 0xb6, 0x00, 0x41, 0x9a, 0x00, 0x6f, 0x2a, 0x12, 0x55, 0xb6, 0x00, 0x41, 0x9a, 0x00, 0x66, 0x2a, 0x12, 0x57,
                        0xb6, 0x00, 0x41, 0x9a, 0x00, 0x5d, 0x2a, 0x12, 0x59, 0xb6, 0x00, 0x41, 0x9a, 0x00, 0x54, 0x2a, 0x12, 0x4f, 0xb6, 0x00,
                        0x41, 0x9a, 0x00, 0x4b, 0x2a, 0x12, 0x5b, 0xb6, 0x00, 0x41, 0x9a, 0x00, 0x42, 0x2a, 0x12, 0x5d, 0xb6, 0x00, 0x41, 0x9a,
                        0x00, 0x39, 0x2a, 0x12, 0x5f, 0xb6, 0x00, 0x41, 0x9a, 0x00, 0x30, 0x2a, 0x12, 0x61, 0xb6, 0x00, 0x41, 0x9a, 0x00, 0x27,
                        0x2a, 0x12, 0x63, 0xb6, 0x00, 0x41, 0x9a, 0x00, 0x1e, 0x2a, 0x12, 0x51, 0xb6, 0x00, 0x41, 0x9a, 0x00, 0x15, 0x2a, 0x12,
                        0x65, 0xb6, 0x00, 0x41, 0x9a, 0x00, 0x0c, 0x2a, 0x12, 0x67, 0xb6, 0x00, 0x41, 0x99, 0x00, 0x0d, 0x04, 0xbd, 0x00, 0x42,
                        0x59, 0x03, 0x12, 0x3f, 0x53, 0xb0, 0x2a, 0x12, 0x49, 0xb6, 0x00, 0x41, 0x9a, 0x00, 0x1e, 0x2a, 0x12, 0x69, 0xb6, 0x00,
                        0x41, 0x9a, 0x00, 0x15, 0x2a, 0x12, 0x4b, 0xb6, 0x00, 0x41, 0x9a, 0x00, 0x0c, 0x2a, 0x12, 0x4d, 0xb6, 0x00, 0x41, 0x99,
                        0x00, 0x12, 0x05, 0xbd, 0x00, 0x42, 0x59, 0x03, 0x12, 0x53, 0x53, 0x59, 0x04, 0x12, 0x3f, 0x53, 0xb0, 0x03, 0xbd, 0x00,
                        0x42, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 9, name_index: 164, descriptor_index: 165, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 151, max_stack: 1, max_locals: 0, code: vec![
                        0xb2, 0x00, 0x6b, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 41, name_index: 166, descriptor_index: 125, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 151, max_stack: 6, max_locals: 3, code: vec![
                        0x1a, 0x9b, 0x00, 0x17, 0x1a, 0x10, 0x7f, 0xa3, 0x00, 0x11, 0x1b, 0x9e, 0x00, 0x0d, 0x1c, 0x9b, 0x00, 0x09, 0x1c, 0x10,
                        0x64, 0xa4, 0x00, 0x0b, 0xbb, 0x00, 0x10, 0x59, 0xb7, 0x00, 0x12, 0xbf, 0xb2, 0x00, 0x71, 0xc6, 0x00, 0x09, 0xb2, 0x00,
                        0x71, 0xb6, 0x00, 0x75, 0x1a, 0x1b, 0x1c, 0xb8, 0x00, 0x7a, 0xb2, 0x00, 0x7e, 0x04, 0x60, 0xb3, 0x00, 0x7e, 0xbb, 0x00,
                        0x76, 0x59, 0xb7, 0x00, 0x82, 0xb3, 0x00, 0x71, 0xb2, 0x00, 0x71, 0xbb, 0x00, 0x83, 0x59, 0xb2, 0x00, 0x7e, 0x1b, 0xb2,
                        0x00, 0x71, 0xb7, 0x00, 0x85, 0x14, 0x00, 0x88, 0x14, 0x00, 0x88, 0xb6, 0x00, 0x8a, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 42, name_index: 5, descriptor_index: 6, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 151, max_stack: 2, max_locals: 2, code: vec![
                        0x1a, 0xb2, 0x00, 0x7e, 0xa0, 0x00, 0x12, 0x2b, 0xb2, 0x00, 0x71, 0xa6, 0x00, 0x0b, 0x2b, 0xb6, 0x00, 0x75, 0x01, 0xb3,
                        0x00, 0x71, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 266, name_index: 124, descriptor_index: 125, attributes: Vec::new() },
                Member { access_flags: 266, name_index: 9, descriptor_index: 10, attributes: Vec::new() },
                Member { access_flags: 4104, name_index: 167, descriptor_index: 10, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 151, max_stack: 0, max_locals: 0, code: vec![
                        0xb8, 0x00, 0x07, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 4104, name_index: 168, descriptor_index: 6, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 151, max_stack: 2, max_locals: 2, code: vec![
                        0x1a, 0x2b, 0xb8, 0x00, 0x01, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
            ],
            attributes: Vec::new(),
        },
    );
}
