//! Player lifecycle, listener events and media exceptions.

use super::{
    Attribute, ClassFile, CodeAttribute, Constant, ExceptionHandler, Member,
    append_bootstrap_classes, build_bootstrap_class,
};

pub(super) fn append_player(classes: &mut Vec<ClassFile>) {
    append_bootstrap_classes!(classes;
        // javax/microedition/media/MediaException
        ClassFile {
            minor_version: 0,
            major_version: 48,
            constant_pool: vec![
                None,
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 3 }),
                Some(Constant::Class { name_index: 4 }),
                Some(Constant::NameAndType { name_index: 5, descriptor_index: 6 }),
                Some(Constant::Utf8("java/lang/Exception".to_owned())),
                Some(Constant::Utf8("<init>".to_owned())),
                Some(Constant::Utf8("()V".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 8 }),
                Some(Constant::NameAndType { name_index: 5, descriptor_index: 9 }),
                Some(Constant::Utf8("(Ljava/lang/String;)V".to_owned())),
                Some(Constant::Class { name_index: 11 }),
                Some(Constant::Utf8("javax/microedition/media/MediaException".to_owned())),
                Some(Constant::Utf8("Code".to_owned())),
                Some(Constant::Utf8("LineNumberTable".to_owned())),
                Some(Constant::Utf8("SourceFile".to_owned())),
                Some(Constant::Utf8("generated_bootstrap.rs".to_owned())),
            ],
            access_flags: 33,
            this_class: 10,
            super_class: 2,
            interfaces: vec![],
            fields: Vec::new(),
            methods: vec![
                Member { access_flags: 1, name_index: 5, descriptor_index: 6, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 12, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb7, 0x00, 0x01, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 5, descriptor_index: 9, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 12, max_stack: 2, max_locals: 2, code: vec![
                        0x2a, 0x2b, 0xb7, 0x00, 0x07, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
            ],
            attributes: Vec::new(),
        },
        // javax/microedition/media/Player
        ClassFile {
            minor_version: 0,
            major_version: 48,
            constant_pool: vec![
                None,
                Some(Constant::Class { name_index: 2 }),
                Some(Constant::Utf8("javax/microedition/media/Player".to_owned())),
                Some(Constant::Class { name_index: 4 }),
                Some(Constant::Utf8("java/lang/Object".to_owned())),
                Some(Constant::Class { name_index: 6 }),
                Some(Constant::Utf8("javax/microedition/media/Controllable".to_owned())),
                Some(Constant::Utf8("CLOSED".to_owned())),
                Some(Constant::Utf8("I".to_owned())),
                Some(Constant::Utf8("ConstantValue".to_owned())),
                Some(Constant::Integer(0)),
                Some(Constant::Utf8("UNREALIZED".to_owned())),
                Some(Constant::Integer(100)),
                Some(Constant::Utf8("REALIZED".to_owned())),
                Some(Constant::Integer(200)),
                Some(Constant::Utf8("PREFETCHED".to_owned())),
                Some(Constant::Integer(300)),
                Some(Constant::Utf8("STARTED".to_owned())),
                Some(Constant::Integer(400)),
                Some(Constant::Utf8("TIME_UNKNOWN".to_owned())),
                Some(Constant::Utf8("J".to_owned())),
                Some(Constant::Long(-1)),
                None,
                Some(Constant::Utf8("realize".to_owned())),
                Some(Constant::Utf8("()V".to_owned())),
                Some(Constant::Utf8("Exceptions".to_owned())),
                Some(Constant::Class { name_index: 27 }),
                Some(Constant::Utf8("javax/microedition/media/MediaException".to_owned())),
                Some(Constant::Utf8("prefetch".to_owned())),
                Some(Constant::Utf8("start".to_owned())),
                Some(Constant::Utf8("stop".to_owned())),
                Some(Constant::Utf8("deallocate".to_owned())),
                Some(Constant::Utf8("close".to_owned())),
                Some(Constant::Utf8("setMediaTime".to_owned())),
                Some(Constant::Utf8("(J)J".to_owned())),
                Some(Constant::Utf8("getMediaTime".to_owned())),
                Some(Constant::Utf8("()J".to_owned())),
                Some(Constant::Utf8("getDuration".to_owned())),
                Some(Constant::Utf8("getContentType".to_owned())),
                Some(Constant::Utf8("()Ljava/lang/String;".to_owned())),
                Some(Constant::Utf8("getState".to_owned())),
                Some(Constant::Utf8("()I".to_owned())),
                Some(Constant::Utf8("setLoopCount".to_owned())),
                Some(Constant::Utf8("(I)V".to_owned())),
                Some(Constant::Utf8("setTimeBase".to_owned())),
                Some(Constant::Utf8("(Ljavax/microedition/media/TimeBase;)V".to_owned())),
                Some(Constant::Utf8("getTimeBase".to_owned())),
                Some(Constant::Utf8("()Ljavax/microedition/media/TimeBase;".to_owned())),
                Some(Constant::Utf8("addPlayerListener".to_owned())),
                Some(Constant::Utf8("(Ljavax/microedition/media/PlayerListener;)V".to_owned())),
                Some(Constant::Utf8("removePlayerListener".to_owned())),
                Some(Constant::Utf8("SourceFile".to_owned())),
                Some(Constant::Utf8("generated_bootstrap.rs".to_owned())),
            ],
            access_flags: 1537,
            this_class: 1,
            super_class: 3,
            interfaces: vec![5],
            fields: vec![
                Member { access_flags: 25, name_index: 7, descriptor_index: 8, attributes: vec![
                    Attribute::Raw { name_index: 9, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x0a,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 11, descriptor_index: 8, attributes: vec![
                    Attribute::Raw { name_index: 9, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x0c,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 13, descriptor_index: 8, attributes: vec![
                    Attribute::Raw { name_index: 9, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x0e,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 15, descriptor_index: 8, attributes: vec![
                    Attribute::Raw { name_index: 9, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x10,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 17, descriptor_index: 8, attributes: vec![
                    Attribute::Raw { name_index: 9, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x12,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 19, descriptor_index: 20, attributes: vec![
                    Attribute::Raw { name_index: 9, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x15,
                    ] },
                ] },
            ],
            methods: vec![
                Member { access_flags: 1025, name_index: 23, descriptor_index: 24, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 28, descriptor_index: 24, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 29, descriptor_index: 24, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 30, descriptor_index: 24, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 31, descriptor_index: 24, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 32, descriptor_index: 24, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 33, descriptor_index: 34, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 35, descriptor_index: 36, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 37, descriptor_index: 36, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 38, descriptor_index: 39, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 40, descriptor_index: 41, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 42, descriptor_index: 43, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 44, descriptor_index: 45, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 46, descriptor_index: 47, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 48, descriptor_index: 49, attributes: Vec::new() },
                Member { access_flags: 1025, name_index: 50, descriptor_index: 49, attributes: Vec::new() },
            ],
            attributes: Vec::new(),
        },
        // javax/microedition/media/PlayerImpl$1
        ClassFile {
            minor_version: 0,
            major_version: 48,
            constant_pool: vec![
                None,
                Some(Constant::Class { name_index: 2 }),
                Some(Constant::Utf8("javax/microedition/media/PlayerImpl$1".to_owned())),
                Some(Constant::Class { name_index: 4 }),
                Some(Constant::Utf8("java/lang/Object".to_owned())),
                Some(Constant::Utf8("SourceFile".to_owned())),
                Some(Constant::Utf8("generated_bootstrap.rs".to_owned())),
                Some(Constant::Utf8("EnclosingMethod".to_owned())),
                Some(Constant::Class { name_index: 9 }),
                Some(Constant::Utf8("javax/microedition/media/PlayerImpl".to_owned())),
                Some(Constant::Utf8("InnerClasses".to_owned())),
            ],
            access_flags: 4128,
            this_class: 1,
            super_class: 3,
            interfaces: vec![],
            fields: Vec::new(),
            methods: Vec::new(),
            attributes: Vec::new(),
        },
        // javax/microedition/media/PlayerImpl$EventTask
        ClassFile {
            minor_version: 0,
            major_version: 48,
            constant_pool: vec![
                None,
                Some(Constant::Class { name_index: 2 }),
                Some(Constant::Utf8("javax/microedition/media/Player".to_owned())),
                Some(Constant::Methodref { class_index: 4, name_and_type_index: 5 }),
                Some(Constant::Class { name_index: 6 }),
                Some(Constant::NameAndType { name_index: 7, descriptor_index: 8 }),
                Some(Constant::Utf8("javax/microedition/media/PlayerImpl$EventTask".to_owned())),
                Some(Constant::Utf8("<init>".to_owned())),
                Some(Constant::Utf8("(Ljavax/microedition/media/PlayerImpl;)V".to_owned())),
                Some(Constant::Fieldref { class_index: 4, name_and_type_index: 10 }),
                Some(Constant::NameAndType { name_index: 11, descriptor_index: 12 }),
                Some(Constant::Utf8("this$0".to_owned())),
                Some(Constant::Utf8("Ljavax/microedition/media/PlayerImpl;".to_owned())),
                Some(Constant::Methodref { class_index: 14, name_and_type_index: 15 }),
                Some(Constant::Class { name_index: 16 }),
                Some(Constant::NameAndType { name_index: 7, descriptor_index: 17 }),
                Some(Constant::Utf8("java/util/TimerTask".to_owned())),
                Some(Constant::Utf8("()V".to_owned())),
                Some(Constant::Methodref { class_index: 19, name_and_type_index: 20 }),
                Some(Constant::Class { name_index: 21 }),
                Some(Constant::NameAndType { name_index: 22, descriptor_index: 23 }),
                Some(Constant::Utf8("javax/microedition/media/PlayerImpl".to_owned())),
                Some(Constant::Utf8("access$100".to_owned())),
                Some(Constant::Utf8("(Ljavax/microedition/media/PlayerImpl;)J".to_owned())),
                Some(Constant::Methodref { class_index: 19, name_and_type_index: 25 }),
                Some(Constant::NameAndType { name_index: 26, descriptor_index: 27 }),
                Some(Constant::Utf8("access$200".to_owned())),
                Some(Constant::Utf8("(J)I".to_owned())),
                Some(Constant::Methodref { class_index: 19, name_and_type_index: 29 }),
                Some(Constant::NameAndType { name_index: 30, descriptor_index: 8 }),
                Some(Constant::Utf8("access$300".to_owned())),
                Some(Constant::Methodref { class_index: 19, name_and_type_index: 32 }),
                Some(Constant::NameAndType { name_index: 33, descriptor_index: 8 }),
                Some(Constant::Utf8("access$400".to_owned())),
                Some(Constant::Utf8("Code".to_owned())),
                Some(Constant::Utf8("LineNumberTable".to_owned())),
                Some(Constant::Utf8("run".to_owned())),
                Some(Constant::Utf8("StackMapTable".to_owned())),
                Some(Constant::Class { name_index: 39 }),
                Some(Constant::Utf8("java/lang/Object".to_owned())),
                Some(Constant::Class { name_index: 41 }),
                Some(Constant::Utf8("java/lang/Throwable".to_owned())),
                Some(Constant::Utf8("(Ljavax/microedition/media/PlayerImpl;Ljavax/microedition/media/PlayerImpl$1;)V".to_owned())),
                Some(Constant::Utf8("SourceFile".to_owned())),
                Some(Constant::Utf8("generated_bootstrap.rs".to_owned())),
                Some(Constant::Utf8("InnerClasses".to_owned())),
                Some(Constant::Utf8("EventTask".to_owned())),
                Some(Constant::Class { name_index: 48 }),
                Some(Constant::Utf8("javax/microedition/media/PlayerImpl$1".to_owned())),
                Some(Constant::Utf8("pumpVolumeEvent".to_owned())),
                Some(Constant::Utf8("()Z".to_owned())),
                Some(Constant::NameAndType { name_index: 49, descriptor_index: 50 }),
                Some(Constant::Methodref { class_index: 19, name_and_type_index: 51 }),
            ],
            access_flags: 48,
            this_class: 4,
            super_class: 14,
            interfaces: vec![],
            fields: vec![
                Member { access_flags: 4112, name_index: 11, descriptor_index: 12, attributes: Vec::new() },
            ],
            methods: vec![
                Member { access_flags: 2, name_index: 7, descriptor_index: 8, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 34, max_stack: 2, max_locals: 2, code: vec![
                        0x2a, 0x2b, 0xb5, 0x00, 0x09, 0x2a, 0xb7, 0x00, 0x0d, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 1, name_index: 36, descriptor_index: 17, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 34, max_stack: 2, max_locals: 3, code: vec![
                        // Deliver a bounded volume batch after the normal pump.
                        // Keep the timer only for playback or a new pending change.
                        0x2a, 0xb4, 0x00, 0x09, 0x59, 0x4c, 0xc2, 0x2a, 0xb4, 0x00, 0x09, 0xb8, 0x00, 0x1c, 0x2a, 0xb4,
                        0x00, 0x09, 0xb6, 0x00, 0x34, 0x9a, 0x00, 0x0a, 0x2a, 0xb4, 0x00, 0x09, 0xb8, 0x00, 0x1f, 0x2b,
                        0xc3, 0xa7, 0x00, 0x08, 0x4d, 0x2b, 0xc3, 0x2c, 0xbf, 0xb1,
                    ], exception_table: vec![
                        ExceptionHandler { start_pc: 7, end_pc: 33, handler_pc: 36, catch_type: 0 },
                        ExceptionHandler { start_pc: 36, end_pc: 39, handler_pc: 36, catch_type: 0 },
                    ], attributes: Vec::new() }),
                ] },
                Member { access_flags: 4096, name_index: 7, descriptor_index: 42, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 34, max_stack: 2, max_locals: 3, code: vec![
                        0x2a, 0x2b, 0xb7, 0x00, 0x03, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
            ],
            attributes: Vec::new(),
        },
        // javax/microedition/media/PlayerImpl
        ClassFile {
            minor_version: 0,
            major_version: 48,
            constant_pool: vec![
                None,
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 3 }),
                Some(Constant::Class { name_index: 4 }),
                Some(Constant::NameAndType { name_index: 5, descriptor_index: 6 }),
                Some(Constant::Utf8("javax/microedition/media/PlayerImpl".to_owned())),
                Some(Constant::Utf8("stopEventPump".to_owned())),
                Some(Constant::Utf8("()V".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 8 }),
                Some(Constant::NameAndType { name_index: 9, descriptor_index: 6 }),
                Some(Constant::Utf8("pumpEvents".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 11 }),
                Some(Constant::NameAndType { name_index: 12, descriptor_index: 13 }),
                Some(Constant::Utf8("state0".to_owned())),
                Some(Constant::Utf8("(J)I".to_owned())),
                Some(Constant::Fieldref { class_index: 2, name_and_type_index: 15 }),
                Some(Constant::NameAndType { name_index: 16, descriptor_index: 17 }),
                Some(Constant::Utf8("handle".to_owned())),
                Some(Constant::Utf8("J".to_owned())),
                Some(Constant::Methodref { class_index: 19, name_and_type_index: 20 }),
                Some(Constant::Class { name_index: 21 }),
                Some(Constant::NameAndType { name_index: 22, descriptor_index: 6 }),
                Some(Constant::Utf8("java/lang/Object".to_owned())),
                Some(Constant::Utf8("<init>".to_owned())),
                Some(Constant::Class { name_index: 24 }),
                Some(Constant::Utf8("java/util/Vector".to_owned())),
                Some(Constant::Methodref { class_index: 23, name_and_type_index: 20 }),
                Some(Constant::Fieldref { class_index: 2, name_and_type_index: 27 }),
                Some(Constant::NameAndType { name_index: 28, descriptor_index: 29 }),
                Some(Constant::Utf8("listeners".to_owned())),
                Some(Constant::Utf8("Ljava/util/Vector;".to_owned())),
                Some(Constant::Fieldref { class_index: 2, name_and_type_index: 31 }),
                Some(Constant::NameAndType { name_index: 32, descriptor_index: 33 }),
                Some(Constant::Utf8("toneDevice".to_owned())),
                Some(Constant::Utf8("Z".to_owned())),
                Some(Constant::Class { name_index: 35 }),
                Some(Constant::Utf8("javax/microedition/media/VolumeControlImpl".to_owned())),
                Some(Constant::Methodref { class_index: 34, name_and_type_index: 37 }),
                Some(Constant::NameAndType { name_index: 22, descriptor_index: 38 }),
                Some(Constant::Utf8("(Ljavax/microedition/media/PlayerImpl;)V".to_owned())),
                Some(Constant::Fieldref { class_index: 2, name_and_type_index: 40 }),
                Some(Constant::NameAndType { name_index: 41, descriptor_index: 42 }),
                Some(Constant::Utf8("volumeControl".to_owned())),
                Some(Constant::Utf8("Ljavax/microedition/media/VolumeControlImpl;".to_owned())),
                Some(Constant::Class { name_index: 44 }),
                Some(Constant::Utf8("javax/microedition/media/ToneControlImpl".to_owned())),
                Some(Constant::Methodref { class_index: 43, name_and_type_index: 37 }),
                Some(Constant::Fieldref { class_index: 2, name_and_type_index: 47 }),
                Some(Constant::NameAndType { name_index: 48, descriptor_index: 49 }),
                Some(Constant::Utf8("toneControl".to_owned())),
                Some(Constant::Utf8("Ljavax/microedition/media/ToneControlImpl;".to_owned())),
                Some(Constant::Class { name_index: 51 }),
                Some(Constant::Utf8("java/lang/IllegalArgumentException".to_owned())),
                Some(Constant::Methodref { class_index: 50, name_and_type_index: 20 }),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 54 }),
                Some(Constant::NameAndType { name_index: 55, descriptor_index: 56 }),
                Some(Constant::Utf8("createLocator0".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;)J".to_owned())),
                Some(Constant::Class { name_index: 58 }),
                Some(Constant::Utf8("javax/microedition/media/Manager".to_owned())),
                Some(Constant::String { string_index: 60 }),
                Some(Constant::Utf8("device://tone".to_owned())),
                Some(Constant::Methodref { class_index: 62, name_and_type_index: 63 }),
                Some(Constant::Class { name_index: 64 }),
                Some(Constant::NameAndType { name_index: 65, descriptor_index: 66 }),
                Some(Constant::Utf8("java/lang/String".to_owned())),
                Some(Constant::Utf8("equals".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/Object;)Z".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 68 }),
                Some(Constant::NameAndType { name_index: 22, descriptor_index: 69 }),
                Some(Constant::Utf8("(JZ)V".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 71 }),
                Some(Constant::NameAndType { name_index: 72, descriptor_index: 73 }),
                Some(Constant::Utf8("createBytes0".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;[B)J".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 75 }),
                Some(Constant::NameAndType { name_index: 76, descriptor_index: 77 }),
                Some(Constant::Utf8("realize0".to_owned())),
                Some(Constant::Utf8("(J)V".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 79 }),
                Some(Constant::NameAndType { name_index: 80, descriptor_index: 77 }),
                Some(Constant::Utf8("prefetch0".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 82 }),
                Some(Constant::NameAndType { name_index: 83, descriptor_index: 77 }),
                Some(Constant::Utf8("start0".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 85 }),
                Some(Constant::NameAndType { name_index: 86, descriptor_index: 6 }),
                Some(Constant::Utf8("startEventPump".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 88 }),
                Some(Constant::NameAndType { name_index: 89, descriptor_index: 77 }),
                Some(Constant::Utf8("stop0".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 91 }),
                Some(Constant::NameAndType { name_index: 92, descriptor_index: 77 }),
                Some(Constant::Utf8("deallocate0".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 94 }),
                Some(Constant::NameAndType { name_index: 95, descriptor_index: 77 }),
                Some(Constant::Utf8("close0".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 97 }),
                Some(Constant::NameAndType { name_index: 98, descriptor_index: 99 }),
                Some(Constant::Utf8("setMediaTime0".to_owned())),
                Some(Constant::Utf8("(JJ)J".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 101 }),
                Some(Constant::NameAndType { name_index: 102, descriptor_index: 103 }),
                Some(Constant::Utf8("mediaTime0".to_owned())),
                Some(Constant::Utf8("(J)J".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 105 }),
                Some(Constant::NameAndType { name_index: 106, descriptor_index: 103 }),
                Some(Constant::Utf8("duration0".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 108 }),
                Some(Constant::NameAndType { name_index: 109, descriptor_index: 110 }),
                Some(Constant::Utf8("contentType0".to_owned())),
                Some(Constant::Utf8("(J)Ljava/lang/String;".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 112 }),
                Some(Constant::NameAndType { name_index: 113, descriptor_index: 114 }),
                Some(Constant::Utf8("setLoopCount0".to_owned())),
                Some(Constant::Utf8("(JI)V".to_owned())),
                Some(Constant::Class { name_index: 116 }),
                Some(Constant::Utf8("javax/microedition/media/Player".to_owned())),
                Some(Constant::Class { name_index: 118 }),
                Some(Constant::Utf8("java/lang/IllegalStateException".to_owned())),
                Some(Constant::Methodref { class_index: 117, name_and_type_index: 20 }),
                Some(Constant::Fieldref { class_index: 121, name_and_type_index: 122 }),
                Some(Constant::Class { name_index: 123 }),
                Some(Constant::NameAndType { name_index: 124, descriptor_index: 125 }),
                Some(Constant::Utf8("javax/microedition/media/SystemTimeBase".to_owned())),
                Some(Constant::Utf8("INSTANCE".to_owned())),
                Some(Constant::Utf8("Ljavax/microedition/media/SystemTimeBase;".to_owned())),
                Some(Constant::Class { name_index: 127 }),
                Some(Constant::Utf8("javax/microedition/media/MediaException".to_owned())),
                Some(Constant::String { string_index: 129 }),
                Some(Constant::Utf8("custom time base is unsupported".to_owned())),
                Some(Constant::Methodref { class_index: 126, name_and_type_index: 131 }),
                Some(Constant::NameAndType { name_index: 22, descriptor_index: 132 }),
                Some(Constant::Utf8("(Ljava/lang/String;)V".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 134 }),
                Some(Constant::NameAndType { name_index: 135, descriptor_index: 6 }),
                Some(Constant::Utf8("ensureOpen".to_owned())),
                Some(Constant::Methodref { class_index: 23, name_and_type_index: 137 }),
                Some(Constant::NameAndType { name_index: 138, descriptor_index: 66 }),
                Some(Constant::Utf8("contains".to_owned())),
                Some(Constant::Methodref { class_index: 23, name_and_type_index: 140 }),
                Some(Constant::NameAndType { name_index: 141, descriptor_index: 142 }),
                Some(Constant::Utf8("addElement".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/Object;)V".to_owned())),
                Some(Constant::Methodref { class_index: 23, name_and_type_index: 144 }),
                Some(Constant::NameAndType { name_index: 145, descriptor_index: 66 }),
                Some(Constant::Utf8("removeElement".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 147 }),
                Some(Constant::NameAndType { name_index: 148, descriptor_index: 6 }),
                Some(Constant::Utf8("ensureControlState".to_owned())),
                Some(Constant::Class { name_index: 150 }),
                Some(Constant::Utf8("javax/microedition/media/Control".to_owned())),
                Some(Constant::String { string_index: 152 }),
                Some(Constant::Utf8("VolumeControl".to_owned())),
                Some(Constant::String { string_index: 154 }),
                Some(Constant::Utf8("javax.microedition.media.control.VolumeControl".to_owned())),
                Some(Constant::String { string_index: 156 }),
                Some(Constant::Utf8("ToneControl".to_owned())),
                Some(Constant::String { string_index: 158 }),
                Some(Constant::Utf8("javax.microedition.media.control.ToneControl".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 160 }),
                Some(Constant::NameAndType { name_index: 161, descriptor_index: 13 }),
                Some(Constant::Utf8("volume0".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 163 }),
                Some(Constant::NameAndType { name_index: 164, descriptor_index: 165 }),
                Some(Constant::Utf8("setVolume0".to_owned())),
                Some(Constant::Utf8("(JI)I".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 167 }),
                Some(Constant::NameAndType { name_index: 168, descriptor_index: 169 }),
                Some(Constant::Utf8("muted0".to_owned())),
                Some(Constant::Utf8("(J)Z".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 171 }),
                Some(Constant::NameAndType { name_index: 172, descriptor_index: 69 }),
                Some(Constant::Utf8("setMuted0".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 174 }),
                Some(Constant::NameAndType { name_index: 175, descriptor_index: 176 }),
                Some(Constant::Utf8("setToneSequence0".to_owned())),
                Some(Constant::Utf8("(J[B)V".to_owned())),
                Some(Constant::Class { name_index: 178 }),
                Some(Constant::Utf8("javax/microedition/media/PlayerListener".to_owned())),
                Some(Constant::String { string_index: 180 }),
                Some(Constant::Utf8("volumeChanged".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 182 }),
                Some(Constant::NameAndType { name_index: 183, descriptor_index: 184 }),
                Some(Constant::Utf8("fireEvent".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;Ljava/lang/Object;)V".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 186 }),
                Some(Constant::NameAndType { name_index: 187, descriptor_index: 13 }),
                Some(Constant::Utf8("nextEvent0".to_owned())),
                Some(Constant::Methodref { class_index: 2, name_and_type_index: 189 }),
                Some(Constant::NameAndType { name_index: 190, descriptor_index: 103 }),
                Some(Constant::Utf8("eventData0".to_owned())),
                Some(Constant::String { string_index: 192 }),
                Some(Constant::Utf8("started".to_owned())),
                Some(Constant::Class { name_index: 194 }),
                Some(Constant::Utf8("java/lang/Long".to_owned())),
                Some(Constant::Methodref { class_index: 193, name_and_type_index: 196 }),
                Some(Constant::NameAndType { name_index: 22, descriptor_index: 77 }),
                Some(Constant::String { string_index: 198 }),
                Some(Constant::Utf8("stopped".to_owned())),
                Some(Constant::String { string_index: 200 }),
                Some(Constant::Utf8("endOfMedia".to_owned())),
                Some(Constant::String { string_index: 202 }),
                Some(Constant::Utf8("closed".to_owned())),
                Some(Constant::Methodref { class_index: 23, name_and_type_index: 204 }),
                Some(Constant::NameAndType { name_index: 205, descriptor_index: 206 }),
                Some(Constant::Utf8("size".to_owned())),
                Some(Constant::Utf8("()I".to_owned())),
                Some(Constant::Methodref { class_index: 23, name_and_type_index: 208 }),
                Some(Constant::NameAndType { name_index: 209, descriptor_index: 210 }),
                Some(Constant::Utf8("copyInto".to_owned())),
                Some(Constant::Utf8("([Ljava/lang/Object;)V".to_owned())),
                Some(Constant::InterfaceMethodref { class_index: 177, name_and_type_index: 212 }),
                Some(Constant::NameAndType { name_index: 213, descriptor_index: 214 }),
                Some(Constant::Utf8("playerUpdate".to_owned())),
                Some(Constant::Utf8("(Ljavax/microedition/media/Player;Ljava/lang/String;Ljava/lang/Object;)V".to_owned())),
                Some(Constant::Class { name_index: 216 }),
                Some(Constant::Utf8("java/lang/RuntimeException".to_owned())),
                Some(Constant::Fieldref { class_index: 2, name_and_type_index: 218 }),
                Some(Constant::NameAndType { name_index: 219, descriptor_index: 220 }),
                Some(Constant::Utf8("eventTimer".to_owned())),
                Some(Constant::Utf8("Ljava/util/Timer;".to_owned())),
                Some(Constant::Class { name_index: 222 }),
                Some(Constant::Utf8("java/util/Timer".to_owned())),
                Some(Constant::Methodref { class_index: 221, name_and_type_index: 20 }),
                Some(Constant::Class { name_index: 225 }),
                Some(Constant::Utf8("javax/microedition/media/PlayerImpl$EventTask".to_owned())),
                Some(Constant::Methodref { class_index: 224, name_and_type_index: 227 }),
                Some(Constant::NameAndType { name_index: 22, descriptor_index: 228 }),
                Some(Constant::Utf8("(Ljavax/microedition/media/PlayerImpl;Ljavax/microedition/media/PlayerImpl$1;)V".to_owned())),
                Some(Constant::Long(10)),
                None,
                Some(Constant::Methodref { class_index: 221, name_and_type_index: 232 }),
                Some(Constant::NameAndType { name_index: 233, descriptor_index: 234 }),
                Some(Constant::Utf8("schedule".to_owned())),
                Some(Constant::Utf8("(Ljava/util/TimerTask;JJ)V".to_owned())),
                Some(Constant::Methodref { class_index: 221, name_and_type_index: 236 }),
                Some(Constant::NameAndType { name_index: 237, descriptor_index: 6 }),
                Some(Constant::Utf8("cancel".to_owned())),
                Some(Constant::Utf8("Code".to_owned())),
                Some(Constant::Utf8("LineNumberTable".to_owned())),
                Some(Constant::Utf8("StackMapTable".to_owned())),
                Some(Constant::Utf8("fromLocator".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;)Ljavax/microedition/media/Player;".to_owned())),
                Some(Constant::Utf8("Exceptions".to_owned())),
                Some(Constant::Utf8("fromBytes".to_owned())),
                Some(Constant::Utf8("([BLjava/lang/String;)Ljavax/microedition/media/Player;".to_owned())),
                Some(Constant::Utf8("realize".to_owned())),
                Some(Constant::Utf8("prefetch".to_owned())),
                Some(Constant::Utf8("start".to_owned())),
                Some(Constant::Utf8("stop".to_owned())),
                Some(Constant::Utf8("deallocate".to_owned())),
                Some(Constant::Utf8("close".to_owned())),
                Some(Constant::Utf8("setMediaTime".to_owned())),
                Some(Constant::Utf8("getMediaTime".to_owned())),
                Some(Constant::Utf8("()J".to_owned())),
                Some(Constant::Utf8("getDuration".to_owned())),
                Some(Constant::Utf8("getContentType".to_owned())),
                Some(Constant::Utf8("()Ljava/lang/String;".to_owned())),
                Some(Constant::Utf8("getState".to_owned())),
                Some(Constant::Utf8("setLoopCount".to_owned())),
                Some(Constant::Utf8("(I)V".to_owned())),
                Some(Constant::Utf8("setTimeBase".to_owned())),
                Some(Constant::Utf8("(Ljavax/microedition/media/TimeBase;)V".to_owned())),
                Some(Constant::Utf8("getTimeBase".to_owned())),
                Some(Constant::Utf8("()Ljavax/microedition/media/TimeBase;".to_owned())),
                Some(Constant::Utf8("addPlayerListener".to_owned())),
                Some(Constant::Utf8("(Ljavax/microedition/media/PlayerListener;)V".to_owned())),
                Some(Constant::Utf8("removePlayerListener".to_owned())),
                Some(Constant::Utf8("getControls".to_owned())),
                Some(Constant::Utf8("()[Ljavax/microedition/media/Control;".to_owned())),
                Some(Constant::Utf8("getControl".to_owned())),
                Some(Constant::Utf8("(Ljava/lang/String;)Ljavax/microedition/media/Control;".to_owned())),
                Some(Constant::Utf8("volumeLevel".to_owned())),
                Some(Constant::Utf8("setVolumeLevel".to_owned())),
                Some(Constant::Utf8("(I)I".to_owned())),
                Some(Constant::Utf8("muted".to_owned())),
                Some(Constant::Utf8("()Z".to_owned())),
                Some(Constant::Utf8("setMuted".to_owned())),
                Some(Constant::Utf8("(Z)V".to_owned())),
                Some(Constant::Utf8("setToneSequence".to_owned())),
                Some(Constant::Utf8("([B)V".to_owned())),
                Some(Constant::Utf8("(Ljavax/microedition/media/control/VolumeControl;)V".to_owned())),
                Some(Constant::Class { name_index: 283 }),
                Some(Constant::Utf8("java/lang/Throwable".to_owned())),
                Some(Constant::Class { name_index: 285 }),
                Some(Constant::Utf8("[Ljava/lang/Object;".to_owned())),
                Some(Constant::Utf8("access$100".to_owned())),
                Some(Constant::Utf8("(Ljavax/microedition/media/PlayerImpl;)J".to_owned())),
                Some(Constant::Utf8("access$200".to_owned())),
                Some(Constant::Utf8("access$300".to_owned())),
                Some(Constant::Utf8("access$400".to_owned())),
                Some(Constant::Utf8("SourceFile".to_owned())),
                Some(Constant::Utf8("generated_bootstrap.rs".to_owned())),
                Some(Constant::Utf8("InnerClasses".to_owned())),
                Some(Constant::Utf8("EventTask".to_owned())),
                Some(Constant::Class { name_index: 296 }),
                Some(Constant::Utf8("javax/microedition/media/PlayerImpl$1".to_owned())),
                Some(Constant::Utf8("volumeEventPending".to_owned())),
                Some(Constant::Utf8("I".to_owned())),
                Some(Constant::NameAndType { name_index: 297, descriptor_index: 298 }),
                Some(Constant::Fieldref { class_index: 2, name_and_type_index: 299 }),
                Some(Constant::Utf8("pumpVolumeEvent".to_owned())),
                Some(Constant::Integer(i32::MAX)),
            ],
            access_flags: 48,
            this_class: 2,
            super_class: 19,
            interfaces: vec![115],
            fields: vec![
                Member { access_flags: 18, name_index: 16, descriptor_index: 17, attributes: Vec::new() },
                Member { access_flags: 18, name_index: 32, descriptor_index: 33, attributes: Vec::new() },
                Member { access_flags: 18, name_index: 28, descriptor_index: 29, attributes: Vec::new() },
                Member { access_flags: 18, name_index: 41, descriptor_index: 42, attributes: Vec::new() },
                Member { access_flags: 18, name_index: 48, descriptor_index: 49, attributes: Vec::new() },
                Member { access_flags: 2, name_index: 219, descriptor_index: 220, attributes: Vec::new() },
                Member { access_flags: 2, name_index: 297, descriptor_index: 298, attributes: Vec::new() },
            ],
            methods: vec![
                Member { access_flags: 2, name_index: 22, descriptor_index: 69, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 238, max_stack: 4, max_locals: 4, code: vec![
                        0x2a, 0xb7, 0x00, 0x12, 0x2a, 0xbb, 0x00, 0x17, 0x59, 0xb7, 0x00, 0x19, 0xb5, 0x00, 0x1a, 0x2a, 0x1f, 0xb5, 0x00, 0x0e,
                        0x2a, 0x1d, 0xb5, 0x00, 0x1e, 0x2a, 0xbb, 0x00, 0x22, 0x59, 0x2a, 0xb7, 0x00, 0x24, 0xb5, 0x00, 0x27, 0x2a, 0x1d, 0x99,
                        0x00, 0x0e, 0xbb, 0x00, 0x2b, 0x59, 0x2a, 0xb7, 0x00, 0x2d, 0xa7, 0x00, 0x04, 0x01, 0xb5, 0x00, 0x2e, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 8, name_index: 241, descriptor_index: 242, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 238, max_stack: 6, max_locals: 1, code: vec![
                        0x2a, 0xc7, 0x00, 0x0b, 0xbb, 0x00, 0x32, 0x59, 0xb7, 0x00, 0x34, 0xbf, 0xbb, 0x00, 0x02, 0x59, 0x2a, 0xb8, 0x00, 0x35,
                        0x2a, 0x12, 0x3b, 0xb6, 0x00, 0x3d, 0xb7, 0x00, 0x43, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 8, name_index: 244, descriptor_index: 245, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 238, max_stack: 5, max_locals: 2, code: vec![
                        0x2a, 0xc6, 0x00, 0x07, 0x2b, 0xc7, 0x00, 0x0b, 0xbb, 0x00, 0x32, 0x59, 0xb7, 0x00, 0x34, 0xbf, 0xbb, 0x00, 0x02, 0x59,
                        0x2b, 0x2a, 0xb8, 0x00, 0x46, 0x03, 0xb7, 0x00, 0x43, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 33, name_index: 246, descriptor_index: 6, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 238, max_stack: 2, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x0e, 0xb8, 0x00, 0x4a, 0x2a, 0xb7, 0x00, 0x07, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 33, name_index: 247, descriptor_index: 6, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 238, max_stack: 2, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x0e, 0xb8, 0x00, 0x4e, 0x2a, 0xb7, 0x00, 0x07, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 33, name_index: 248, descriptor_index: 6, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 238, max_stack: 2, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x0e, 0xb8, 0x00, 0x51, 0x2a, 0xb7, 0x00, 0x07, 0x2a, 0xb7, 0x00, 0x54, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 33, name_index: 249, descriptor_index: 6, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 238, max_stack: 2, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x0e, 0xb8, 0x00, 0x57, 0x2a, 0xb7, 0x00, 0x07, 0x2a, 0xb7, 0x00, 0x01, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 33, name_index: 250, descriptor_index: 6, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 238, max_stack: 2, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x0e, 0xb8, 0x00, 0x5a, 0x2a, 0xb7, 0x00, 0x07, 0x2a, 0xb7, 0x00, 0x01, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 33, name_index: 251, descriptor_index: 6, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 238, max_stack: 2, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x0e, 0xb8, 0x00, 0x5d, 0x2a, 0xb7, 0x00, 0x07, 0x2a, 0xb7, 0x00, 0x01, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 33, name_index: 252, descriptor_index: 103, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 238, max_stack: 4, max_locals: 5, code: vec![
                        0x2a, 0xb4, 0x00, 0x0e, 0x1f, 0xb8, 0x00, 0x60, 0x42, 0x2a, 0xb7, 0x00, 0x07, 0x21, 0xad,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 33, name_index: 253, descriptor_index: 254, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 238, max_stack: 2, max_locals: 3, code: vec![
                        0x2a, 0xb4, 0x00, 0x0e, 0xb8, 0x00, 0x64, 0x40, 0x2a, 0xb7, 0x00, 0x07, 0x1f, 0xad,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 33, name_index: 255, descriptor_index: 254, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 238, max_stack: 2, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x0e, 0xb8, 0x00, 0x68, 0xad,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 33, name_index: 256, descriptor_index: 257, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 238, max_stack: 2, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x0e, 0xb8, 0x00, 0x6b, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 33, name_index: 258, descriptor_index: 206, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 238, max_stack: 2, max_locals: 2, code: vec![
                        0x2a, 0xb4, 0x00, 0x0e, 0xb8, 0x00, 0x0a, 0x3c, 0x2a, 0xb7, 0x00, 0x07, 0x1b, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 33, name_index: 259, descriptor_index: 260, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 238, max_stack: 3, max_locals: 2, code: vec![
                        0x2a, 0xb4, 0x00, 0x0e, 0x1b, 0xb8, 0x00, 0x6f, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 33, name_index: 261, descriptor_index: 262, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 238, max_stack: 3, max_locals: 3, code: vec![
                        0x2a, 0xb4, 0x00, 0x0e, 0xb8, 0x00, 0x0a, 0x3d, 0x1c, 0x10, 0x64, 0x9f, 0x00, 0x0e, 0x1c, 0x11, 0x01, 0x90, 0x9f, 0x00,
                        0x07, 0x1c, 0x9a, 0x00, 0x0b, 0xbb, 0x00, 0x75, 0x59, 0xb7, 0x00, 0x77, 0xbf, 0x2b, 0xc6, 0x00, 0x14, 0x2b, 0xb2, 0x00,
                        0x78, 0xa5, 0x00, 0x0d, 0xbb, 0x00, 0x7e, 0x59, 0x12, 0x80, 0xb7, 0x00, 0x82, 0xbf, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 33, name_index: 263, descriptor_index: 264, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 238, max_stack: 2, max_locals: 2, code: vec![
                        0x2a, 0xb4, 0x00, 0x0e, 0xb8, 0x00, 0x0a, 0x3c, 0x1b, 0x10, 0x64, 0x9f, 0x00, 0x07, 0x1b, 0x9a, 0x00, 0x0b, 0xbb, 0x00,
                        0x75, 0x59, 0xb7, 0x00, 0x77, 0xbf, 0xb2, 0x00, 0x78, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 33, name_index: 265, descriptor_index: 266, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 238, max_stack: 2, max_locals: 2, code: vec![
                        0x2a, 0xb7, 0x00, 0x85, 0x2b, 0xc6, 0x00, 0x16, 0x2a, 0xb4, 0x00, 0x1a, 0x2b, 0xb6, 0x00, 0x88, 0x9a, 0x00, 0x0b, 0x2a,
                        0xb4, 0x00, 0x1a, 0x2b, 0xb6, 0x00, 0x8b, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 33, name_index: 267, descriptor_index: 266, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 238, max_stack: 2, max_locals: 2, code: vec![
                        0x2a, 0xb7, 0x00, 0x85, 0x2b, 0xc6, 0x00, 0x0c, 0x2a, 0xb4, 0x00, 0x1a, 0x2b, 0xb6, 0x00, 0x8f, 0x57, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 33, name_index: 268, descriptor_index: 269, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 238, max_stack: 4, max_locals: 1, code: vec![
                        0x2a, 0xb7, 0x00, 0x92, 0x2a, 0xb4, 0x00, 0x1e, 0x99, 0x00, 0x16, 0x05, 0xbd, 0x00, 0x95, 0x59, 0x03, 0x2a, 0xb4, 0x00,
                        0x27, 0x53, 0x59, 0x04, 0x2a, 0xb4, 0x00, 0x2e, 0x53, 0xb0, 0x04, 0xbd, 0x00, 0x95, 0x59, 0x03, 0x2a, 0xb4, 0x00, 0x27,
                        0x53, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 33, name_index: 270, descriptor_index: 271, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 238, max_stack: 2, max_locals: 2, code: vec![
                        0x2a, 0xb7, 0x00, 0x92, 0x2b, 0xc7, 0x00, 0x0b, 0xbb, 0x00, 0x32, 0x59, 0xb7, 0x00, 0x34, 0xbf, 0x2b, 0x12, 0x97, 0xb6,
                        0x00, 0x3d, 0x9a, 0x00, 0x0c, 0x2b, 0x12, 0x99, 0xb6, 0x00, 0x3d, 0x99, 0x00, 0x08, 0x2a, 0xb4, 0x00, 0x27, 0xb0, 0x2a,
                        0xb4, 0x00, 0x1e, 0x99, 0x00, 0x1a, 0x2b, 0x12, 0x9b, 0xb6, 0x00, 0x3d, 0x9a, 0x00, 0x0c, 0x2b, 0x12, 0x9d, 0xb6, 0x00,
                        0x3d, 0x99, 0x00, 0x08, 0x2a, 0xb4, 0x00, 0x2e, 0xb0, 0x01, 0xb0,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 32, name_index: 272, descriptor_index: 206, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 238, max_stack: 2, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x0e, 0xb8, 0x00, 0x9f, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 32, name_index: 273, descriptor_index: 274, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 238, max_stack: 3, max_locals: 2, code: vec![
                        0x2a, 0xb4, 0x00, 0x0e, 0x1b, 0xb8, 0x00, 0xa2, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 32, name_index: 275, descriptor_index: 276, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 238, max_stack: 2, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x0e, 0xb8, 0x00, 0xa6, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 32, name_index: 277, descriptor_index: 278, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 238, max_stack: 3, max_locals: 2, code: vec![
                        0x2a, 0xb4, 0x00, 0x0e, 0x1b, 0xb8, 0x00, 0xaa, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 32, name_index: 279, descriptor_index: 280, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 238, max_stack: 3, max_locals: 2, code: vec![
                        0x2a, 0xb4, 0x00, 0x0e, 0x2b, 0xb8, 0x00, 0xad, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 32, name_index: 180, descriptor_index: 281, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 238, max_stack: 3, max_locals: 2, code: vec![
                        // Count notifications without allocating or calling a
                        // listener on the setter stack. Reject counter overflow.
                        0x2a, 0xb4, 0x01, 0x2c, 0x13, 0x01, 0x2e, 0xa0, 0x00, 0x0b, 0xbb, 0x00, 0x75, 0x59, 0xb7, 0x00,
                        0x77, 0xbf, 0x2a, 0x59, 0xb4, 0x01, 0x2c, 0x04, 0x60, 0xb5, 0x01, 0x2c, 0x2a, 0xb7, 0x00, 0x54,
                        0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                // Called only by EventTask while holding the Player monitor.
                // Drain a bounded snapshot of pending notifications. Changes
                // made by a listener are counted for a later timer turn.
                Member { access_flags: 0, name_index: 301, descriptor_index: 276, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 238, max_stack: 3, max_locals: 2, code: vec![
                        0x2a, 0xb4, 0x00, 0x0e, 0xb8, 0x00, 0x0a, 0x99, 0x00, 0x56, 0x2a, 0xb4, 0x01, 0x2c, 0x3c, 0x1b,
                        0x10, 0x20, 0xa4, 0x00, 0x06, 0x10, 0x20, 0x3c, 0x2a, 0x59, 0xb4, 0x01, 0x2c, 0x1b, 0x64, 0xb5,
                        0x01, 0x2c, 0x1b, 0x99, 0x00, 0x1d, 0x2a, 0xb4, 0x00, 0x0e, 0xb8, 0x00, 0x0a, 0x99, 0x00, 0x30,
                        0x84, 0x01, 0xff, 0x2a, 0x12, 0xb3, 0x2a, 0xb4, 0x00, 0x27, 0xb7, 0x00, 0xb5, 0xa7, 0xff, 0xe5,
                        0x2a, 0xb4, 0x00, 0x0e, 0xb8, 0x00, 0x0a, 0x59, 0x99, 0x00, 0x14, 0x11, 0x01, 0x90, 0x9f, 0x00,
                        0x0c, 0x2a, 0xb4, 0x01, 0x2c, 0x9a, 0x00, 0x05, 0x03, 0xac, 0x04, 0xac, 0x57, 0x2a, 0x03, 0xb5,
                        0x01, 0x2c, 0x03, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 2, name_index: 135, descriptor_index: 6, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 238, max_stack: 2, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x0e, 0xb8, 0x00, 0x0a, 0x9a, 0x00, 0x0b, 0xbb, 0x00, 0x75, 0x59, 0xb7, 0x00, 0x77, 0xbf, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 2, name_index: 148, descriptor_index: 6, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 238, max_stack: 2, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x0e, 0xb8, 0x00, 0x0a, 0x9a, 0x00, 0x0b, 0xbb, 0x00, 0x75, 0x59, 0xb7, 0x00, 0x77, 0xbf, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 2, name_index: 9, descriptor_index: 6, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 238, max_stack: 6, max_locals: 4, code: vec![
                        0x2a, 0xb4, 0x00, 0x0e, 0xb8, 0x00, 0xb9, 0x59, 0x3c, 0x99, 0x00, 0x5c, 0x2a, 0xb4, 0x00, 0x0e, 0xb8, 0x00, 0xbc, 0x41,
                        0x1b, 0x04, 0xa0, 0x00, 0x14, 0x2a, 0x12, 0xbf, 0xbb, 0x00, 0xc1, 0x59, 0x20, 0xb7, 0x00, 0xc3, 0xb7, 0x00, 0xb5, 0xa7,
                        0x00, 0x3b, 0x1b, 0x05, 0xa0, 0x00, 0x14, 0x2a, 0x12, 0xc5, 0xbb, 0x00, 0xc1, 0x59, 0x20, 0xb7, 0x00, 0xc3, 0xb7, 0x00,
                        0xb5, 0xa7, 0x00, 0x25, 0x1b, 0x06, 0xa0, 0x00, 0x14, 0x2a, 0x12, 0xc7, 0xbb, 0x00, 0xc1, 0x59, 0x20, 0xb7, 0x00, 0xc3,
                        0xb7, 0x00, 0xb5, 0xa7, 0x00, 0x0f, 0x1b, 0x07, 0xa0, 0x00, 0x0a, 0x2a, 0x12, 0xc9, 0x01, 0xb7, 0x00, 0xb5, 0xa7, 0xff,
                        0x9e, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 2, name_index: 183, descriptor_index: 184, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 238, max_stack: 4, max_locals: 6, code: vec![
                        0x2a, 0x59, 0x3a, 0x04, 0xc2, 0x2a, 0xb4, 0x00, 0x1a, 0xb6, 0x00, 0xcb, 0xbd, 0x00, 0x13, 0x4e, 0x2a, 0xb4, 0x00, 0x1a,
                        0x2d, 0xb6, 0x00, 0xcf, 0x19, 0x04, 0xc3, 0xa7, 0x00, 0x0b, 0x3a, 0x05, 0x19, 0x04, 0xc3, 0x19, 0x05, 0xbf, 0x03, 0x36,
                        0x04, 0x15, 0x04, 0x2d, 0xbe, 0xa2, 0x00, 0x1d, 0x2d, 0x15, 0x04, 0x32, 0xc0, 0x00, 0xb1, 0x2a, 0x2b, 0x2c, 0xb9, 0x00,
                        0xd3, 0x04, 0x00, 0xa7, 0x00, 0x05, 0x3a, 0x05, 0x84, 0x04, 0x01, 0xa7, 0xff, 0xe2, 0xb1,
                    ], exception_table: vec![
                        ExceptionHandler { start_pc: 5, end_pc: 27, handler_pc: 30, catch_type: 0 },
                        ExceptionHandler { start_pc: 30, end_pc: 35, handler_pc: 30, catch_type: 0 },
                        ExceptionHandler { start_pc: 48, end_pc: 63, handler_pc: 66, catch_type: 215 },
                    ], attributes: Vec::new() }),
                ] },
                Member { access_flags: 2, name_index: 86, descriptor_index: 6, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 238, max_stack: 6, max_locals: 1, code: vec![
                        // VolumeControl also emits events before playback starts.
                        0x2a, 0xb4, 0x00, 0xd9, 0xc6, 0x00, 0x04, 0xb1,
                        0x2a, 0xbb, 0x00, 0xdd, 0x59, 0xb7, 0x00, 0xdf, 0xb5, 0x00, 0xd9, 0x2a, 0xb4, 0x00, 0xd9, 0xbb, 0x00, 0xe0, 0x59,
                        0x2a, 0x01, 0xb7, 0x00, 0xe2, 0x14, 0x00, 0xe5, 0x14, 0x00, 0xe5, 0xb6, 0x00, 0xe7, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 2, name_index: 5, descriptor_index: 6, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 238, max_stack: 2, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0xd9, 0xc6, 0x00, 0x0f, 0x2a, 0xb4, 0x00, 0xd9, 0xb6, 0x00, 0xeb, 0x2a, 0x01, 0xb5, 0x00, 0xd9, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 266, name_index: 55, descriptor_index: 56, attributes: Vec::new() },
                Member { access_flags: 266, name_index: 72, descriptor_index: 73, attributes: Vec::new() },
                Member { access_flags: 266, name_index: 12, descriptor_index: 13, attributes: Vec::new() },
                Member { access_flags: 266, name_index: 76, descriptor_index: 77, attributes: Vec::new() },
                Member { access_flags: 266, name_index: 80, descriptor_index: 77, attributes: Vec::new() },
                Member { access_flags: 266, name_index: 83, descriptor_index: 77, attributes: Vec::new() },
                Member { access_flags: 266, name_index: 89, descriptor_index: 77, attributes: Vec::new() },
                Member { access_flags: 266, name_index: 92, descriptor_index: 77, attributes: Vec::new() },
                Member { access_flags: 266, name_index: 95, descriptor_index: 77, attributes: Vec::new() },
                Member { access_flags: 266, name_index: 109, descriptor_index: 110, attributes: Vec::new() },
                Member { access_flags: 266, name_index: 106, descriptor_index: 103, attributes: Vec::new() },
                Member { access_flags: 266, name_index: 102, descriptor_index: 103, attributes: Vec::new() },
                Member { access_flags: 266, name_index: 98, descriptor_index: 99, attributes: Vec::new() },
                Member { access_flags: 266, name_index: 113, descriptor_index: 114, attributes: Vec::new() },
                Member { access_flags: 266, name_index: 161, descriptor_index: 13, attributes: Vec::new() },
                Member { access_flags: 266, name_index: 164, descriptor_index: 165, attributes: Vec::new() },
                Member { access_flags: 266, name_index: 168, descriptor_index: 169, attributes: Vec::new() },
                Member { access_flags: 266, name_index: 172, descriptor_index: 69, attributes: Vec::new() },
                Member { access_flags: 266, name_index: 175, descriptor_index: 176, attributes: Vec::new() },
                Member { access_flags: 266, name_index: 187, descriptor_index: 13, attributes: Vec::new() },
                Member { access_flags: 266, name_index: 190, descriptor_index: 103, attributes: Vec::new() },
                Member { access_flags: 4104, name_index: 286, descriptor_index: 287, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 238, max_stack: 2, max_locals: 1, code: vec![
                        0x2a, 0xb4, 0x00, 0x0e, 0xad,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 4104, name_index: 288, descriptor_index: 13, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 238, max_stack: 2, max_locals: 2, code: vec![
                        0x1e, 0xb8, 0x00, 0x0a, 0xac,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 4104, name_index: 289, descriptor_index: 38, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 238, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb7, 0x00, 0x07, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
                Member { access_flags: 4104, name_index: 290, descriptor_index: 38, attributes: vec![
                    Attribute::Code(CodeAttribute { name_index: 238, max_stack: 1, max_locals: 1, code: vec![
                        0x2a, 0xb7, 0x00, 0x01, 0xb1,
                    ], exception_table: Vec::new(), attributes: Vec::new() }),
                ] },
            ],
            attributes: Vec::new(),
        },
        // javax/microedition/media/PlayerListener
        ClassFile {
            minor_version: 0,
            major_version: 48,
            constant_pool: vec![
                None,
                Some(Constant::Class { name_index: 2 }),
                Some(Constant::Utf8("javax/microedition/media/PlayerListener".to_owned())),
                Some(Constant::Class { name_index: 4 }),
                Some(Constant::Utf8("java/lang/Object".to_owned())),
                Some(Constant::Utf8("CLOSED".to_owned())),
                Some(Constant::Utf8("Ljava/lang/String;".to_owned())),
                Some(Constant::Utf8("ConstantValue".to_owned())),
                Some(Constant::String { string_index: 9 }),
                Some(Constant::Utf8("closed".to_owned())),
                Some(Constant::Utf8("DEVICE_AVAILABLE".to_owned())),
                Some(Constant::String { string_index: 12 }),
                Some(Constant::Utf8("deviceAvailable".to_owned())),
                Some(Constant::Utf8("DEVICE_UNAVAILABLE".to_owned())),
                Some(Constant::String { string_index: 15 }),
                Some(Constant::Utf8("deviceUnavailable".to_owned())),
                Some(Constant::Utf8("DURATION_UPDATED".to_owned())),
                Some(Constant::String { string_index: 18 }),
                Some(Constant::Utf8("durationUpdated".to_owned())),
                Some(Constant::Utf8("END_OF_MEDIA".to_owned())),
                Some(Constant::String { string_index: 21 }),
                Some(Constant::Utf8("endOfMedia".to_owned())),
                Some(Constant::Utf8("ERROR".to_owned())),
                Some(Constant::String { string_index: 24 }),
                Some(Constant::Utf8("error".to_owned())),
                Some(Constant::Utf8("STARTED".to_owned())),
                Some(Constant::String { string_index: 27 }),
                Some(Constant::Utf8("started".to_owned())),
                Some(Constant::Utf8("STOPPED".to_owned())),
                Some(Constant::String { string_index: 30 }),
                Some(Constant::Utf8("stopped".to_owned())),
                Some(Constant::Utf8("VOLUME_CHANGED".to_owned())),
                Some(Constant::String { string_index: 33 }),
                Some(Constant::Utf8("volumeChanged".to_owned())),
                Some(Constant::Utf8("playerUpdate".to_owned())),
                Some(Constant::Utf8("(Ljavax/microedition/media/Player;Ljava/lang/String;Ljava/lang/Object;)V".to_owned())),
                Some(Constant::Utf8("SourceFile".to_owned())),
                Some(Constant::Utf8("generated_bootstrap.rs".to_owned())),
            ],
            access_flags: 1537,
            this_class: 1,
            super_class: 3,
            interfaces: vec![],
            fields: vec![
                Member { access_flags: 25, name_index: 5, descriptor_index: 6, attributes: vec![
                    Attribute::Raw { name_index: 7, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x08,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 10, descriptor_index: 6, attributes: vec![
                    Attribute::Raw { name_index: 7, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x0b,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 13, descriptor_index: 6, attributes: vec![
                    Attribute::Raw { name_index: 7, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x0e,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 16, descriptor_index: 6, attributes: vec![
                    Attribute::Raw { name_index: 7, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x11,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 19, descriptor_index: 6, attributes: vec![
                    Attribute::Raw { name_index: 7, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x14,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 22, descriptor_index: 6, attributes: vec![
                    Attribute::Raw { name_index: 7, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x17,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 25, descriptor_index: 6, attributes: vec![
                    Attribute::Raw { name_index: 7, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x1a,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 28, descriptor_index: 6, attributes: vec![
                    Attribute::Raw { name_index: 7, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x1d,
                    ] },
                ] },
                Member { access_flags: 25, name_index: 31, descriptor_index: 6, attributes: vec![
                    Attribute::Raw { name_index: 7, name: "ConstantValue".to_owned(), bytes: vec![
                        0x00, 0x20,
                    ] },
                ] },
            ],
            methods: vec![
                Member { access_flags: 1025, name_index: 34, descriptor_index: 35, attributes: Vec::new() },
            ],
            attributes: Vec::new(),
        },
    );
}
